import { notFound } from 'next/navigation';
import Link from 'next/link';
import { stays } from '@/data/catalog';

export function generateStaticParams() { return stays.map((stay) => ({ slug: stay.slug })); }

export default async function StayDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const stay = stays.find((item) => item.slug === slug);
  if (!stay) notFound();
  const gallery = stay.gallery?.length ? stay.gallery : [stay.image, stay.image, stay.image];
  return <div className="subpage">
    <section className="detail-head"><div className="container"><div className="detail-breadcrumb"><Link href="/">Trang chủ</Link><span>/</span><Link href="/stay">Lưu trú</Link><span>/</span><span>{stay.name}</span></div><div className="detail-title-row"><div><span className="property-type">{stay.type}</span><h1>{stay.name}</h1><p>📍 {stay.location}</p></div><div className="detail-score"><b>{stay.rating}</b><span>Rất tốt</span></div></div></div></section>
    <nav className="sub-nav"><div className="container sub-nav-inner"><a href="#overview">Tổng quan</a><a href="#rooms">Hạng phòng / villa</a><a href="#amenities">Tiện ích</a><a href="#policy">Chính sách</a><Link href="/stay">← Quay lại danh sách</Link></div></nav>
    <section className="section detail-section"><div className="container"><div className="detail-gallery"><div className="gallery-main" style={{backgroundImage:`url(${gallery[0]})`}}/><div style={{backgroundImage:`url(${gallery[1]})`}}/><div style={{backgroundImage:`url(${gallery[2]})`}}/></div><div className="detail-layout"><main><section id="overview" className="detail-block"><h2>Thông tin lưu trú</h2><p>{stay.summary}</p><div className="amenity-grid">{stay.highlights.map(item=><div key={item}>✓ {item}</div>)}</div></section><section id="rooms" className="detail-block"><h2>Chọn hạng phòng / villa</h2><p>Giá thực tế phụ thuộc ngày ở, số khách và chính sách tại thời điểm đặt.</p><div className="room-table">{(stay.rooms || ['Phòng tiêu chuẩn','Phòng gia đình']).map(room=><div className="room-row" key={room}><div><b>{room}</b><span>Phù hợp theo số khách · Chính sách xác nhận theo ngày</span></div><div><strong>Liên hệ giá</strong><a href="tel:0969973949">Kiểm tra phòng</a></div></div>)}</div></section><section id="amenities" className="detail-block"><h2>Tiện ích nổi bật</h2><div className="amenity-grid">{stay.highlights.map(item=><div key={item}>✦ {item}</div>)}</div></section><section id="policy" className="detail-block"><h2>Chính sách</h2><div className="policy-grid"><div><b>Nhận / trả phòng</b><p>Theo chính sách từng hạng phòng hoặc villa.</p></div><div><b>Đặt cọc</b><p>Hiển thị theo gói giá và ngày lưu trú.</p></div><div><b>Hoàn hủy</b><p>Áp dụng theo điều kiện của từng gói đặt.</p></div><div><b>Phụ thu</b><p>Trẻ em, người lớn thêm và dịch vụ phát sinh được xác nhận trước.</p></div></div></section></main><aside className="booking-box"><h3>Kiểm tra giá & phòng</h3><label>Ngày nhận phòng<input type="date"/></label><label>Ngày trả phòng<input type="date"/></label><label>Khách<select defaultValue="2"><option value="2">2 khách</option><option value="4">4 khách</option><option value="6">6 khách</option><option value="8">8 khách</option></select></label><div className="booking-note">Giá tốt nhất được xác nhận theo ngày thực tế.</div><a className="primary-button full" href="tel:0969973949">☎ Gọi kiểm tra phòng</a><a className="zalo-outline" href="https://zalo.me/0969973949">Chat Zalo</a><Link className="text-link" href="/destinations">Xem thêm điểm đến →</Link></aside></div><div className="sub-cta"><div><h2>Muốn so sánh thêm lựa chọn?</h2><p>Quay lại danh sách lưu trú hoặc xem điểm đến để tìm sản phẩm tương tự.</p></div><div className="sub-cta-actions"><Link className="call" href="/stay">Xem lưu trú khác</Link><Link className="zalo" href="/destinations">Điểm đến</Link></div></div></div></section>
  </div>
}
