import { SearchBar } from '@/components/SearchBar';
import { stays } from '@/data/catalog';
import Link from 'next/link';

export const metadata = { title: 'Villa, Resort & Khách sạn' };

export default function StayPage() {
  return <div className="subpage">
    <section className="sub-hero"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / Lưu trú</div><div className="sub-hero-grid"><div><span className="sub-kicker">LƯU TRÚ TOÀN QUỐC</span><h1>Villa, Resort & Khách sạn</h1><p>Tìm chỗ nghỉ theo điểm đến, ngày ở, số khách và loại hình lưu trú. Giao diện kết quả được tổ chức theo trải nghiệm đặt phòng hiện đại.</p></div><div className="sub-hero-cta"><a className="solid" href="tel:0969973949">☎ Tư vấn đặt phòng</a><a className="outline" href="https://zalo.me/0969973949">Zalo</a></div></div></div></section>
    <nav className="sub-nav"><div className="container sub-nav-inner"><Link href="/stay">Tất cả lưu trú</Link><Link href="/stay?type=villa">Villa & Resort</Link><Link href="/stay?type=hotel">Khách sạn</Link><Link href="/destinations">Điểm đến</Link><Link href="/guide">Cẩm nang</Link></div></nav>
    <section className="sub-section white"><div className="container"><SearchBar /></div></section>
    <section className="sub-section"><div className="container"><div className="sub-toolbar"><div><b>{stays.length} lựa chọn nổi bật</b><br/><span>Oceanami · NovaWorld · Vinpearl · FLC và các sản phẩm đang cập nhật</span></div><div className="sub-filter-row"><span className="sub-chip active">Phù hợp nhất</span><span className="sub-chip">Giá tốt</span><span className="sub-chip">5 sao</span></div></div><div className="booking-layout"><aside className="booking-filter"><h3>Bộ lọc</h3><div><label>Loại chỗ nghỉ</label><select defaultValue="all"><option value="all">Tất cả</option><option>Villa</option><option>Khách sạn</option><option>Resort</option></select></div><div><label>Ngân sách</label><select defaultValue="all"><option value="all">Tất cả mức giá</option><option>Dưới 1.500.000đ</option><option>1.500.000đ – 3.000.000đ</option><option>Trên 3.000.000đ</option></select></div><div><label>Hạng sao</label><select defaultValue="all"><option value="all">Tất cả</option><option>5 sao</option><option>4 sao</option><option>3 sao</option></select></div></aside><div className="booking-results">{stays.map(stay=><article className="booking-card" key={stay.slug}><img src={stay.image} alt={stay.name}/><div><span className="meta">{stay.type}</span><h3>{stay.name}</h3><p>📍 {stay.location}</p><p className="summary">{stay.summary}</p><Link className="view-link" href={`/stay/${stay.slug}`}>Xem tiện ích, hình ảnh & chính sách →</Link></div><div className="booking-price"><small>Giá theo ngày</small><strong>Liên hệ</strong><Link href={`/stay/${stay.slug}`}>Xem phòng</Link></div></article>)}</div></div><div className="sub-cta"><div><h2>Cần kiểm tra phòng nhanh?</h2><p>Gửi ngày ở, số khách và điểm đến để Thúy Nguyên Travel kiểm tra phương án phù hợp.</p></div><div className="sub-cta-actions"><a className="call" href="tel:0969973949">☎ 0969 973 949</a><a className="zalo" href="https://zalo.me/0969973949">Chat Zalo</a></div></div></div></section>
  </div>
}
