/** @type {import('next').NextConfig} */
const contentSecurityPolicy = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "script-src-attr 'none'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob: https:",
  "font-src 'self' data: https:",
  "connect-src 'self' https:",
  "media-src 'self' blob: https:",
  "frame-src 'self' https://www.google.com https://maps.google.com",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

const securityHeaders = [
  { key: 'Content-Security-Policy', value: contentSecurityPolicy },
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'geolocation=(self), camera=(), microphone=(), payment=(), usb=()' },
  { key: 'X-Permitted-Cross-Domain-Policies', value: 'none' },
];

const nextConfig = {
  poweredByHeader: false,
  reactStrictMode: true,
  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }];
  },
  async redirects() {
    return [
      {source:'/stay/:slug',destination:'/luu-tru/:slug',permanent:true},
      {source:'/stay',destination:'/luu-tru',permanent:true},
      {source:'/tours/:slug',destination:'/tour-du-lich/:slug',permanent:true},
      {source:'/tours',destination:'/tour-du-lich',permanent:true},
      {source:'/cruises/:slug',destination:'/du-thuyen/:slug',permanent:true},
      {source:'/cruises',destination:'/du-thuyen',permanent:true},
      {source:'/destinations',destination:'/diem-den',permanent:true},
      {source:'/guide/category/:slug',destination:'/cam-nang/danh-muc/:slug',permanent:true},
      {source:'/guide/read',destination:'/cam-nang/doc',permanent:true},
      {source:'/guide/:slug',destination:'/cam-nang/:slug',permanent:true},
      {source:'/cam-nang/villa-flc-sam-son-kinh-nghiem-thue-gia-tot',destination:'/diem-den/sam-son/villa',permanent:true},
      {source:'/guide',destination:'/cam-nang',permanent:true},
      {source:'/product/:slug',destination:'/san-pham/:slug',permanent:true},
      {source:'/san-pham/anyla-sam-son',destination:'/khach-san-resort/anyla-sam-son',permanent:true},
      {source:'/san-pham/emerald-villa-flc-sam-son',destination:'/villa/emerald-villa-flc-sam-son',permanent:true},
      {source:'/san-pham/flc-grand-hotel-ha-long',destination:'/khach-san-resort/flc-grand-hotel-ha-long',permanent:true},
      {source:'/san-pham/flc-grand-hotel-samson',destination:'/khach-san-resort/flc-grand-hotel-samson',permanent:true},
      {source:'/san-pham/flc-luxury-hotel-samson',destination:'/khach-san-resort/flc-luxury-hotel-samson',permanent:true},
      {source:'/san-pham/flc-luxury-resort-phu-tho',destination:'/khach-san-resort/flc-luxury-resort-phu-tho',permanent:true},
      {source:'/san-pham/flc-luxury-resort-quy-nhon',destination:'/khach-san-resort/flc-luxury-resort-quy-nhon',permanent:true},
      {source:'/san-pham/flc-luxury-resort-samson',destination:'/khach-san-resort/flc-luxury-resort-samson',permanent:true},
      {source:'/san-pham/gio-villa-hoi-an',destination:'/villa/gio-villa-hoi-an',permanent:true},
      {source:'/san-pham/lasong-hotel-villas-sam-son',destination:'/khach-san-resort/lasong-hotel-villas-sam-son',permanent:true},
      {source:'/san-pham/luviaf-quy-nhon',destination:'/khach-san-resort/luviaf-quy-nhon',permanent:true},
      {source:'/san-pham/marron-sam-son-hotel',destination:'/khach-san-resort/marron-sam-son-hotel',permanent:true},
      {source:'/san-pham/nang-villa-hoi-an',destination:'/villa/nang-villa-hoi-an',permanent:true},
      {source:'/san-pham/nhan-villa-hoi-an',destination:'/villa/nhan-villa-hoi-an',permanent:true},
      {source:'/san-pham/sam-villa-hoi-an',destination:'/villa/sam-villa-hoi-an',permanent:true},
      {source:'/san-pham/sol-villa-hoi-an',destination:'/villa/sol-villa-hoi-an',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-bt-37-02',destination:'/villa/villa-flc-sam-son-bt-37-02',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-bt31-08',destination:'/villa/villa-flc-sam-son-bt31-08',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-bt40-06',destination:'/villa/villa-flc-sam-son-bt40-06',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt-167',destination:'/villa/villa-flc-sam-son-nt-167',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt04',destination:'/villa/villa-flc-sam-son-nt04',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt05',destination:'/villa/villa-flc-sam-son-nt05',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt12a',destination:'/villa/villa-flc-sam-son-nt12a',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt166',destination:'/villa/villa-flc-sam-son-nt166',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt168',destination:'/villa/villa-flc-sam-son-nt168',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt22',destination:'/villa/villa-flc-sam-son-nt22',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt25',destination:'/villa/villa-flc-sam-son-nt25',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt27',destination:'/villa/villa-flc-sam-son-nt27',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt34',destination:'/villa/villa-flc-sam-son-nt34',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt35',destination:'/villa/villa-flc-sam-son-nt35',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-nt36',destination:'/villa/villa-flc-sam-son-nt36',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sb03',destination:'/villa/villa-flc-sam-son-sb03',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sb04',destination:'/villa/villa-flc-sam-son-sb04',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sb33',destination:'/villa/villa-flc-sam-son-sb33',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sb58',destination:'/villa/villa-flc-sam-son-sb58',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sh05',destination:'/villa/villa-flc-sam-son-sh05',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sh08',destination:'/villa/villa-flc-sam-son-sh08',permanent:true},
      {source:'/san-pham/villa-flc-sam-son-sh18',destination:'/villa/villa-flc-sam-son-sh18',permanent:true},
      {source:'/san-pham/villa-ha-long-bt6b-36-5pn',destination:'/villa/villa-ha-long-bt6b-36-5pn',permanent:true},
      {source:'/san-pham/villa-ha-long-bt6b-40-6pn',destination:'/villa/villa-ha-long-bt6b-40-6pn',permanent:true},
      {source:'/san-pham/villa-ha-long-bt8-09-5pn',destination:'/villa/villa-ha-long-bt8-09-5pn',permanent:true},
      {source:'/san-pham/villa-ha-long-bt8-10-5pn',destination:'/villa/villa-ha-long-bt8-10-5pn',permanent:true},
      {source:'/san-pham/villa-ha-long-bt9-39b',destination:'/villa/villa-ha-long-bt9-39b',permanent:true},
      {source:'/san-pham/villa-ha-long-bt9-45-5pn',destination:'/villa/villa-ha-long-bt9-45-5pn',permanent:true},
      {source:'/san-pham/villa-ngu-binh-retreat-sam-son',destination:'/villa/villa-ngu-binh-retreat-sam-son',permanent:true},
      {source:'/product',destination:'/san-pham',permanent:true},
      {source:'/search',destination:'/tim-kiem',permanent:true},
      {source:'/about',destination:'/gioi-thieu',permanent:true},
      {source:'/contact',destination:'/lien-he',permanent:true},
      {source:'/terms',destination:'/dieu-khoan',permanent:true},
      {source:'/privacy',destination:'/chinh-sach-bao-mat',permanent:true},
      {source:'/payment-guide',destination:'/huong-dan-thanh-toan',permanent:true},
      {source:'/account',destination:'/tai-khoan',permanent:true},
      {source:'/checkout',destination:'/thanh-toan',permanent:true},
    ];
  },
  async rewrites() {
    return [
      {source:'/luu-tru/:slug',destination:'/stay/:slug'},
      {source:'/luu-tru',destination:'/stay'},
      {source:'/tour-du-lich/:slug',destination:'/tours/:slug'},
      {source:'/tour-du-lich',destination:'/tours'},
      {source:'/du-thuyen/:slug',destination:'/cruises/:slug'},
      {source:'/du-thuyen',destination:'/cruises'},
      {source:'/cam-nang/danh-muc/:slug',destination:'/guide/category/:slug'},
      {source:'/cam-nang/doc',destination:'/guide/read'},
      {source:'/cam-nang/:slug',destination:'/guide/:slug'},
      {source:'/cam-nang',destination:'/guide'},
      {source:'/san-pham/:slug',destination:'/product/:slug'},
      {source:'/san-pham',destination:'/product'},
      {source:'/tim-kiem',destination:'/search'},
      {source:'/gioi-thieu',destination:'/about'},
      {source:'/lien-he',destination:'/contact'},
      {source:'/dieu-khoan',destination:'/terms'},
      {source:'/chinh-sach-bao-mat',destination:'/privacy'},
      {source:'/huong-dan-thanh-toan',destination:'/payment-guide'},
      {source:'/tai-khoan',destination:'/account'},
      {source:'/thanh-toan',destination:'/checkout'},
    ];
  },
};

export default nextConfig;
