const resendKey=String(process.env.RESEND_API_KEY||'').trim();
const from=String(process.env.EMAIL_FROM||'HappyGo Travel <booking@happygo.vn>').trim();
const replyTo=String(process.env.EMAIL_REPLY_TO||'info@happygo.vn').trim();
const brandUrl=String(process.env.PUBLIC_SITE_URL||'https://banguyen310941-coder.github.io/thuy-nguyen-travel').replace(/\/$/,'');
const hotline=String(process.env.BUSINESS_HOTLINE||'0969973949').trim();
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=(v)=>{if(!v)return 'Theo xác nhận';const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?esc(v):d.toLocaleDateString('vi-VN')};
const nights=(a,b)=>{if(!a||!b)return 1;const x=new Date(`${a}T12:00:00`),y=new Date(`${b}T12:00:00`);return Math.max(1,Math.round((y-x)/86400000))};
function shell({preview,title,body,footer='HappyGo Travel · Hành trình hạnh phúc · Kết nối yêu thương'}){return `<!doctype html><html><body style="margin:0;background:#f3f6f8;font-family:Arial,sans-serif;color:#17324d"><div style="display:none;max-height:0;overflow:hidden">${esc(preview)}</div><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:28px 12px"><table width="680" style="width:100%;max-width:680px;background:#fff;border-collapse:collapse"><tr><td align="center" style="padding:26px;border-bottom:4px solid #0d47a1"><div style="font-size:30px;font-weight:900"><span style="color:#0d47a1">Happy</span><span style="color:#ff6500">Go</span></div><div style="color:#0d47a1;font-size:11px;font-weight:800;letter-spacing:5px">TRAVEL</div></td></tr><tr><td style="padding:28px"><h1 style="text-align:center;color:#123c64;font-family:Georgia,serif;font-size:27px;margin:0 0 24px">${esc(title)}</h1>${body}</td></tr><tr><td style="border-top:1px solid #ccd8e3;padding:16px 28px;text-align:center;color:#64798a;font-size:11px">${footer}<br>Hotline: ${esc(hotline)} · <a href="${brandUrl}" style="color:#0d47a1">Website HappyGo Travel</a></td></tr></table></td></tr></table></body></html>`}
async function send({to,subject,html,tags=[]}){if(!resendKey)return {ok:false,skipped:true,error:'RESEND_API_KEY is not configured'};const payload={from,to:Array.isArray(to)?to:[to],subject,html,tags};if(replyTo)payload.reply_to=replyTo;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${resendKey}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.message||`Email provider error ${response.status}`);return {ok:true,id:data?.id||null}}
export async function sendBookingConfirmation(booking){if(!booking?.email)return {ok:false,skipped:true,error:'Booking has no email'};const subject=`[${booking.code}] HappyGo Travel đã nhận yêu cầu của bạn`;const body=`<p>Kính gửi <b>${esc(booking.customerName)}</b>,</p><p>Cảm ơn Quý khách đã gửi yêu cầu tới HappyGo Travel. Đội ngũ tư vấn sẽ kiểm tra tình trạng và liên hệ xác nhận.</p><table width="100%" cellpadding="8" style="background:#f6f9fc;font-size:13px"><tr><td>Mã yêu cầu</td><td><b>${esc(booking.code)}</b></td></tr><tr><td>Dịch vụ</td><td>${esc(booking.product)}</td></tr><tr><td>Ngày đi</td><td>${date(booking.startDate)}</td></tr></table>`;return send({to:booking.email,subject,html:shell({preview:`Đã nhận yêu cầu ${booking.code}`,title:'ĐÃ NHẬN YÊU CẦU ĐẶT DỊCH VỤ',body}),tags:[{name:'type',value:'booking-request'}]})}
export async function sendConfirmedBooking(booking){if(!booking?.email)return {ok:false,skipped:true,error:'Booking has no email'};const roomCount=Math.max(1,Number(booking.rooms||1));const nightCount=nights(booking.start_date,booking.end_date);const note=esc(booking.admin_note||'').replace(/\n/g,'<br>');const body=`<p style="font-size:14px">Kính gửi Quý khách <b>${esc(booking.customer_name)}</b>,</p><p style="font-size:14px;line-height:1.6">HappyGo Travel trân trọng xác nhận đặt dịch vụ của Quý khách với thông tin dưới đây:</p><table width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;border:1px solid #173f87;font-size:13px"><tr style="background:#123b8c;color:#fff"><td><b>Mã xác nhận:</b></td><td><b>${esc(booking.code)}</b></td><td><b>Loại dịch vụ:</b></td><td>${esc(booking.kind)}</td></tr><tr><td style="border:1px solid #7890b2">Họ & tên</td><td style="border:1px solid #7890b2">${esc(booking.customer_name)}</td><td style="border:1px solid #7890b2">Số lượng khách</td><td style="border:1px solid #7890b2">${Number(booking.adults||1)} người lớn · ${Number(booking.children||0)} trẻ em</td></tr><tr><td style="border:1px solid #7890b2">Ngày nhận</td><td style="border:1px solid #7890b2">${date(booking.start_date)}</td><td style="border:1px solid #7890b2">Ngày trả</td><td style="border:1px solid #7890b2">${date(booking.end_date)}</td></tr><tr><td style="border:1px solid #7890b2">Dịch vụ</td><td style="border:1px solid #7890b2">${esc(booking.product)}</td><td style="border:1px solid #7890b2">Số lượng</td><td style="border:1px solid #7890b2">${roomCount} phòng/căn · ${nightCount} đêm</td></tr></table><h3 style="background:#123b8c;color:#fff;padding:9px 12px;font-size:14px;margin:20px 0 0">THÔNG TIN ĐẶT PHÒNG / DỊCH VỤ</h3><div style="border:1px solid #7890b2;border-top:0;padding:14px;font-size:13px;line-height:1.65"><b>Dịch vụ đã xác nhận:</b> ${esc(booking.product)}<br><b>Thời gian:</b> ${date(booking.start_date)} → ${date(booking.end_date)} (${nightCount} đêm)<br><b>Số lượng:</b> ${roomCount} phòng/căn<br>${note?`<br><b>Thông tin bổ sung từ HappyGo:</b><br>${note}`:''}</div><div style="margin-top:18px;padding:14px;background:#fff8ed;border-left:4px solid #ff6500;font-size:12px;line-height:1.6"><b>Lưu ý:</b> Quý khách vui lòng kiểm tra kỹ họ tên, ngày sử dụng dịch vụ và số lượng. Nếu cần thay đổi, vui lòng liên hệ HappyGo Travel sớm nhất qua hotline ${esc(hotline)}.</div><p style="margin-top:20px;font-size:13px">Trân trọng,<br><b style="color:#0d47a1">HappyGo Travel</b></p>`;return send({to:booking.email,subject:`[${booking.code}] THƯ XÁC NHẬN ĐẶT PHÒNG - HappyGo Travel`,html:shell({preview:`Xác nhận booking ${booking.code}`,title:'THƯ XÁC NHẬN ĐẶT PHÒNG',body}),tags:[{name:'type',value:'booking-confirmed'}]})}
export function campaignHtml({title,message,ctaLabel,ctaUrl}){const paragraphs=String(message||'').split(/\n+/).filter(Boolean).map(p=>`<p style="font-size:15px;line-height:1.7;margin:0 0 14px">${esc(p)}</p>`).join('');const cta=ctaLabel&&ctaUrl?`<p><a href="${esc(ctaUrl)}" style="display:inline-block;background:#0d47a1;color:#fff;text-decoration:none;padding:12px 18px;border-radius:8px;font-weight:700">${esc(ctaLabel)}</a></p>`:'';return shell({preview:title,title,body:`${paragraphs}${cta}`,footer:'Bạn nhận email này vì đã từng liên hệ hoặc sử dụng dịch vụ của HappyGo Travel.'})}
export async function sendCampaignEmail({to,subject,title,message,ctaLabel,ctaUrl}){return send({to,subject,html:campaignHtml({title,message,ctaLabel,ctaUrl}),tags:[{name:'type',value:'customer-campaign'}]})}
