import type {Metadata} from 'next';
import {AdminStorageGuard} from '@/components/AdminStorageGuard';
import {AdminSeoGuideSeedSync} from '@/components/AdminSeoGuideSeedSync';
import {AdminSeoDemoSeeder} from '@/components/AdminSeoDemoSeeder';
import {AdminTourSeedSync} from '@/components/AdminTourSeedSync';
import {PortalWorkspaceBar} from '@/components/PortalWorkspaceBar';
import './admin.css';
import './bookings.css';
import './cms.css';
import './editor.css';
import './editor-pro-v2.css';
import './product-v2.css';
import './product-manager.css';
import './units.css';
import './utility.css';
import './admin-mobile-fixes.css';
import './media-picker.css';
import './rate-calendar.css';
import './connectivity.css';
import './admin-refresh.css';
import './admin-detail-pro.css';
import './team-chat-v4.css';
import './admin-action-language.css';
import './crm-workboard-v2.css';
import './partner-manager-v2.css';
import './affiliate-admin.css';
import './affiliate-payout-queue.css';
import './affiliate-applications.css';

export const metadata:Metadata={title:'Quản trị HappyGo Travel',description:'Ứng dụng quản trị và điều hành HappyGo Travel.',applicationName:'HappyGo Travel Admin',manifest:'/admin/manifest.webmanifest',appleWebApp:{capable:true,statusBarStyle:'default',title:'HappyGo Admin'},robots:{index:false,follow:false,nocache:true}};
export default function AdminLayout({children}:{children:React.ReactNode}){return <><PortalWorkspaceBar scope="admin" status="Production"/><AdminStorageGuard/><AdminSeoGuideSeedSync/><AdminSeoDemoSeeder/><AdminTourSeedSync/>{children}</>}
