'use client';

import { useState } from 'react';
import { AdminBookings } from '@/components/AdminBookings';
import { AdminCustomers } from '@/components/AdminCustomers';

const modules=[['▦','Tổng quan'],['◎','Khách hàng / CRM'],['▣','Đơn đặt dịch vụ'],['▤','Sản phẩm'],['✈','Tour du lịch'],['⌂','Villa & Resort'],['▥','Khách sạn'],['≋','Du thuyền'],['✎','Bài viết / Cẩm nang'],['▧','Media (Ảnh/Video)'],['⌂','Giao diện (Trang chủ)'],['⌕','Cấu hình SEO'],['⇩','Google Drive'],['⚙','Cài đặt']] as const;
const products=[['Oceanami Villas & Beach Club','Villa','Phước Hải','Hoạt động'],['NovaWorld Phan Thiết','Villa','Phan Thiết','Hoạt động'],['Vinpearl Resort Nha Trang','Khách sạn','Nha Trang','Hoạt động'],['Ambassador Hạ Long','Du thuyền','Hạ Long','Hoạt động']];
function Table({rows}:{rows:string[][]}){return <div className="admin-table">{rows.map((r,i)=><div key={i}>{r.map((c,j)=>j===0?<b key={j}>{c}</b>:j===r.length-1?<em key={j}>{c}</em>:<span key={j}>{c}</span>)}</div>)}</div>}
function Products({title}:{title:string}){return <section className="admin-panel"><div className="admin-panel-head"><div><h2>{title}</h2><p>Quản lý giá bán, ảnh, nội dung, SEO và trạng thái hiển thị.</p></div><button>+ Thêm sản phẩm</button></div><div className="admin-form-row"><label>Tìm kiếm<input placeholder="Tên sản phẩm, địa điểm..."/></label><label>Trạng thái<select><option>Tất cả</option><option>Hoạt động</option><option>Nháp</option><option>Ẩn</option></select></label></div><Table rows={products}/></section>}
export default function AdminPage(){const [active,setActive]=useState('Tổng quan');return <div className="admin-app"><aside className="admin-sidebar"><div className="admin-brand"><span>TN</span><div><b>THÚY NGUYÊN</b><small>TRAVEL ADMIN</small></div></div><nav>{modules.map(([icon,name])=><button key={name} className={active===name?'active':''} onClick={()=>setActive(name)}><i>{icon}</i><span>{name}</span></button>)}</nav><a className="admin-back" href="/">← Xem website</a></aside><main className="admin-main"><header className="admin-top"><div><small>THÚY NGUYÊN TRAVEL / QUẢN TRỊ</small><h1>{active}</h1></div><div className="admin-user"><span>●</span><div><b>Quản trị viên</b><small>Đang hoạt động</small></div></div></header>
{active==='Tổng quan'&&<><div className="admin-welcome"><div><small>TỔNG QUAN HỆ THỐNG</small><h2>Xin chào, Thúy Nguyên Travel</h2><p>Theo dõi khách hàng, đơn hàng, doanh thu và nội dung website tại một nơi.</p></div><a href="/">Xem website ↗</a></div><div className="admin-stats dashboard"><div><span>👤 Khách hàng</span><b>1.248</b><small>↑ 12% tháng này</small></div><div><span>🟠 Đơn hàng</span><b>356</b><small>24 đơn chờ xử lý</small></div><div><span>💵 Doanh thu</span><b>486,7 tr</b><small>30 ngày gần nhất</small></div><div><span>🟣 Bài viết</span><b>42</b><small>36 bài đã xuất bản</small></div></div><div className="admin-dashboard-grid"><section className="admin-panel chart-panel"><div className="admin-panel-head"><div><h2>Doanh thu 30 ngày</h2><p>Biểu đồ tổng quan hiệu quả bán hàng</p></div><select><option>30 ngày</option><option>7 ngày</option></select></div><div className="fake-chart"><span>500tr</span><span>400tr</span><span>300tr</span><span>200tr</span><span>100tr</span><svg viewBox="0 0 700 180" preserveAspectRatio="none"><polyline points="0,155 70,140 140,148 210,115 280,122 350,85 420,96 490,60 560,75 630,32 700,45"/></svg></div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Đơn gần đây</h2><p>Cần chăm sóc và xác nhận</p></div><button onClick={()=>setActive('Đơn đặt dịch vụ')}>Xem tất cả</button></div><Table rows={[["Oceanami Villas","0969 123 456","Mới"],["Ambassador Hạ Long","0988 234 567","Tư vấn"],["Tour Bắc Kinh","0912 345 678","Đã chốt"]]}/></section></div><section className="admin-panel"><div className="admin-panel-head"><div><h2>Sản phẩm nổi bật</h2><p>Những sản phẩm đang được quan tâm</p></div><button onClick={()=>setActive('Sản phẩm')}>Quản lý sản phẩm</button></div><Table rows={products}/></section></>}
{active==='Khách hàng / CRM'&&<AdminCustomers/>}{active==='Đơn đặt dịch vụ'&&<AdminBookings/>}{['Sản phẩm','Tour du lịch','Villa & Resort','Khách sạn','Du thuyền'].includes(active)&&<Products title={active}/>} 
{active==='Giao diện (Trang chủ)'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Chỉnh sửa trang chủ</h2><p>Banner, ô tìm kiếm, dịch vụ nổi bật, điểm đến và sản phẩm nổi bật.</p></div><button>Xem trước</button></div><div className="admin-form-row"><label>Tiêu đề chính<input defaultValue="Du lịch trọn gói – Nghỉ dưỡng đẳng cấp"/></label><label>Hotline<input defaultValue="0969 973 949"/></label></div><div className="admin-form-row"><label>Mô tả<input defaultValue="Vé · Tour · Villa · Resort · Du thuyền – Khám phá thế giới cùng chúng tôi!"/></label><label>Ảnh banner<input placeholder="Chọn từ thư viện media"/></label></div><div className="editor-actions"><button>Lưu nháp</button><button className="admin-primary">Lưu & xuất bản</button></div></section>}
{active==='Media (Ảnh/Video)'&&<section className="admin-panel"><div className="admin-panel-head"><div><h2>Media / Ảnh & Video</h2><p>Thư viện dùng chung cho sản phẩm, banner và bài viết.</p></div><button>+ Tải media</button></div><div className="drive-drop"><b>Kéo thả ảnh hoặc video vào đây</b><span>JPG, PNG, WebP, MP4</span><button className="admin-primary">Chọn tệp</button></div></section>}
{active==='Bài viết / Cẩm nang'&&<section className="admin-panel editor-panel"><div className="admin-panel-head"><div><h2>Trình soạn thảo bài viết</h2><p>Chỉnh sửa nội dung trực quan như Word.</p></div></div><div className="admin-form-row"><label>Tiêu đề<input placeholder="Nhập tiêu đề bài viết"/></label><label>Danh mục<select><option>Cẩm nang</option><option>Tour</option><option>Villa</option></select></label></div><div className="word-editor"><div className="editor-toolbar"><button><b>B</b></button><button><i>I</i></button><button>H2</button><button>H3</button><button>• Danh sách</button><button>🔗 Link</button><button>🖼 Ảnh</button><button>🎬 Video</button></div><div className="editor-canvas" contentEditable suppressContentEditableWarning><h2>Nội dung bài viết</h2><p>Bắt đầu nhập nội dung tại đây...</p></div></div><div className="editor-actions"><button>Lưu nháp</button><button className="admin-primary">Đăng bài</button></div></section>}
{active==='Cấu hình SEO'&&<section className="admin-panel"><h2>Cấu hình SEO</h2><p>Title, meta description, schema, sitemap và Open Graph.</p><div className="admin-form-row"><label>SEO Title<input defaultValue="Thúy Nguyên Travel - Tour, Villa, Khách sạn & Du thuyền"/></label><label>Slug<input defaultValue="/"/></label></div></section>}{active==='Google Drive'&&<section className="admin-panel"><h2>Google Drive → Website</h2><p>Nhập dữ liệu sản phẩm từ thư mục Drive, chuẩn hóa rồi tạo bản nháp.</p><div className="drive-drop"><b>Kết nối nguồn sản phẩm</b><span>Ảnh · Word · Excel · PDF</span><button className="admin-primary">Kết nối Google Drive</button></div></section>}{active==='Cài đặt'&&<section className="admin-panel"><h2>Cài đặt hệ thống</h2><div className="admin-form-row"><label>Tên thương hiệu<input defaultValue="Thúy Nguyên Travel"/></label><label>Hotline<input defaultValue="0969973949"/></label></div><div className="admin-form-row"><label>Email<input defaultValue="info@thuynguyentravel.com"/></label><label>Zalo<input defaultValue="0969973949"/></label></div></section>}</main></div>}
