import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor,type AdminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';

const ENTITY='admin_shared_state';
const KEY='happygo_customer_feedback_v1';
function elevated(actor:AdminActor){return actor.role==='owner'||actor.role==='admin'||actor.permissions.includes('*')}
function canSeeAll(actor:AdminActor){return elevated(actor)||actor.role!=='sales'}
function array(value:unknown):any[]{return Array.isArray(value)?value:[]}
function unwrap(value:unknown){const item=value as any;return item&&typeof item==='object'&&'value' in item?item.value:item}
function uuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
function text(value:unknown,max=4000){return String(value??'').trim().slice(0,max)}
async function latest(){const rows=await db()`select after_data from audit_logs where entity_type=${ENTITY} and entity_id=${KEY} order by created_at desc,id desc limit 1`;return rows[0]?unwrap(rows[0].after_data):undefined}
async function save(actor:AdminActor,value:unknown,action:string){const now=new Date().toISOString();await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},${action},${ENTITY},${KEY},${JSON.stringify({value,updatedAt:now,updatedBy:actor.name})}::jsonb)`}
async function bookingFor(actor:AdminActor,id:string){const sql=db();const rows=canSeeAll(actor)?await sql`select id,code,status,customer_id,customer_name_snapshot,phone_snapshot,email_snapshot,end_date,sales_staff_id,coalesce((select string_agg(product_name_snapshot,', ' order by id) from booking_items where booking_id=bookings.id),'') product_name from bookings where id=${id} limit 1`:await sql`select id,code,status,customer_id,customer_name_snapshot,phone_snapshot,email_snapshot,end_date,sales_staff_id,coalesce((select string_agg(product_name_snapshot,', ' order by id) from booking_items where booking_id=bookings.id),'') product_name from bookings where id=${id} and sales_staff_id=${actor.id} limit 1`;return rows[0]||null}
function ended(row:any){if(String(row.status)==='completed')return true;if(!row.end_date)return false;return +new Date(`${String(row.end_date).slice(0,10)}T23:59:59`)<Date.now()}

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});
 try{const sql=db(),[raw,bookings,staff]=await Promise.all([latest(),canSeeAll(actor)?sql`select b.id,b.code,b.status,b.customer_id,b.customer_name_snapshot,b.phone_snapshot,b.email_snapshot,b.end_date,b.sales_staff_id,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.id) from booking_items bi where bi.booking_id=b.id),'') product_name from bookings b where b.status<>'cancelled' order by coalesce(b.end_date,b.start_date) desc nulls last,b.created_at desc limit 1500`:sql`select b.id,b.code,b.status,b.customer_id,b.customer_name_snapshot,b.phone_snapshot,b.email_snapshot,b.end_date,b.sales_staff_id,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.id) from booking_items bi where bi.booking_id=b.id),'') product_name from bookings b where b.status<>'cancelled' and b.sales_staff_id=${actor.id} order by coalesce(b.end_date,b.start_date) desc nulls last,b.created_at desc limit 1500`,sql`select id,name from staff where status='active' order by name`]);const allowedIds=new Set(bookings.map((row:any)=>String(row.id))),items=array(raw).filter(item=>allowedIds.has(String(item?.bookingId||'')));
  return NextResponse.json({ok:true,items,bookings:bookings.filter((row:any)=>ended(row)).map((row:any)=>({id:String(row.id),code:String(row.code),customerId:String(row.customer_id||''),customerName:String(row.customer_name_snapshot||''),phone:String(row.phone_snapshot||''),email:String(row.email_snapshot||''),product:String(row.product_name||''),status:String(row.status),endDate:row.end_date?String(row.end_date).slice(0,10):'',salesStaffId:String(row.sales_staff_id||'')})),staff:staff.map((row:any)=>({id:String(row.id),name:String(row.name)})),capabilities:{manage:elevated(actor),actorId:actor.id,actorName:actor.name}},{headers:{'Cache-Control':'no-store, max-age=0'}})
 }catch(error){console.error('customer_feedback_get_failed',error);return NextResponse.json({error:'Không đọc được phản hồi khách hàng production.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({})),action=String(body.action||'');
 try{const items=array(await latest()),now=new Date().toISOString();
  if(action==='add'){
   const bookingId=String(body.bookingId||'');if(!uuid(bookingId))return NextResponse.json({error:'Booking không hợp lệ.'},{status:400});const booking=await bookingFor(actor,bookingId);if(!booking)return NextResponse.json({error:'Không tìm thấy booking hoặc không có quyền.'},{status:404});if(!ended(booking)||String(booking.status)==='cancelled')return NextResponse.json({error:'Chỉ ghi phản hồi cho booking đã kết thúc.'},{status:409});const rating=Math.max(1,Math.min(5,Math.round(Number(body.rating)||0))),kind=String(body.type||'normal');if(!['praise','normal','complaint'].includes(kind))return NextResponse.json({error:'Loại phản hồi không hợp lệ.'},{status:400});const content=text(body.content,6000),resolution=text(body.resolution,4000);if(!content)return NextResponse.json({error:'Cần nhập nội dung phản hồi.'},{status:400});let assignedToId='',assignedToName='',dueAt='';if(kind==='complaint'){assignedToId=String(body.assignedToId||'');if(!uuid(assignedToId))return NextResponse.json({error:'Khiếu nại cần người phụ trách.'},{status:400});const assignee=(await db()`select id,name from staff where id=${assignedToId} and status='active' limit 1`)[0];if(!assignee)return NextResponse.json({error:'Người phụ trách không còn hoạt động.'},{status:400});assignedToName=String(assignee.name);const due=new Date(String(body.dueAt||''));if(Number.isNaN(+due))return NextResponse.json({error:'Khiếu nại cần hạn xử lý hợp lệ.'},{status:400});dueAt=due.toISOString()}
   const id=randomUUID(),entry={id,bookingId,bookingCode:String(booking.code),customerId:String(booking.customer_id||''),customerName:String(booking.customer_name_snapshot||''),rating,type:kind,content,resolution,status:kind==='complaint'?'open':'resolved',createdAt:now,createdById:actor.id,createdBy:actor.name,...(kind==='complaint'?{assignedToId,assignedToName,dueAt}:{resolvedAt:now,resolvedBy:actor.name,resolvedById:actor.id})};await save(actor,[entry,...items].slice(0,10000),'customer_feedback.add');const customerId=String(booking.customer_id||'');if(uuid(customerId)){const label=kind==='complaint'?'Khiếu nại':kind==='praise'?'Khen ngợi':'Phản hồi';await db()`insert into crm_activities(customer_id,staff_id,type,content,next_follow_up_at) values(${customerId},${actor.id},'feedback',${`Phản hồi sau chuyến ${String(booking.code)}: ${rating}/5 sao · ${label} · ${content}${assignedToName?` · Phụ trách: ${assignedToName}`:''}`},${dueAt||null})`}return NextResponse.json({ok:true,id})
  }
  if(action==='resolve'){
   const id=String(body.id||''),current=items.find(item=>String(item?.id||'')===id);if(!current)return NextResponse.json({error:'Không tìm thấy phản hồi.'},{status:404});if(String(current.status)!=='open')return NextResponse.json({error:'Khiếu nại này đã được xử lý.'},{status:409});const booking=await bookingFor(actor,String(current.bookingId||''));if(!booking)return NextResponse.json({error:'Không có quyền với booking này.'},{status:403});if(!elevated(actor)&&String(current.assignedToId||'')!==actor.id)return NextResponse.json({error:'Chỉ người được giao hoặc Quản trị viên được đóng khiếu nại.'},{status:403});const resolution=text(body.resolution,6000);if(!resolution)return NextResponse.json({error:'Cần nhập kết quả xử lý.'},{status:400});const next=items.map(item=>String(item?.id||'')===id?{...item,resolution,status:'resolved',resolvedAt:now,resolvedBy:actor.name,resolvedById:actor.id}:item);await save(actor,next,'customer_feedback.resolve');const customerId=String(current.customerId||booking.customer_id||'');if(uuid(customerId))await db()`insert into crm_activities(customer_id,staff_id,type,content) values(${customerId},${actor.id},'complaint_resolved',${`Đã xử lý khiếu nại booking ${String(current.bookingCode||booking.code)}: ${resolution}`})`;return NextResponse.json({ok:true})
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400})
 }catch(error){console.error('customer_feedback_post_failed',error);return NextResponse.json({error:'Không thể cập nhật phản hồi khách hàng production.'},{status:500})}
}
