import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {GuideArticleReader} from '@/components/GuideArticleReader';
import type {PublicGuideArticle} from '@/components/usePublicGuideArticles';
import {PublicServiceNav} from '@/components/PublicServiceNav';
import {getPublishedGuideSeo} from '@/lib/public-guide-seo';
import {getPublicSiteState} from '@/lib/server/public-site-state';
import {getSiteUrl} from '@/lib/site-url';

type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const item=await getPublishedGuideSeo(slug);const base=getSiteUrl();const canonical=`${base}/cam-nang/bai-viet/${encodeURIComponent(slug)}`;if(!item)return{title:'Bài viết không tồn tại | HappyGo Travel',robots:{index:false,follow:true},alternates:{canonical}};const title=item.seoTitle||item.title;const description=item.seoDescription||item.excerpt;return{title,description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{title,description,url:canonical,type:'article',images:item.cover?[{url:item.cover,alt:item.title}]:undefined},twitter:{card:'summary_large_image',title,description,images:item.cover?[item.cover]:undefined}}}
export default async function CmsGuideArticlePage({params}:Props){const {slug}=await params;const[item,state]=await Promise.all([getPublishedGuideSeo(slug),getPublicSiteState()]);if(!item)notFound();const articles=Array.isArray(state.tn_cms_articles_v3)?state.tn_cms_articles_v3 as PublicGuideArticle[]:[];const initialArticles=articles.filter(article=>article.slug===slug);const base=getSiteUrl();const url=`${base}/cam-nang/bai-viet/${encodeURIComponent(slug)}`;const schema=[{'@context':'https://schema.org','@type':'Article',headline:item.title,description:item.excerpt,image:item.cover?[item.cover]:undefined,datePublished:item.date||undefined,dateModified:item.updatedAt||item.date||undefined,mainEntityOfPage:url,author:{'@type':'Organization',name:'HappyGo Travel'},publisher:{'@type':'Organization',name:'HappyGo Travel',url:base}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Trang chủ',item:base},{'@type':'ListItem',position:2,name:'Cẩm nang',item:`${base}/cam-nang`},{'@type':'ListItem',position:3,name:item.title,item:url}]}];return <div className="subpage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><section className="sub-hero compact"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / <Link href="/cam-nang">Cẩm nang</Link> / {item.category}</div><div className="sub-hero-grid"><div><span className="sub-kicker">CẨM NANG HAPPYGO TRAVEL</span><h1>{item.title}</h1>{item.excerpt&&<p>{item.excerpt}</p>}</div></div></div></section><PublicServiceNav active="guide"/><section className="sub-section white"><div className="container article-container"><GuideArticleReader slug={slug} initialArticles={initialArticles}/></div></section></div>}
