import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor,type AdminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';
const ENTITY='admin_shared_state',OPS_KEY='happygo_booking_ops_checklist_v1',LOG_KEY='happygo_booking_operator_history_v1',FOLLOWUPS_KEY='happygo_crm_followups_v1';
function elevated(a:AdminActor){return a.role==='owner'||a.role==='admin'||a.permissions.includes('*')}
function operations(a:AdminActor){return elevated(a)||a.role==='operations'}
function finance(a:AdminActor){return elevated(a)||a.role==='accounting'||a.permissions.includes('ledger')}
function readAll(a:AdminActor){return operations(a)||finance(a)}
function array(v:unknown):any[]{return Array.isArray(v)?v:[]}
function object(v:unknown):Record<string,any>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>: {}}
function unwrap(v:unknown){const x=v as any;return x&&typeof x==='object'&&'value' in x?x.value:x}
function uuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
async function latest(key:string){const r=await db()`select after_data from audit_logs where entity_type=${ENTITY} and entity_id=${key} order by created_at desc,id desc limit 1`;return r[0]?unwrap(r[0].after_data):undefined}
async function save(actor:AdminActor,key:string,value:unknown,action:string){const now=new Date().toISOString();await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},${action},${ENTITY},${key},${JSON.stringify({value,updatedAt:now,updatedBy:actor.name})}::jsonb)`}
function log(actor:AdminActor,bookingId:string,bookingCode:string,action:string,fromId='',fromName='',toId='',toName=''){return{id:randomUUID(),bookingId,bookingCode,action,fromId,fromName,toId,toName,changedById:actor.id,changedByName:actor.name,at:new Date().toISOString()}}
async function booking(actor:AdminActor,id:string){const sql=db();const rows=readAll(actor)?await sql`select id,code,status,customer_id,customer_name_snapshot,phone_snapshot,email_snapshot,start_date,end_date,selling_total_vnd,cost_total_vnd,sales_staff_id,sales_staff_name_snapshot from bookings where id=${id} limit 1`:await sql`select id,code,status,customer_id,customer_name_snapshot,phone_snapshot,email_snapshot,start_date,end_date,selling_total_vnd,cost_total_vnd,sales_staff_id,sales_staff_name_snapshot from bookings where id=${id} and sales_staff_id=${actor.id} limit 1`;return rows[0]||null}
async function totals(bookingId:string){const [receipts,payments]=await Promise.all([db()`select coalesce(sum(amount_vnd),0)::bigint total from payments where booking_id=${bookingId} and status='paid'`,db()`select coalesce(sum(coalesce(paid_amount_vnd,amount_vnd)),0)::bigint total from payment_requests where booking_id=${bookingId} and status='paid'`]);return{customerPaid:Number(receipts[0]?.total||0),supplierPaid:Number(payments[0]?.total||0)}}

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'bookings');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});
 try{const sql=db(),[opsRaw,logsRaw,rows,operators]=await Promise.all([latest(OPS_KEY),latest(LOG_KEY),readAll(actor)?sql`select b.id,b.code,b.status,b.customer_id,b.customer_name_snapshot,b.phone_snapshot,b.email_snapshot,b.start_date,b.end_date,b.selling_total_vnd,b.cost_total_vnd,b.sales_staff_id,b.sales_staff_name_snapshot,b.created_at,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.id) from booking_items bi where bi.booking_id=b.id),'') product_name,coalesce((select sum(p.amount_vnd) from payments p where p.booking_id=b.id and p.status='paid'),0)::bigint customer_paid,coalesce((select sum(coalesce(pr.paid_amount_vnd,pr.amount_vnd)) from payment_requests pr where pr.booking_id=b.id and pr.status='paid'),0)::bigint supplier_paid from bookings b where b.status<>'cancelled' order by b.created_at desc limit 1000`:sql`select b.id,b.code,b.status,b.customer_id,b.customer_name_snapshot,b.phone_snapshot,b.email_snapshot,b.start_date,b.end_date,b.selling_total_vnd,b.cost_total_vnd,b.sales_staff_id,b.sales_staff_name_snapshot,b.created_at,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.id) from booking_items bi where bi.booking_id=b.id),'') product_name,coalesce((select sum(p.amount_vnd) from payments p where p.booking_id=b.id and p.status='paid'),0)::bigint customer_paid,coalesce((select sum(coalesce(pr.paid_amount_vnd,pr.amount_vnd)) from payment_requests pr where pr.booking_id=b.id and pr.status='paid'),0)::bigint supplier_paid from bookings b where b.status<>'cancelled' and b.sales_staff_id=${actor.id} order by b.created_at desc limit 1000`,sql`select id,name,role,department,permissions from staff where status='active' and (role in ('operations','admin') or department in ('operations','resa')) order by name`]);const ops=object(opsRaw),logs=array(logsRaw);return NextResponse.json({ok:true,ops,logs,bookings:rows.map((r:any)=>({id:String(r.id),code:String(r.code),status:String(r.status),customerId:String(r.customer_id||''),customerName:String(r.customer_name_snapshot||''),phone:String(r.phone_snapshot||''),email:String(r.email_snapshot||''),startDate:r.start_date?String(r.start_date).slice(0,10):'',endDate:r.end_date?String(r.end_date).slice(0,10):'',sellingTotal:Number(r.selling_total_vnd||0),costTotal:r.cost_total_vnd===null?null:Number(r.cost_total_vnd),salesStaffId:String(r.sales_staff_id||''),salesStaffName:String(r.sales_staff_name_snapshot||''),product:String(r.product_name||''),customerPaid:Number(r.customer_paid||0),supplierPaid:Number(r.supplier_paid||0),createdAt:String(r.created_at)})),operators:operators.map((o:any)=>({id:String(o.id),name:String(o.name),role:String(o.role),department:String(o.department||'')})),capabilities:{editOps:operations(actor),finance:finance(actor),close:operations(actor),manager:elevated(actor),actorId:actor.id,actorName:actor.name,role:actor.role}} ,{headers:{'Cache-Control':'no-store, max-age=0'}})
 }catch(error){console.error('service_operations_get_failed',error);return NextResponse.json({error:'Không đọc được Điều hành dịch vụ production.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'bookings');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({})),action=String(body.action||''),bookingId=String(body.bookingId||'');if(!uuid(bookingId))return NextResponse.json({error:'Booking không hợp lệ.'},{status:400});const b=await booking(actor,bookingId);if(!b)return NextResponse.json({error:'Không tìm thấy booking hoặc không có quyền.'},{status:404});
 try{const ops=object(await latest(OPS_KEY)),current=object(ops[bookingId]),logs=array(await latest(LOG_KEY)),now=new Date().toISOString();
  if(action==='assign'){
   if(!operations(actor))return NextResponse.json({error:'Không có quyền phân Điều hành.'},{status:403});const operatorId=String(body.operatorId||''),fromId=String(current.operatorId||''),fromName=String(current.operatorName||'');let toId='',toName='';if(operatorId){if(!uuid(operatorId))return NextResponse.json({error:'Nhân viên không hợp lệ.'},{status:400});const person=(await db()`select id,name from staff where id=${operatorId} and status='active' and (role in ('operations','admin') or department in ('operations','resa')) limit 1`)[0];if(!person)return NextResponse.json({error:'Không tìm thấy Điều hành đang hoạt động.'},{status:400});toId=String(person.id);toName=String(person.name)}const next={...ops,[bookingId]:{...current,operatorId:toId,operatorName:toName,operatorAssignedAt:toId?now:'',operatorAssignedBy:actor.name,updatedAt:now,updatedBy:actor.name}};await save(actor,OPS_KEY,next,'booking_ops.assign');const kind=!toId?'unassign':fromId?'reassign':'assign';await save(actor,LOG_KEY,[log(actor,bookingId,String(b.code),kind,fromId,fromName,toId,toName),...logs].slice(0,5000),'booking_ops.operator_log');return NextResponse.json({ok:true})
  }
  if(action==='accept'){
   if(!operations(actor))return NextResponse.json({error:'Không có quyền nhận bàn giao.'},{status:403});if(current.handoffAccepted)return NextResponse.json({ok:true});const selfOps=actor.role==='operations'||elevated(actor);if(!current.operatorId&&!selfOps)return NextResponse.json({error:'Booking chưa có Điều hành phụ trách.'},{status:409});const takeover=Boolean(current.operatorId&&String(current.operatorId)!==actor.id&&actor.role==='operations'),fromId=String(current.operatorId||''),fromName=String(current.operatorName||''),toId=takeover||!current.operatorId?actor.id:fromId,toName=takeover||!current.operatorId?actor.name:fromName;const next={...ops,[bookingId]:{...current,handoffAccepted:true,handoffAcceptedAt:now,handoffAcceptedBy:actor.name,handoffAcceptedById:actor.id,operatorId:toId,operatorName:toName,operatorAssignedAt:current.operatorAssignedAt||now,operatorAssignedBy:current.operatorAssignedBy||actor.name,updatedAt:now,updatedBy:actor.name}};await save(actor,OPS_KEY,next,'booking_ops.accept');if((takeover||!fromId)&&toId){const kind=fromId?'reassign':'self_accept';await save(actor,LOG_KEY,[log(actor,bookingId,String(b.code),kind,fromId,fromName,toId,toName),...logs].slice(0,5000),'booking_ops.operator_log')}return NextResponse.json({ok:true})
  }
  if(action==='checklist'){
   if(!operations(actor))return NextResponse.json({error:'Không có quyền cập nhật checklist.'},{status:403});const changes=object(body.changes),safe:any={};for(const key of ['supplierConfirmed','voucherReady','customerConfirmationSent','finalCheck','supplierName','supplierContact','supplierRef','opsNote'])if(key in changes)safe[key]=typeof changes[key]==='string'?String(changes[key]).slice(0,4000):Boolean(changes[key]);const next={...ops,[bookingId]:{...current,...safe,updatedAt:now,updatedBy:actor.name}};await save(actor,OPS_KEY,next,'booking_ops.checklist');return NextResponse.json({ok:true})
  }
  if(action==='posttrip'){
   const changes=object(body.changes),safe:any={};if('customerCompleted' in changes){if(!operations(actor))return NextResponse.json({error:'Không có quyền xác nhận hoàn tất khách.'},{status:403});safe.customerCompleted=Boolean(changes.customerCompleted)}if('supplierReconciled' in changes){if(!operations(actor))return NextResponse.json({error:'Không có quyền đối soát NCC.'},{status:403});safe.supplierReconciled=Boolean(changes.supplierReconciled)}if('financeReconciled' in changes){if(!finance(actor))return NextResponse.json({error:'Không có quyền đối soát tài chính.'},{status:403});safe.financeReconciled=Boolean(changes.financeReconciled)}if('afterTripNote' in changes)safe.afterTripNote=String(changes.afterTripNote||'').slice(0,4000);const next={...ops,[bookingId]:{...current,...safe,updatedAt:now,updatedBy:actor.name}};await save(actor,OPS_KEY,next,'booking_ops.posttrip');return NextResponse.json({ok:true})
  }
  if(action==='close'){
   if(!operations(actor))return NextResponse.json({error:'Không có quyền đóng booking.'},{status:403});const latestOps=object((object(await latest(OPS_KEY)))[bookingId]);if(!latestOps.customerCompleted||!latestOps.supplierReconciled||!latestOps.financeReconciled)return NextResponse.json({error:'Cần hoàn tất đủ khách hàng, NCC và tài chính trước khi đóng.'},{status:409});const sums=await totals(bookingId),customerDue=Math.max(0,Number(b.selling_total_vnd||0)-sums.customerPaid),supplierDue=Math.max(0,Number(b.cost_total_vnd||0)-sums.supplierPaid);if(customerDue>0||supplierDue>0)return NextResponse.json({error:`Chưa thể đóng: còn phải thu ${customerDue.toLocaleString('vi-VN')}đ, còn phải chi ${supplierDue.toLocaleString('vi-VN')}đ.`},{status:409});await db()`update bookings set status='completed',completed_at=coalesce(completed_at,now()),updated_at=now() where id=${bookingId}`;const allOps=object(await latest(OPS_KEY)),closed={...allOps,[bookingId]:{...object(allOps[bookingId]),closedAt:now,closedBy:actor.name,updatedAt:now,updatedBy:actor.name}};await save(actor,OPS_KEY,closed,'booking_ops.close');const customerId=String(b.customer_id||'');if(customerId&&uuid(customerId)){const due=new Date(Date.now()+2*86400000).toISOString(),content=`Booking ${String(b.code)} đã hoàn tất và đối soát xong. Chăm sóc sau chuyến.`;await db()`insert into crm_activities(customer_id,staff_id,type,content,next_follow_up_at) values(${customerId},${actor.id},'post_trip',${content},${due})`;const c=(await db()`select name,phone,email from customers where id=${customerId} limit 1`)[0],tasks=array(await latest(FOLLOWUPS_KEY)),key=String(c?.phone||'').replace(/\D/g,'')?`phone:${String(c.phone).replace(/\D/g,'')}`:`email:${String(c?.email||'').toLowerCase()}`;if(!tasks.some(t=>String(t?.customerId||'')===customerId&&String(t?.title||'').includes(String(b.code)))){const task={id:randomUUID(),customerId,customerKey:key,customerName:String(c?.name||b.customer_name_snapshot||''),phone:String(c?.phone||b.phone_snapshot||''),bookingCode:String(b.code),title:`Chăm sóc sau chuyến · ${String(b.code)}`,dueAt:due,status:'open',note:'Hỏi trải nghiệm, xin đánh giá và gợi ý hành trình tiếp theo.',createdBy:actor.name,createdById:actor.id,createdAt:now};await save(actor,FOLLOWUPS_KEY,[task,...tasks].slice(0,5000),'crm.followup.posttrip')}}await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'booking.close','booking',${bookingId},${JSON.stringify({customerPaid:sums.customerPaid,supplierPaid:sums.supplierPaid,closedBy:actor.name})}::jsonb)`;return NextResponse.json({ok:true})
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400})
 }catch(error){console.error('service_operations_post_failed',error);return NextResponse.json({error:'Không thể cập nhật Điều hành dịch vụ production.'},{status:500})}
}
