import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor,type AdminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';

const ENTITY='admin_shared_state';
const PROPOSALS='happygo_marketing_budget_proposals_v1';
const EXPENSES='happygo_marketing_expenses_v1';
const proposalStatuses=new Set(['draft','pending','changes_requested','approved','rejected']);
function elevated(actor:AdminActor){return actor.role==='owner'||actor.role==='admin'||actor.permissions.includes('*')}
function array(value:unknown):any[]{return Array.isArray(value)?value:[]}
function unwrap(value:unknown){const item=value as any;return item&&typeof item==='object'&&'value' in item?item.value:item}
function amount(value:unknown){const n=Math.round(Number(value)||0);return Number.isFinite(n)?Math.max(0,n):0}
function text(value:unknown,max=4000){return String(value??'').trim().slice(0,max)}
async function latest(key:string){const rows=await db()`select after_data from audit_logs where entity_type=${ENTITY} and entity_id=${key} order by created_at desc,id desc limit 1`;return rows[0]?unwrap(rows[0].after_data):undefined}
async function save(actor:AdminActor,key:string,value:unknown,action:string){const now=new Date().toISOString();await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},${action},${ENTITY},${key},${JSON.stringify({value,updatedAt:now,updatedBy:actor.name})}::jsonb)`}
function audit(actor:AdminActor,action:string,detail=''){return{id:randomUUID(),at:new Date().toISOString(),byId:actor.id,byName:actor.name,action,detail}}

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'email');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});
 try{const [proposalsRaw,expensesRaw]=await Promise.all([latest(PROPOSALS),latest(EXPENSES)]);return NextResponse.json({ok:true,proposals:array(proposalsRaw),expenses:array(expensesRaw),capabilities:{work:true,manage:elevated(actor),actorId:actor.id,actorName:actor.name}},{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(error){console.error('marketing_budget_get_failed',error);return NextResponse.json({error:'Không đọc được ngân sách Marketing production.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'email');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({})),action=String(body.action||'');
 try{const [proposalsRaw,expensesRaw]=await Promise.all([latest(PROPOSALS),latest(EXPENSES)]),proposals=array(proposalsRaw),expenses=array(expensesRaw),manager=elevated(actor),now=new Date().toISOString();
  if(action==='saveProposal'){
   const id=text(body.id,100),current=id?proposals.find(item=>String(item?.id||'')===id):null,submit=Boolean(body.submit);if(current&&!manager&&String(current.createdById||'')!==actor.id)return NextResponse.json({error:'Bạn chỉ được sửa đề xuất do mình tạo.'},{status:403});if(current&&!manager&&!['draft','changes_requested'].includes(String(current.status)))return NextResponse.json({error:'Đề xuất đã trình duyệt nên không thể sửa.'},{status:409});const title=text(body.title,300),campaign=text(body.campaign,300),month=text(body.month,7),channel=text(body.channel,100),objective=text(body.objective,300),startDate=text(body.startDate,10),endDate=text(body.endDate,10),requestedAmount=amount(body.requestedAmount),expectedLeads=amount(body.expectedLeads),expectedRevenue=amount(body.expectedRevenue),justification=text(body.justification,6000),note=text(body.note,4000);if(!title||!campaign||!/^[0-9]{4}-[0-9]{2}$/.test(month)||requestedAmount<=0||!justification)return NextResponse.json({error:'Thông tin đề xuất chưa đầy đủ.'},{status:400});if(startDate&&endDate&&endDate<startDate)return NextResponse.json({error:'Ngày kết thúc phải sau ngày bắt đầu.'},{status:400});const status=submit?'pending':current?.status==='changes_requested'?'changes_requested':'draft',entry=current?{...current,title,campaign,month,channel,objective,startDate,endDate,requestedAmount,expectedLeads,expectedRevenue,justification,note,status,updatedAt:now,...(submit?{submittedAt:now}:{}),audit:[...array(current.audit),audit(actor,submit?'Cập nhật và trình duyệt':'Cập nhật đề xuất',`${requestedAmount} · ${channel}`)]}:{id:randomUUID(),title,campaign,month,channel,objective,startDate,endDate,requestedAmount,approvedAmount:0,expectedLeads,expectedRevenue,justification,note,status,createdById:actor.id,createdByName:actor.name,createdAt:now,updatedAt:now,...(submit?{submittedAt:now}:{}),audit:[audit(actor,submit?'Tạo và trình duyệt':'Tạo đề xuất nháp',`${requestedAmount} · ${channel}`)]};const next=current?proposals.map(item=>String(item?.id||'')===String(entry.id)?entry:item):[entry,...proposals];await save(actor,PROPOSALS,next.slice(0,5000),'marketing.proposal.save');return NextResponse.json({ok:true,id:entry.id})
  }
  if(action==='decision'){
   if(!manager)return NextResponse.json({error:'Chỉ Chủ tài khoản/Quản trị viên được duyệt ngân sách.'},{status:403});const id=text(body.id,100),decision=text(body.decision,30);if(!proposalStatuses.has(decision)||!['approved','changes_requested','rejected'].includes(decision))return NextResponse.json({error:'Quyết định không hợp lệ.'},{status:400});const current=proposals.find(item=>String(item?.id||'')===id);if(!current)return NextResponse.json({error:'Không tìm thấy đề xuất.'},{status:404});if(String(current.status)!=='pending')return NextResponse.json({error:'Chỉ đề xuất đang Chờ duyệt mới được quyết định.'},{status:409});const approvedAmount=decision==='approved'?amount(body.approvedAmount):Number(current.approvedAmount||0);if(decision==='approved'&&approvedAmount<=0)return NextResponse.json({error:'Ngân sách duyệt phải lớn hơn 0.'},{status:400});const reason=text(body.reason,4000);if((decision==='changes_requested'||decision==='rejected')&&!reason)return NextResponse.json({error:'Cần ghi nội dung xử lý.'},{status:400});const changes=decision==='approved'?{status:'approved',approvedAmount,approvedAt:now,approvedBy:actor.name}:decision==='rejected'?{status:'rejected',rejectedAt:now,rejectedBy:actor.name,note:reason}:{status:'changes_requested',note:reason};const actionLabel=decision==='approved'?'Đã duyệt ngân sách':decision==='rejected'?'Từ chối đề xuất':'Yêu cầu bổ sung';const next=proposals.map(item=>String(item?.id||'')===id?{...item,...changes,updatedAt:now,audit:[...array(item.audit),audit(actor,actionLabel,decision==='approved'?String(approvedAmount):reason)]}:item);await save(actor,PROPOSALS,next,'marketing.proposal.decision');return NextResponse.json({ok:true})
  }
  if(action==='addExpense'){
   const proposalId=text(body.proposalId,100),proposal=proposalId?proposals.find(item=>String(item?.id||'')===proposalId):null;if(proposalId&&!proposal)return NextResponse.json({error:'Không tìm thấy đề xuất ngân sách.'},{status:404});if(proposal&&String(proposal.status)!=='approved')return NextResponse.json({error:'Chỉ được ghi chi phí vào đề xuất đã duyệt.'},{status:409});if(!proposal&&!manager)return NextResponse.json({error:'Nhân viên Marketing phải chọn đề xuất đã duyệt trước khi ghi chi phí.'},{status:409});const date=text(body.date,10),campaign=text(body.campaign||proposal?.campaign,300),category=text(body.category,200),channel=text(body.channel||proposal?.channel,100),vendor=text(body.vendor,300),value=amount(body.amount),documentRef=text(body.documentRef,300),note=text(body.note,4000);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!campaign||!vendor||value<=0)return NextResponse.json({error:'Thông tin chi phí chưa đầy đủ.'},{status:400});if(proposal&&amount(proposal.approvedAmount)>0){const spent=expenses.filter(item=>String(item?.proposalId||'')===proposalId).reduce((sum,item)=>sum+amount(item?.amount),0);if(spent+value>amount(proposal.approvedAmount)&&!manager)return NextResponse.json({error:'Khoản chi vượt ngân sách đã duyệt; cần Quản trị viên xử lý.'},{status:409})}const entry={id:randomUUID(),proposalId,campaign,month:date.slice(0,7),date,category,channel,vendor,amount:value,documentRef,note,createdById:actor.id,createdByName:actor.name,createdAt:now};await save(actor,EXPENSES,[entry,...expenses].slice(0,10000),'marketing.expense.create');return NextResponse.json({ok:true,id:entry.id})
  }
  if(action==='deleteExpense'){
   if(!manager)return NextResponse.json({error:'Chỉ Chủ tài khoản/Quản trị viên được xóa chi phí.'},{status:403});const id=text(body.id,100);if(!expenses.some(item=>String(item?.id||'')===id))return NextResponse.json({error:'Không tìm thấy chi phí.'},{status:404});await save(actor,EXPENSES,expenses.filter(item=>String(item?.id||'')!==id),'marketing.expense.delete');return NextResponse.json({ok:true})
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400})
 }catch(error){console.error('marketing_budget_post_failed',error);return NextResponse.json({error:'Không thể cập nhật ngân sách Marketing production.'},{status:500})}
}
