import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function money(value:unknown){const digits=String(value??'').replace(/[^0-9]/g,'');return digits?Math.max(0,Number(digits)):0}
function meta(label:unknown){const raw=String(label||'');try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==='object'?parsed:{note:raw}}catch{return{note:raw}}}
function label(body:any){return JSON.stringify({note:String(body.note||'').slice(0,1000),status:['available','hold','soldout'].includes(String(body.status))?String(body.status):'available',minStay:Math.max(1,Number(body.minStay)||1),oldPrice:String(body.oldPrice||'').slice(0,80)})}
async function unitAccess(sql:ReturnType<typeof db>,unitId:string){const rows=await sql`select u.id,u.product_id,u.name,u.code,p.name product_name,p.type,p.data product_data,u.data unit_data from product_units u join products p on p.id=u.product_id where u.id=${unitId} and p.partner_id is null limit 1`;return rows[0]||null}

export async function GET(req:NextRequest){if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'rates');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});try{const sql=db(),[products,units,rules]=await Promise.all([sql`select id,name,type,slug,status,data from products where partner_id is null and type in('Villa & Resort','Khách sạn','Du thuyền') and status<>'hidden' order by name`,sql`select u.id,u.product_id,u.code,u.name,u.retail_price_vnd,u.data,u.status from product_units u join products p on p.id=u.product_id where p.partner_id is null and p.type in('Villa & Resort','Khách sạn','Du thuyền') and p.status<>'hidden' order by u.name`,sql`select r.* from rate_rules r join products p on p.id=r.product_id where p.partner_id is null order by r.start_date,r.id`]);const items=products.map((product:any)=>{const data=product.data&&typeof product.data==='object'?product.data:{};return{id:String(product.id),name:String(product.name),type:String(product.type),slug:String(product.slug),place:String(data.place||''),status:String(product.status),units:units.filter((unit:any)=>String(unit.product_id)===String(product.id)).map((unit:any)=>({...(unit.data&&typeof unit.data==='object'?unit.data:{}),id:String(unit.id),code:String(unit.code||''),name:String(unit.name||''),weekdayPrice:String((unit.data as any)?.weekdayPrice||unit.retail_price_vnd||''),status:String(unit.status||'available')}))}});const rateItems=rules.map((rule:any)=>{const extra=meta(rule.label);return{id:String(rule.id),productId:String(rule.product_id),unitId:String(rule.unit_id||''),start:String(rule.start_date).slice(0,10),end:String(rule.end_date).slice(0,10),price:String(rule.retail_price_vnd||''),oldPrice:String((extra as any).oldPrice||''),quantity:String(rule.inventory??0),minStay:String((extra as any).minStay||1),status:String((extra as any).status||(Number(rule.inventory)===0?'soldout':'available')),note:String((extra as any).note||'')}});return NextResponse.json({ok:true,products:items,rates:rateItems},{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(error){console.error('admin_rates_get_failed',error);return NextResponse.json({error:'Không đọc được lịch giá production.'},{status:500})}}

export async function POST(req:NextRequest){if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'rates');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({})),action=String(body.action||'');try{const sql=db();if(action==='save'){const unitId=String(body.unitId||''),start=String(body.start||''),end=String(body.end||''),price=money(body.price),status=String(body.status||'available');if(!uuid.test(unitId)||!/\d{4}-\d{2}-\d{2}/.test(start)||!/\d{4}-\d{2}-\d{2}/.test(end)||end<start)return NextResponse.json({error:'Khoảng ngày hoặc đơn vị bán không hợp lệ.'},{status:400});if(status==='available'&&price<=0)return NextResponse.json({error:'Cần nhập giá bán hợp lệ.'},{status:400});const unit=await unitAccess(sql,unitId);if(!unit)return NextResponse.json({error:'Không tìm thấy căn/phòng/cabin production.'},{status:404});const id=uuid.test(String(body.id||''))?String(body.id):randomUUID(),inventory=status==='soldout'?0:Math.max(0,Number(body.quantity)||0);await sql`insert into rate_rules(id,product_id,unit_id,start_date,end_date,retail_price_vnd,net_price_vnd,inventory,label) values(${id},${String(unit.product_id)},${unitId},${start},${end},${price},null,${inventory},${label(body)}) on conflict(id) do update set start_date=excluded.start_date,end_date=excluded.end_date,retail_price_vnd=excluded.retail_price_vnd,inventory=excluded.inventory,label=excluded.label`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'rate.save','rate_rule',${id},${JSON.stringify({unitId,start,end,price,inventory,status})}::jsonb)`;return NextResponse.json({ok:true,id})}if(action==='delete'){const id=String(body.id||'');if(!uuid.test(id))return NextResponse.json({error:'Khoảng giá không hợp lệ.'},{status:400});const current=(await sql`select r.id,r.product_id,r.unit_id,r.start_date,r.end_date,r.retail_price_vnd from rate_rules r join products p on p.id=r.product_id where r.id=${id} and p.partner_id is null limit 1`)[0];if(!current)return NextResponse.json({error:'Không tìm thấy khoảng giá.'},{status:404});await sql`delete from rate_rules where id=${id}`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,before_data) values(${actor.id},'rate.delete','rate_rule',${id},${JSON.stringify(current)}::jsonb)`;return NextResponse.json({ok:true})}return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400})}catch(error){console.error('admin_rates_post_failed',error);return NextResponse.json({error:'Không thể cập nhật lịch giá production.'},{status:500})}}
