import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {tours} from '@/data/catalog';
import {TourDetailClient} from '@/components/TourDetailClient';
import {CmsTourDetail} from '@/components/CmsTourDetail';
import {getPublishedTourSeo} from '@/lib/public-tour-seo';
import {getSiteUrl} from '@/lib/site-url';

const amount=(v?:string)=>{const n=String(v||'').replace(/\D/g,'');return n?Number(n):undefined};
export function generateStaticParams(){return tours.map(t=>({slug:t.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const base=getSiteUrl();const canonical=`${base}/tour-du-lich/${encodeURIComponent(slug)}`;const t=tours.find(x=>x.slug===slug);if(t)return{title:t.seoTitle||`${t.name} - ${t.duration}`,description:t.seoDescription||t.summary,alternates:{canonical},openGraph:{title:t.name,description:t.summary,url:canonical,images:[{url:t.image,alt:t.name}],type:'website'},twitter:{card:'summary_large_image',title:t.name,description:t.summary,images:[t.image]}};const cms=await getPublishedTourSeo(slug);if(!cms)return{title:'Tour không tồn tại | HappyGo Travel',robots:{index:false,follow:true},alternates:{canonical}};const title=cms.seoTitle||`${cms.name}${cms.duration?` - ${cms.duration}`:''}`;const description=cms.seoDescription||cms.summary;return{title,description,alternates:{canonical},robots:{index:true,follow:true},openGraph:{title:cms.name,description,url:canonical,type:'website',images:cms.cover?[{url:cms.cover,alt:cms.name}]:undefined},twitter:{card:'summary_large_image',title:cms.name,description,images:cms.cover?[cms.cover]:undefined}}}
export default async function TourDetailPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const base=getSiteUrl();const t=tours.find(x=>x.slug===slug);if(t){const url=`${base}/tour-du-lich/${t.slug}`;const price=amount(t.priceFrom);const trip:any={"@context":"https://schema.org","@type":"TouristTrip","name":t.name,"description":t.summary,"image":[t.image,...(t.gallery||[])],"url":url,"touristType":"Du khách Việt Nam","provider":{"@type":"TravelAgency","name":"HappyGo Travel","url":base,"telephone":"+84969973949"}};if(price)trip.offers={"@type":"Offer","priceCurrency":"VND","price":price,"url":url,"availability":"https://schema.org/InStock"};if(t.rating&&t.reviewCount)trip.aggregateRating={"@type":"AggregateRating","ratingValue":t.rating,"reviewCount":t.reviewCount,"bestRating":10,"worstRating":1};const schema:any[]=[trip,{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Trang chủ","item":base},{"@type":"ListItem","position":2,"name":"Tour du lịch","item":`${base}/tour-du-lich`},{"@type":"ListItem","position":3,"name":t.name,"item":url}]}];if(t.faq?.length)schema.push({"@context":"https://schema.org","@type":"FAQPage","mainEntity":t.faq.map(x=>({"@type":"Question","name":x.q,"acceptedAnswer":{"@type":"Answer","text":x.a}}))});return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><TourDetailClient base={t}/></>};const cms=await getPublishedTourSeo(slug);if(!cms)notFound();const url=`${base}/tour-du-lich/${encodeURIComponent(slug)}`;const price=amount(cms.price);const schema:any[]=[{"@context":"https://schema.org","@type":"TouristTrip","name":cms.name,"description":cms.summary,"image":[cms.cover,...cms.gallery].filter(Boolean),"url":url,"provider":{"@type":"TravelAgency","name":"HappyGo Travel","url":base,"telephone":"+84969973949"},...(price?{offers:{"@type":"Offer","priceCurrency":"VND","price":price,"url":url,"availability":"https://schema.org/InStock"}}:{})},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Trang chủ","item":base},{"@type":"ListItem","position":2,"name":"Tour du lịch","item":`${base}/tour-du-lich`},{"@type":"ListItem","position":3,"name":cms.name,"item":url}]}];return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><CmsTourDetail slug={slug}/></>}
