import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor,type AdminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';
const ENTITY='admin_shared_state',FOLLOWUPS='happygo_crm_followups_v1';
function elevated(a:AdminActor){return a.role==='owner'||a.role==='admin'||a.permissions.includes('*')}
function array(v:unknown):any[]{return Array.isArray(v)?v:[]}
function unwrap(v:unknown){const x=v as any;return x&&typeof x==='object'&&'value' in x?x.value:x}
function normalizePhone(v:string){const d=String(v||'').replace(/\D/g,'');return d.startsWith('84')&&d.length===11?`0${d.slice(2)}`:d}
function key(phone:string,email:string){const p=normalizePhone(phone);return p?`phone:${p}`:`email:${String(email||'').trim().toLowerCase()}`}
async function latest(k:string){const r=await db()`select after_data from audit_logs where entity_type=${ENTITY} and entity_id=${k} order by created_at desc,id desc limit 1`;return r[0]?unwrap(r[0].after_data):undefined}
async function save(actor:AdminActor,k:string,value:unknown,action:string){const now=new Date().toISOString();await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},${action},${ENTITY},${k},${JSON.stringify({value,updatedAt:now,updatedBy:actor.name})}::jsonb)`}
async function customer(actor:AdminActor,phone:string,email:string){const sql=db(),p=normalizePhone(phone),e=String(email||'').trim().toLowerCase();const rows=p?await sql`select c.id,c.name,c.phone,c.email,ca.staff_id from customers c left join customer_assignments ca on ca.customer_id=c.id where c.phone=${p} limit 1`:e?await sql`select c.id,c.name,c.phone,c.email,ca.staff_id from customers c left join customer_assignments ca on ca.customer_id=c.id where lower(coalesce(c.email,''))=${e} limit 1`:[];const c=rows[0];if(!c||(!elevated(actor)&&String(c.staff_id||'')!==actor.id))return null;return{id:String(c.id),name:String(c.name||''),phone:String(c.phone||''),email:String(c.email||''),staffId:String(c.staff_id||'')}}

export async function GET(req:NextRequest){if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});try{const c=await customer(actor,req.nextUrl.searchParams.get('phone')||'',req.nextUrl.searchParams.get('email')||'');if(!c)return NextResponse.json({error:'Không tìm thấy khách hoặc không có quyền.'},{status:404});const rows=await db()`select a.id,a.type,a.content,a.next_follow_up_at,a.created_at,a.staff_id,s.name staff_name from crm_activities a left join staff s on s.id=a.staff_id where a.customer_id=${c.id} order by a.created_at desc limit 1000`;return NextResponse.json({ok:true,customer:c,items:rows.map((r:any)=>({id:String(r.id),type:String(r.type||'note'),content:String(r.content||''),result:String(r.type||'note'),staffId:String(r.staff_id||''),staffName:String(r.staff_name||'Hệ thống'),createdAt:String(r.created_at),nextAt:r.next_follow_up_at?String(r.next_follow_up_at):''}))},{headers:{'Cache-Control':'no-store, max-age=0'}})}catch(error){console.error('crm_history_get_failed',error);return NextResponse.json({error:'Không đọc được lịch sử CRM production.'},{status:500})}}

export async function POST(req:NextRequest){if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({}));try{const c=await customer(actor,String(body.phone||''),String(body.email||''));if(!c)return NextResponse.json({error:'Không tìm thấy khách hoặc không có quyền.'},{status:404});const type=String(body.type||'note').slice(0,100),result=String(body.result||'Đã liên hệ').trim().slice(0,300),content=String(body.content||'').trim().slice(0,5000),nextAt=String(body.nextAt||'');if(!content)return NextResponse.json({error:'Nội dung chăm sóc không được để trống.'},{status:400});if(nextAt&&Number.isNaN(+new Date(nextAt)))return NextResponse.json({error:'Thời gian chăm sóc tiếp không hợp lệ.'},{status:400});const text=result?`${result} · ${content}`:content,rows=await db()`insert into crm_activities(customer_id,staff_id,type,content,next_follow_up_at) values(${c.id},${actor.id},${type},${text},${nextAt?new Date(nextAt).toISOString():null}) returning id,created_at`;if(nextAt){const tasks=array(await latest(FOLLOWUPS)),now=new Date().toISOString(),task={id:randomUUID(),customerId:c.id,customerKey:key(c.phone,c.email),customerName:c.name,phone:c.phone,title:`Chăm sóc tiếp: ${result}`,dueAt:new Date(nextAt).toISOString(),status:'open',note:content,createdBy:actor.name,createdById:actor.id,createdAt:now,historyId:String(rows[0].id)};await save(actor,FOLLOWUPS,[task,...tasks].slice(0,5000),'crm.followup.from_history')}return NextResponse.json({ok:true,id:String(rows[0].id),createdAt:String(rows[0].created_at)})}catch(error){console.error('crm_history_post_failed',error);return NextResponse.json({error:'Không lưu được lịch sử CRM production.'},{status:500})}}
