import {NextRequest,NextResponse} from 'next/server';
import {randomUUID} from 'node:crypto';
import {db,hasDatabase} from '@/lib/db';
import {adminActor,type AdminActor} from '@/lib/server/admin-access';

export const dynamic='force-dynamic';
export const runtime='nodejs';
const ENTITY='admin_shared_state',KEY='happygo_crm_opportunities_v1',PIPELINE='happygo_crm_pipeline_v1';
function elevated(a:AdminActor){return a.role==='owner'||a.role==='admin'||a.permissions.includes('*')}
function object(v:unknown):Record<string,any>{return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>: {}}
function array(v:unknown):any[]{return Array.isArray(v)?v:[]}
function unwrap(v:unknown){const x=v as any;return x&&typeof x==='object'&&'value' in x?x.value:x}
function normalizePhone(v:string){const d=String(v||'').replace(/\D/g,'');return d.startsWith('84')&&d.length===11?`0${d.slice(2)}`:d}
function customerKey(phone:string,email:string){const p=normalizePhone(phone);return p?`phone:${p}`:`email:${String(email||'').trim().toLowerCase()}`}
function code(){const d=new Date();return `HG${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
async function latest(key:string){const rows=await db()`select after_data from audit_logs where entity_type=${ENTITY} and entity_id=${key} order by created_at desc,id desc limit 1`;return rows[0]?unwrap(rows[0].after_data):undefined}
async function save(actor:AdminActor,key:string,value:unknown,action:string){const now=new Date().toISOString();await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},${action},${ENTITY},${key},${JSON.stringify({value,updatedAt:now,updatedBy:actor.name})}::jsonb)`}
async function resolveCustomer(actor:AdminActor,phone:string,email:string){const sql=db(),p=normalizePhone(phone),e=String(email||'').trim().toLowerCase();const rows=p?await sql`select c.id,c.name,c.phone,c.email,c.source,ca.staff_id,st.name staff_name from customers c left join customer_assignments ca on ca.customer_id=c.id left join staff st on st.id=ca.staff_id where c.phone=${p} limit 1`:e?await sql`select c.id,c.name,c.phone,c.email,c.source,ca.staff_id,st.name staff_name from customers c left join customer_assignments ca on ca.customer_id=c.id left join staff st on st.id=ca.staff_id where lower(coalesce(c.email,''))=${e} limit 1`:[];const c=rows[0];if(!c)return null;if(!elevated(actor)&&String(c.staff_id||'')!==actor.id)return null;return{id:String(c.id),name:String(c.name||''),phone:String(c.phone||''),email:String(c.email||''),source:String(c.source||''),staffId:String(c.staff_id||''),staffName:String(c.staff_name||'')}}

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const phone=req.nextUrl.searchParams.get('phone')||'',email=req.nextUrl.searchParams.get('email')||'';
 try{const customer=await resolveCustomer(actor,phone,email);if(!customer)return NextResponse.json({error:'Không tìm thấy khách hoặc không có quyền.'},{status:404});const key=customerKey(customer.phone,customer.email),all=object(await latest(KEY)),pipeline=object(await latest(PIPELINE));return NextResponse.json({ok:true,customer,key,data:object(all[key]),pipeline:pipeline[key]||null,actor:{id:actor.id,name:actor.name}} ,{headers:{'Cache-Control':'no-store, max-age=0'}})
 }catch(error){console.error('crm_opportunity_get_failed',error);return NextResponse.json({error:'Không đọc được nhu cầu/báo giá production.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'customers');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({})),phone=String(body.phone||''),email=String(body.email||''),action=String(body.action||'');
 try{const customer=await resolveCustomer(actor,phone,email);if(!customer)return NextResponse.json({error:'Không tìm thấy khách hoặc không có quyền.'},{status:404});const key=customerKey(customer.phone,customer.email),all=object(await latest(KEY)),current=object(all[key]),quotes=array(current.quotes),now=new Date().toISOString();
  if(action==='need.save'){
   const raw=object(body.need),need={destination:String(raw.destination||'').slice(0,300),startDate:String(raw.startDate||''),endDate:String(raw.endDate||''),adults:Math.max(0,Number(raw.adults)||0),children:Math.max(0,Number(raw.children)||0),rooms:Math.max(0,Number(raw.rooms)||0),budget:Math.max(0,Math.round(Number(raw.budget)||0)),service:String(raw.service||'Dịch vụ du lịch').slice(0,200),detail:String(raw.detail||'').slice(0,5000),updatedAt:now};const next={...all,[key]:{...current,need}};await save(actor,KEY,next,'crm_opportunity.need');await db()`insert into crm_activities(customer_id,staff_id,type,content) values(${customer.id},${actor.id},'need_update',${`Cập nhật nhu cầu: ${need.destination||'Chưa chọn điểm đến'} · ${need.service}`})`;return NextResponse.json({ok:true,need})
  }
  if(action==='quote.create'){
   const amount=Math.max(0,Math.round(Number(body.amount)||0)),title=String(body.title||'').trim().slice(0,500),detail=String(body.detail||'').trim().slice(0,10000),validUntil=String(body.validUntil||''),basedOnId=String(body.basedOnId||'');if(amount<=0||!title)return NextResponse.json({error:'Nhập tên phương án và giá báo khách.'},{status:400});const version=Math.max(0,...quotes.map(q=>Number(q?.version||0)))+1,quote={id:randomUUID(),version,amount,title,detail,validUntil,status:'draft',createdAt:now,createdBy:actor.name,createdById:actor.id,...(basedOnId?{basedOnId}: {})};const next={...all,[key]:{...current,quotes:[quote,...quotes]}};await save(actor,KEY,next,'crm_opportunity.quote_create');await db()`insert into crm_activities(customer_id,staff_id,type,content) values(${customer.id},${actor.id},'quote_create',${`Báo giá V${version}: ${title} · ${amount.toLocaleString('vi-VN')}đ`})`;return NextResponse.json({ok:true,quote})
  }
  if(action==='quote.status'){
   const id=String(body.id||''),status=String(body.status||'');if(!['draft','sent','accepted','rejected'].includes(status))return NextResponse.json({error:'Trạng thái báo giá không hợp lệ.'},{status:400});const found=quotes.find(q=>String(q?.id||'')===id);if(!found)return NextResponse.json({error:'Không tìm thấy báo giá.'},{status:404});const reason=status==='rejected'?String(body.rejectionReason||'').trim().slice(0,1000):String(found.rejectionReason||'');if(status==='rejected'&&!reason)return NextResponse.json({error:'Cần ghi lý do khách từ chối.'},{status:400});const nextQuotes=quotes.map(q=>String(q?.id||'')===id?{...q,status,rejectionReason:status==='rejected'?reason:q.rejectionReason,sentAt:status==='sent'?(q.sentAt||now):q.sentAt,acceptedAt:status==='accepted'?now:q.acceptedAt,rejectedAt:status==='rejected'?now:q.rejectedAt}:q);await save(actor,KEY,{...all,[key]:{...current,quotes:nextQuotes}},'crm_opportunity.quote_status');if(status==='sent'||status==='accepted'){const pipeline=object(await latest(PIPELINE));pipeline[key]={stage:status==='accepted'?'closing':'quoted',changedAt:now,customerId:customer.id};await save(actor,PIPELINE,pipeline,'crm.pipeline.quote')}await db()`insert into crm_activities(customer_id,staff_id,type,content) values(${customer.id},${actor.id},${status==='rejected'?'quote_rejected':status==='accepted'?'quote_accepted':'quote_status'},${status==='rejected'?`Khách từ chối báo giá: ${reason}`:`Báo giá ${String(found.title||'')} → ${status}`})`;return NextResponse.json({ok:true})
  }
  if(action==='booking.convert'){
   const id=String(body.id||''),quote=quotes.find(q=>String(q?.id||'')===id);if(!quote)return NextResponse.json({error:'Không tìm thấy báo giá.'},{status:404});if(quote.bookingId)return NextResponse.json({error:`Báo giá này đã tạo booking ${String(quote.bookingCode||'')}.`},{status:409});const need=object(current.need);if(!need.destination&&!need.detail)return NextResponse.json({error:'Hãy nhập nhu cầu khách trước khi tạo booking.'},{status:400});const bookingCode=code(),assignmentId=customer.staffId||actor.id,assignmentName=customer.staffName||actor.name,source=`CRM · ${String(body.source||customer.source||'Khác')}`,product=String(quote.title||'Dịch vụ HappyGo'),note=`CRM: ${String(need.destination||'Chưa chọn điểm đến')}\nNhu cầu: ${String(need.detail||'—')}\nBáo giá V${Number(quote.version||1)}: ${String(quote.detail||'—')}`;const inserted=await db()`insert into bookings(code,customer_id,status,source,start_date,end_date,adults,children,rooms,customer_name_snapshot,phone_snapshot,email_snapshot,note,selling_total_vnd,sales_staff_id,sales_staff_name_snapshot,sales_assigned_at) values(${bookingCode},${customer.id},'contacting',${source},${need.startDate||null},${need.endDate||null},${Math.max(1,Number(need.adults)||1)},${Math.max(0,Number(need.children)||0)},${Math.max(1,Number(need.rooms)||1)},${customer.name},${customer.phone},${customer.email||null},${note},${Math.round(Number(quote.amount)||0)},${assignmentId||null},${assignmentName||null},now()) returning id`;const bookingId=String(inserted[0].id);await db()`insert into booking_items(booking_id,product_name_snapshot,quantity,selling_price_vnd,data_snapshot) values(${bookingId},${product},1,${Math.round(Number(quote.amount)||0)},${JSON.stringify({kind:String(need.service||'Dịch vụ du lịch'),source:'crm_quote',quoteId:id,quoteVersion:Number(quote.version||1)})}::jsonb)`;const nextQuotes=quotes.map(q=>String(q?.id||'')===id?{...q,status:'accepted',acceptedAt:now,bookingId,bookingCode}:q);await save(actor,KEY,{...all,[key]:{...current,quotes:nextQuotes}},'crm_opportunity.convert_booking');const pipeline=object(await latest(PIPELINE));pipeline[key]={stage:'won',changedAt:now,customerId:customer.id};await save(actor,PIPELINE,pipeline,'crm.pipeline.won');await db()`insert into crm_activities(customer_id,staff_id,type,content) values(${customer.id},${actor.id},'quote_booking',${`Tạo booking ${bookingCode} từ báo giá V${Number(quote.version||1)} · ${Number(quote.amount||0).toLocaleString('vi-VN')}đ`})`;await db()`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'crm.quote.convert_booking','booking',${bookingId},${JSON.stringify({bookingCode,customerId:customer.id,quoteId:id,quoteVersion:Number(quote.version||1),sellingTotal:Number(quote.amount||0)})}::jsonb)`;return NextResponse.json({ok:true,bookingId,bookingCode})
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400})
 }catch(error){console.error('crm_opportunity_post_failed',error);return NextResponse.json({error:'Không thể cập nhật nhu cầu/báo giá production.'},{status:500})}
}
