import type {Metadata} from 'next';
import Link from 'next/link';
import {CruiseCatalog,type CmsCruiseProduct,type CruiseCatalogQuery} from '@/components/CruiseCatalog';
import {ContactCtaGroup} from '@/components/ContactCtaGroup';
import {PublicServiceNav} from '@/components/PublicServiceNav';
import {getSiteUrl} from '@/lib/site-url';
import {getPublicSiteState} from '@/lib/server/public-site-state';

const path='/du-thuyen';
type PageProps={searchParams:Promise<CruiseCatalogQuery>};
export function generateMetadata():Metadata{const canonical=`${getSiteUrl()}${path}`;return{title:'Du thuyền Hạ Long & Lan Hạ',description:'Đặt du thuyền Hạ Long, Lan Hạ cùng HappyGo Travel. Tư vấn hành trình, cabin, lịch đi và lựa chọn nghỉ đêm theo nhu cầu.',alternates:{canonical},openGraph:{title:'Du thuyền Hạ Long & Lan Hạ | HappyGo Travel',description:'Khám phá du thuyền Hạ Long và Lan Hạ theo ngày đi, thời lượng và cabin.',url:canonical,type:'website'},twitter:{card:'summary_large_image',title:'Du thuyền Hạ Long & Lan Hạ | HappyGo Travel',description:'Tìm cabin và hành trình phù hợp cùng HappyGo Travel.'}}}

export default async function CruisesPage({searchParams}:PageProps){const base=getSiteUrl(),canonical=`${base}${path}`,state=await getPublicSiteState(),initialCms=Array.isArray(state.tn_cms_products_v3_units)?state.tn_cms_products_v3_units as CmsCruiseProduct[]:[],query=await searchParams;const schema=[{"@context":"https://schema.org","@type":"CollectionPage","name":"Du thuyền Hạ Long & Lan Hạ","url":canonical,"description":"Danh mục du thuyền của HappyGo Travel"},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Trang chủ","item":base},{"@type":"ListItem","position":2,"name":"Du thuyền","item":canonical}]}];return <div className="subpage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="sub-hero"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / Du thuyền</div><div className="sub-hero-grid"><div><span className="sub-kicker">HẠ LONG & LAN HẠ</span><h1>Du thuyền Hạ Long & Lan Hạ</h1><p>Hành trình trong ngày, nghỉ đêm và trải nghiệm vịnh. Cabin và giá được HappyGo Travel kiểm tra theo ngày đi thực tế.</p></div><ContactCtaGroup callLabel="Kiểm tra cabin"/></div></div></section><PublicServiceNav active="cruise"/><section className="sub-section"><div className="container"><CruiseCatalog initialCms={initialCms} query={query}/><div className="sub-cta"><div><h2>Chưa biết nên đi 1 ngày hay ngủ đêm?</h2><p>HappyGo Travel tư vấn hành trình theo thời gian, ngân sách và nhóm khách của bạn.</p></div><ContactCtaGroup mode="footer" callLabel="Gọi tư vấn" zaloLabel="Chat Zalo"/></div></div></section></div>}
