import type {Metadata} from 'next';
import Link from 'next/link';
import {CruiseCatalog,type CmsCruiseProduct,type CruiseCatalogQuery} from '@/components/CruiseCatalog';
import {ContactCtaGroup} from '@/components/ContactCtaGroup';
import {PublicServiceNav} from '@/components/PublicServiceNav';
import {getSiteUrl} from '@/lib/site-url';
import {getPublicSiteState} from '@/lib/server/public-site-state';
import {destinationSlug,getSeoDestination} from '@/data/seo-destinations';

const path='/du-thuyen';
type PageProps={searchParams:Promise<CruiseCatalogQuery>};
export async function generateMetadata({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}):Promise<Metadata>{
 const query=await searchParams,raw=Array.isArray(query.q)?String(query.q[0]||''):String(query.q||''),destination=getSeoDestination(raw)?.name||raw,slug=destinationSlug(destination),canonical=slug?`${getSiteUrl()}/diem-den/${slug}/du-thuyen`:`${getSiteUrl()}/du-thuyen`,title=destination?`Du thuyền ${destination}`:'Du thuyền Hạ Long & Lan Hạ',description=destination?`Du thuyền tại ${destination} cùng HappyGo Travel. Xem hành trình, lịch đi và dịch vụ phù hợp.`:'Đặt du thuyền Hạ Long, Lan Hạ cùng HappyGo Travel. Tư vấn hành trình, cabin, lịch đi và lựa chọn nghỉ đêm theo nhu cầu.';
 return{title,description,alternates:{canonical},openGraph:{title:`${title} | HappyGo Travel`,description,url:canonical,type:'website'},twitter:{card:'summary_large_image',title:`${title} | HappyGo Travel`,description}};
}

export default async function CruisesPage({searchParams}:PageProps){const base=getSiteUrl(),canonical=`${base}${path}`,state=await getPublicSiteState(),initialCms=Array.isArray(state.tn_cms_products_v3_units)?state.tn_cms_products_v3_units as CmsCruiseProduct[]:[],query=await searchParams,rawQ=Array.isArray(query.q)?String(query.q[0]||''):String(query.q||''),q=getSeoDestination(rawQ)?.name||rawQ,effectiveQuery=q?{...query,q}:query;const schema=[{"@context":"https://schema.org","@type":"CollectionPage","name":"Du thuyền Hạ Long & Lan Hạ","url":canonical,"description":"Danh mục du thuyền của HappyGo Travel"},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Trang chủ","item":base},{"@type":"ListItem","position":2,"name":"Du thuyền","item":canonical}]}];return <div className="subpage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="sub-hero"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / Du thuyền</div><div className="sub-hero-grid"><div><span className="sub-kicker">{q?`DU THUYỀN ${q.toUpperCase()}`:'HẠ LONG & LAN HẠ'}</span><h1>{q?`Du thuyền ${q}`:'Du thuyền Hạ Long & Lan Hạ'}</h1><p>{q?`Các hành trình du thuyền phù hợp tại ${q}. Giá và tình trạng chỗ được kiểm tra theo ngày đi thực tế.`:'Hành trình trong ngày, nghỉ đêm và trải nghiệm vịnh. Cabin và giá được HappyGo Travel kiểm tra theo ngày đi thực tế.'}</p></div><ContactCtaGroup callLabel="Kiểm tra cabin"/></div></div></section><PublicServiceNav active="cruise" destination={q}/><section className="sub-section"><div className="container"><CruiseCatalog initialCms={initialCms} query={effectiveQuery}/><div className="sub-cta"><div><h2>Chưa biết nên đi 1 ngày hay ngủ đêm?</h2><p>HappyGo Travel tư vấn hành trình theo thời gian, ngân sách và nhóm khách của bạn.</p></div><ContactCtaGroup mode="footer" callLabel="Gọi tư vấn" zaloLabel="Chat Zalo"/></div></div></section></div>}
