'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';

type Account={id:string;customerId:string;name:string;phone:string;email:string;status:string;createdAt:string;lastLoginAt?:string};
type Booking={id:string;code:string;status:string;source:string;startDate:string;endDate:string;sellingTotal:number;paidTotal:number;salesStaffName:string;createdAt:string;products:Array<{name:string;unit:string;quantity:number;sellingPrice:number}>};
const statusLabel:Record<string,string>={new:'Mới tiếp nhận',contacting:'Đang tư vấn',confirmed:'Đã xác nhận',completed:'Hoàn tất',cancelled:'Đã hủy'};
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(v))+'đ';
async function request(body?:unknown){const r=await fetch('/api/account',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Không thể xử lý tài khoản.');return j}

export default function AccountPage(){
 const[account,setAccount]=useState<Account|null>(null),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[mode,setMode]=useState<'login'|'register'>('login'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState('');
 async function load(){setLoading(true);try{const j=await request();setAccount(j.authenticated?j.account:null);setBookings(j.authenticated?j.bookings||[]:[])}catch(e){setMsg(e instanceof Error?e.message:'Không đọc được tài khoản.')}finally{setLoading(false)}}
 useEffect(()=>{localStorage.removeItem('happygo_customer_accounts_v1');localStorage.removeItem('happygo_customer_session_v1');void load()},[]);
 async function submit(){setBusy(true);setMsg('');try{await request({action:mode,name,phone,email,password});setPassword('');await load();window.dispatchEvent(new Event('happygo-customer-auth'));setMsg(mode==='login'?'Đăng nhập thành công.':'Đã tạo tài khoản HappyGo an toàn trên hệ thống production.')}catch(e){setMsg(e instanceof Error?e.message:'Không thể xử lý tài khoản.')}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await request({action:'logout'});setAccount(null);setBookings([]);setPassword('');setMsg('Đã đăng xuất.');window.dispatchEvent(new Event('happygo-customer-auth'))}catch(e){setMsg(e instanceof Error?e.message:'Không thể đăng xuất.')}finally{setBusy(false)}}
 if(loading)return <main className="customer-account-page"><section className="customer-account-card"><small>HAPPYGO TRAVEL</small><h1>Đang tải tài khoản...</h1></section></main>;
 return <main className="customer-account-page"><section className="customer-account-card">{account?<><small>TÀI KHOẢN HAPPYGO · PRODUCTION</small><h1>Xin chào, {account.name}</h1><p>{account.phone} · {account.email}</p><div className="customer-account-actions"><Link href="/checkout">Đặt dịch vụ</Link><button disabled={busy} onClick={logout}>Đăng xuất</button></div>{msg&&<p className="account-message">{msg}</p>}<p className="account-note">Phiên đăng nhập được bảo vệ bằng cookie HttpOnly. Mật khẩu không còn lưu trong trình duyệt.</p><div className="customer-booking-history"><div className="admin-panel-head"><div><small>DỊCH VỤ CỦA TÔI</small><h2>Booking đã gửi</h2><p>Theo dõi các yêu cầu gắn với hồ sơ khách hàng của bạn.</p></div><span>{bookings.length} booking</span></div>{bookings.map(b=><article key={b.id} className="admin-customer-card"><div><b>{b.code}</b><small>{b.products.map(x=>x.name).join(', ')||'Dịch vụ HappyGo'}</small><small>{b.startDate||'Chưa chốt ngày'}{b.endDate?` → ${b.endDate}`:''}</small></div><div><b>{statusLabel[b.status]||b.status}</b><small>{b.salesStaffName?`Tư vấn: ${b.salesStaffName}`:'Đang chờ phân tư vấn'}</small><small>Tạo: {new Date(b.createdAt).toLocaleString('vi-VN')}</small></div><div><b>{b.sellingTotal>0?money(b.sellingTotal):'Chờ báo giá'}</b><small>Đã thanh toán: {money(b.paidTotal)}</small>{b.sellingTotal>0&&<small>Còn lại: {money(Math.max(0,b.sellingTotal-b.paidTotal))}</small>}</div></article>)}{!bookings.length&&<div className="admin-empty-state">Bạn chưa có booking nào trên tài khoản này.</div>}</div></>:<><small>HAPPYGO TRAVEL</small><h1>{mode==='login'?'Đăng nhập khách hàng':'Tạo tài khoản khách hàng'}</h1><div className="account-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setMsg('')}}>Đăng nhập</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setMsg('')}}>Đăng ký</button></div>{mode==='register'&&<><label>Họ và tên<input autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Số điện thoại<input autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09xxxxxxxx"/></label></>}<label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='register'?'Tối thiểu 8 ký tự':''}/></label>{msg&&<p className="account-message">{msg}</p>}<button className="account-primary" disabled={busy} onClick={submit}>{busy?'Đang xử lý...':mode==='login'?'Đăng nhập':'Tạo tài khoản'}</button><Link className="guest-booking" href="/">Tiếp tục xem và đặt dịch vụ không cần tài khoản →</Link><p className="account-note">Đăng ký là tùy chọn. Tài khoản giúp bạn theo dõi booking và thanh toán trên nhiều thiết bị.</p></>}</section></main>;
}
