'use client';
import {useEffect,useMemo,useState} from 'react';

type Booking={id:string;code:string;customerId:string;customerName:string;phone:string;email:string;product:string;status:string;endDate:string;salesStaffId:string};
type Staff={id:string;name:string};
type Feedback={id:string;bookingId:string;bookingCode:string;customerId?:string;customerName:string;rating:number;type:'praise'|'normal'|'complaint';content:string;resolution:string;status:'open'|'resolved';createdAt:string;createdBy:string;createdById?:string;assignedToId?:string;assignedToName?:string;dueAt?:string;resolvedAt?:string;resolvedBy?:string};
type ApiData={items:Feedback[];bookings:Booking[];staff:Staff[];capabilities:{manage:boolean;actorId:string;actorName:string}};
function defaultDue(){const d=new Date();d.setDate(d.getDate()+1);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function overdue(f:Feedback){return f.status==='open'&&Boolean(f.dueAt)&&+new Date(f.dueAt!)<Date.now()}
export function AdminCustomerFeedback(){
 const[data,setData]=useState<ApiData>({items:[],bookings:[],staff:[],capabilities:{manage:false,actorId:'',actorName:''}}),[loading,setLoading]=useState(true),[bookingId,setBookingId]=useState(''),[rating,setRating]=useState(5),[type,setType]=useState<Feedback['type']>('praise'),[content,setContent]=useState(''),[resolution,setResolution]=useState(''),[assignedToId,setAssignedToId]=useState(''),[dueAt,setDueAt]=useState(defaultDue()),[filter,setFilter]=useState<'all'|'open'|'complaint'|'mine'|'overdue'>('all'),[msg,setMsg]=useState('');
 async function load(){setLoading(true);try{const res=await fetch('/api/admin/customer-feedback',{cache:'no-store'}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không đọc được phản hồi khách hàng.');setData(json)}catch(error){setMsg(error instanceof Error?error.message:'Không đọc được phản hồi khách hàng.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function post(body:Record<string,unknown>){const res=await fetch('/api/admin/customer-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không thể cập nhật phản hồi.');return json}
 const visible=useMemo(()=>data.items.filter(item=>{if(filter==='open')return item.status==='open';if(filter==='complaint')return item.type==='complaint';if(filter==='mine')return item.status==='open'&&item.assignedToId===data.capabilities.actorId;if(filter==='overdue')return overdue(item);return true}).sort((a,b)=>Number(overdue(b))-Number(overdue(a))||+new Date(b.createdAt)-+new Date(a.createdAt)),[data.items,data.capabilities.actorId,filter]);
 const avg=visible.length?visible.reduce((sum,item)=>sum+Number(item.rating||0),0)/visible.length:0,complaints=visible.filter(item=>item.type==='complaint'&&item.status==='open').length,late=visible.filter(overdue).length;
 async function add(){if(!bookingId)return setMsg('Chọn booking đã kết thúc.');if(!content.trim())return setMsg('Nhập nội dung phản hồi của khách.');if(type==='complaint'&&!assignedToId)return setMsg('Khiếu nại cần giao một nhân viên phụ trách.');if(type==='complaint'&&!dueAt)return setMsg('Khiếu nại cần có hạn xử lý.');try{await post({action:'add',bookingId,rating,type,content:content.trim(),resolution:resolution.trim(),assignedToId,dueAt:type==='complaint'?new Date(dueAt).toISOString():''});setBookingId('');setRating(5);setType('praise');setContent('');setResolution('');setAssignedToId('');setDueAt(defaultDue());setMsg('Đã lưu phản hồi production và cập nhật lịch sử CRM.');await load()}catch(error){setMsg(error instanceof Error?error.message:'Không thể lưu phản hồi.')}}
 async function resolve(item:Feedback){const value=prompt('Nhập kết quả xử lý khiếu nại:',item.resolution||'');if(value===null||!value.trim())return;try{await post({action:'resolve',id:item.id,resolution:value.trim()});setMsg(`Đã đóng khiếu nại ${item.bookingCode} và ghi lịch sử CRM.`);await load()}catch(error){setMsg(error instanceof Error?error.message:'Không thể xử lý khiếu nại.')}}
 return <section className="admin-panel"><div className="admin-panel-head"><div><small>CHẤT LƯỢNG DỊCH VỤ · PRODUCTION</small><h2>Đánh giá sau chuyến & khiếu nại</h2><p>Phản hồi được lưu trên server; khiếu nại có người phụ trách, hạn xử lý và chỉ người được giao hoặc Quản trị viên mới được đóng.</p></div><button className="admin-secondary" onClick={()=>void load()} disabled={loading}>↻ Tải lại</button></div>
 <div className="service-kpis"><article><small>PHẢN HỒI HIỂN THỊ</small><b>{visible.length}</b></article><article><small>ĐIỂM HÀI LÒNG</small><b>{avg?avg.toFixed(1):'—'}/5</b></article><article><small>KHIẾU NẠI CHƯA XỬ LÝ</small><b>{complaints}</b></article><article><small>ĐÃ QUÁ HẠN</small><b>{late}</b></article></div>
 <div className="admin-form-row"><label>Booking đã kết thúc<select value={bookingId} onChange={e=>setBookingId(e.target.value)}><option value="">— Chọn booking —</option>{data.bookings.map(b=><option value={b.id} key={b.id}>{b.code} · {b.customerName} · {b.product}</option>)}</select></label><label>Mức hài lòng<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(x=><option value={x} key={x}>{x}/5 sao</option>)}</select></label><label>Loại phản hồi<select value={type} onChange={e=>setType(e.target.value as Feedback['type'])}><option value="praise">Khen ngợi</option><option value="normal">Góp ý / bình thường</option><option value="complaint">Khiếu nại cần xử lý</option></select></label><label>Nội dung phản hồi<input value={content} onChange={e=>setContent(e.target.value)} placeholder="Khách hài lòng điều gì, chưa hài lòng điều gì..."/></label><label>Hướng xử lý ban đầu<input value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Xin lỗi, kiểm tra NCC, hoàn tiền..."/></label>{type==='complaint'&&<><label>Giao người phụ trách<select value={assignedToId} onChange={e=>setAssignedToId(e.target.value)}><option value="">— Chọn nhân viên —</option>{data.staff.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Hạn xử lý<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label></>}<button className="admin-primary" onClick={()=>void add()}>Lưu phản hồi</button></div>
 {msg&&<p className="admin-api-note">{msg}</p>}<div className="service-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Tất cả</button><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Chưa xử lý</button><button className={filter==='mine'?'active':''} onClick={()=>setFilter('mine')}>Việc của tôi</button><button className={filter==='overdue'?'active':''} onClick={()=>setFilter('overdue')}>Quá hạn</button><button className={filter==='complaint'?'active':''} onClick={()=>setFilter('complaint')}>Khiếu nại</button></div>
 {loading?<div className="admin-empty-state">Đang tải phản hồi production...</div>:<div className="admin-customer-grid">{visible.map(f=><article className={`admin-customer-card ${overdue(f)?'complaint-overdue':''}`} key={f.id}><div><b>{f.customerName} · {f.bookingCode}</b><span>{'★'.repeat(f.rating)}{'☆'.repeat(5-f.rating)}</span><small>{new Date(f.createdAt).toLocaleString('vi-VN')} · {f.createdBy}</small></div><div><b>{f.type==='complaint'?'Khiếu nại':f.type==='praise'?'Khen ngợi':'Góp ý'}</b><small>{f.content}</small>{f.resolution&&<small>Xử lý: {f.resolution}</small>}</div><div><span className={f.status==='resolved'?'status-confirmed':'status-cancelled'}>{f.status==='resolved'?'Đã xử lý':overdue(f)?'Quá hạn':'Chờ xử lý'}</span>{f.assignedToName&&<small>Phụ trách: {f.assignedToName}</small>}{f.dueAt&&<small>Hạn: {new Date(f.dueAt).toLocaleString('vi-VN')}</small>}{f.resolvedBy&&<small>Xử lý bởi: {f.resolvedBy}</small>}</div>{f.status==='open'&&(data.capabilities.manage||f.assignedToId===data.capabilities.actorId)&&<button className="admin-primary" onClick={()=>void resolve(f)}>Xử lý khiếu nại</button>}</article>)}{!visible.length&&<div className="admin-empty-state">Chưa có phản hồi phù hợp.</div>}</div>}</section>}
