'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';

type Customer={id:string;key:string;name:string;phone:string;email:string;bookingCount:number;assignment:{staffId:string;staffName:string}|null;latestBooking:{code:string}|null};
type Booking={id:string;code:string;status:string;customerId:string;customerName:string;phone:string;email:string;salesStaffId:string;salesStaffName:string;product:string;startDate:string;createdAt:string};
type Followup={id:string;customerId?:string;customerKey:string;customerName:string;phone:string;bookingCode?:string;title:string;dueAt:string;status:'open'|'done';note?:string;createdBy?:string;createdAt?:string;doneAt?:string};
type Workflow={customers:Customer[];bookings:Booking[];followups:Followup[];capabilities?:{manage?:boolean}};

async function getWorkflow(){const response=await fetch('/api/admin/crm-workflow',{cache:'no-store'});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401?'Phiên quản trị đã hết hạn.':json.error||'Không đọc được CRM Workflow.');return json as Workflow}
async function postWorkflow(body:unknown){const response=await fetch('/api/admin/crm-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Không cập nhật được CRM Workflow.');return json}

export function AdminCrmWorkboard({openBookings,openCustomers}:{openBookings:()=>void;openCustomers:()=>void}){
 const[customers,setCustomers]=useState<Customer[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[tasks,setTasks]=useState<Followup[]>([]),[manage,setManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[show,setShow]=useState(false),[customerId,setCustomerId]=useState(''),[title,setTitle]=useState('Gọi lại tư vấn khách'),[due,setDue]=useState(''),[note,setNote]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const data=await getWorkflow();setCustomers(Array.isArray(data.customers)?data.customers:[]);setBookings(Array.isArray(data.bookings)?data.bookings:[]);setTasks(Array.isArray(data.followups)?data.followups:[]);setManage(Boolean(data.capabilities?.manage))}catch(error){setMessage(error instanceof Error?error.message:'Không đọc được CRM production.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer)},[load]);
 const assignmentByCustomer=useMemo(()=>new Map(customers.map(c=>[c.id,c.assignment?.staffName||''])),[customers]);
 const activeBookings=useMemo(()=>bookings.filter(b=>!['completed','cancelled'].includes(b.status)),[bookings]);
 const openTasks=useMemo(()=>tasks.filter(t=>t.status==='open').sort((a,b)=>+new Date(a.dueAt)-+new Date(b.dueAt)),[tasks]);
 const now=Date.now(),overdue=openTasks.filter(t=>+new Date(t.dueAt)<now),today=openTasks.filter(t=>new Date(t.dueAt).toDateString()===new Date().toDateString()),unassigned=manage?activeBookings.filter(b=>!b.salesStaffId&&!assignmentByCustomer.get(b.customerId)):[];
 async function add(){if(!customerId||!due||!title.trim())return setMessage('Chọn khách, nội dung và thời gian nhắc.');setBusy(true);setMessage('');try{await postWorkflow({action:'followup.create',customerId,title,dueAt:due,note});await load();setShow(false);setNote('');setDue('');setMessage('✓ Đã lưu nhắc chăm sóc lên production.')}catch(error){setMessage(error instanceof Error?error.message:'Không tạo được nhắc việc.')}finally{setBusy(false)}}
 async function done(id:string){setBusy(true);setMessage('');try{await postWorkflow({action:'followup.done',id});await load();setMessage('✓ Đã hoàn tất follow-up và ghi vào lịch sử CRM.')}catch(error){setMessage(error instanceof Error?error.message:'Không hoàn tất được nhắc việc.')}finally{setBusy(false)}}
 return <section className="admin-panel crm-workboard"><div className="admin-panel-head"><div><small>CRM WORKFLOW · PRODUCTION</small><h2>Điều hành Sale & nhắc chăm sóc</h2><p>Khách, booking và nhắc chăm sóc được đọc từ server; tạo/hoàn tất follow-up không còn phụ thuộc trình duyệt đang dùng.</p></div><div className="editor-actions"><button className="admin-secondary" disabled={loading} onClick={()=>void load()}>↻ {loading?'Đang tải':'Làm mới'}</button><button className="admin-primary" onClick={()=>setShow(v=>!v)}>＋ Tạo nhắc việc</button></div></div>{message&&<p className={message.startsWith('✓')?'cms-message':'admin-api-note'}>{message}</p>}<div className="crm-work-kpis"><button onClick={openCustomers}><small>Khách phụ trách</small><b>{customers.length}</b><span>Mở CRM →</span></button><button onClick={openBookings}><small>Booking đang xử lý</small><b>{activeBookings.length}</b><span>Mở Booking →</span></button><article className={overdue.length?'danger':''}><small>Follow-up quá hạn</small><b>{overdue.length}</b><span>Cần xử lý ngay</span></article><article><small>Nhắc việc hôm nay</small><b>{today.length}</b><span>Trong ngày</span></article>{manage&&<article className={unassigned.length?'warning':''}><small>Booking chưa phân Sale</small><b>{unassigned.length}</b><span>Cần phân công</span></article>}</div>{show&&<div className="crm-followup-form"><label>Khách hàng<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Chọn khách</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone||c.email} · {c.latestBooking?.code||`${c.bookingCount} booking`}</option>)}</select></label><label>Nội dung<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Thời gian<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Ghi chú<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="admin-primary" disabled={busy||!customerId||!due||!title.trim()} onClick={()=>void add()}>{busy?'Đang lưu...':'Lưu nhắc việc'}</button></div>}<div className="crm-followup-list"><div className="crm-followup-head"><div><b>Việc cần chăm sóc</b><small>{loading?'Đang đồng bộ production':`${openTasks.length} đang mở`}</small></div><span>{openTasks.length}</span></div>{openTasks.slice(0,20).map(t=><article key={t.id} className={+new Date(t.dueAt)<now?'overdue':''}><div><b>{t.title}</b><span>{t.customerName} · {t.phone}{t.bookingCode?` · ${t.bookingCode}`:''}</span><small>{t.note||'Không có ghi chú'}</small></div><time>{new Date(t.dueAt).toLocaleString('vi-VN')}</time><button disabled={busy} onClick={()=>void done(t.id)}>✓ Hoàn tất</button></article>)}{!loading&&!openTasks.length&&<div className="admin-empty-state"><b>Không có follow-up đang mở</b><span>Nhắc việc mới sẽ đồng bộ giữa các thiết bị ngay sau khi lưu.</span></div>}</div></section>;
}
