'use client';

import {useEffect,useMemo,useState} from 'react';
import {AdminMediaManager,AdminMediaPicker} from '@/components/AdminMediaLibrary';

type SeoSettings={siteTitle:string;description:string;keywords:string;ogImage:string;organizationName:string;canonicalBase:string};
type SiteSettings={brand:string;hotline:string;email:string;zalo:string};
type DriveFile={id:string;name:string;mimeType:string;modifiedTime?:string;webViewLink?:string;size?:string};
const seoKey='tn_cms_seo_v1';const siteKey='tn_cms_site_settings_v1';
const defaultSeo:SeoSettings={siteTitle:'HappyGo Travel',description:'HappyGo Travel - Tour, villa, khách sạn, resort và du thuyền toàn quốc. Hành trình hạnh phúc, kết nối yêu thương.',keywords:'HappyGo Travel, du lịch, tour, villa, khách sạn, resort, du thuyền',ogImage:'',organizationName:'HappyGo Travel',canonicalBase:'https://happygo.vn'};
const defaultSite:SiteSettings={brand:'HappyGo Travel',hotline:'0969973949',email:'info@happygo.vn',zalo:'0969973949'};
function migrateSeo(v:Partial<SeoSettings>|null|undefined){const next={...defaultSeo,...(v||{})};if(/th[uú]y\s*nguy[eê]n/i.test(next.siteTitle))next.siteTitle='HappyGo Travel';if(/th[uú]y\s*nguy[eê]n/i.test(next.organizationName))next.organizationName='HappyGo Travel';if(next.canonicalBase.includes('github.io/thuy-nguyen-travel'))next.canonicalBase='https://happygo.vn';return next}
function migrateSite(v:Partial<SiteSettings>|null|undefined){const next={...defaultSite,...(v||{})};if(/th[uú]y\s*nguy[eê]n/i.test(next.brand))next.brand='HappyGo Travel';if(/thuynguyen/i.test(next.email))next.email='info@happygo.vn';return next}
async function readConfig(type:'site'|'seo'){const response=await fetch(`/api/admin/site-config?type=${type}`,{cache:'no-store'});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401?'Phiên quản trị đã hết hạn hoặc chưa có quyền Cài đặt.':json.error||'Không đọc được cấu hình.');return json.value}
async function writeConfig(type:'site'|'seo',value:unknown){const response=await fetch('/api/admin/site-config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,value})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401?'Phiên quản trị đã hết hạn hoặc chưa có quyền Cài đặt.':json.error||'Không lưu được cấu hình production.');return json}

export function AdminMediaPanel(){return <AdminMediaManager/>}
export function AdminSeoPanel(){
 const [form,setForm]=useState<SeoSettings>(defaultSeo);const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;try{const raw=localStorage.getItem(seoKey);if(raw)setForm(migrateSeo(JSON.parse(raw)))}catch{}void readConfig('seo').then(value=>{if(value&&alive){const next=migrateSeo(value);setForm(next);localStorage.setItem(seoKey,JSON.stringify(next))}}).catch(error=>alive&&setMsg(error instanceof Error?error.message:'Không đọc được SEO production.'));return()=>{alive=false}},[]);
 const set=<K extends keyof SeoSettings>(k:K,v:SeoSettings[K])=>setForm(f=>({...f,[k]:v}));const score=useMemo(()=>{let s=0;if(form.siteTitle.length>=10&&form.siteTitle.length<=60)s+=25;if(form.description.length>=80&&form.description.length<=180)s+=30;if(form.keywords.trim())s+=10;if(form.organizationName.trim())s+=10;if(form.canonicalBase.startsWith('http'))s+=15;if(form.ogImage)s+=10;return s},[form]);
 const save=async()=>{setBusy(true);setMsg('');try{await writeConfig('seo',form);localStorage.setItem(seoKey,JSON.stringify(form));window.dispatchEvent(new Event('tn-seo-updated'));setMsg('✓ Đã lưu SEO production. Metadata website sẽ đọc cấu hình này trên máy chủ.')}catch(error){setMsg(error instanceof Error?error.message:'Không lưu được SEO production.')}finally{setBusy(false)}};
 return <section className="admin-panel"><div className="admin-panel-head"><div><small>SEO · PRODUCTION</small><h2>Cấu hình SEO toàn website</h2><p>Thiết lập title, description, Open Graph và thương hiệu HappyGo trực tiếp trên máy chủ.</p></div><strong className={score>=70?'seo-good':''}>{score}/100</strong></div><div className="utility-form-grid"><label className="wide">Tên website / Title mặc định<input value={form.siteTitle} onChange={e=>set('siteTitle',e.target.value)}/></label><label className="wide">Meta description<textarea rows={4} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label className="wide">Từ khóa gợi ý<input value={form.keywords} onChange={e=>set('keywords',e.target.value)}/></label><label>Tên thương hiệu / tổ chức<input value={form.organizationName} onChange={e=>set('organizationName',e.target.value)}/></label><label>Canonical base URL<input value={form.canonicalBase} onChange={e=>set('canonicalBase',e.target.value)}/></label><div className="wide"><b className="field-label">Ảnh Open Graph mặc định</b><AdminMediaPicker value={form.ogImage} onChange={v=>set('ogImage',v)} label="Chọn ảnh OG"/></div></div><div className="seo-admin-checks"><span className={form.siteTitle.length>=10&&form.siteTitle.length<=60?'ok':''}>Title 10–60 ký tự</span><span className={form.description.length>=80&&form.description.length<=180?'ok':''}>Description 80–180 ký tự</span><span className={form.canonicalBase.startsWith('http')?'ok':''}>Canonical hợp lệ</span><span className={form.ogImage?'ok':''}>Có ảnh chia sẻ</span></div><button type="button" className="admin-primary" disabled={busy} onClick={()=>void save()}>{busy?'Đang lưu...':'Lưu SEO production'}</button>{msg&&<p className={msg.startsWith('✓')?'cms-message':'admin-api-note'}>{msg}</p>}</section>
}
export function AdminSettingsPanel(){
 const [form,setForm]=useState<SiteSettings>(defaultSite);const [msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;try{const raw=localStorage.getItem(siteKey);if(raw)setForm(migrateSite(JSON.parse(raw)))}catch{}void readConfig('site').then(value=>{if(value&&alive){const next=migrateSite(value);setForm(next);localStorage.setItem(siteKey,JSON.stringify(next));window.dispatchEvent(new Event('tn-site-settings-updated'))}}).catch(error=>alive&&setMsg(error instanceof Error?error.message:'Không đọc được cài đặt production.'));return()=>{alive=false}},[]);
 const set=<K extends keyof SiteSettings>(k:K,v:SiteSettings[K])=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{setBusy(true);setMsg('');try{await writeConfig('site',form);localStorage.setItem(siteKey,JSON.stringify(form));window.dispatchEvent(new Event('tn-site-settings-updated'));setMsg('✓ Đã lưu cài đặt production và đồng bộ cho website.')}catch(error){setMsg(error instanceof Error?error.message:'Không lưu được cài đặt production.')}finally{setBusy(false)}};
 return <section className="admin-panel"><div className="admin-panel-head"><div><small>CÀI ĐẶT · PRODUCTION</small><h2>Cài đặt hệ thống</h2><p>Thông tin thương hiệu và liên hệ được lưu trên máy chủ và dùng chung trên các thiết bị.</p></div></div><div className="utility-form-grid"><label>Tên thương hiệu<input value={form.brand} onChange={e=>set('brand',e.target.value)}/></label><label>Hotline<input value={form.hotline} onChange={e=>set('hotline',e.target.value.replace(/\D/g,''))}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Zalo<input value={form.zalo} onChange={e=>set('zalo',e.target.value.replace(/\D/g,''))}/></label></div><button type="button" className="admin-primary" disabled={busy} onClick={()=>void save()}>{busy?'Đang lưu...':'Lưu cài đặt production'}</button>{msg&&<p className={msg.startsWith('✓')?'cms-message':'admin-api-note'}>{msg}</p>}</section>
}

export function AdminDrivePanel(){
 const[files,setFiles]=useState<DriveFile[]>([]);const[loading,setLoading]=useState(false);const[msg,setMsg]=useState('');const[preview,setPreview]=useState('');const[selected,setSelected]=useState<DriveFile|null>(null);
 async function load(){setLoading(true);setMsg('');setPreview('');try{const r=await fetch('/api/admin/drive/files',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===401?'Phiên quản trị đã hết hạn hoặc chưa có quyền Cài đặt.':j.error||'Không kết nối được Google Drive.');setFiles(j.files||[]);setMsg(`✓ Đã kết nối Google Drive · ${j.files?.length||0} file trong thư mục nguồn.`)}catch(e){setMsg(e instanceof Error?e.message:'Không kết nối được Google Drive.')}finally{setLoading(false)}}
 async function open(file:DriveFile){setSelected(file);setPreview('Đang đọc file...');try{const r=await fetch(`/api/admin/drive/file?id=${encodeURIComponent(file.id)}`,{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Không đọc được file.');setPreview(j.content||j.message||'File không có nội dung text để xem trước.')}catch(e){setPreview(e instanceof Error?e.message:'Không đọc được file.')}}
 return <section className="admin-panel"><div className="admin-panel-head"><div><small>GOOGLE DRIVE · TÙY CHỌN</small><h2>Google Drive → Website</h2><p>Drive được đọc qua Vercel bằng phiên Admin HttpOnly; OAuth token và secret không xuất hiện trên trình duyệt.</p></div><em className={`pm-status ${files.length?'approved':'draft'}`}>{files.length?'Đã kết nối':'Chưa cấu hình OAuth'}</em></div><div className="editor-actions"><button type="button" className="admin-primary" disabled={loading} onClick={()=>void load()}>{loading?'Đang kết nối...':'Kết nối / Làm mới Drive'}</button></div>{msg&&<p className={msg.startsWith('✓')?'cms-message':'admin-api-note'}>{msg}</p>}<div className="drive-drop" style={{alignItems:'stretch',textAlign:'left'}}>{files.length===0?<><b>Drive là tích hợp tùy chọn</b><span>Website và hệ thống vận hành không phụ thuộc Google Drive. Khi hoàn tất OAuth riêng trên Vercel, bấm Kết nối để đọc thư mục nguồn.</span></>:<div style={{display:'grid',gap:8}}>{files.map(f=><button key={f.id} type="button" onClick={()=>void open(f)} style={{textAlign:'left',padding:10,border:'1px solid #dce6ee',borderRadius:8,background:selected?.id===f.id?'#eef6ff':'#fff'}}><b>{f.name}</b><small style={{display:'block'}}>{f.mimeType}{f.modifiedTime?` · ${new Date(f.modifiedTime).toLocaleString('vi-VN')}`:''}</small></button>)}</div>}</div>{selected&&<div style={{marginTop:16}}><h3>{selected.name}</h3>{selected.webViewLink&&<a href={selected.webViewLink} target="_blank" rel="noreferrer">Mở file trên Google Drive ↗</a>}<pre style={{whiteSpace:'pre-wrap',maxHeight:420,overflow:'auto',background:'#f6f8fa',padding:14,borderRadius:10}}>{preview}</pre></div>}</section>
}
