'use client';

import {useEffect,useMemo,useState} from 'react';
import {AdminMediaPicker} from '@/components/AdminMediaLibrary';
import {UnifiedProductUnitsEditor,blankUnifiedUnit,type UnifiedUnit} from '@/components/UnifiedProductUnitsEditor';

type ProductType='Sản phẩm'|'Villa & Resort'|'Khách sạn'|'Du thuyền';
type Status='draft'|'published'|'hidden';
type Product={id:string;type:ProductType;name:string;slug:string;place:string;price:string;status:Status;summary:string;cover:string;gallery:string;rating:string;serviceStars:string;category:string;address:string;checkin:string;checkout:string;amenities:string;policies:string;childrenPolicy:string;extraCharge:string;duration:string;pickup:string;boarding:string;itinerary:string;content:string;seoTitle:string;seoDescription:string;units:UnifiedUnit[];updatedAt:string};
const KEY='tn_cms_products_v3_units';
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const blank=(type:ProductType):Product=>({id:'',type,name:'',slug:'',place:'',price:'',status:'draft',summary:'',cover:'',gallery:'',rating:'',serviceStars:'',category:'',address:'',checkin:'14:00',checkout:'12:00',amenities:'',policies:'',childrenPolicy:'',extraCharge:'',duration:'',pickup:'',boarding:'',itinerary:'',content:'',seoTitle:'',seoDescription:'',units:[],updatedAt:''});
const seeds:Product[]=[{...blank('Villa & Resort'),id:'stay_oceanami',name:'Oceanami Villas & Beach Club',slug:'oceanami-villas-beach-club',place:'Phước Hải, Bà Rịa - Vũng Tàu',price:'4.500.000đ',status:'published',rating:'8.8',serviceStars:'5',summary:'Khu nghỉ dưỡng 5 sao với nhiều căn villa riêng biệt.',units:[{...blankUnifiedUnit(),id:'oca_a12',code:'OCA-A12',name:'Villa 3PN A12',bedrooms:'3',capacity:'6 người lớn + 2 trẻ em',area:'350 m²',view:'Vườn',weekdayPrice:'4.500.000đ',weekendPrice:'5.500.000đ'}]},{...blank('Khách sạn'),id:'stay_vinpearl_nt',name:'Vinpearl Resort Nha Trang',slug:'vinpearl-resort-nha-trang',place:'Hòn Tre, Nha Trang',status:'published',serviceStars:'5',summary:'Resort biển phù hợp gia đình và cặp đôi.'},{...blank('Du thuyền'),id:'cruise_ambassador1',name:'Ambassador I - Vịnh Hạ Long',slug:'ambassador-i-ha-long-2n1d',place:'Vịnh Hạ Long',duration:'2 ngày 1 đêm',price:'4.500.000đ/khách',status:'published',serviceStars:'5'}];
function normalizeProduct(p:any,type:ProductType):Product{return {...blank(type),...p,serviceStars:String(p?.serviceStars||p?.stars||''),units:Array.isArray(p?.units)?p.units.map((u:any)=>({...blankUnifiedUnit(),...u,id:u?.id||uid('u')})):[]}}
function F({label,children,wide=false,hint}:{label:string;children:React.ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'pm-field wide':'pm-field'}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function AdminProductManagerV3({type}:{type:ProductType}){
 const[items,setItems]=useState<Product[]>([]);const[mode,setMode]=useState<'list'|'edit'>('list');const[form,setForm]=useState<Product>(blank(type));const[q,setQ]=useState('');const[msg,setMsg]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);const loaded=raw?JSON.parse(raw):seeds;setItems((Array.isArray(loaded)?loaded:seeds).map((p:any)=>normalizeProduct(p,p?.type||'Villa & Resort')))}catch{setItems(seeds)}},[]);
 useEffect(()=>{setMode('list');setForm(blank(type));setMsg('')},[type]);
 const saveItems=(next:Product[])=>{try{localStorage.setItem(KEY,JSON.stringify(next));setItems(next);window.dispatchEvent(new Event('tn-products-updated'));return true}catch{setMsg('Chưa lưu được sản phẩm. Bộ nhớ trình duyệt có thể đã đầy.');return false}};
 const shown=useMemo(()=>items.filter(p=>(type==='Sản phẩm'||p.type===type)&&(!q||`${p.name} ${p.place} ${p.category}`.toLowerCase().includes(q.toLowerCase()))),[items,type,q]);
 const set=<K extends keyof Product>(k:K,v:Product[K])=>setForm(s=>({...s,[k]:v}));
 const add=()=>{setForm(blank(type==='Sản phẩm'?'Villa & Resort':type));setMode('edit')};
 const edit=(p:Product)=>{setForm(normalizeProduct(JSON.parse(JSON.stringify(p)),p.type));setMode('edit');setMsg('')};
 const duplicate=(p:Product)=>{const copy={...normalizeProduct(JSON.parse(JSON.stringify(p)),p.type),id:uid('p'),name:`${p.name} - Bản sao`,slug:`${p.slug}-copy`,status:'draft' as Status,units:(p.units||[]).map(u=>({...u,id:uid('u')}))};if(saveItems([...items,copy]))edit(copy)};
 const remove=(p:Product)=>{if(!confirm(`Xóa “${p.name}” và toàn bộ hạng phòng/căn/cabin?`))return;if(saveItems(items.filter(x=>x.id!==p.id))&&form.id===p.id)setMode('list')};
 const save=(status:Status)=>{if(!form.name.trim()){setMsg('Vui lòng nhập tên sản phẩm.');return}if(status==='published'&&!form.serviceStars){setMsg('Vui lòng chọn hạng dịch vụ / số sao trước khi đăng.');return}const next={...form,id:form.id||uid('p'),slug:form.slug||slugify(form.name),status,updatedAt:new Date().toISOString()};const nextItems=items.some(x=>x.id===next.id)?items.map(x=>x.id===next.id?next:x):[...items,next];if(!saveItems(nextItems))return;setForm(next);setMsg(status==='published'?'Đã cập nhật và đăng sản phẩm.':'Đã lưu bản nháp sản phẩm.')};
 if(mode==='list')return <section className="admin-panel product-manager"><div className="admin-panel-head"><div><h2>{type}</h2><p>Admin và Đối tác hiện dùng cùng chuẩn: số sao, hạng phòng/căn/cabin, giá và ảnh riêng.</p></div><button type="button" className="admin-primary" onClick={add}>+ Thêm mới</button></div><div className="admin-list-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm sản phẩm..."/><span>{shown.length} sản phẩm</span></div><div className="pm-list">{shown.map(p=><article key={p.id}>{p.cover?<img src={p.cover} alt={p.name}/>:<div className="pm-placeholder">{p.type==='Du thuyền'?'🛳':p.type==='Khách sạn'?'🏨':'🏝'}</div>}<div className="pm-info"><b>{p.name}</b><span>{p.place||'Chưa nhập địa điểm'} {p.serviceStars?`· ${'★'.repeat(Number(p.serviceStars))}`:''}</span><small>{(p.units||[]).length} căn / hạng phòng / cabin</small></div><strong>{p.price||'Liên hệ'}</strong><em className={`pm-status ${p.status}`}>{p.status==='published'?'Đang bán':p.status==='hidden'?'Đang ẩn':'Bản nháp'}</em><div className="pm-actions"><button type="button" onClick={()=>edit(p)}>Sửa</button><button type="button" onClick={()=>duplicate(p)}>Nhân bản</button><button type="button" className="danger-action" onClick={()=>remove(p)}>Xóa</button></div></article>)}</div></section>;
 const unitKind=form.type==='Khách sạn'?'hotel':form.type==='Villa & Resort'?'villa':form.type==='Du thuyền'?'cruise':'generic';
 const unitLabel=form.type==='Khách sạn'?'3. Hạng phòng & giá riêng':form.type==='Villa & Resort'?'3. Căn Villa / loại căn & giá riêng':'3. Cabin & giá riêng';
 return <section className="admin-editor-shell product-manager-editor"><div className="admin-editor-main"><div className="editor-title-row"><button type="button" className="editor-back" onClick={()=>setMode('list')}>← Danh sách</button><b>{form.id?'Chỉnh sửa sản phẩm':'Thêm sản phẩm mới'}</b><span>{msg}</span></div><input className="post-title-input" value={form.name} onChange={e=>{const old=form.name;set('name',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}} placeholder="Tên khu / sản phẩm"/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div>
 <section className="pm-section"><h3>1. Thông tin chung</h3><div className="pm-grid"><F label="Loại"><select value={form.type} onChange={e=>set('type',e.target.value as ProductType)}><option>Villa & Resort</option><option>Khách sạn</option><option>Du thuyền</option></select></F><F label="Hạng dịch vụ / số sao *" hint="Bắt buộc trước khi xuất bản"><select value={form.serviceStars} onChange={e=>set('serviceStars',e.target.value)}><option value="">— Chọn số sao —</option><option value="1">★ 1 sao</option><option value="2">★★ 2 sao</option><option value="3">★★★ 3 sao</option><option value="4">★★★★ 4 sao</option><option value="5">★★★★★ 5 sao</option></select></F><F label="Phân loại"><input value={form.category} onChange={e=>set('category',e.target.value)}/></F><F label="Khu vực"><input value={form.place} onChange={e=>set('place',e.target.value)}/></F><F label="Địa chỉ"><input value={form.address} onChange={e=>set('address',e.target.value)}/></F><F label="Giá từ"><input value={form.price} onChange={e=>set('price',e.target.value)}/></F><F label="Điểm đánh giá"><input value={form.rating} onChange={e=>set('rating',e.target.value)}/></F><F label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></F><F label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></F><F label="Thời lượng / hành trình"><input value={form.duration} onChange={e=>set('duration',e.target.value)}/></F><F label="Điểm đón / bến"><input value={form.pickup} onChange={e=>set('pickup',e.target.value)}/></F><F label="Mô tả ngắn" wide><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)}/></F></div></section>
 <section className="pm-section"><h3>2. Ảnh đại diện & Album</h3><p className="pm-section-note">Đây là ảnh chung của khách sạn/resort. Ảnh từng hạng phòng/căn được tải riêng ở phần bên dưới.</p><div className="media-product-grid"><div><b>Ảnh đại diện</b><AdminMediaPicker value={form.cover} onChange={v=>set('cover',v)} label="Chọn ảnh đại diện"/></div><div><b>Album sản phẩm</b><AdminMediaPicker multiple value={form.gallery} onChange={v=>set('gallery',v)} label="Chọn ảnh Album"/></div></div></section>
 <section className="pm-section"><UnifiedProductUnitsEditor units={form.units||[]} onChange={v=>set('units',v)} kind={unitKind} label={unitLabel}/></section>
 <section className="pm-section"><h3>4. Nội dung & chính sách</h3><div className="pm-grid"><F label="Tiện ích" wide><textarea rows={5} value={form.amenities} onChange={e=>set('amenities',e.target.value)}/></F><F label="Chính sách" wide><textarea rows={6} value={form.policies} onChange={e=>set('policies',e.target.value)}/></F><F label="Chính sách trẻ em" wide><textarea rows={4} value={form.childrenPolicy} onChange={e=>set('childrenPolicy',e.target.value)}/></F><F label="Phụ thu chung" wide><textarea rows={4} value={form.extraCharge} onChange={e=>set('extraCharge',e.target.value)}/></F><F label="Nội dung chi tiết" wide><textarea rows={8} value={form.content} onChange={e=>set('content',e.target.value)}/></F><F label="SEO title" wide><input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></F><F label="Meta description" wide><textarea rows={4} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></F></div></section></div><aside className="admin-editor-side"><div className="editor-box publish-box"><h3>Xuất bản</h3><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value as Status)}><option value="published">Đang bán</option><option value="draft">Bản nháp</option><option value="hidden">Ẩn</option></select></label><div className="publish-actions"><button type="button" onClick={()=>save('draft')}>Lưu nháp</button><button type="button" className="admin-primary" onClick={()=>save('published')}>{form.id?'Cập nhật & đăng':'Thêm & đăng'}</button></div>{form.id&&<button type="button" className="danger-action full-danger" onClick={()=>remove(form)}>Xóa toàn bộ sản phẩm</button>}</div><div className="editor-box"><h3>Ảnh đại diện</h3>{form.cover?<img className="admin-cover-preview" src={form.cover} alt=""/>:<small>Chưa chọn ảnh</small>}</div></aside></section>}
