'use client';

import {useEffect,useMemo,useState} from 'react';
type Status='draft'|'published'|'scheduled';
type Article={id:string;title:string;slug:string;category:string;excerpt:string;cover:string;content:string;seoTitle:string;seoDescription:string;status:Status;publishAt:string;date:string};
const blank:Article={id:'',title:'',slug:'',category:'Cẩm nang du lịch',excerpt:'',cover:'',content:'',seoTitle:'',seoDescription:'',status:'draft',publishAt:'',date:''};
const seeds:Article[]=[{...blank,id:'a1',title:'Kinh nghiệm du lịch Phan Thiết cho gia đình',slug:'kinh-nghiem-du-lich-phan-thiet-cho-gia-dinh',category:'Cẩm nang du lịch',status:'published',date:'20/08/2026'},{...blank,id:'a2',title:'Top villa nghỉ dưỡng đẹp tại Phước Hải',slug:'top-villa-nghi-duong-dep-tai-phuoc-hai',category:'Villa & Resort',status:'draft',date:'18/08/2026'},{...blank,id:'a3',title:'Review du thuyền Ambassador Hạ Long',slug:'review-du-thuyen-ambassador-ha-long',category:'Du thuyền',status:'published',date:'16/08/2026'}];
function slugify(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export function AdminContentEditor(){
 const key='tn_cms_articles_v2';const [mode,setMode]=useState<'list'|'edit'>('list');const [form,setForm]=useState<Article>(blank);const [items,setItems]=useState<Article[]>([]);const [saved,setSaved]=useState('');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(key)||'null')||seeds)}catch{setItems(seeds)}},[]);
 const persist=(x:Article[])=>{setItems(x);localStorage.setItem(key,JSON.stringify(x))};
 const seoScore=useMemo(()=>{let s=0;if(form.title.length>=35)s+=30;if(form.seoDescription.length>=100)s+=30;if(form.cover)s+=20;if(form.content.length>=400)s+=20;return s},[form]);
 function set<K extends keyof Article>(k:K,v:Article[K]){setForm(f=>({...f,[k]:v}))}function newPost(){setForm(blank);setSaved('');setMode('edit')}
 function edit(a:Article){setForm({...a});setSaved('');setMode('edit')}
 function remove(id:string){if(!window.confirm('Xóa bài viết này? Thao tác này không thể hoàn tác.'))return;persist(items.filter(a=>a.id!==id))}
 function save(status:Status){if(!form.title.trim()){setSaved('Vui lòng nhập tiêu đề.');return}const next={...form,id:form.id||`article_${Date.now()}`,slug:form.slug||slugify(form.title),status,date:form.date||new Date().toLocaleDateString('vi-VN')};const exists=items.some(a=>a.id===next.id);persist(exists?items.map(a=>a.id===next.id?next:a):[next,...items]);setForm(next);setSaved(status==='published'?'Đã đăng bài.':'Đã lưu bài.');}
 if(mode==='list')return <section className="admin-panel wp-list-panel"><div className="admin-panel-head"><div><h2>Bài viết / Cẩm nang</h2><p>Viết mới, sửa và xóa bài viết như CMS.</p></div><button type="button" className="admin-primary" onClick={newPost}>+ Viết bài mới</button></div><div className="wp-content-list">{items.map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.category}</span></div><span>{a.date}</span><em>{a.status==='published'?'Đã đăng':a.status==='scheduled'?'Hẹn giờ':'Bản nháp'}</em><div className="pm-actions"><button type="button" onClick={()=>edit(a)}>Sửa</button><button type="button" className="danger-action" onClick={()=>remove(a.id)}>Xóa</button></div></article>)}</div></section>;
 return <section className="admin-editor-shell"><div className="admin-editor-main"><div className="editor-title-row"><button type="button" className="editor-back" onClick={()=>setMode('list')}>← Danh sách bài</button><span>{saved}</span></div><input className="post-title-input" value={form.title} onChange={e=>{const old=form.title;set('title',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}} placeholder="Nhập tiêu đề bài viết"/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div><div className="classic-editor"><textarea value={form.content} onChange={e=>set('content',e.target.value)} placeholder="Viết nội dung bài tại đây..."/></div><div className="editor-box"><h3>Mô tả ngắn</h3><textarea rows={3} value={form.excerpt} onChange={e=>set('excerpt',e.target.value)}/></div><div className="editor-box"><div className="editor-box-head"><h3>SEO bài viết</h3><b className={seoScore>=70?'seo-good':''}>{seoScore}/100</b></div><label>SEO Title<input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></label><label>Meta description<textarea rows={3} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></label></div></div><aside className="admin-editor-side"><div className="editor-box publish-box"><h3>Xuất bản</h3><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value as Status)}><option value="draft">Bản nháp</option><option value="published">Đăng ngay</option><option value="scheduled">Hẹn giờ</option></select></label>{form.status==='scheduled'&&<label>Thời gian đăng<input type="datetime-local" value={form.publishAt} onChange={e=>set('publishAt',e.target.value)}/></label>}<div className="publish-actions"><button type="button" onClick={()=>save('draft')}>Lưu nháp</button><button type="button" className="admin-primary" onClick={()=>save(form.status==='scheduled'?'scheduled':'published')}>{form.status==='scheduled'?'Lên lịch':'Đăng bài'}</button></div>{form.id&&<button type="button" className="danger-action full-danger" onClick={()=>{remove(form.id);setMode('list')}}>Xóa bài viết</button>}</div><div className="editor-box"><h3>Chuyên mục</h3><select value={form.category} onChange={e=>set('category',e.target.value)}><option>Cẩm nang du lịch</option><option>Tour</option><option>Villa & Resort</option><option>Khách sạn</option><option>Du thuyền</option></select></div><div className="editor-box"><h3>Ảnh đại diện</h3><input value={form.cover} onChange={e=>set('cover',e.target.value)} placeholder="URL ảnh"/></div></aside></section>;
}
