'use client';
import {useEffect,useMemo,useState} from 'react';
import {AdminOperatorMonthlyReport} from '@/components/AdminOperatorMonthlyReport';

type Booking={id:string;code:string;status:string;startDate?:string;endDate?:string;sellingTotal:number;costTotal:number|null;customerPaid:number;supplierPaid:number};
type Followup={id:string;dueAt:string;status:'open'|'done'};
type Complaint={id:string;type:string;status:'open'|'resolved';assignedToId?:string;dueAt?:string};
type Ops={supplierConfirmed?:boolean;voucherReady?:boolean;customerConfirmationSent?:boolean;finalCheck?:boolean;operatorId?:string;handoffAccepted?:boolean;customerCompleted?:boolean;supplierReconciled?:boolean;financeReconciled?:boolean;closedAt?:string};
type Capabilities={manager:boolean;finance:boolean;actorId:string;actorName:string;role:string};

function days(value?:string){if(!value)return 999;const d=new Date(`${value.slice(0,10)}T00:00:00`),n=new Date();n.setHours(0,0,0,0);return Math.ceil((+d-+n)/86400000)}
function dueSoon(value?:string){if(!value)return true;const time=+new Date(value);return Number.isFinite(time)&&time<=Date.now()+86400000}
function serviceIssues(o:Ops,paid:boolean,left:number){const issues:string[]=[];if(left<0||left>7)return issues;if(left<=7&&!o.supplierConfirmed)issues.push('NCC');if(left<=3&&!paid)issues.push('thanh toán NCC');if(left<=3&&!o.voucherReady)issues.push('voucher');if(left<=2&&!o.customerConfirmationSent)issues.push('phiếu khách');if(left<=1&&!o.finalCheck)issues.push('kiểm tra cuối');return issues}

export function AdminTodayWork({open}:{open:(m:string)=>void}){
 const[bookings,setBookings]=useState<Booking[]>([]),[followups,setFollowups]=useState<Followup[]>([]),[complaints,setComplaints]=useState<Complaint[]>([]),[ops,setOps]=useState<Record<string,Ops>>({}),[caps,setCaps]=useState<Capabilities|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{try{const[opsResult,crmResult,feedbackResult]=await Promise.allSettled([fetch('/api/admin/service-operations',{cache:'no-store'}),fetch('/api/admin/crm-workflow',{cache:'no-store'}),fetch('/api/admin/customer-feedback',{cache:'no-store'})]);if(opsResult.status!=='fulfilled'||!opsResult.value.ok)throw new Error('Không đọc được dữ liệu công việc production.');const opsData=await opsResult.value.json();let crmData:any={followups:[]},feedbackData:any={items:[]};if(crmResult.status==='fulfilled'&&crmResult.value.ok)crmData=await crmResult.value.json();if(feedbackResult.status==='fulfilled'&&feedbackResult.value.ok)feedbackData=await feedbackResult.value.json();if(!alive)return;setBookings(Array.isArray(opsData.bookings)?opsData.bookings:[]);setOps(opsData.ops&&typeof opsData.ops==='object'?opsData.ops:{});setCaps(opsData.capabilities||null);setFollowups(Array.isArray(crmData.followups)?crmData.followups:[]);setComplaints(Array.isArray(feedbackData.items)?feedbackData.items:[]);setError('')}catch(e){if(alive)setError(e instanceof Error?e.message:'Không tải được công việc hôm nay.')}};load();const refresh=()=>load();window.addEventListener('focus',refresh);['tn-bookings-updated','happygo-crm-followups-updated','happygo-customer-feedback-updated','happygo-booking-ops-updated','happygo-payment-updated','happygo-customer-receipts-updated','happygo-admin-auth'].forEach(name=>window.addEventListener(name,refresh));return()=>{alive=false;window.removeEventListener('focus',refresh);['tn-bookings-updated','happygo-crm-followups-updated','happygo-customer-feedback-updated','happygo-booking-ops-updated','happygo-payment-updated','happygo-customer-receipts-updated','happygo-admin-auth'].forEach(name=>window.removeEventListener(name,refresh))}},[]);
 const work=useMemo(()=>{if(!caps)return{follow:0,complaint:0,depart:0,ops:0,handoff:0,unassigned:0,reconcile:0};const visible=bookings.filter(b=>b.status!=='cancelled'),follow=followups.filter(f=>f.status==='open'&&dueSoon(f.dueAt)).length,complaint=complaints.filter(c=>c.type==='complaint'&&c.status==='open'&&c.assignedToId===caps.actorId&&dueSoon(c.dueAt)).length,manager=caps.manager,operator=caps.role==='operations',accounting=caps.role==='accounting',assignedOps=visible.filter(b=>ops[String(b.id)]?.operatorId===caps.actorId&&b.status!=='completed'),opsScope=manager?visible.filter(b=>b.status!=='completed'):operator?assignedOps:[],departScope=manager?visible:operator?assignedOps:visible,depart=departScope.filter(b=>b.status!=='completed'&&days(b.startDate)>=0&&days(b.startDate)<=3).length,opsCount=opsScope.filter(b=>serviceIssues(ops[String(b.id)]||{},Number(b.supplierPaid||0)>0,days(b.startDate)).length>0).length,handoff=(manager?visible:operator?assignedOps:[]).filter(b=>b.status==='confirmed'&&!ops[String(b.id)]?.handoffAccepted).length,unassigned=(manager||operator)?visible.filter(b=>b.status==='confirmed'&&!ops[String(b.id)]?.operatorId).length:0,reconcileScope=manager||accounting?visible:operator?assignedOps:[],reconcile=reconcileScope.filter(b=>{const o=ops[String(b.id)]||{},postDone=[o.customerCompleted,o.supplierReconciled,o.financeReconciled].every(Boolean),customerDue=Math.max(0,Number(b.sellingTotal||0)-Number(b.customerPaid||0)),supplierDue=Math.max(0,Number(b.costTotal||0)-Number(b.supplierPaid||0));return b.status!=='completed'&&days(b.endDate||b.startDate)<0&&!o.closedAt&&(!postDone||customerDue>0||supplierDue>0)}).length;return{follow,complaint,depart,ops:opsCount,handoff,unassigned,reconcile}},[caps,bookings,followups,complaints,ops]);
 const total=work.follow+work.complaint+work.depart+work.ops+work.handoff+work.unassigned+work.reconcile;
 return <><section className="admin-panel today-work"><div className="admin-panel-head"><div><small>CÔNG VIỆC CỦA TÔI</small><h2>Hôm nay cần xử lý gì?</h2><p>Số liệu đọc trực tiếp từ Booking, CRM, phản hồi khách và Điều hành production; không còn phụ thuộc cache của từng máy.</p></div><strong className={total?'today-count alert':'today-count'}>{total} việc</strong></div>{error&&<div className="admin-empty-state"><b>Chưa tải được công việc</b><span>{error}</span></div>}<div className="today-work-grid"><button onClick={()=>open('Điều hành Sale')}><span>⏰</span><div><b>{work.follow}</b><strong>Chăm sóc khách</strong><small>Đến hạn / quá hạn trong 24 giờ</small></div></button><button onClick={()=>open('Khách hàng / CRM')} className={work.complaint?'urgent':''}><span>☎</span><div><b>{work.complaint}</b><strong>Khiếu nại được giao</strong><small>Đến hạn / quá hạn trong 24 giờ</small></div></button><button onClick={()=>open('Điều hành dịch vụ')}><span>🧳</span><div><b>{work.depart}</b><strong>Khách sắp đi</strong><small>Booking phụ trách khởi hành trong 3 ngày</small></div></button><button onClick={()=>open('Điều hành dịch vụ')} className={work.handoff?'urgent':''}><span>⇄</span><div><b>{work.handoff}</b><strong>Chưa nhận bàn giao</strong><small>Booking đã phân nhưng chưa bắt đầu Điều hành</small></div></button><button onClick={()=>open('Điều hành dịch vụ')} className={work.ops?'urgent':''}><span>⚠️</span><div><b>{work.ops}</b><strong>Quá hạn bước dịch vụ</strong><small>NCC / thanh toán / voucher / phiếu khách / kiểm tra cuối</small></div></button><button onClick={()=>open('Điều hành dịch vụ')} className={work.unassigned?'urgent':''}><span>👤</span><div><b>{work.unassigned}</b><strong>Chưa phân Điều hành</strong><small>Booking xác nhận chưa có người phụ trách</small></div></button><button onClick={()=>open('Điều hành dịch vụ')} className={work.reconcile?'urgent':''}><span>✓</span><div><b>{work.reconcile}</b><strong>Chờ đối soát</strong><small>Checklist hoặc công nợ chưa hoàn tất</small></div></button></div></section><AdminOperatorMonthlyReport/></>
}
