'use client';

import {useEffect,useMemo,useState} from 'react';
import {AdminMediaManager,AdminMediaPicker} from '@/components/AdminMediaLibrary';

type SeoSettings={siteTitle:string;description:string;keywords:string;ogImage:string;organizationName:string;canonicalBase:string};
type SiteSettings={brand:string;hotline:string;email:string;zalo:string};
const seoKey='tn_cms_seo_v1';const siteKey='tn_cms_site_settings_v1';
const defaultSeo:SeoSettings={siteTitle:'Thúy Nguyên Travel',description:'Đặt villa, khách sạn, resort, tour và du thuyền toàn quốc.',keywords:'du lịch, tour, villa, khách sạn, resort, du thuyền',ogImage:'',organizationName:'Thúy Nguyên Travel',canonicalBase:'https://banguyen310941-coder.github.io/thuy-nguyen-travel'};
const defaultSite:SiteSettings={brand:'Thúy Nguyên Travel',hotline:'0969973949',email:'info@thuynguyentravel.com',zalo:'0969973949'};

export function AdminMediaPanel(){return <AdminMediaManager/>}
export function AdminSeoPanel(){const [form,setForm]=useState<SeoSettings>(defaultSeo);const [msg,setMsg]=useState('');useEffect(()=>{try{const raw=localStorage.getItem(seoKey);if(raw)setForm({...defaultSeo,...JSON.parse(raw)})}catch{}},[]);const set=<K extends keyof SeoSettings>(k:K,v:SeoSettings[K])=>setForm(f=>({...f,[k]:v}));const score=useMemo(()=>{let s=0;if(form.siteTitle.length>=20&&form.siteTitle.length<=60)s+=25;if(form.description.length>=100&&form.description.length<=170)s+=30;if(form.keywords.trim())s+=10;if(form.organizationName.trim())s+=10;if(form.canonicalBase.startsWith('http'))s+=15;if(form.ogImage)s+=10;return s},[form]);const save=()=>{localStorage.setItem(seoKey,JSON.stringify(form));setMsg('Đã lưu cấu hình SEO trên trình duyệt này.')};return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Cấu hình SEO toàn website</h2><p>Thiết lập title, description, Open Graph và thương hiệu.</p></div><strong className={score>=70?'seo-good':''}>{score}/100</strong></div><div className="utility-form-grid"><label className="wide">Tên website / Title mặc định<input value={form.siteTitle} onChange={e=>set('siteTitle',e.target.value)}/></label><label className="wide">Meta description<textarea rows={4} value={form.description} onChange={e=>set('description',e.target.value)}/></label><label className="wide">Từ khóa gợi ý<input value={form.keywords} onChange={e=>set('keywords',e.target.value)}/></label><label>Tên tổ chức<input value={form.organizationName} onChange={e=>set('organizationName',e.target.value)}/></label><label>Canonical base URL<input value={form.canonicalBase} onChange={e=>set('canonicalBase',e.target.value)}/></label><div className="wide"><b className="field-label">Ảnh Open Graph mặc định</b><AdminMediaPicker value={form.ogImage} onChange={v=>set('ogImage',v)} label="Chọn ảnh OG"/></div></div><div className="seo-admin-checks"><span className={form.siteTitle.length>=20&&form.siteTitle.length<=60?'ok':''}>Title 20–60 ký tự</span><span className={form.description.length>=100&&form.description.length<=170?'ok':''}>Description 100–170 ký tự</span><span className={form.canonicalBase.startsWith('http')?'ok':''}>Canonical hợp lệ</span><span className={form.ogImage?'ok':''}>Có ảnh chia sẻ</span></div><button type="button" className="admin-primary" onClick={save}>Lưu cấu hình SEO</button>{msg&&<p className="cms-message">{msg}</p>}</section>}
export function AdminSettingsPanel(){const [form,setForm]=useState<SiteSettings>(defaultSite);const [msg,setMsg]=useState('');useEffect(()=>{try{const raw=localStorage.getItem(siteKey);if(raw)setForm({...defaultSite,...JSON.parse(raw)})}catch{}},[]);const set=<K extends keyof SiteSettings>(k:K,v:SiteSettings[K])=>setForm(f=>({...f,[k]:v}));const save=()=>{localStorage.setItem(siteKey,JSON.stringify(form));window.dispatchEvent(new Event('tn-site-settings-updated'));setMsg('Đã lưu cài đặt website trên trình duyệt này.')};return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Cài đặt hệ thống</h2><p>Thông tin thương hiệu và liên hệ dùng chung trên website.</p></div></div><div className="utility-form-grid"><label>Tên thương hiệu<input value={form.brand} onChange={e=>set('brand',e.target.value)}/></label><label>Hotline<input value={form.hotline} onChange={e=>set('hotline',e.target.value.replace(/\D/g,''))}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Zalo<input value={form.zalo} onChange={e=>set('zalo',e.target.value.replace(/\D/g,''))}/></label></div><button type="button" className="admin-primary" onClick={save}>Lưu cài đặt</button>{msg&&<p className="cms-message">{msg}</p>}</section>}
export function AdminDrivePanel(){return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Google Drive → Website</h2><p>Đọc tài liệu/bảng giá/ảnh trong Drive → tạo bản nháp → duyệt → xuất bản.</p></div><em className="pm-status draft">Chờ backend</em></div><div className="drive-drop"><b>Chưa bật kết nối Drive trên GitHub Pages</b><span>Google Drive cần OAuth và backend an toàn. Module sẽ được kích hoạt khi chuyển website sang hosting riêng.</span></div></section>}
