'use client';

import {useEffect,useMemo,useState} from 'react';

type EntryType='income'|'expense';type Fund='cash'|'bank'|'wallet';
type Entry={id:string;voucherNo:string;type:EntryType;date:string;category:string;description:string;counterparty:string;fund:Fund;amount:number;documentRef:string;note:string;source:string;sourceId:string;createdBy:string;createdAt:string;voidedAt:string;voidedBy:string;voidReason:string};
type ApiData={entries:Entry[];balances:{cash:number;bank:number;wallet:number;updatedAt:string};totals:{income:number;expense:number};capabilities:{manageBalances:boolean;manual:boolean;void:boolean}};
const money=(value:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(value))+'đ';const today=()=>new Date().toISOString().slice(0,10);const monthNow=()=>today().slice(0,7);const fundLabel:Record<Fund,string>={cash:'Tiền mặt',bank:'Ngân hàng',wallet:'Ví điện tử'};const sourceLabel:Record<string,string>={receipt:'Phiếu thu khách',supplier:'Thanh toán NCC',manual:'Bút toán thủ công',marketing:'Marketing'};

export function AdminAccountingWorkspace(){
 const[data,setData]=useState<ApiData>({entries:[],balances:{cash:0,bank:0,wallet:0,updatedAt:''},totals:{income:0,expense:0},capabilities:{manageBalances:false,manual:false,void:false}}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[month,setMonth]=useState(monthNow()),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[balanceOpen,setBalanceOpen]=useState(false);
 const[type,setType]=useState<EntryType>('income'),[date,setDate]=useState(today()),[category,setCategory]=useState('Thu khác'),[description,setDescription]=useState(''),[counterparty,setCounterparty]=useState(''),[fund,setFund]=useState<Fund>('bank'),[amount,setAmount]=useState(''),[documentRef,setDocumentRef]=useState(''),[note,setNote]=useState('');const[cash,setCash]=useState('0'),[bank,setBank]=useState('0'),[wallet,setWallet]=useState('0');
 async function load(){setLoading(true);try{const res=await fetch('/api/admin/accounting',{cache:'no-store'}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không đọc được sổ kế toán.');setData(json);setCash(String(json.balances.cash||0));setBank(String(json.balances.bank||0));setWallet(String(json.balances.wallet||0))}catch(error){setMessage(error instanceof Error?error.message:'Không đọc được sổ kế toán.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const activeEntries=data.entries.filter(item=>!item.voidedAt);const monthEntries=useMemo(()=>activeEntries.filter(item=>item.date.slice(0,7)===month).filter(item=>!query.trim()||`${item.voucherNo} ${item.category} ${item.description} ${item.counterparty} ${item.documentRef}`.toLowerCase().includes(query.toLowerCase())),[activeEntries,month,query]);
 const monthIncome=monthEntries.filter(item=>item.type==='income').reduce((sum,item)=>sum+item.amount,0),monthExpense=monthEntries.filter(item=>item.type==='expense').reduce((sum,item)=>sum+item.amount,0);const allNet=data.totals.income-data.totals.expense;const openingTotal=data.balances.cash+data.balances.bank+data.balances.wallet;
 async function post(body:Record<string,unknown>){const res=await fetch('/api/admin/accounting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không thể cập nhật kế toán.');return json}
 function changeType(next:EntryType){setType(next);setCategory(next==='income'?'Thu khác':'Chi phí khác')}
 async function saveEntry(){const value=Number(amount.replace(/\D/g,''));if(!date||!category.trim()||!description.trim()||value<=0)return setMessage('Nhập đủ ngày, nhóm, nội dung và số tiền.');try{const json=await post({action:'manual',type,date,category,description,counterparty,fund,amount:value,documentRef,note});setMessage(`Đã ghi ${json.voucherNo}.`);setOpen(false);setDescription('');setCounterparty('');setAmount('');setDocumentRef('');setNote('');setMonth(date.slice(0,7));await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể ghi bút toán.')}}
 async function saveBalances(){try{await post({action:'balances',cash:Number(cash.replace(/\D/g,'')),bank:Number(bank.replace(/\D/g,'')),wallet:Number(wallet.replace(/\D/g,''))});setMessage('Đã cập nhật số dư đầu kỳ.');setBalanceOpen(false);await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể cập nhật số dư.')}}
 async function voidEntry(item:Entry){const reason=prompt(`Lý do hủy bút toán ${item.voucherNo}`,'');if(!reason?.trim())return;try{await post({action:'void',id:item.id,reason});setMessage(`Đã hủy ${item.voucherNo}; chứng từ vẫn được giữ trong lịch sử.`);await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể hủy bút toán.')}}
 return <section className="admin-panel accounting-workspace">
  <div className="admin-panel-head"><div><small>SỔ KẾ TOÁN PRODUCTION</small><h2>Thu · Chi · Số dư</h2><p>Phiếu thu khách và thanh toán nhà cung cấp tự động vào sổ. Bút toán đã ghi không bị xóa, chỉ được hủy có lý do.</p></div><div className="receipt-actions">{data.capabilities.manual&&<button className="admin-primary" onClick={()=>setOpen(value=>!value)}>+ Ghi bút toán</button>}{data.capabilities.manageBalances&&<button className="admin-secondary" onClick={()=>setBalanceOpen(value=>!value)}>Số dư đầu kỳ</button>}</div></div>
  {message&&<p className="admin-api-note">{message}</p>}
  <div className="payment-kpis"><article><small>THU THÁNG {month}</small><b>{money(monthIncome)}</b></article><article><small>CHI THÁNG {month}</small><b>{money(monthExpense)}</b></article><article><small>CHÊNH LỆCH THÁNG</small><b>{money(monthIncome-monthExpense)}</b></article><article><small>SỐ DƯ ƯỚC TÍNH TOÀN HỆ THỐNG</small><b>{money(openingTotal+allNet)}</b></article></div>
  {balanceOpen&&data.capabilities.manageBalances&&<div className="receipt-form"><h3>Số dư đầu kỳ</h3><div className="receipt-grid"><label>Tiền mặt<input inputMode="numeric" value={cash} onChange={event=>setCash(event.target.value)}/></label><label>Ngân hàng<input inputMode="numeric" value={bank} onChange={event=>setBank(event.target.value)}/></label><label>Ví điện tử<input inputMode="numeric" value={wallet} onChange={event=>setWallet(event.target.value)}/></label></div><div className="receipt-actions"><button className="admin-primary" onClick={saveBalances}>Lưu số dư</button><button className="admin-secondary" onClick={()=>setBalanceOpen(false)}>Hủy</button></div></div>}
  {open&&data.capabilities.manual&&<div className="receipt-form"><div className="receipt-grid"><label>Loại<select value={type} onChange={event=>changeType(event.target.value as EntryType)}><option value="income">Thu</option><option value="expense">Chi</option></select></label><label>Ngày<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Nhóm<input value={category} onChange={event=>setCategory(event.target.value)}/></label><label>Nội dung<input value={description} onChange={event=>setDescription(event.target.value)}/></label><label>Đối tượng<input value={counterparty} onChange={event=>setCounterparty(event.target.value)} placeholder="Khách hàng / NCC / nhân viên"/></label><label>Quỹ<select value={fund} onChange={event=>setFund(event.target.value as Fund)}><option value="bank">Ngân hàng</option><option value="cash">Tiền mặt</option><option value="wallet">Ví điện tử</option></select></label><label>Số tiền<input inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>Số chứng từ<input value={documentRef} onChange={event=>setDocumentRef(event.target.value)}/></label><label>Ghi chú<input value={note} onChange={event=>setNote(event.target.value)}/></label></div><div className="receipt-actions"><button className="admin-primary" onClick={saveEntry}>Ghi sổ</button><button className="admin-secondary" onClick={()=>setOpen(false)}>Hủy</button></div></div>}
  <div className="admin-list-toolbar"><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Tìm số phiếu, nội dung, đối tượng..."/><span>{monthEntries.length} bút toán</span></div>
  <div className="admin-api-note">Số dư đầu kỳ: {money(openingTotal)} · {Object.entries(fundLabel).map(([id,label])=>`${label} ${money(data.balances[id as Fund])}`).join(' · ')}</div>
  {loading?<div className="admin-empty-state">Đang tải sổ kế toán...</div>:<div className="receipt-list">{monthEntries.map(item=><article key={item.id}><div><b>{item.voucherNo}</b><span>{new Date(`${item.date}T00:00:00`).toLocaleDateString('vi-VN')} · {sourceLabel[item.source]||item.source}</span></div><strong>{item.type==='income'?'+':'-'}{money(item.amount)}</strong><div><b>{item.category}</b><span>{item.description}</span></div><div><b>{item.counterparty||'—'}</b><span>{fundLabel[item.fund]}{item.documentRef?` · ${item.documentRef}`:''}</span></div><div><b>{item.createdBy||'Hệ thống'}</b><span>{item.note||'Không có ghi chú'}</span></div>{data.capabilities.void&&<button className="admin-secondary" onClick={()=>voidEntry(item)}>Hủy bút toán</button>}</article>)}{!monthEntries.length&&<div className="admin-empty-state">Tháng này chưa có bút toán.</div>}</div>}
  {!!data.entries.filter(item=>item.voidedAt).length&&<details><summary>Chứng từ đã hủy ({data.entries.filter(item=>item.voidedAt).length})</summary>{data.entries.filter(item=>item.voidedAt).slice(0,100).map(item=><p key={item.id}>{item.voucherNo} · {money(item.amount)} · {item.voidReason} · {item.voidedBy}</p>)}</details>}
 </section>
}
