'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';

type Entry={id:string;type:string;content:string;result:string;staffId:string;staffName:string;createdAt:string;nextAt?:string};
const names:Record<string,string>={call:'Gọi điện',zalo:'Zalo',email:'Email',note:'Ghi chú',booking:'Booking',followup:'Follow-up',follow_up:'Follow-up',follow_up_done:'Hoàn tất follow-up',post_trip:'Sau chuyến',need_update:'Cập nhật nhu cầu',quote_create:'Tạo báo giá',quote_status:'Cập nhật báo giá',quote_rejected:'Báo giá bị từ chối',quote_accepted:'Khách đồng ý báo giá',quote_booking:'Tạo booking từ báo giá',website_booking:'Booking website'};

export function AdminCrmHistory({phone,email,customerName}:{phone:string;email?:string|null;customerName:string}){
 const[items,setItems]=useState<Entry[]>([]),[type,setType]=useState('call'),[content,setContent]=useState(''),[result,setResult]=useState('Đã liên hệ'),[nextAt,setNextAt]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const query=useMemo(()=>`phone=${encodeURIComponent(phone||'')}&email=${encodeURIComponent(email||'')}`,[phone,email]);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`/api/admin/crm-history?${query}`,{cache:'no-store'});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(response.status===401?'Phiên quản trị đã hết hạn.':json.error||'Không đọc được lịch sử CRM.');setItems(Array.isArray(json.items)?json.items:[])}catch(error){setMessage(error instanceof Error?error.message:'Không đọc được lịch sử CRM production.')}finally{setLoading(false)}},[query]);
 useEffect(()=>{void load()},[load]);
 async function add(){if(!content.trim())return setMessage('Nhập nội dung trao đổi trước khi lưu.');setBusy(true);setMessage('');try{const response=await fetch('/api/admin/crm-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,email,type,result,content:content.trim(),nextAt})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Không lưu được lịch sử.');setContent('');setNextAt('');await load();setMessage('✓ Đã lưu tương tác và đồng bộ production.')}catch(error){setMessage(error instanceof Error?error.message:'Không lưu được lịch sử CRM.')}finally{setBusy(false)}}
 return <div className="crm-history"><div className="crm-history-title"><div><b>Lịch sử chăm sóc · Production</b><small>{customerName} · {items.length} tương tác</small></div><button className="admin-secondary" disabled={loading} onClick={()=>void load()}>↻</button></div>{message&&<p className={message.startsWith('✓')?'cms-message':'admin-api-note'}>{message}</p>}<div className="crm-history-form"><select value={type} onChange={e=>setType(e.target.value)}><option value="call">Gọi điện</option><option value="zalo">Zalo</option><option value="email">Email</option><option value="note">Ghi chú</option><option value="booking">Booking</option></select><select value={result} onChange={e=>setResult(e.target.value)}><option>Đã liên hệ</option><option>Khách quan tâm</option><option>Chờ phản hồi</option><option>Gửi báo giá</option><option>Không nghe máy</option><option>Không còn nhu cầu</option><option>Đã chốt</option></select><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Nội dung trao đổi, nhu cầu, mức giá khách quan tâm..."/><label>Chăm sóc tiếp<input type="datetime-local" value={nextAt} onChange={e=>setNextAt(e.target.value)}/><small>{nextAt?'Server sẽ tạo nhắc việc trong Điều hành Sale.':'Không chọn nếu chưa cần hẹn lại.'}</small></label><button className="admin-primary" disabled={busy||!content.trim()} onClick={()=>void add()}>{busy?'Đang lưu...':'Lưu tương tác'}</button></div><div className="crm-timeline">{items.map(item=><article key={item.id}><i>{item.type==='call'?'☎':item.type==='zalo'?'Z':item.type==='email'?'✉':item.type.includes('booking')?'▣':item.type.includes('follow')?'✓':'•'}</i><div><header><b>{names[item.type]||item.type}</b><time>{new Date(item.createdAt).toLocaleString('vi-VN')}</time></header><p>{item.content}</p><small>{item.staffName}{item.nextAt?` · Hẹn tiếp: ${new Date(item.nextAt).toLocaleString('vi-VN')}`:''}</small></div></article>)}{!loading&&!items.length&&<div className="admin-empty-state">Chưa có lịch sử chăm sóc khách này.</div>}{loading&&!items.length&&<div className="admin-empty-state">Đang tải lịch sử production...</div>}</div></div>;
}
