'use client';

import { useState } from 'react';

const sections=['Thông tin cơ bản','Giá & lịch khởi hành','Album ảnh','Điểm nổi bật','Lịch trình','Dịch vụ','Chính sách','Ưu đãi','Đánh giá & FAQ','SEO'];

export function AdminTourEditor(){
 const [tab,setTab]=useState(sections[0]);
 return <section className="admin-panel tour-editor-admin">
  <div className="admin-panel-head"><div><h2>Đăng / chỉnh sửa Tour</h2><p>Các trường được chia theo đúng cấu trúc trang chi tiết tour ngoài website.</p></div><div><button>Xem trước</button> <button className="admin-primary">Lưu tour</button></div></div>
  <div className="tour-editor-tabs">{sections.map(s=><button key={s} className={tab===s?'active':''} onClick={()=>setTab(s)}>{s}</button>)}</div>
  {tab==='Thông tin cơ bản'&&<div className="tour-editor-grid"><label>Tên tour<input defaultValue="Tinh hoa Trung Quốc: Bắc Kinh - Thượng Hải - Hàng Châu - Ô Trấn"/></label><label>Danh mục<select><option>Tour Trung Quốc</option><option>Tour trong nước</option></select></label><label>Thời lượng<input defaultValue="7N6Đ"/></label><label>Khởi hành từ<input defaultValue="Hà Nội"/></label><label>Hãng bay<input defaultValue="Vietjet Air"/></label><label>Tuyến điểm đến<input defaultValue="Hà Nội - Bắc Kinh - Hàng Châu - Ô Trấn - Thượng Hải"/></label><label className="span-2">Mô tả ngắn<textarea defaultValue="Hành trình Trung Quốc nhiều điểm đến, kết hợp di sản lịch sử, đô thị hiện đại và cảnh quan Giang Nam."/></label><label>Phương tiện<input defaultValue="Máy bay, Tàu, Ô tô"/></label><label>Trạng thái<select><option>Đang bán</option><option>Nháp</option><option>Ẩn</option></select></label></div>}
  {tab==='Giá & lịch khởi hành'&&<div className="tour-editor-grid"><label>Giá gốc<input defaultValue="21.680.000đ"/></label><label>Giá bán từ<input defaultValue="21.180.000đ"/></label><label>Giá trẻ em<input placeholder="Theo độ tuổi / nhập giá"/></label><label>Phụ thu phòng đơn<input placeholder="Nhập mức phụ thu"/></label><label className="span-2">Lịch khởi hành<textarea defaultValue={'30/08\n21/09\n27/09\n04/10\n18/10'}/></label></div>}
  {tab==='Album ảnh'&&<><div className="drive-drop"><b>Ảnh đại diện + album tour</b><span>Kéo thả nhiều ảnh hoặc chọn từ Media / Google Drive</span><button className="admin-primary">Chọn ảnh</button></div><div className="tour-media-slots"><span>Ảnh đại diện</span><span>Ảnh 2</span><span>Ảnh 3</span><span>+ Thêm ảnh</span></div></>}
  {tab==='Điểm nổi bật'&&<div className="tour-editor-grid"><label className="span-2">Mỗi dòng là một điểm nổi bật<textarea rows={9} defaultValue={'Khách sạn tiêu chuẩn theo chương trình\nKhám phá Vạn Lý Trường Thành\nTrải nghiệm Giang Nam và Ô Trấn\nTham quan Thượng Hải hiện đại\nẨm thực địa phương đặc sắc'}/></label></div>}
  {tab==='Lịch trình'&&<div className="tour-day-admin">{['Ngày 1','Ngày 2','Ngày 3'].map((d,i)=><article key={d}><div><b>{d}</b><button>× Xóa</button></div><label>Tiêu đề<input defaultValue={i===0?'Hà Nội - Bắc Kinh':i===1?'Bắc Kinh - Vạn Lý Trường Thành':'Bắc Kinh - Cố Cung'}/></label><label>Buổi sáng<textarea/></label><label>Buổi chiều<textarea/></label><label>Buổi tối<textarea/></label><label>Bữa ăn<input placeholder="Sáng / Trưa / Tối"/></label></article>)}<button className="admin-primary">+ Thêm ngày</button></div>}
  {tab==='Dịch vụ'&&<div className="tour-editor-grid"><label>Giá bao gồm<textarea rows={10} defaultValue={'Vé máy bay/di chuyển theo chương trình\nKhách sạn theo tiêu chuẩn tour\nCác bữa ăn theo lịch trình\nVé tham quan\nHướng dẫn viên\nBảo hiểm du lịch'}/></label><label>Không bao gồm<textarea rows={10} defaultValue={'Chi phí cá nhân\nDịch vụ ngoài chương trình\nPhụ thu phòng đơn\nChi phí phát sinh khác'}/></label></div>}
  {tab==='Chính sách'&&<div className="tour-editor-grid"><label className="span-2">Chính sách đặt cọc / hoàn hủy / trẻ em<textarea rows={12}/></label></div>}
  {tab==='Ưu đãi'&&<div className="tour-editor-grid"><label>Tên ưu đãi<input placeholder="Đặt sớm giảm..."/></label><label>Thời hạn<input type="date"/></label><label className="span-2">Nội dung ưu đãi<textarea rows={8}/></label><label><input type="checkbox"/> Hiển thị ưu đãi trên trang tour</label></div>}
  {tab==='Đánh giá & FAQ'&&<div className="tour-editor-grid"><label>Điểm đánh giá<input type="number" step="0.1" defaultValue="8.8"/></label><label>Số đánh giá<input type="number" defaultValue="23"/></label><label className="span-2">FAQ - mỗi câu hỏi/câu trả lời một cặp<textarea rows={10} placeholder={'Hỏi: Tour khởi hành từ đâu?\nĐáp: Hà Nội...\n\nHỏi: Giá đã gồm visa chưa?\nĐáp: ...'}/></label></div>}
  {tab==='SEO'&&<div className="tour-editor-grid"><label className="span-2">SEO Title<input defaultValue="Tour Trung Quốc 7N6Đ Bắc Kinh - Thượng Hải - Hàng Châu - Ô Trấn"/></label><label className="span-2">Meta description<textarea rows={4}/></label><label>Slug<input defaultValue="bac-kinh-van-ly-truong-thanh"/></label><label>Canonical URL<input placeholder="Tự động nếu để trống"/></label><label className="span-2">Schema / từ khóa bổ sung<textarea rows={5}/></label></div>}
 </section>
}
