'use client';

import {useEffect,useMemo,useState} from 'react';
import {bookingRevenue,canEditOperations,canViewBooking,isAccountingStaff,isAdminStaff,isOperationsStaff,isOwner,money,readCurrentStaff,type AdminStaff} from '@/components/AdminSalesAccess';

type Booking={id:number;code:string;product:string;customer_name:string;phone:string;email?:string|null;start_date?:string|null;status:string;revenue?:number;costPrice?:number};
type Ops={handoffAccepted?:boolean;operatorId?:string;operatorName?:string};
type Supplier={id:string;name:string;bankName:string;accountNumber:string;accountName:string;phone:string};
type Receipt={bookingId:number;amount:number};
type PaymentStatus='draft'|'pending_director'|'changes_requested'|'rejected'|'approved'|'paid';
type Payment={id:string;bookingId:number;bookingCode:string;customerName:string;product:string;supplierName:string;amount:number;status:PaymentStatus;paidAmount?:number;createdById:string;createdByName:string;source?:string;serviceOrderId?:string};
type OrderStatus='draft'|'sent'|'confirmed'|'completed'|'cancelled';
type Audit={id:string;at:string;byId:string;byName:string;action:string;detail?:string};
type Order={id:string;bookingId:number;bookingCode:string;customerName:string;product:string;serviceType:string;serviceDate:string;supplierId:string;supplierName:string;supplierContact:string;bankName:string;accountNumber:string;accountName:string;amount:number;dueDate:string;note:string;status:OrderStatus;supplierRef:string;voucherRef:string;voucherReady:boolean;paymentRequestId?:string;createdById:string;createdByName:string;createdAt:string;updatedById:string;updatedByName:string;updatedAt:string;sentAt?:string;confirmedAt?:string;confirmedBy?:string;voucherReadyAt?:string;voucherReadyBy?:string;completedAt?:string;completedBy?:string;cancelledAt?:string;cancelledBy?:string;audit?:Audit[]};
type Draft={bookingId:string;serviceType:string;serviceDate:string;supplierId:string;supplierName:string;supplierContact:string;bankName:string;accountNumber:string;accountName:string;amount:string;dueDate:string;note:string};
type Filter='active'|'need_confirm'|'need_payment'|'need_voucher'|'all';

const KEYS={bookings:'tn_local_bookings_v1',ops:'happygo_booking_ops_checklist_v1',suppliers:'happygo_payment_suppliers_v1',receipts:'happygo_customer_receipts_v1',payments:'happygo_payment_requests_v1',orders:'happygo_supplier_service_orders_v1'};
const blank:Draft={bookingId:'',serviceType:'Khách sạn / Villa',serviceDate:'',supplierId:'',supplierName:'',supplierContact:'',bankName:'',accountNumber:'',accountName:'',amount:'',dueDate:'',note:''};
const statusLabel:Record<OrderStatus,string>={draft:'Nháp',sent:'Đã gửi NCC',confirmed:'NCC đã xác nhận',completed:'Hoàn tất',cancelled:'Đã hủy'};
const paymentLabel:Record<PaymentStatus,string>={draft:'Nháp',pending_director:'Chờ BGĐ duyệt',changes_requested:'Cần bổ sung',rejected:'Bị từ chối',approved:'Kế toán chờ chi',paid:'Đã chi'};
const serviceTypes=['Khách sạn / Villa','Tour / Land','Xe / Transfer','Vé tham quan','Vé máy bay / Tàu','Du thuyền','Nhà hàng','Khác'];
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}
function store<T>(key:string,value:T,event:string){localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new Event(event))}
function num(value:unknown){const parsed=Number(String(value??'').replace(/[^\d.-]/g,''));return Number.isFinite(parsed)?parsed:0}
function date(value?:string){if(!value)return'—';const parsed=new Date(`${value.slice(0,10)}T00:00:00`);return Number.isNaN(+parsed)?value:parsed.toLocaleDateString('vi-VN')}
function time(value?:string){if(!value)return'—';const parsed=new Date(value);return Number.isNaN(+parsed)?value:parsed.toLocaleString('vi-VN')}
function paymentTone(status?:PaymentStatus){if(status==='paid')return'status-confirmed';if(status==='approved'||status==='pending_director')return'status-contacting';if(status==='rejected'||status==='changes_requested')return'status-cancelled';return''}
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]||char))}
function paymentFor(order:Order,payments:Payment[]){return payments.find(payment=>payment.id===order.paymentRequestId)||payments.find(payment=>payment.serviceOrderId===order.id)}

export function AdminSupplierOrders(){
 const[staff,setStaff]=useState<AdminStaff|null>(null),[bookings,setBookings]=useState<Booking[]>([]),[ops,setOps]=useState<Record<string,Ops>>({}),[suppliers,setSuppliers]=useState<Supplier[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[payments,setPayments]=useState<Payment[]>([]),[orders,setOrders]=useState<Order[]>([]),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<Draft>(blank),[filter,setFilter]=useState<Filter>('active'),[message,setMessage]=useState('');
 const load=()=>{setStaff(readCurrentStaff());setBookings(read(KEYS.bookings,[]));setOps(read(KEYS.ops,{}));setSuppliers(read(KEYS.suppliers,[]));setReceipts(read(KEYS.receipts,[]));setPayments(read(KEYS.payments,[]));setOrders(read(KEYS.orders,[]))};
 useEffect(()=>{load();const events=['storage','tn-bookings-updated','happygo-booking-ops-updated','happygo-payment-updated','happygo-customer-receipts-updated','happygo-supplier-orders-updated','happygo-admin-auth','tn-staff-updated'];events.forEach(event=>window.addEventListener(event,load));return()=>events.forEach(event=>window.removeEventListener(event,load))},[]);

 const editOps=canEditOperations(staff),manager=Boolean(staff&&(isOwner(staff)||isAdminStaff(staff))),viewFinance=Boolean(staff&&(manager||isAccountingStaff(staff)||isOperationsStaff(staff)));
 const visibleBookings=useMemo(()=>bookings.filter(booking=>staff&&canViewBooking(staff,booking)&&booking.status!=='cancelled'),[bookings,staff]);
 const eligible=useMemo(()=>visibleBookings.filter(booking=>booking.status==='confirmed'&&ops[String(booking.id)]?.handoffAccepted),[visibleBookings,ops]);
 const visibleOrders=useMemo(()=>orders.filter(order=>visibleBookings.some(booking=>booking.id===order.bookingId)).map(order=>({order,payment:paymentFor(order,payments)})).filter(({order,payment})=>filter==='all'||(filter==='active'&&!['completed','cancelled'].includes(order.status))||(filter==='need_confirm'&&order.status==='sent')||(filter==='need_payment'&&order.status==='confirmed'&&payment?.status!=='paid')||(filter==='need_voucher'&&order.status==='confirmed'&&payment?.status==='paid'&&!order.voucherReady)).sort((a,b)=>+new Date(b.order.updatedAt)-+new Date(a.order.updatedAt)),[orders,payments,visibleBookings,filter]);
 const kpi=useMemo(()=>{const scoped=orders.filter(order=>visibleBookings.some(booking=>booking.id===order.bookingId)&&order.status!=='cancelled');return{sent:scoped.filter(order=>order.status==='sent').length,payment:scoped.filter(order=>order.status==='confirmed'&&paymentFor(order,payments)?.status!=='paid').length,voucher:scoped.filter(order=>order.status==='confirmed'&&paymentFor(order,payments)?.status==='paid'&&!order.voucherReady).length,completed:scoped.filter(order=>order.status==='completed').length}},[orders,payments,visibleBookings]);
 const selectedBooking=visibleBookings.find(booking=>String(booking.id)===draft.bookingId),customerPaid=selectedBooking?receipts.filter(receipt=>receipt.bookingId===selectedBooking.id).reduce((sum,receipt)=>sum+num(receipt.amount),0):0,customerTotal=selectedBooking?bookingRevenue(selectedBooking):0;
 const selected=orders.find(order=>order.id===selectedId)||null,selectedPayment=selected?paymentFor(selected,payments):undefined,formBookings=editingId?visibleBookings.filter(booking=>String(booking.id)===draft.bookingId):eligible;

 function reset(){setOpen(false);setEditingId(null);setDraft(blank)}
 function newOrder(){setEditingId(null);setDraft(blank);setOpen(true);setMessage('')}
 function edit(order:Order){if(!editOps||!['draft','sent'].includes(order.status))return;setEditingId(order.id);setDraft({bookingId:String(order.bookingId),serviceType:order.serviceType,serviceDate:order.serviceDate,supplierId:order.supplierId,supplierName:order.supplierName,supplierContact:order.supplierContact,bankName:order.bankName,accountNumber:order.accountNumber,accountName:order.accountName,amount:String(order.amount),dueDate:order.dueDate,note:order.note});setOpen(true);setSelectedId(null);setMessage('');window.scrollTo({top:0,behavior:'smooth'})}
 function chooseBooking(id:string){const booking=eligible.find(item=>String(item.id)===id);setDraft(current=>({...current,bookingId:id,serviceDate:booking?.start_date?.slice(0,10)||current.serviceDate}))}
 function chooseSupplier(id:string){const supplier=suppliers.find(item=>item.id===id);setDraft(current=>supplier?{...current,supplierId:id,supplierName:supplier.name,supplierContact:supplier.phone||'',bankName:supplier.bankName||'',accountNumber:supplier.accountNumber||'',accountName:supplier.accountName||''}:{...current,supplierId:id})}
 function makeAudit(action:string,detail?:string):Audit{return{id:`svc_aud_${Date.now()}_${Math.random().toString(36).slice(2,5)}`,at:new Date().toISOString(),byId:staff?.id||'',byName:staff?.name||'Hệ thống',action,detail}}

 function save(send:boolean){
  if(!staff||!editOps)return alert('Bạn không có quyền tạo hoặc sửa đơn dịch vụ NCC.');
  const booking=visibleBookings.find(item=>String(item.id)===draft.bookingId),amount=num(draft.amount);
  if(!booking||(!editingId&&!eligible.some(item=>item.id===booking.id)))return alert('Chọn Booking đã xác nhận và đã nhận bàn giao Điều hành.');
  if(!draft.supplierName.trim()||!draft.serviceType.trim()||!draft.serviceDate||amount<=0)return alert('Vui lòng nhập đủ nhà cung cấp, loại dịch vụ, ngày sử dụng và số tiền.');
  const now=new Date().toISOString();
  if(editingId){const current=orders.find(order=>order.id===editingId);if(!current||!['draft','sent'].includes(current.status))return alert('Đơn đã sang bước xác nhận/thanh toán nên không thể sửa nội dung gốc.');const next=orders.map(order=>order.id===editingId?{...order,serviceType:draft.serviceType,serviceDate:draft.serviceDate,supplierId:draft.supplierId,supplierName:draft.supplierName.trim(),supplierContact:draft.supplierContact.trim(),bankName:draft.bankName.trim(),accountNumber:draft.accountNumber.trim(),accountName:draft.accountName.trim(),amount,dueDate:draft.dueDate,note:draft.note.trim(),status:send?'sent':order.status,updatedById:staff.id,updatedByName:staff.name,updatedAt:now,audit:[...(order.audit||[]),makeAudit(send&&order.status==='draft'?'Cập nhật và gửi đơn cho NCC':'Cập nhật nội dung đơn',`${draft.serviceType} · ${draft.supplierName.trim()} · ${money(amount)}`)],...(send&&order.status==='draft'?{sentAt:now}:{})}:order);store(KEYS.orders,next,'happygo-supplier-orders-updated');setOrders(next);setMessage(`Đã cập nhật đơn ${current.bookingCode}.`);reset();return}
  const order:Order={id:`svc_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,bookingId:booking.id,bookingCode:booking.code,customerName:booking.customer_name,product:booking.product,serviceType:draft.serviceType,serviceDate:draft.serviceDate,supplierId:draft.supplierId,supplierName:draft.supplierName.trim(),supplierContact:draft.supplierContact.trim(),bankName:draft.bankName.trim(),accountNumber:draft.accountNumber.trim(),accountName:draft.accountName.trim(),amount,dueDate:draft.dueDate,note:draft.note.trim(),status:send?'sent':'draft',supplierRef:'',voucherRef:'',voucherReady:false,createdById:staff.id,createdByName:staff.name,createdAt:now,updatedById:staff.id,updatedByName:staff.name,updatedAt:now,audit:[makeAudit(send?'Tạo và gửi đơn cho NCC':'Tạo đơn nháp',`${draft.serviceType} · ${draft.supplierName.trim()} · ${money(amount)}`)],...(send?{sentAt:now}:{})};const next=[order,...orders];store(KEYS.orders,next,'happygo-supplier-orders-updated');setOrders(next);setMessage(`Đã tạo đơn ${booking.code} cho ${order.supplierName}.`);reset()
 }
 function patch(order:Order,changes:Partial<Order>,action:string,detail?:string){if(!staff||!editOps)return alert('Bạn không có quyền cập nhật đơn dịch vụ NCC.');const next=orders.map(item=>item.id===order.id?{...item,...changes,updatedAt:new Date().toISOString(),updatedById:staff.id,updatedByName:staff.name,audit:[...(item.audit||[]),makeAudit(action,detail)]}:item);store(KEYS.orders,next,'happygo-supplier-orders-updated');setOrders(next)}
 function markSent(order:Order){if(confirm(`Xác nhận đã gửi yêu cầu cho ${order.supplierName}?`))patch(order,{status:'sent',sentAt:new Date().toISOString()},'Đã gửi đơn cho NCC',order.supplierName)}
 function confirmSupplier(order:Order){const ref=prompt('Mã xác nhận / booking ref của NCC',order.supplierRef||'')??order.supplierRef;if(!ref.trim()&&!confirm('Chưa có mã xác nhận. Vẫn tiếp tục?'))return;patch(order,{status:'confirmed',supplierRef:ref.trim(),confirmedAt:new Date().toISOString(),confirmedBy:staff?.name||''},'NCC đã xác nhận',ref.trim()?`Mã NCC: ${ref.trim()}`:'Chưa có mã NCC')}
 function markVoucher(order:Order){const ref=prompt('Voucher / mã xác nhận gửi khách',order.voucherRef||order.supplierRef||'')??order.voucherRef;if(!ref.trim()&&!confirm('Chưa nhập mã voucher. Vẫn tiếp tục?'))return;patch(order,{voucherReady:true,voucherRef:ref.trim(),voucherReadyAt:new Date().toISOString(),voucherReadyBy:staff?.name||''},'Đã nhận voucher',ref.trim()?`Mã voucher: ${ref.trim()}`:'Chưa có mã voucher')}
 function complete(order:Order,payment?:Payment){if(order.status!=='confirmed'||payment?.status!=='paid'||!order.voucherReady)return alert('Cần đủ xác nhận NCC, thanh toán Đã chi và voucher trước khi hoàn tất.');if(confirm(`Hoàn tất đơn ${order.bookingCode} · ${order.supplierName}?`))patch(order,{status:'completed',completedAt:new Date().toISOString(),completedBy:staff?.name||''},'Hoàn tất đơn NCC','Đã thanh toán và có voucher')}
 function cancel(order:Order){if(confirm(`Hủy đơn ${order.serviceType} · ${order.supplierName}?`))patch(order,{status:'cancelled',cancelledAt:new Date().toISOString(),cancelledBy:staff?.name||''},'Hủy đơn NCC')}
 function requestPayment(order:Order){
  if(!staff||!editOps||order.status!=='confirmed')return alert('Cần quyền Điều hành và xác nhận NCC trước khi gửi thanh toán.');if(order.paymentRequestId||payments.some(payment=>payment.serviceOrderId===order.id))return alert('Đơn này đã có đề nghị thanh toán.');const booking=bookings.find(item=>item.id===order.bookingId);if(!booking)return alert('Không tìm thấy Booking.');const paid=receipts.filter(receipt=>receipt.bookingId===booking.id).reduce((sum,receipt)=>sum+num(receipt.amount),0),sale=bookingRevenue(booking);if(paid<=0)return alert('Booking chưa có Phiếu thu khách.');if(!order.bankName.trim()||!order.accountNumber.trim()||!order.accountName.trim())return alert('Cần đủ ngân hàng, số tài khoản và chủ tài khoản NCC.');if(!confirm(`Gửi đề nghị thanh toán ${money(order.amount)} cho ${order.supplierName}?`))return;
  const now=new Date().toISOString(),id=`pay_${Date.now()}_${Math.random().toString(36).slice(2,5)}`,request={id,bookingId:booking.id,bookingCode:booking.code,customerName:booking.customer_name,product:booking.product,customerPaidType:sale>0&&paid>=sale?'full':'deposit',customerPaidAmount:paid,supplierId:order.supplierId||'',supplierName:order.supplierName,bankName:order.bankName,accountNumber:order.accountNumber,accountName:order.accountName,amount:order.amount,purpose:`Thanh toán đơn ${order.serviceType} · ${order.supplierName} · ${booking.code}`,dueDate:order.dueDate,note:`Nguồn: Đơn NCC ${order.id}${order.note?` · ${order.note}`:''}`,status:'pending_director' as PaymentStatus,createdById:staff.id,createdByName:staff.name,createdAt:now,submittedAt:now,source:'supplier_order',serviceOrderId:order.id,audit:[{id:`aud_${Date.now()}`,at:now,byId:staff.id,byName:staff.name,action:'Tạo từ đơn dịch vụ NCC và gửi đề xuất chi',toStatus:'pending_director',detail:`${order.serviceType} · ${order.supplierName} · ${money(order.amount)}`,snapshot:{amount:order.amount,supplierName:order.supplierName,bankName:order.bankName,accountNumber:order.accountNumber,accountName:order.accountName,customerPaidAmount:paid}}]};const next=[request,...payments];store(KEYS.payments,next,'happygo-payment-updated');setPayments(next);patch(order,{paymentRequestId:id},'Gửi đề nghị thanh toán',`${money(order.amount)} · Chờ BGĐ duyệt`)
 }

 function summary(order:Order,payment?:Payment){return[`PHIẾU ĐẶT DỊCH VỤ NCC · ${order.bookingCode}`,`Khách hàng: ${order.customerName}`,`Sản phẩm: ${order.product}`,`Dịch vụ: ${order.serviceType}`,`Ngày sử dụng: ${date(order.serviceDate)}`,`Nhà cung cấp: ${order.supplierName}`,`Liên hệ NCC: ${order.supplierContact||'—'}`,`Trạng thái: ${statusLabel[order.status]}`,order.supplierRef?`Mã NCC: ${order.supplierRef}`:'',viewFinance?`Giá trị: ${money(order.amount)}`:'',payment?`Thanh toán: ${paymentLabel[payment.status]}`:'',order.voucherReady?`Voucher: ${order.voucherRef||'Đã sẵn sàng'}`:'',order.note?`Yêu cầu: ${order.note}`:''].filter(Boolean).join('\n')}
 async function copy(order:Order,payment?:Payment){const content=summary(order,payment);try{await navigator.clipboard.writeText(content);setMessage(`Đã sao chép nội dung đơn ${order.bookingCode}.`)}catch{prompt('Sao chép nội dung bên dưới',content)}}
 function print(order:Order,payment?:Payment){const popup=window.open('','_blank','width=900,height=760');if(!popup)return alert('Vui lòng cho phép cửa sổ pop-up để in phiếu.');popup.opener=null;const row=(label:string,value:unknown)=>`<div><small>${esc(label)}</small><b>${esc(value||'—')}</b></div>`;popup.document.write(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Phiếu NCC ${esc(order.bookingCode)}</title><style>@page{size:A4;margin:18mm}body{font:14px Arial;color:#17324d}header{display:flex;justify-content:space-between;border-bottom:3px solid #0d47a1;padding-bottom:18px;margin-bottom:24px}h1{font-size:22px;margin:0}.brand{color:#0d47a1;font-size:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 24px}.grid div{padding:12px 0;border-bottom:1px solid #e2e8f0;display:grid;gap:5px}.grid small{color:#64748b;font-size:10px}.note{margin-top:22px;padding:16px;background:#f8fafc;white-space:pre-wrap}.sign{display:grid;grid-template-columns:1fr 1fr;text-align:center;margin-top:54px}.sign b{display:block;margin-bottom:70px}</style></head><body><header><b class="brand">HAPPYGO TRAVEL</b><div><h1>PHIẾU ĐẶT DỊCH VỤ NCC</h1><b>${esc(order.bookingCode)}</b></div></header><div class="grid">${row('Khách hàng',order.customerName)}${row('Sản phẩm',order.product)}${row('Loại dịch vụ',order.serviceType)}${row('Ngày sử dụng',date(order.serviceDate))}${row('Nhà cung cấp',order.supplierName)}${row('Liên hệ NCC',order.supplierContact)}${row('Trạng thái',statusLabel[order.status])}${row('Mã xác nhận NCC',order.supplierRef)}${viewFinance?row('Giá trị đơn',money(order.amount)):''}${viewFinance?row('Hạn thanh toán',date(order.dueDate)):''}${payment?row('Thanh toán',paymentLabel[payment.status]):''}${order.voucherReady?row('Voucher',order.voucherRef||'Đã sẵn sàng'):''}</div>${order.note?`<div class="note"><b>Yêu cầu dịch vụ</b><br><br>${esc(order.note)}</div>`:''}<div class="sign"><div><b>Người lập phiếu</b>${esc(order.createdByName)}</div><div><b>Nhà cung cấp xác nhận</b></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);popup.document.close()}
 function history(order:Order):Audit[]{if(order.audit?.length)return[...order.audit].sort((a,b)=>+new Date(b.at)-+new Date(a.at));const rows:Audit[]=[{id:`create_${order.id}`,at:order.createdAt,byId:order.createdById,byName:order.createdByName,action:'Tạo đơn NCC'}];if(order.sentAt)rows.push({id:`sent_${order.id}`,at:order.sentAt,byId:'',byName:order.updatedByName,action:'Đã gửi đơn cho NCC'});if(order.confirmedAt)rows.push({id:`confirmed_${order.id}`,at:order.confirmedAt,byId:'',byName:order.confirmedBy||order.updatedByName,action:'NCC đã xác nhận',detail:order.supplierRef});if(order.voucherReadyAt)rows.push({id:`voucher_${order.id}`,at:order.voucherReadyAt,byId:'',byName:order.voucherReadyBy||order.updatedByName,action:'Đã nhận voucher',detail:order.voucherRef});if(order.completedAt)rows.push({id:`complete_${order.id}`,at:order.completedAt,byId:'',byName:order.completedBy||order.updatedByName,action:'Hoàn tất đơn NCC'});if(order.cancelledAt)rows.push({id:`cancel_${order.id}`,at:order.cancelledAt,byId:'',byName:order.cancelledBy||order.updatedByName,action:'Hủy đơn NCC'});return rows.sort((a,b)=>+new Date(b.at)-+new Date(a.at))}

 return <section className="admin-panel supplier-orders">
  <div className="admin-panel-head"><div><small>ĐƠN ĐẶT DỊCH VỤ / NHÀ CUNG CẤP</small><h2>Booking → NCC → Thanh toán → Voucher</h2><p>Điều hành tạo đơn sau khi nhận bàn giao; BGĐ/Kế toán duyệt và chi trên cùng dữ liệu.</p></div>{editOps&&<button className="admin-primary" disabled={!eligible.length&&!open} onClick={()=>open?reset():newOrder()}>{open?'Đóng biểu mẫu':'+ Tạo đơn NCC'}</button>}</div>
  {message&&<p className="admin-api-note supplier-message">{message}</p>}
  <div className="service-kpis"><article className={kpi.sent?'warning':''}><small>CHỜ NCC XÁC NHẬN</small><b>{kpi.sent}</b></article><article className={kpi.payment?'warning':''}><small>CHỜ DUYỆT / CHI</small><b>{kpi.payment}</b></article><article className={kpi.voucher?'warning':''}><small>ĐÃ CHI · CHỜ VOUCHER</small><b>{kpi.voucher}</b></article><article><small>ĐÃ HOÀN TẤT</small><b>{kpi.completed}</b></article></div>
  {!eligible.length&&editOps&&!open&&<p className="admin-api-note">Chưa có Booking vừa <b>Đã xác nhận</b> vừa <b>Đã nhận bàn giao Điều hành</b>.</p>}
  {open&&<div className="supplier-editor"><div className="supplier-editor-title"><div><small>{editingId?'CHỈNH SỬA ĐƠN':'ĐƠN DỊCH VỤ MỚI'}</small><b>{editingId?'Cập nhật trước khi NCC xác nhận':'Tạo phiếu từ Booking đã bàn giao'}</b></div>{editingId&&<span>Thông tin khóa sau khi NCC xác nhận.</span>}</div><div className="tour-editor-grid"><label>Booking<select value={draft.bookingId} disabled={Boolean(editingId)} onChange={event=>chooseBooking(event.target.value)}><option value="">— Chọn Booking —</option>{formBookings.map(booking=><option key={booking.id} value={booking.id}>{booking.code} · {booking.customer_name} · {booking.product}</option>)}</select></label><label>Loại dịch vụ<select value={draft.serviceType} onChange={event=>setDraft({...draft,serviceType:event.target.value})}>{serviceTypes.map(type=><option key={type}>{type}</option>)}</select></label><label>Ngày sử dụng<input type="date" value={draft.serviceDate} onChange={event=>setDraft({...draft,serviceDate:event.target.value})}/></label><label>Nhà cung cấp đã lưu<select value={draft.supplierId} onChange={event=>chooseSupplier(event.target.value)}><option value="">— Nhập mới / chọn NCC —</option>{suppliers.map(supplier=><option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><label>Tên nhà cung cấp<input value={draft.supplierName} onChange={event=>setDraft({...draft,supplierName:event.target.value})}/></label><label>Liên hệ NCC<input value={draft.supplierContact} onChange={event=>setDraft({...draft,supplierContact:event.target.value})}/></label><label>Ngân hàng<input value={draft.bankName} onChange={event=>setDraft({...draft,bankName:event.target.value})}/></label><label>Số tài khoản<input value={draft.accountNumber} onChange={event=>setDraft({...draft,accountNumber:event.target.value})}/></label><label>Chủ tài khoản<input value={draft.accountName} onChange={event=>setDraft({...draft,accountName:event.target.value})}/></label><label>Số tiền phải trả NCC<input inputMode="numeric" value={draft.amount} onChange={event=>setDraft({...draft,amount:event.target.value})} placeholder="VD 5.000.000"/></label><label>Hạn thanh toán<input type="date" value={draft.dueDate} onChange={event=>setDraft({...draft,dueDate:event.target.value})}/></label><label className="span-2">Ghi chú<textarea rows={3} value={draft.note} onChange={event=>setDraft({...draft,note:event.target.value})}/></label>{selectedBooking&&<div className="span-2 admin-api-note">Khách đã thu: <b>{money(customerPaid)}</b> / Giá bán: <b>{money(customerTotal)}</b> · Điều hành: <b>{ops[String(selectedBooking.id)]?.operatorName||'Chưa ghi nhận'}</b></div>}<div className="span-2 editor-actions"><button onClick={reset}>Hủy</button><button onClick={()=>save(false)}>{editingId?'Lưu thay đổi':'Lưu nháp'}</button><button className="admin-primary" onClick={()=>save(true)}>Lưu & đã gửi NCC</button></div></div></div>}
  <div className="service-filters"><button className={filter==='active'?'active':''} onClick={()=>setFilter('active')}>Đang xử lý</button><button className={filter==='need_confirm'?'active':''} onClick={()=>setFilter('need_confirm')}>Chờ NCC ({kpi.sent})</button><button className={filter==='need_payment'?'active':''} onClick={()=>setFilter('need_payment')}>Chờ thanh toán ({kpi.payment})</button><button className={filter==='need_voucher'?'active':''} onClick={()=>setFilter('need_voucher')}>Chờ voucher ({kpi.voucher})</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Tất cả</button></div>
  <div className="admin-customer-grid">{visibleOrders.map(({order,payment})=><article className="admin-customer-card supplier-order-card" key={order.id}><div><b>{order.bookingCode} · {order.customerName}</b><span>{order.serviceType} · {order.product}</span><small>{date(order.serviceDate)} · NCC: {order.supplierName}</small></div><div><b>{statusLabel[order.status]}</b><small>{order.supplierRef?`Mã NCC: ${order.supplierRef}`:'Chưa có mã NCC'}{order.voucherReady?` · Voucher: ${order.voucherRef||'Đã có'}`:''}</small></div><div>{viewFinance?<><b>{money(order.amount)}</b><small>{order.dueDate?`Hạn ${date(order.dueDate)}`:'Chưa đặt hạn thanh toán'}</small>{order.bankName&&<small>{order.bankName} · {order.accountNumber}</small>}</>:<><b>Chi phí NCC: {order.amount>0?'Đã nhập':'Chưa nhập'}</b><small>Thông tin tài chính được giới hạn theo quyền.</small></>}{payment&&<span className={paymentTone(payment.status)}>{paymentLabel[payment.status]}</span>}</div><div className="pm-actions"><button onClick={()=>setSelectedId(order.id)}>Chi tiết</button><button onClick={()=>print(order,payment)}>In phiếu</button>{editOps&&['draft','sent'].includes(order.status)&&<button onClick={()=>edit(order)}>Sửa</button>}{editOps&&order.status==='draft'&&<button onClick={()=>markSent(order)}>Đã gửi NCC</button>}{editOps&&order.status==='sent'&&<button className="admin-primary" onClick={()=>confirmSupplier(order)}>NCC đã xác nhận</button>}{editOps&&order.status==='confirmed'&&!payment&&<button className="admin-primary" onClick={()=>requestPayment(order)}>Gửi thanh toán</button>}{editOps&&order.status==='confirmed'&&payment?.status==='paid'&&!order.voucherReady&&<button onClick={()=>markVoucher(order)}>Đã có voucher</button>}{editOps&&order.status==='confirmed'&&payment?.status==='paid'&&order.voucherReady&&<button className="admin-primary" onClick={()=>complete(order,payment)}>Hoàn tất</button>}{editOps&&!['completed','cancelled'].includes(order.status)&&<button className="danger-action" onClick={()=>cancel(order)}>Hủy</button>}</div><div className="supplier-order-meta"><small>Tạo: {order.createdByName} · {time(order.createdAt)} · Cập nhật: {order.updatedByName} · {time(order.updatedAt)}</small>{order.note&&<p>{order.note}</p>}</div></article>)}{!visibleOrders.length&&<div className="admin-empty-state"><b>Không có đơn NCC phù hợp</b><span>Tạo đơn từ Booking đã xác nhận và bàn giao Điều hành.</span></div>}</div>
  {selected&&<div className="supplier-detail-overlay" onClick={()=>setSelectedId(null)}><section className="supplier-detail" role="dialog" aria-modal="true" aria-labelledby="supplier-detail-title" onClick={event=>event.stopPropagation()}><header><div><small>ĐƠN DỊCH VỤ · {selected.bookingCode}</small><h2 id="supplier-detail-title">{selected.serviceType}</h2><p>{selected.customerName} · {selected.product}</p></div><button aria-label="Đóng" onClick={()=>setSelectedId(null)}>×</button></header><div className="supplier-progress"><span className="done"><i>1</i><b>Booking</b><small>Đã bàn giao</small></span><span className={selected.status!=='draft'?'done':'active'}><i>2</i><b>Nhà cung cấp</b><small>{selected.status==='draft'?'Chưa gửi':selected.status==='sent'?'Chờ xác nhận':'Đã xác nhận'}</small></span><span className={selectedPayment?.status==='paid'?'done':selectedPayment?'active':''}><i>3</i><b>Thanh toán</b><small>{selectedPayment?paymentLabel[selectedPayment.status]:'Chưa đề nghị'}</small></span><span className={selected.voucherReady?'done':selectedPayment?.status==='paid'?'active':''}><i>4</i><b>Voucher</b><small>{selected.voucherReady?'Đã sẵn sàng':'Chưa có'}</small></span></div><div className="supplier-detail-grid"><article><small>NHÀ CUNG CẤP</small><b>{selected.supplierName}</b><span>{selected.supplierContact||'Chưa có liên hệ'}</span></article><article><small>NGÀY SỬ DỤNG</small><b>{date(selected.serviceDate)}</b><span>{statusLabel[selected.status]}</span></article><article><small>MÃ NCC / VOUCHER</small><b>{selected.supplierRef||'Chưa có'}</b><span>{selected.voucherRef||'Chưa có voucher'}</span></article>{viewFinance&&<article><small>GIÁ TRỊ / HẠN CHI</small><b>{money(selected.amount)}</b><span>{date(selected.dueDate)}</span></article>}</div>{viewFinance&&selected.bankName&&<div className="supplier-bank"><small>THÔNG TIN THANH TOÁN NCC</small><b>{selected.bankName} · {selected.accountNumber}</b><span>{selected.accountName}</span></div>}{selected.note&&<div className="supplier-note"><small>YÊU CẦU DỊCH VỤ</small><p>{selected.note}</p></div>}<div className="supplier-detail-actions"><button onClick={()=>copy(selected,selectedPayment)}>Sao chép nội dung</button><button onClick={()=>print(selected,selectedPayment)}>In phiếu NCC</button>{editOps&&['draft','sent'].includes(selected.status)&&<button className="admin-primary" onClick={()=>edit(selected)}>Sửa đơn</button>}</div><section className="supplier-timeline"><div><small>NHẬT KÝ XỬ LÝ</small><b>{history(selected).length} hoạt động</b></div>{history(selected).map(item=><article key={item.id}><i></i><div><b>{item.action}</b>{item.detail&&<span>{item.detail}</span>}<small>{item.byName} · {time(item.at)}</small></div></article>)}</section></section></div>}
 </section>
}
