'use client';

import {useMemo,useState} from 'react';

const API_BASE=(process.env.NEXT_PUBLIC_API_BASE_URL||'').replace(/\/$/,'');
const presets=[
 {name:'Ưu đãi Tour mới',subject:'Ưu đãi hành trình mới từ HappyGo Travel',title:'Hành trình mới dành cho bạn',message:'Xin chào {{name}},\nHappyGo Travel vừa cập nhật các hành trình và ưu đãi mới. Đội ngũ tư vấn sẵn sàng hỗ trợ chọn lịch khởi hành, khách sạn và phương án phù hợp nhất với nhu cầu của bạn.',ctaLabel:'Xem ưu đãi mới'},
 {name:'Chăm sóc khách cũ',subject:'HappyGo Travel gửi lời chào đến bạn',title:'Cảm ơn bạn đã đồng hành cùng chúng tôi',message:'Xin chào {{name}},\nCảm ơn bạn đã từng quan tâm hoặc sử dụng dịch vụ của HappyGo Travel. Khi có kế hoạch du lịch mới, bạn có thể trả lời email này để đội ngũ tư vấn hỗ trợ nhanh nhất.',ctaLabel:'Xem website'},
 {name:'Lịch khởi hành mới',subject:'Lịch khởi hành mới từ HappyGo Travel',title:'Lịch tour mới đã sẵn sàng',message:'Xin chào {{name}},\nMột số lịch khởi hành mới của HappyGo Travel đã được mở bán. Nếu bạn đang dự định đi du lịch trong thời gian tới, hãy xem lịch và liên hệ sớm để được kiểm tra chỗ và giá tốt.',ctaLabel:'Xem lịch Tour'}
];

export function AdminEmailCampaigns(){
 const[key,setKey]=useState(()=>typeof window==='undefined'?'':localStorage.getItem('tn_admin_api_key')||'');
 const[status,setStatus]=useState('customer');const[limit,setLimit]=useState(100);const[subject,setSubject]=useState(presets[0].subject);const[title,setTitle]=useState(presets[0].title);const[message,setMessage]=useState(presets[0].message);const[ctaLabel,setCtaLabel]=useState(presets[0].ctaLabel);const[ctaUrl,setCtaUrl]=useState('https://happygo-travel.vercel.app');const[sending,setSending]=useState(false);const[result,setResult]=useState('');
 const preview=useMemo(()=>message.replace(/{{\s*name\s*}}/gi,'Nguyễn Văn A'),[message]);
 const apply=(p:typeof presets[number])=>{setSubject(p.subject);setTitle(p.title);setMessage(p.message);setCtaLabel(p.ctaLabel);setResult('')};
 async function send(){if(!key.trim()){setResult('Vui lòng nhập khóa quản trị API.');return}if(!subject.trim()||!message.trim()){setResult('Cần nhập tiêu đề email và nội dung.');return}if(!confirm(`Gửi email tới tối đa ${limit} khách trong nhóm đã chọn? Chỉ khách có marketing_consent=true mới được gửi.`))return;setSending(true);setResult('');try{localStorage.setItem('tn_admin_api_key',key);const response=await fetch(`${API_BASE}/api/admin/email-campaigns/send`,{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({customerStatus:status,limit,subject,title,message,ctaLabel,ctaUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Không gửi được chiến dịch email.');setResult(`✓ Hoàn tất: gửi thành công ${data.sent}/${data.total} email${data.failed?` · lỗi ${data.failed}`:''}.`)}catch(error){setResult(error instanceof Error?error.message:'Có lỗi khi gửi email.')}finally{setSending(false)}}
 return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Email & Marketing</h2><p>Gửi email qua Resend từ Vercel. Danh sách người nhận lấy trực tiếp từ PostgreSQL và chỉ gồm khách đã đồng ý nhận marketing.</p></div></div><div className="tour-editor-grid"><label>Khóa quản trị API<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="ADMIN_API_KEY trên Vercel"/></label><label>Nhóm khách<select value={status} onChange={e=>setStatus(e.target.value)}><option value="customer">Khách đã xác nhận / đã mua</option><option value="contacting">Khách đang tư vấn</option><option value="lead">Khách tiềm năng</option><option value="">Tất cả khách đã đồng ý nhận email</option></select></label><label>Số lượng tối đa mỗi lần<input type="number" min="1" max="200" value={limit} onChange={e=>setLimit(Math.min(200,Math.max(1,Number(e.target.value)||1)))}/></label><div><span style={{fontSize:11,fontWeight:800,color:'#526b7f'}}>Mẫu nhanh</span><div className="booking-note-templates" style={{marginTop:5}}>{presets.map(p=><button key={p.name} type="button" onClick={()=>apply(p)}>{p.name}</button>)}</div></div><label className="span-2">Tiêu đề email<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label className="span-2">Tiêu đề trong email<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="span-2">Nội dung<textarea rows={9} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Có thể dùng {{name}} để chèn tên khách"/></label><label>Nút kêu gọi hành động<input value={ctaLabel} onChange={e=>setCtaLabel(e.target.value)}/></label><label>Link của nút<input value={ctaUrl} onChange={e=>setCtaUrl(e.target.value)}/></label></div><div style={{marginTop:18,border:'1px solid #dfe8ef',borderRadius:12,overflow:'hidden'}}><div style={{background:'#0d47a1',color:'#fff',padding:'17px 20px'}}><b>HAPPYGO TRAVEL</b><small style={{display:'block',marginTop:4,color:'#dbeafe'}}>HÀNH TRÌNH HẠNH PHÚC · KẾT NỐI YÊU THƯƠNG</small></div><div style={{padding:20}}><h3 style={{marginTop:0}}>{title||'Tiêu đề email'}</h3><p style={{whiteSpace:'pre-line',lineHeight:1.65}}>{preview}</p>{ctaLabel&&<span className="admin-primary" style={{display:'inline-block'}}>{ctaLabel}</span>}</div></div><div className="editor-actions"><button type="button" className="admin-primary" disabled={sending} onClick={send}>{sending?'Đang gửi email...':'Gửi email cho nhóm khách'}</button></div>{result&&<p className={result.startsWith('✓')?'cms-message':'admin-api-note'}>{result}</p>}<p className="admin-api-note">Email chỉ gửi thật khi Vercel đã có DATABASE_URL, ADMIN_API_KEY, RESEND_API_KEY và domain gửi mail đã được xác minh trên Resend.</p></section>
}
