'use client';

import {useEffect,useMemo,useState} from 'react';

type Status='pending_director'|'changes_requested'|'rejected'|'approved'|'paid';
type Booking={id:string;code:string;customerName:string;product:string;sellingTotal:number;paidTotal:number};
type Supplier={id:string;name:string;bankName:string;accountNumber:string;accountName:string;phone:string};
type Event={id:string;action:string;fromStatus?:string;toStatus?:string;detail?:string;actorName?:string;createdAt:string};
type RequestItem={id:string;bookingId:string;bookingCode:string;customerName:string;product:string;supplierId:string;supplierName:string;bankName:string;accountNumber:string;accountName:string;customerPaidAmount:number;amount:number;purpose:string;dueDate:string;note:string;status:Status;createdById:string;createdByName:string;submittedAt:string;directorBy:string;directorAt:string;directorNote:string;paidBy:string;paidAt:string;paidAmount:number|null;paymentMethod:string;transactionRef:string;accountingNote:string;events:Event[]};
type ApiData={requests:RequestItem[];bookings:Booking[];suppliers:Supplier[];capabilities:{create:boolean;approve:boolean;pay:boolean;all:boolean}};
const statusLabel:Record<Status,string>={pending_director:'Chờ BGĐ duyệt',changes_requested:'Cần bổ sung',rejected:'Từ chối',approved:'Kế toán chờ chi',paid:'Đã chi'};
const money=(value:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(value))+'đ';

export function AdminPaymentApprovals(){
 const[data,setData]=useState<ApiData>({requests:[],bookings:[],suppliers:[],capabilities:{create:false,approve:false,pay:false,all:false}}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[open,setOpen]=useState(false);
 const[bookingId,setBookingId]=useState(''),[supplierId,setSupplierId]=useState(''),[supplierName,setSupplierName]=useState(''),[bankName,setBankName]=useState(''),[accountNumber,setAccountNumber]=useState(''),[accountName,setAccountName]=useState(''),[amount,setAmount]=useState(''),[purpose,setPurpose]=useState(''),[dueDate,setDueDate]=useState(''),[note,setNote]=useState('');
 async function load(){setLoading(true);try{const res=await fetch('/api/admin/payment-requests',{cache:'no-store'}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không đọc được đề xuất chi.');setData(json)}catch(error){setMessage(error instanceof Error?error.message:'Không đọc được đề xuất chi.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const eligibleBookings=data.bookings.filter(item=>item.paidTotal>0);const selected=data.bookings.find(item=>item.id===bookingId);
 const counts=useMemo(()=>({director:data.requests.filter(item=>item.status==='pending_director').length,accounting:data.requests.filter(item=>item.status==='approved').length,paid:data.requests.filter(item=>item.status==='paid').length}),[data.requests]);
 function chooseSupplier(id:string){setSupplierId(id);const item=data.suppliers.find(s=>s.id===id);if(item){setSupplierName(item.name);setBankName(item.bankName);setAccountNumber(item.accountNumber);setAccountName(item.accountName)}else{setSupplierName('');setBankName('');setAccountNumber('');setAccountName('')}}
 async function post(body:Record<string,unknown>){const res=await fetch('/api/admin/payment-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không thể cập nhật đề xuất chi.');return json}
 async function create(){const value=Number(amount.replace(/\D/g,''));if(!bookingId||value<=0||!supplierName.trim()||!accountNumber.trim()||!accountName.trim()||!purpose.trim())return setMessage('Nhập đủ booking, nhà cung cấp, tài khoản, số tiền và nội dung chi.');try{setMessage('Đang gửi đề xuất...');await post({action:'create',bookingId,supplierId,supplierName,bankName,accountNumber,accountName,amount:value,purpose,dueDate,note});setOpen(false);setBookingId('');chooseSupplier('');setAmount('');setPurpose('');setDueDate('');setNote('');setMessage('Đã gửi đề xuất cho BGĐ/Quản trị duyệt.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể tạo đề xuất.')}}
 async function review(item:RequestItem,status:'approved'|'rejected'|'changes_requested'){const label=status==='approved'?'Ghi chú duyệt (có thể bỏ trống)':status==='rejected'?'Lý do từ chối':'Nội dung cần bổ sung';const noteText=prompt(label,'');if(noteText===null)return;if(status!=='approved'&&!noteText.trim())return alert('Cần ghi rõ lý do.');try{await post({action:'review',id:item.id,status,note:noteText});setMessage('Đã cập nhật kết quả duyệt.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể duyệt đề xuất.')}}
 async function revise(item:RequestItem){const amountText=prompt('Số tiền đề nghị chi',String(item.amount));if(amountText===null)return;const nextAmount=Number(amountText.replace(/\D/g,''));const nextPurpose=prompt('Nội dung thanh toán',item.purpose);if(nextPurpose===null)return;const nextSupplier=prompt('Nhà cung cấp',item.supplierName);if(nextSupplier===null)return;const nextBank=prompt('Ngân hàng',item.bankName)||'';const nextAccount=prompt('Số tài khoản',item.accountNumber);if(nextAccount===null)return;const nextAccountName=prompt('Chủ tài khoản',item.accountName);if(nextAccountName===null)return;const nextDue=prompt('Hạn thanh toán YYYY-MM-DD',item.dueDate)||'';const nextNote=prompt('Ghi chú',item.note)||'';try{await post({action:'revise',id:item.id,amount:nextAmount,purpose:nextPurpose,supplierName:nextSupplier,bankName:nextBank,accountNumber:nextAccount,accountName:nextAccountName,dueDate:nextDue,note:nextNote});setMessage('Đã sửa và gửi lại đề xuất.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể gửi lại đề xuất.')}}
 async function pay(item:RequestItem){const amountText=prompt('Số tiền thực chi',String(item.amount));if(amountText===null)return;const paidAmount=Number(amountText.replace(/\D/g,''));const paymentMethod=prompt('Phương thức chi','Chuyển khoản')||'Chuyển khoản',transactionRef=prompt('Mã giao dịch / số chứng từ','')||'',accountingNote=prompt('Ghi chú kế toán','')||'';if(!paidAmount)return alert('Số tiền không hợp lệ.');try{await post({action:'pay',id:item.id,paidAmount,paymentMethod,transactionRef,accountingNote});setMessage('Đã xác nhận chi và tự động ghi vào sổ kế toán.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể xác nhận chi.')}}
 return <section className="admin-panel payment-approval">
  <div className="admin-panel-head payment-head"><div><small>KIỂM SOÁT THANH TOÁN PRODUCTION</small><h2>Đề xuất & duyệt chi</h2><p>Sale/nhân viên lập đề xuất → BGĐ/Quản trị duyệt → Kế toán xác nhận chi. Dữ liệu và lịch sử thao tác lưu trên Neon.</p></div>{data.capabilities.create&&<button className="admin-primary" onClick={()=>setOpen(value=>!value)}>+ Tạo đề xuất chi</button>}</div>
  <div className="payment-kpis"><article><small>CHỜ BGĐ DUYỆT</small><b>{counts.director}</b></article><article><small>KẾ TOÁN CHỜ CHI</small><b>{counts.accounting}</b></article><article><small>ĐÃ CHI</small><b>{counts.paid}</b></article></div>
  {message&&<p className="admin-api-note">{message}</p>}
  {open&&data.capabilities.create&&<div className="payment-form"><div className="receipt-grid">
   <label>Booking đã có phiếu thu<select value={bookingId} onChange={event=>setBookingId(event.target.value)}><option value="">Chọn booking</option>{eligibleBookings.map(item=><option key={item.id} value={item.id}>{item.code} · {item.customerName} · đã thu {money(item.paidTotal)}</option>)}</select></label>
   <label>Nhà cung cấp<select value={supplierId} onChange={event=>chooseSupplier(event.target.value)}><option value="">Nhà cung cấp mới</option>{data.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
   <label>Tên nhà cung cấp<input value={supplierName} onChange={event=>setSupplierName(event.target.value)}/></label><label>Ngân hàng<input value={bankName} onChange={event=>setBankName(event.target.value)}/></label><label>Số tài khoản<input value={accountNumber} onChange={event=>setAccountNumber(event.target.value)}/></label><label>Chủ tài khoản<input value={accountName} onChange={event=>setAccountName(event.target.value)}/></label>
   <label>Số tiền đề nghị<input inputMode="numeric" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>Nội dung chi<input value={purpose} onChange={event=>setPurpose(event.target.value)} placeholder="Thanh toán phòng/tour/vé..."/></label><label>Hạn thanh toán<input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label><label>Ghi chú<input value={note} onChange={event=>setNote(event.target.value)}/></label>
  </div>{selected&&<p className="admin-api-note">Booking {selected.code}: giá bán {money(selected.sellingTotal)} · khách đã thanh toán {money(selected.paidTotal)}.</p>}<div className="receipt-actions"><button className="admin-primary" onClick={create}>Gửi đề xuất</button><button className="admin-secondary" onClick={()=>setOpen(false)}>Hủy</button></div></div>}
  {loading?<div className="admin-empty-state">Đang tải đề xuất production...</div>:<div className="receipt-list">{data.requests.map(item=><article key={item.id}><div><b>{item.bookingCode} · {item.supplierName}</b><span>{item.customerName}{item.product?` · ${item.product}`:''}</span></div><strong>{money(item.amount)}</strong><div><b>{statusLabel[item.status]||item.status}</b><span>{item.purpose}{item.dueDate?` · Hạn ${new Date(`${item.dueDate}T00:00:00`).toLocaleDateString('vi-VN')}`:''}</span></div><div><b>Người lập: {item.createdByName}</b><span>Khách đã thu {money(item.customerPaidAmount)} · STK {item.accountNumber} · {item.accountName}</span></div>
   <div className="receipt-actions">{data.capabilities.approve&&item.status==='pending_director'&&<><button className="admin-primary" onClick={()=>review(item,'approved')}>Duyệt</button><button className="admin-secondary" onClick={()=>review(item,'changes_requested')}>Yêu cầu bổ sung</button><button className="admin-secondary" onClick={()=>review(item,'rejected')}>Từ chối</button></>}{item.status==='changes_requested'&&<button className="admin-primary" onClick={()=>revise(item)}>Sửa & gửi lại</button>}{data.capabilities.pay&&item.status==='approved'&&<button className="admin-primary" onClick={()=>pay(item)}>Xác nhận đã chi</button>}</div>
   {item.status==='paid'&&<small>Đã chi {money(item.paidAmount||0)} · {item.paymentMethod}{item.transactionRef?` · ${item.transactionRef}`:''} · {item.paidBy}</small>}{item.directorNote&&<small>Ghi chú duyệt: {item.directorNote}</small>}
   {!!item.events?.length&&<details><summary>Lịch sử ({item.events.length})</summary>{item.events.map(event=><p key={event.id}><b>{event.actorName||'Hệ thống'}</b> · {new Date(event.createdAt).toLocaleString('vi-VN')} · {event.action}{event.detail?` · ${event.detail}`:''}</p>)}</details>}
  </article>)}{!data.requests.length&&<div className="admin-empty-state">Chưa có đề xuất chi.</div>}</div>}
 </section>
}
