'use client';
import {useEffect,useMemo,useState} from 'react';

type BookingItem={productName?:string};
type Booking={id:string;code:string;customerName:string;phone:string;email?:string;status:string;createdAt:string;startDate?:string;endDate?:string;sellingTotal:number;items?:BookingItem[]};
type Followup={id:string;customerKey:string;status:'open'|'done'};

function customerKey(phone?:unknown,email?:unknown){const digits=String(phone||'').replace(/\D/g,'');return digits?`phone:${digits}`:`email:${String(email||'').trim().toLowerCase()}`}
function money(value:number){return `${Math.round(Number(value)||0).toLocaleString('vi-VN')} đ`}
function monthsSince(value?:string){if(!value)return 999;const time=+new Date(value);return Number.isFinite(time)?Math.max(0,(Date.now()-time)/2629800000):999}
function productName(booking?:Booking){return (booking?.items||[]).map(item=>String(item.productName||'').trim()).filter(Boolean).join(', ')||'Dịch vụ HappyGo'}

export function AdminCustomerRetention({openCustomer}:{openCustomer?:(key:string)=>void}){
 const[bookings,setBookings]=useState<Booking[]>([]),[tasks,setTasks]=useState<Followup[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{
  let alive=true;
  const load=async()=>{try{const[bRes,cRes]=await Promise.all([fetch('/api/admin/bookings',{cache:'no-store'}),fetch('/api/admin/crm-workflow',{cache:'no-store'})]);if(!bRes.ok)throw new Error('Không đọc được booking production.');const bData=await bRes.json();const cData=cRes.ok?await cRes.json():{followups:[]};if(!alive)return;setBookings(Array.isArray(bData.bookings)?bData.bookings:[]);setTasks(Array.isArray(cData.followups)?cData.followups:[]);setError('')}catch(e){if(alive)setError(e instanceof Error?e.message:'Không tải được dữ liệu khách cũ.')}finally{if(alive)setLoading(false)}};
  load();const refresh=()=>load();window.addEventListener('focus',refresh);['tn-bookings-updated','happygo-crm-followups-updated','happygo-admin-auth'].forEach(name=>window.addEventListener(name,refresh));return()=>{alive=false;window.removeEventListener('focus',refresh);['tn-bookings-updated','happygo-crm-followups-updated','happygo-admin-auth'].forEach(name=>window.removeEventListener(name,refresh))}
 },[]);
 const rows=useMemo(()=>{const map=new Map<string,Booking[]>();bookings.filter(b=>b.status!=='cancelled').forEach(b=>{const key=customerKey(b.phone,b.email);if(!key||key==='email:')return;map.set(key,[...(map.get(key)||[]),b])});return[...map.entries()].map(([key,list])=>{const sorted=[...list].sort((a,b)=>+new Date(b.endDate||b.startDate||b.createdAt)-+new Date(a.endDate||a.startDate||a.createdAt)),completed=sorted.filter(b=>b.status==='completed'),last=completed[0]||sorted[0],spent=completed.reduce((sum,b)=>sum+Number(b.sellingTotal||0),0),months=monthsSince(last?.endDate||last?.startDate||last?.createdAt),openTask=tasks.some(t=>t.customerKey===key&&t.status==='open');return{key,name:last?.customerName||'Khách hàng',phone:last?.phone||'',completed:completed.length,spent,last,months,openTask}}).filter(x=>x.completed>0).sort((a,b)=>(b.completed-a.completed)||(b.spent-a.spent))},[bookings,tasks]);
 const returning=rows.filter(x=>x.completed>=2),dormant=rows.filter(x=>x.months>=6&&!x.openTask),vip=rows.filter(x=>x.completed>=3||x.spent>=50000000),revenue=rows.reduce((sum,x)=>sum+x.spent,0);
 return <section className="admin-panel"><div className="admin-panel-head"><div><small>CHĂM SÓC SAU CHUYẾN</small><h2>Khách cũ & cơ hội bán lại</h2><p>Dữ liệu lấy trực tiếp từ Booking và CRM production, đồng nhất trên mọi thiết bị.</p></div></div>{error&&<div className="admin-empty-state"><b>Chưa tải được dữ liệu</b><span>{error}</span></div>}<div className="service-kpis"><article><small>KHÁCH ĐÃ HOÀN TẤT</small><b>{rows.length}</b></article><article><small>KHÁCH QUAY LẠI</small><b>{returning.length}</b></article><article><small>KHÁCH VIP</small><b>{vip.length}</b></article><article><small>≥ 6 THÁNG CHƯA QUAY LẠI</small><b>{dormant.length}</b></article></div><div className="crm-auto-box"><div><small>GIÁ TRỊ KHÁCH CŨ</small><b>{money(revenue)}</b><span>Doanh thu booking đã hoàn tất trong đúng phạm vi tài khoản được server cho phép xem.</span></div></div><div className="admin-customer-grid">{rows.slice(0,20).map(x=><article className="admin-customer-card" key={x.key}><div><b>{x.name}</b><a href={`tel:${x.phone.replace(/\D/g,'')}`}>{x.phone||'Không SĐT'}</a><small>{productName(x.last)}</small></div><div><b>{x.completed} chuyến hoàn tất</b><small>Tổng giá trị {money(x.spent)}</small><small>{x.months<1?'Vừa đi gần đây':`Khoảng ${Math.floor(x.months)} tháng từ chuyến gần nhất`}</small></div><div>{(x.completed>=3||x.spent>=50000000)&&<span className="status-confirmed">VIP</span>}{x.completed>=2&&<small>↻ Khách quay lại</small>}{x.months>=6&&<small>⚠ Nên tái chăm sóc</small>}{x.openTask&&<small>✓ Đã có lịch chăm sóc</small>}</div>{openCustomer&&<button onClick={()=>openCustomer(x.key)}>Mở CRM</button>}</article>)}</div>{!loading&&!error&&!rows.length&&<div className="admin-empty-state">Chưa có booking hoàn tất để phân tích khách cũ.</div>}</section>
}
