'use client';

import {useEffect,useMemo,useState} from 'react';

type ProductType='Sản phẩm'|'Tour du lịch'|'Villa & Resort'|'Khách sạn'|'Du thuyền';
type Product={id:string;type:ProductType;name:string;slug:string;place:string;price:string;salePrice:string;status:'draft'|'published'|'hidden';summary:string;cover:string;gallery:string;rating:string;category:string;duration:string;address:string;checkin:string;checkout:string;roomTypes:string;cabins:string;itinerary:string;amenities:string;policies:string;childrenPolicy:string;extraCharge:string;pickup:string;boarding:string;meals:string;activities:string;faq:string;content:string;seoTitle:string;seoDescription:string;updatedAt:string};

const empty=(type:ProductType):Product=>({id:'',type,name:'',slug:'',place:'',price:'',salePrice:'',status:'draft',summary:'',cover:'',gallery:'',rating:'',category:'',duration:'',address:'',checkin:'14:00',checkout:'12:00',roomTypes:'',cabins:'',itinerary:'',amenities:'',policies:'',childrenPolicy:'',extraCharge:'',pickup:'',boarding:'',meals:'',activities:'',faq:'',content:'',seoTitle:'',seoDescription:'',updatedAt:''});
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const id=()=>`p_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;

const seeds:Product[]=[
 {...empty('Villa & Resort'),id:'stay_oceanami',name:'Oceanami Villas & Beach Club',slug:'oceanami-villas-beach-club',place:'Phước Hải, Bà Rịa - Vũng Tàu',price:'4.500.000đ',status:'published',rating:'8.8',category:'Villa nguyên căn',summary:'Khu nghỉ dưỡng 5 sao với villa dành cho gia đình và nhóm bạn.',roomTypes:'Villa 3PN | 6 khách | Liên hệ giá\nVilla 4PN Beach Front | 8 khách | Liên hệ giá',amenities:'Hồ bơi\nBãi biển\nKhu vui chơi trẻ em\nGym',cover:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/6d/33/35/oceanami-villas-beach.jpg?w=1200&h=800&s=1',seoTitle:'Oceanami Villas & Beach Club - Đặt villa Phước Hải',updatedAt:'2026-08-22'},
 {...empty('Villa & Resort'),id:'stay_novaworld',name:'NovaWorld Phan Thiết',slug:'novaworld-phan-thiet',place:'Phan Thiết, Bình Thuận',price:'Liên hệ',status:'published',rating:'9.0',category:'Villa nguyên căn',summary:'Villa nghỉ dưỡng trong quần thể NovaWorld Phan Thiết.',roomTypes:'Villa 2PN\nVilla 3PN\nVilla 4PN',updatedAt:'2026-08-22'},
 {...empty('Khách sạn'),id:'stay_vinpearl_nt',name:'Vinpearl Resort Nha Trang',slug:'vinpearl-resort-nha-trang',place:'Hòn Tre, Nha Trang',address:'Hòn Tre, Nha Trang, Khánh Hòa',price:'Liên hệ',status:'published',rating:'8.9',category:'5 sao',summary:'Resort biển phù hợp gia đình và cặp đôi.',roomTypes:'Deluxe | 2 khách | Liên hệ giá\nGrand Deluxe | 2 khách | Liên hệ giá\nVilla gia đình | Liên hệ',updatedAt:'2026-08-22'},
 {...empty('Khách sạn'),id:'stay_flc_ss',name:'FLC Sầm Sơn',slug:'flc-sam-son',place:'Sầm Sơn, Thanh Hóa',price:'Liên hệ',status:'published',category:'5 sao',summary:'Khu nghỉ dưỡng biển cho gia đình, hội nhóm và khách đoàn.',updatedAt:'2026-08-22'},
 {...empty('Du thuyền'),id:'cruise_ambassador1',name:'Ambassador I - Vịnh Hạ Long',slug:'ambassador-i-ha-long-2n1d',place:'Vịnh Hạ Long',duration:'2 ngày 1 đêm',price:'4.500.000đ/khách',status:'published',rating:'9.1',summary:'Du thuyền ngủ đêm trên Vịnh Hạ Long.',cabins:'Cabin tiêu chuẩn | 2 khách | Liên hệ\nCabin cao cấp | 2 khách | Liên hệ\nSuite | 2 khách | Liên hệ',itinerary:'Ngày 1: Lên tàu - tham quan vịnh - ăn tối\nNgày 2: Hoạt động buổi sáng - trả phòng',updatedAt:'2026-08-22'},
 {...empty('Du thuyền'),id:'cruise_ambassador_signature',name:'Ambassador Signature - Vịnh Lan Hạ',slug:'ambassador-signature-lan-ha',place:'Vịnh Lan Hạ',duration:'2 ngày 1 đêm',price:'4.500.000đ/khách',status:'published',summary:'Du thuyền ngủ đêm khám phá Vịnh Lan Hạ.',updatedAt:'2026-08-22'},
 {...empty('Tour du lịch'),id:'tour_bac_kinh',name:'Bắc Kinh - Vạn Lý Trường Thành',slug:'bac-kinh-van-ly-truong-thanh',place:'Bắc Kinh, Trung Quốc',duration:'5N4Đ',price:'15.990.000đ',status:'published',category:'Tour Trung Quốc',rating:'9.2',summary:'Khám phá Bắc Kinh và Vạn Lý Trường Thành.',itinerary:'Ngày 1: Hà Nội - Bắc Kinh\nNgày 2: Quảng trường Thiên An Môn - Tử Cấm Thành\nNgày 3: Vạn Lý Trường Thành\nNgày 4: Tự do mua sắm\nNgày 5: Bắc Kinh - Hà Nội',updatedAt:'2026-08-22'},
 {...empty('Tour du lịch'),id:'tour_danang',name:'Đà Nẵng - Hội An - Bà Nà',slug:'da-nang-hoi-an-ba-na',place:'Đà Nẵng',duration:'4N3Đ',price:'Liên hệ',status:'published',category:'Tour trong nước',summary:'Tour miền Trung kết hợp biển, phố cổ và Bà Nà.',updatedAt:'2026-08-22'}
];

function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'pm-field wide':'pm-field'}><span>{label}</span>{children}</label>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="pm-section"><h3>{title}</h3><div className="pm-grid">{children}</div></section>}

export function AdminProductManager({type}:{type:ProductType}){
 const storageKey='tn_cms_products_v2';
 const [items,setItems]=useState<Product[]>([]);const [mode,setMode]=useState<'list'|'edit'>('list');const [form,setForm]=useState<Product>(empty(type));const [query,setQuery]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);setItems(saved?JSON.parse(saved):seeds)}catch{setItems(seeds)}},[]);
 useEffect(()=>{setMode('list');setForm(empty(type));setMessage('')},[type]);
 function persist(next:Product[]){setItems(next);localStorage.setItem(storageKey,JSON.stringify(next))}
 const visible=useMemo(()=>items.filter(p=>(type==='Sản phẩm'||p.type===type)&&(!query||`${p.name} ${p.place} ${p.slug}`.toLowerCase().includes(query.toLowerCase()))),[items,type,query]);
 function edit(p:Product){setForm({...p});setMessage('');setMode('edit')}
 function add(){setForm(empty(type==='Sản phẩm'?'Villa & Resort':type));setMessage('');setMode('edit')}
 function duplicate(p:Product){const copy={...p,id:id(),name:`${p.name} - Bản sao`,slug:`${p.slug}-copy`,status:'draft' as const,updatedAt:new Date().toISOString()};persist([...items,copy]);edit(copy)}
 function set<K extends keyof Product>(k:K,v:Product[K]){setForm(f=>({...f,[k]:v}))}
 function save(status:Product['status']){if(!form.name.trim()){setMessage('Vui lòng nhập tên sản phẩm.');return}const now=new Date().toISOString();const next={...form,id:form.id||id(),slug:form.slug||slugify(form.name),status,updatedAt:now};const found=items.some(x=>x.id===next.id);persist(found?items.map(x=>x.id===next.id?next:x):[...items,next]);setForm(next);setMessage(found?'Đã cập nhật sản phẩm cũ.':'Đã thêm sản phẩm mới.');}
 function remove(p:Product){if(!confirm(`Xóa ${p.name}?`))return;persist(items.filter(x=>x.id!==p.id))}

 if(mode==='list')return <section className="admin-panel product-manager"><div className="admin-panel-head"><div><h2>{type}</h2><p>Chỉnh sửa sản phẩm hiện có hoặc thêm mới. Dữ liệu thử nghiệm hiện được lưu trên trình duyệt.</p></div><button className="admin-primary" onClick={add}>+ Thêm mới</button></div><div className="admin-list-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, địa điểm, slug..."/><span>{visible.length} sản phẩm</span></div><div className="pm-list">{visible.map(p=><article key={p.id}>{p.cover?<img src={p.cover} alt=""/>:<div className="pm-placeholder">{p.type==='Tour du lịch'?'✈':p.type==='Du thuyền'?'🛳':p.type==='Khách sạn'?'🏨':'🏝'}</div>}<div className="pm-info"><b>{p.name}</b><span>{p.type} · {p.place||'Chưa nhập địa điểm'}</span><small>Cập nhật: {p.updatedAt?new Date(p.updatedAt).toLocaleDateString('vi-VN'):'—'}</small></div><strong>{p.salePrice||p.price||'Liên hệ'}</strong><em className={`pm-status ${p.status}`}>{p.status==='published'?'Đang bán':p.status==='hidden'?'Đang ẩn':'Bản nháp'}</em><div className="pm-actions"><button onClick={()=>edit(p)}>Sửa</button><button onClick={()=>duplicate(p)}>Nhân bản</button><button className="danger" onClick={()=>remove(p)}>Xóa</button></div></article>)}</div></section>;

 return <section className="admin-editor-shell product-manager-editor"><div className="admin-editor-main"><div className="editor-title-row"><button className="editor-back" onClick={()=>setMode('list')}>← Danh sách</button><b>{form.id?'Chỉnh sửa sản phẩm cũ':'Thêm sản phẩm mới'}</b><span>{message}</span></div><input className="post-title-input" value={form.name} onChange={e=>{const before=form.name;set('name',e.target.value);if(!form.slug||form.slug===slugify(before))set('slug',slugify(e.target.value))}} placeholder="Tên sản phẩm"/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div>

 <Section title="1. Thông tin cơ bản"><Field label="Nhóm sản phẩm"><select value={form.type} onChange={e=>set('type',e.target.value as ProductType)}><option>Tour du lịch</option><option>Villa & Resort</option><option>Khách sạn</option><option>Du thuyền</option></select></Field><Field label="Danh mục / phân loại"><input value={form.category} onChange={e=>set('category',e.target.value)}/></Field><Field label="Điểm đến / khu vực"><input value={form.place} onChange={e=>set('place',e.target.value)}/></Field><Field label="Địa chỉ"><input value={form.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Giá từ"><input value={form.price} onChange={e=>set('price',e.target.value)}/></Field><Field label="Giá khuyến mãi"><input value={form.salePrice} onChange={e=>set('salePrice',e.target.value)}/></Field><Field label="Điểm đánh giá"><input value={form.rating} onChange={e=>set('rating',e.target.value)}/></Field><Field label="Thời lượng"><input value={form.duration} onChange={e=>set('duration',e.target.value)}/></Field><Field label="Mô tả ngắn" wide><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)}/></Field></Section>

 {(form.type==='Villa & Resort'||form.type==='Khách sạn')&&<Section title="2. Lưu trú & hạng phòng"><Field label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></Field><Field label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></Field><Field label="Hạng phòng / villa & bảng giá" wide><textarea rows={8} value={form.roomTypes} onChange={e=>set('roomTypes',e.target.value)} placeholder="Tên hạng | sức chứa | diện tích | giá..."/></Field><Field label="Chính sách trẻ em" wide><textarea rows={3} value={form.childrenPolicy} onChange={e=>set('childrenPolicy',e.target.value)}/></Field><Field label="Phụ thu" wide><textarea rows={3} value={form.extraCharge} onChange={e=>set('extraCharge',e.target.value)}/></Field></Section>}

 {form.type==='Du thuyền'&&<Section title="2. Cabin & hành trình"><Field label="Điểm đón / bến"><input value={form.pickup} onChange={e=>set('pickup',e.target.value)}/></Field><Field label="Giờ lên tàu"><input value={form.boarding} onChange={e=>set('boarding',e.target.value)}/></Field><Field label="Hạng cabin & giá" wide><textarea rows={8} value={form.cabins} onChange={e=>set('cabins',e.target.value)} placeholder="Tên cabin | diện tích | sức chứa | giá..."/></Field><Field label="Lịch trình" wide><textarea rows={8} value={form.itinerary} onChange={e=>set('itinerary',e.target.value)}/></Field><Field label="Bữa ăn"><textarea rows={5} value={form.meals} onChange={e=>set('meals',e.target.value)}/></Field><Field label="Hoạt động"><textarea rows={5} value={form.activities} onChange={e=>set('activities',e.target.value)}/></Field></Section>}

 {form.type==='Tour du lịch'&&<Section title="2. Lịch trình Tour"><Field label="Lịch trình từng ngày" wide><textarea rows={12} value={form.itinerary} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1: ...\nNgày 2: ..."/></Field></Section>}

 <Section title="3. Nội dung & chính sách"><Field label="Nội dung giới thiệu" wide><textarea rows={10} value={form.content} onChange={e=>set('content',e.target.value)}/></Field><Field label="Tiện ích / dịch vụ bao gồm"><textarea rows={7} value={form.amenities} onChange={e=>set('amenities',e.target.value)}/></Field><Field label="Chính sách"><textarea rows={7} value={form.policies} onChange={e=>set('policies',e.target.value)}/></Field><Field label="FAQ" wide><textarea rows={7} value={form.faq} onChange={e=>set('faq',e.target.value)} placeholder="Câu hỏi: ...\nTrả lời: ..."/></Field></Section>

 <Section title="4. SEO"><Field label="SEO Title" wide><input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></Field><Field label="Meta description" wide><textarea rows={4} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></Field></Section>
 </div><aside className="admin-editor-side"><div className="editor-box publish-box"><h3>{form.id?'Cập nhật':'Đăng mới'}</h3><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value as Product['status'])}><option value="draft">Bản nháp</option><option value="published">Đang bán</option><option value="hidden">Ẩn</option></select></label><div className="publish-actions"><button onClick={()=>save('draft')}>Lưu nháp</button><button className="admin-primary" onClick={()=>save('published')}>{form.id?'Cập nhật & đăng':'Thêm & đăng'}</button></div></div><div className="editor-box"><h3>Ảnh đại diện</h3>{form.cover&&<img className="pm-cover" src={form.cover} alt=""/>}<input value={form.cover} onChange={e=>set('cover',e.target.value)} placeholder="URL ảnh đại diện"/></div><div className="editor-box"><h3>Album ảnh</h3><textarea rows={8} value={form.gallery} onChange={e=>set('gallery',e.target.value)} placeholder="Mỗi dòng một URL ảnh"/></div></aside></section>;
}
