'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
type Status='draft'|'published'|'scheduled';
type Article={id:string;title:string;slug:string;category:string;excerpt:string;cover:string;content:string;seoTitle:string;seoDescription:string;status:Status;publishAt:string;date:string};
const blank:Article={id:'',title:'',slug:'',category:'Cẩm nang du lịch',excerpt:'',cover:'',content:'',seoTitle:'',seoDescription:'',status:'draft',publishAt:'',date:''};
const seeds:Article[]=[{...blank,id:'a1',title:'Kinh nghiệm du lịch Phan Thiết cho gia đình',slug:'kinh-nghiem-du-lich-phan-thiet-cho-gia-dinh',category:'Cẩm nang du lịch',status:'published',date:'20/08/2026'},{...blank,id:'a2',title:'Top villa nghỉ dưỡng đẹp tại Phước Hải',slug:'top-villa-nghi-duong-dep-tai-phuoc-hai',category:'Villa & Resort',status:'draft',date:'18/08/2026'},{...blank,id:'a3',title:'Review du thuyền Ambassador Hạ Long',slug:'review-du-thuyen-ambassador-ha-long',category:'Du thuyền',status:'published',date:'16/08/2026'}];
function slugify(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
export function AdminContentEditor(){
 const key='tn_cms_articles_v3';const [mode,setMode]=useState<'list'|'edit'>('list');const [form,setForm]=useState<Article>(blank);const [items,setItems]=useState<Article[]>([]);const [saved,setSaved]=useState('');const editorRef=useRef<HTMLTextAreaElement|null>(null);
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(key)||'null')||seeds)}catch{setItems(seeds)}},[]);
 const persist=(x:Article[])=>{setItems(x);localStorage.setItem(key,JSON.stringify(x))};
 const seoScore=useMemo(()=>{let s=0;if(form.title.length>=35)s+=25;if(form.seoDescription.length>=100)s+=25;if(form.cover)s+=15;if(form.content.length>=800)s+=20;if(form.slug)s+=15;return s},[form]);
 const words=useMemo(()=>form.content.trim()?form.content.trim().split(/\s+/).length:0,[form.content]);
 function set<K extends keyof Article>(k:K,v:Article[K]){setForm(f=>({...f,[k]:v}))}function newPost(){setForm(blank);setSaved('');setMode('edit')}function edit(a:Article){setForm({...a});setSaved('');setMode('edit')}
 function remove(id:string){if(!window.confirm('Xóa bài viết này? Thao tác này không thể hoàn tác.'))return;persist(items.filter(a=>a.id!==id))}
 function save(status:Status){if(!form.title.trim()){setSaved('Vui lòng nhập tiêu đề.');return}const next={...form,id:form.id||`article_${Date.now()}`,slug:form.slug||slugify(form.title),status,date:form.date||new Date().toLocaleDateString('vi-VN')};const exists=items.some(a=>a.id===next.id);persist(exists?items.map(a=>a.id===next.id?next:a):[next,...items]);setForm(next);setSaved(status==='published'?'Đã đăng bài.':'Đã lưu bài.');}
 function insert(before:string,after='',placeholder='Nội dung'){const el=editorRef.current;if(!el)return;const start=el.selectionStart??form.content.length;const end=el.selectionEnd??start;const selected=form.content.slice(start,end)||placeholder;const next=form.content.slice(0,start)+before+selected+after+form.content.slice(end);set('content',next);setTimeout(()=>{el.focus();const pos=start+before.length+selected.length+after.length;el.setSelectionRange(pos,pos)},0)}
 function insertBlock(block:string){const el=editorRef.current;const start=el?.selectionStart??form.content.length;const next=form.content.slice(0,start)+block+form.content.slice(start);set('content',next);setTimeout(()=>el?.focus(),0)}
 if(mode==='list')return <section className="admin-panel wp-list-panel"><div className="admin-panel-head"><div><h2>Bài viết / Cẩm nang</h2><p>Trình soạn bài nâng cao, quản lý bài cũ, SEO và xuất bản.</p></div><button type="button" className="admin-primary" onClick={newPost}>+ Viết bài mới</button></div><div className="wp-content-list">{items.map(a=><article key={a.id}><div><b>{a.title}</b><span>{a.category}</span></div><span>{a.date}</span><em>{a.status==='published'?'Đã đăng':a.status==='scheduled'?'Hẹn giờ':'Bản nháp'}</em><div className="pm-actions"><button type="button" onClick={()=>edit(a)}>Sửa</button><button type="button" className="danger-action" onClick={()=>remove(a.id)}>Xóa</button></div></article>)}</div></section>;
 return <section className="admin-editor-shell"><div className="admin-editor-main"><div className="editor-title-row"><button type="button" className="editor-back" onClick={()=>setMode('list')}>← Danh sách bài</button><span>{saved}</span></div><input className="post-title-input" value={form.title} onChange={e=>{const old=form.title;set('title',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}} placeholder="Nhập tiêu đề bài viết"/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div>
 <div className="pro-editor"><div className="pro-toolbar"><select onChange={e=>{if(e.target.value==='h2')insert('<h2>','</h2>','Tiêu đề H2');if(e.target.value==='h3')insert('<h3>','</h3>','Tiêu đề H3');e.currentTarget.value='p'}} defaultValue="p"><option value="p">Đoạn văn</option><option value="h2">Tiêu đề H2</option><option value="h3">Tiêu đề H3</option></select><span className="tool-sep"/><button type="button" onClick={()=>insert('<strong>','</strong>','chữ đậm')}><b>B</b></button><button type="button" onClick={()=>insert('<em>','</em>','chữ nghiêng')}><i>I</i></button><button type="button" onClick={()=>insert('<u>','</u>','gạch chân')}><u>U</u></button><button type="button" onClick={()=>insert('<mark>','</mark>','nổi bật')}>Highlight</button><span className="tool-sep"/><button type="button" onClick={()=>insertBlock('\n<ul>\n  <li>Mục 1</li>\n  <li>Mục 2</li>\n</ul>\n')}>• Danh sách</button><button type="button" onClick={()=>insertBlock('\n<ol>\n  <li>Bước 1</li>\n  <li>Bước 2</li>\n</ol>\n')}>1. Danh sách</button><button type="button" onClick={()=>insert('<blockquote>','</blockquote>','Trích dẫn')}>❝ Quote</button><span className="tool-sep"/><button type="button" onClick={()=>insert('<a href="https://">','</a>','Liên kết')}>🔗 Link</button><button type="button" onClick={()=>insertBlock('\n<img src="URL_ANH" alt="Mô tả ảnh" />\n')}>🖼 Ảnh</button><button type="button" onClick={()=>insertBlock('\n<iframe src="URL_VIDEO" title="Video"></iframe>\n')}>🎬 Video</button><button type="button" onClick={()=>insertBlock('\n<table><thead><tr><th>Tiêu đề 1</th><th>Tiêu đề 2</th></tr></thead><tbody><tr><td>Nội dung</td><td>Nội dung</td></tr></tbody></table>\n')}>▦ Bảng</button><button type="button" onClick={()=>insertBlock('\n<a class="cta-button" href="tel:0969973949">Gọi 0969 973 949</a>\n')}>☎ CTA</button><span className="tool-sep"/><button type="button" onClick={()=>insertBlock('\n<hr />\n')}>― Ngăn cách</button><button type="button" onClick={()=>insertBlock('\n<div class="note-box"><strong>Lưu ý:</strong> Nhập nội dung tại đây.</div>\n')}>💡 Box lưu ý</button></div><textarea ref={editorRef} value={form.content} onChange={e=>set('content',e.target.value)} placeholder="Bắt đầu viết nội dung bài... Bạn có thể dùng thanh công cụ phía trên để chèn tiêu đề, link, ảnh, video, bảng, CTA và các khối nội dung."/><div className="editor-meta-bar"><span>{words} từ · {form.content.length} ký tự</span><span>Ước tính đọc: {Math.max(1,Math.ceil(words/220))} phút</span></div></div>
 <div className="editor-helper-grid"><div className="editor-helper"><h4>Khung bài SEO du lịch</h4><p>Chèn nhanh bố cục: mở bài, điểm nổi bật, lịch trình/kinh nghiệm, giá, lưu ý và CTA.</p><button type="button" onClick={()=>insertBlock('\n<h2>Tổng quan</h2>\n<p>...</p>\n<h2>Điểm nổi bật</h2>\n<ul><li>...</li></ul>\n<h2>Kinh nghiệm / Lịch trình</h2>\n<p>...</p>\n<h2>Chi phí tham khảo</h2>\n<p>...</p>\n<h2>Lưu ý quan trọng</h2>\n<p>...</p>\n<a class="cta-button" href="tel:0969973949">Liên hệ Thúy Nguyên Travel</a>\n')}>+ Chèn khung SEO</button></div><div className="editor-helper"><h4>Khối FAQ</h4><p>Thêm câu hỏi thường gặp giúp bài dễ đọc và hỗ trợ SEO.</p><button type="button" onClick={()=>insertBlock('\n<h2>Câu hỏi thường gặp</h2>\n<h3>Câu hỏi 1?</h3>\n<p>Trả lời...</p>\n<h3>Câu hỏi 2?</h3>\n<p>Trả lời...</p>\n')}>+ Chèn FAQ</button></div></div>
 <div className="editor-box"><h3>Mô tả ngắn</h3><textarea rows={3} value={form.excerpt} onChange={e=>set('excerpt',e.target.value)} placeholder="Đoạn giới thiệu hiển thị ở danh sách bài viết"/></div><div className="editor-box"><div className="editor-box-head"><h3>SEO bài viết</h3><b className={seoScore>=70?'seo-good':''}>{seoScore}/100</b></div><label>SEO Title<input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)} placeholder="Khoảng 50–60 ký tự"/></label><label>Meta description<textarea rows={3} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)} placeholder="Khoảng 120–160 ký tự"/></label></div></div><aside className="admin-editor-side"><div className="editor-box publish-box"><h3>Xuất bản</h3><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value as Status)}><option value="draft">Bản nháp</option><option value="published">Đăng ngay</option><option value="scheduled">Hẹn giờ</option></select></label>{form.status==='scheduled'&&<label>Thời gian đăng<input type="datetime-local" value={form.publishAt} onChange={e=>set('publishAt',e.target.value)}/></label>}<div className="publish-actions"><button type="button" onClick={()=>save('draft')}>Lưu nháp</button><button type="button" className="admin-primary" onClick={()=>save(form.status==='scheduled'?'scheduled':'published')}>{form.status==='scheduled'?'Lên lịch':'Đăng bài'}</button></div>{form.id&&<button type="button" className="danger-action full-danger" onClick={()=>{remove(form.id);setMode('list')}}>Xóa bài viết</button>}</div><div className="editor-box"><h3>Chuyên mục</h3><select value={form.category} onChange={e=>set('category',e.target.value)}><option>Cẩm nang du lịch</option><option>Tour</option><option>Villa & Resort</option><option>Khách sạn</option><option>Du thuyền</option></select></div><div className="editor-box"><h3>Ảnh đại diện</h3><input value={form.cover} onChange={e=>set('cover',e.target.value)} placeholder="URL ảnh hoặc chọn từ Media"/></div><div className="editor-box"><h3>Checklist bài viết</h3><small>✓ Tiêu đề rõ chủ đề</small><small>✓ Có H2/H3</small><small>✓ Có ảnh đại diện</small><small>✓ Có CTA hotline/Zalo</small><small>✓ Meta description 120–160 ký tự</small></div></aside></section>;
}
