'use client';
import {useEffect,useMemo,useState} from 'react';

type Activity={id:string;type:string;content:string;nextFollowUpAt?:string|null;staffId?:string;staffName?:string;createdAt:string};
type Assignment={staffId:string;staffName:string;source:string;assignedAt:string};
type Customer={id:string;name:string;phone:string;email:string;status:'lead'|'contacting'|'customer'|'inactive';source:string;note:string;createdAt:string;updatedAt:string;bookingCount:number;latestBookingAt:string;assignment:Assignment|null;activities:Activity[]};
type Sale={id:string;name:string;email:string};
type Rotation={enabled:boolean;lastStaffId:string;assignedCount:number};
const labels:Record<Customer['status'],string>={lead:'Lead mới',contacting:'Đang chăm sóc',customer:'Khách hàng',inactive:'Ngưng theo dõi'};
const sources=['Facebook','Zalo','Hotline','Khách giới thiệu','Khách cũ quay lại','Đối tác','Khách vãng lai','Google','TikTok','Website','Khác'];
function date(v?:string){if(!v)return'—';const d=new Date(v);return Number.isNaN(+d)?v:d.toLocaleString('vi-VN')}
async function api(body?:unknown){const r=await fetch('/api/admin/crm',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Không thể xử lý CRM.');return j}

export function AdminCustomers(){
 const[items,setItems]=useState<Customer[]>([]),[sales,setSales]=useState<Sale[]>([]),[rotation,setRotation]=useState<Rotation>({enabled:false,lastStaffId:'',assignedCount:0}),[manage,setManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[showLead,setShowLead]=useState(false),[selected,setSelected]=useState<Customer|null>(null);
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[source,setSource]=useState('Facebook'),[note,setNote]=useState(''),[saleId,setSaleId]=useState('');
 const[activity,setActivity]=useState(''),[activityType,setActivityType]=useState('note'),[followUp,setFollowUp]=useState('');
 async function load(){setLoading(true);try{const j=await api();setItems(j.customers||[]);setSales(j.sales||[]);setRotation(j.rotation||{enabled:false,lastStaffId:'',assignedCount:0});setManage(Boolean(j.capabilities?.manage));if(selected){const next=(j.customers||[]).find((x:Customer)=>x.id===selected.id);if(next)setSelected(next)}}catch(e){setMsg(e instanceof Error?e.message:'Không đọc được CRM.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>items.filter(c=>!q||`${c.name} ${c.phone} ${c.email} ${c.source} ${c.assignment?.staffName||''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 async function act(body:unknown,success:string){setBusy(true);setMsg('');try{const j=await api(body);setMsg(success.replace('{count}',String(j.count??'')));await load();return true}catch(e){setMsg(e instanceof Error?e.message:'Không thể cập nhật.');return false}finally{setBusy(false)}}
 async function create(){if(await act({action:'create',name,phone,email,source,note,salesStaffId:saleId},`Đã thêm ${name.trim()||'khách hàng'} vào CRM production.`)){setName('');setPhone('');setEmail('');setSource('Facebook');setNote('');setSaleId('');setShowLead(false)}}
 async function assign(c:Customer,id:string){await act({action:'assign',customerId:c.id,staffId:id},id?'Đã phân Sale.':'Đã bỏ phân Sale.')}
 async function status(c:Customer,value:Customer['status']){await act({action:'status',customerId:c.id,status:value},'Đã cập nhật trạng thái khách.')}
 async function toggleAuto(){await act({action:'toggleAuto',enabled:!rotation.enabled},!rotation.enabled?'Đã bật chia khách xoay vòng trên server.':'Đã tắt chia khách tự động.')}
 async function distribute(){await act({action:'distribute'},'Đã phân {count} khách chưa có Sale.')}
 async function addActivity(){if(!selected||!activity.trim())return;const ok=await act({action:'activity',customerId:selected.id,type:activityType,content:activity,nextFollowUpAt:followUp},'Đã lưu lịch sử chăm sóc.');if(ok){setActivity('');setFollowUp('')}}
 return <section className="admin-panel">
  <div className="admin-panel-head"><div><small>CRM PRODUCTION</small><h2>Khách hàng & phân Sale</h2><p>Dữ liệu khách, phân Sale và lịch sử chăm sóc được lưu trực tiếp trên Neon và dùng chung trên mọi thiết bị.</p></div><button className="admin-primary" onClick={()=>setShowLead(v=>!v)}>+ Nhập khách hàng</button></div>
  {manage&&<div className="crm-auto-box"><div><small>PHÂN KHÁCH TỰ ĐỘNG</small><b>{rotation.enabled?'Đang bật · Xoay vòng Sale':'Đang tắt'}</b><span>{sales.length} Sale đang hoạt động · đã tự động phân {rotation.assignedCount} lượt</span></div><div><button className={rotation.enabled?'admin-primary':'admin-secondary'} disabled={busy} onClick={toggleAuto}>{rotation.enabled?'Tắt tự động':'Bật tự động'}</button><button className="admin-secondary" disabled={busy||!rotation.enabled} onClick={distribute}>Phân khách chưa giao ngay</button></div></div>}
  {showLead&&<div className="admin-form-row"><label>Họ tên *<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn A"/></label><label>Điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="09..."/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Nguồn<select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></label>{manage&&<label>Giao cho Sale<select value={saleId} onChange={e=>setSaleId(e.target.value)}><option value="">Tự động / chưa giao</option>{sales.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>Nhu cầu ban đầu<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Đi đâu, ngày dự kiến, số khách, ngân sách..."/></label><button className="admin-primary" disabled={busy} onClick={create}>{busy?'Đang lưu...':'Lưu vào CRM'}</button></div>}
  {msg&&<p className="admin-api-note">{msg}</p>}
  <div className="admin-list-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên, SĐT, email, nguồn hoặc Sale"/><span>{loading?'Đang tải...':`${visible.length} khách`}</span></div>
  <div className="admin-customer-grid">{visible.map(c=><article className="admin-customer-card crm-assigned-card" key={c.id}><div><b>{c.name}</b>{c.phone?<a href={`tel:${c.phone.replace(/\D/g,'')}`}>{c.phone}</a>:<small>Không có SĐT</small>}<small>{c.email||'Không có email'}</small><small>Nguồn: <b>{c.source||'—'}</b></small></div><div><span>{c.bookingCount} booking</span><small>{c.assignment?`Sale: ${c.assignment.staffName}${c.assignment.source==='round_robin'?' · Tự động':''}`:'Chưa phân Sale'}</small><small>Cập nhật: {date(c.updatedAt)}</small></div><label><small>Trạng thái</small><select value={c.status} disabled={busy} onChange={e=>void status(c,e.target.value as Customer['status'])}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{manage&&<label className="crm-assign"><small>Phân cho Sale</small><select value={c.assignment?.staffId||''} disabled={busy} onChange={e=>void assign(c,e.target.value)}><option value="">— Chưa phân —</option>{sales.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button onClick={()=>setSelected(c)}>Hồ sơ chăm sóc</button></article>)}</div>
  {!loading&&!visible.length&&<div className="admin-empty-state">Chưa có khách phù hợp.</div>}
  {selected&&<div className="admin-customer-detail crm-customer-profile"><div className="admin-panel-head"><div><h3>{selected.name}</h3><p>{selected.phone||'Không SĐT'} · {selected.email||'Không email'} · {labels[selected.status]}</p>{selected.note&&<p>Nhu cầu ban đầu: {selected.note}</p>}</div><button onClick={()=>setSelected(null)}>Đóng</button></div><div className="admin-form-row"><label>Loại chăm sóc<select value={activityType} onChange={e=>setActivityType(e.target.value)}><option value="call">Gọi điện</option><option value="message">Nhắn tin</option><option value="quote">Gửi báo giá</option><option value="note">Ghi chú</option><option value="follow_up">Hẹn chăm sóc</option></select></label><label>Nội dung<input value={activity} onChange={e=>setActivity(e.target.value)} placeholder="Nội dung trao đổi với khách"/></label><label>Nhắc lại lúc<input type="datetime-local" value={followUp} onChange={e=>setFollowUp(e.target.value)}/></label><button className="admin-primary" disabled={busy||!activity.trim()} onClick={addActivity}>Lưu chăm sóc</button></div><h4>Lịch sử CRM</h4><div className="admin-table">{selected.activities?.map(a=><div key={a.id}><b>{a.type}</b><span>{a.content}</span><span>{a.staffName||'Hệ thống'}</span><em>{date(a.createdAt)}{a.nextFollowUpAt?` · Hẹn ${date(a.nextFollowUpAt)}`:''}</em></div>)}</div>{!selected.activities?.length&&<div className="admin-empty-state">Chưa có lịch sử chăm sóc.</div>}</div>}
 </section>
}
