'use client';

import {useEffect,useMemo,useState} from 'react';
import {AdminRateCalendar} from '@/components/AdminRateCalendar';

type Unit={id:string;code:string;name:string;weekdayPrice?:string;weekendPrice?:string;status?:string};
type Product={id:string;name:string;type:string;slug:string;place?:string;status:string;units?:Unit[]};
const KEY='tn_cms_products_v3_units';
export function AdminRateManager(){const [products,setProducts]=useState<Product[]>([]);const [productId,setProductId]=useState('');const [unitId,setUnitId]=useState('');const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]') as Product[];setProducts(x.filter(p=>p.status!=='hidden'&&(p.type==='Villa & Resort'||p.type==='Khách sạn'||p.type==='Du thuyền')))}catch{setProducts([])}};useEffect(()=>{load();window.addEventListener('tn-products-updated',load);return()=>window.removeEventListener('tn-products-updated',load)},[]);const product=useMemo(()=>products.find(p=>p.id===productId)||products[0]||null,[products,productId]);useEffect(()=>{if(product&&!productId)setProductId(product.id)},[product,productId]);const units=product?.units||[];const unit=useMemo(()=>units.find(u=>u.id===unitId)||units[0]||null,[units,unitId]);useEffect(()=>{if(unit)setUnitId(unit.id);else setUnitId('')},[product?.id]);return <section className="admin-panel rate-manager"><div className="admin-panel-head"><div><h2>Lịch giá & tồn phòng</h2><p>Quản lý giá theo ngày, số lượng còn bán và trạng thái phòng/cabin giống hệ thống OTA.</p></div></div>{!products.length?<div className="unit-empty">Chưa có sản phẩm lưu trú/du thuyền. Hãy tạo sản phẩm và căn/phòng/cabin trước.</div>:<><div className="rate-manager-selectors"><label>Sản phẩm<select value={product?.id||''} onChange={e=>{setProductId(e.target.value);setUnitId('')}}>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.type}</option>)}</select></label><label>Căn / phòng / cabin<select value={unit?.id||''} onChange={e=>setUnitId(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.name||u.code||'Chưa đặt tên'}{u.code?` · ${u.code}`:''}</option>)}</select></label></div>{unit?<><div className="rate-current-card"><div><small>Sản phẩm</small><b>{product?.name}</b><span>{product?.place||product?.type}</span></div><div><small>Căn/phòng đang chỉnh</small><b>{unit.name||unit.code}</b><span>Giá nền: {unit.weekdayPrice||'chưa nhập'} · Cuối tuần: {unit.weekendPrice||'chưa nhập'}</span></div></div><AdminRateCalendar unitId={unit.id}/></>:<div className="unit-empty">Sản phẩm này chưa có căn/phòng/cabin. Hãy thêm trong mục sản phẩm trước.</div>}</>}</section>}
