'use client';

import {ChangeEvent,useEffect,useMemo,useRef,useState} from 'react';

type BackupFile={kind:'happygo-admin-backup';schemaVersion:1;app:string;createdAt:string;source:string;checksum:string;data:Record<string,string>;summary:{keys:number;bytes:number;records:number}};
type ImportPreview={fileName:string;createdAt:string;checksumOk:boolean;data:Record<string,string>;keys:number;bytes:number;records:number;skipped:number};
type Activity={id:string;action:'export'|'import';at:string;fileName:string;keys:number;records:number;mode?:'merge'|'replace'};
type ImportMode='merge'|'replace';

const ACTIVITY_KEY='happygo_backup_activity_v1';
const PREFIXES=['tn_','happygo_'];
const EXCLUDED_KEYS=new Set([
 'tn_admin_api_key',
 'tn_admin_staff_v1',
 'happygo_owner_login_v1',
 'happygo_admin_current_staff_v3',
 'happygo_admin_session_v1',
 'happygo_customer_accounts_v1',
 'happygo_customer_session_v1',
 'happygo_partner_accounts_v1',
 'happygo_partner_session_v1',
 'happygo_partner_api_v1',
 ACTIVITY_KEY,
]);
const EXCLUDED_PARTS=['token','secret','password','api_key','session','quick_open','selected_unit'];

function safeKey(key:string){return PREFIXES.some(prefix=>key.startsWith(prefix))&&!EXCLUDED_KEYS.has(key)&&!EXCLUDED_PARTS.some(part=>key.toLowerCase().includes(part))}
function bytes(value:string){return new Blob([value]).size}
function records(value:string){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.length;if(parsed&&typeof parsed==='object')return Object.keys(parsed).length;return parsed==null?0:1}catch{return value?1:0}}
function formatBytes(value:number){if(value<1024)return`${value} B`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KB`;return`${(value/1024/1024).toFixed(2)} MB`}
function time(value:string){const parsed=new Date(value);return Number.isNaN(+parsed)?value:parsed.toLocaleString('vi-VN')}
function fileStamp(){const now=new Date(),pad=(value:number)=>String(value).padStart(2,'0');return`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}_${pad(now.getHours())}-${pad(now.getMinutes())}`}
function readActivity():Activity[]{try{const parsed=JSON.parse(localStorage.getItem(ACTIVITY_KEY)||'[]');return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function category(key:string){const value=key.toLowerCase();if(/booking|supplier|payment|receipt|voucher|inventory|ledger|operator/.test(value))return'Vận hành';if(/crm|customer|review|feedback|followup/.test(value))return'Khách hàng / CRM';if(/cms|product|tour|rate|media|homepage|seo|site_settings/.test(value))return'Nội dung website';if(/partner/.test(value))return'Đối tác';if(/chat|support/.test(value))return'Trao đổi';return'Cấu hình khác'}
function scan(){const data:Record<string,string>={};for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(key&&safeKey(key)){const value=localStorage.getItem(key);if(value!==null)data[key]=value}}return data}
async function digest(data:Record<string,string>){const input=new TextEncoder().encode(JSON.stringify(data));const hash=await crypto.subtle.digest('SHA-256',input);return Array.from(new Uint8Array(hash)).map(value=>value.toString(16).padStart(2,'0')).join('')}
function download(payload:BackupFile,fileName:string){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=fileName;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function identity(value:unknown,index:number){if(value&&typeof value==='object'){const item=value as Record<string,unknown>;for(const key of ['id','code','customerKey','slug','date','bookingCode'])if(item[key]!=null)return`${key}:${String(item[key])}`}return`json:${JSON.stringify(value)}:${index}`}
function mergeValue(current:string|null,incoming:string){if(current===null)return incoming;try{const oldValue=JSON.parse(current),newValue=JSON.parse(incoming);if(Array.isArray(oldValue)&&Array.isArray(newValue)){const map=new Map<string,unknown>();newValue.forEach((item,index)=>map.set(identity(item,index),item));oldValue.forEach((item,index)=>map.set(identity(item,index),item));return JSON.stringify([...map.values()])}if(oldValue&&newValue&&typeof oldValue==='object'&&typeof newValue==='object'&&!Array.isArray(oldValue)&&!Array.isArray(newValue))return JSON.stringify({...newValue,...oldValue});return current}catch{return current}}

export function AdminBackupCenter(){
 const[fileInput,setFileInput]=useState(0),[preview,setPreview]=useState<ImportPreview|null>(null),[mode,setMode]=useState<ImportMode>('merge'),[activity,setActivity]=useState<Activity[]>([]),[inventory,setInventory]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),inputRef=useRef<HTMLInputElement|null>(null);
 const refresh=()=>{setInventory(scan());setActivity(readActivity())};
 useEffect(()=>{refresh()},[]);
 const stats=useMemo(()=>Object.values(inventory).reduce((result,value)=>({keys:result.keys+1,bytes:result.bytes+bytes(value),records:result.records+records(value)}),{keys:0,bytes:0,records:0}),[inventory]);
 const groups=useMemo(()=>Object.entries(inventory).reduce<Record<string,{keys:number;bytes:number;records:number}>>((result,[key,value])=>{const name=category(key),current=result[name]||{keys:0,bytes:0,records:0};result[name]={keys:current.keys+1,bytes:current.bytes+bytes(value),records:current.records+records(value)};return result},{}),[inventory]);

 function log(entry:Activity){const next=[entry,...readActivity()].slice(0,20);localStorage.setItem(ACTIVITY_KEY,JSON.stringify(next));setActivity(next)}
 async function makeBackup(reason='dinh-ky',shouldLog=true){const data=scan(),summary=Object.values(data).reduce((result,value)=>({keys:result.keys+1,bytes:result.bytes+bytes(value),records:result.records+records(value)}),{keys:0,bytes:0,records:0}),createdAt=new Date().toISOString(),fileName=`happygo-backup_${reason}_${fileStamp()}.json`,payload:BackupFile={kind:'happygo-admin-backup',schemaVersion:1,app:'HappyGo Travel Admin',createdAt,source:location.origin,checksum:await digest(data),data,summary};download(payload,fileName);if(shouldLog)log({id:`backup_${Date.now()}`,action:'export',at:createdAt,fileName,keys:summary.keys,records:summary.records});return payload}
 async function exportNow(){setBusy(true);setMessage('');try{const payload=await makeBackup();setMessage(`Đã tải bản sao lưu gồm ${payload.summary.records} bản ghi. Hãy cất file ở nơi an toàn.`)}catch{setMessage('Không thể tạo file sao lưu trên trình duyệt này.')}finally{setBusy(false)}}
 async function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];setPreview(null);setMessage('');if(!file)return;if(file.size>25*1024*1024){setMessage('File vượt quá 25 MB. Vui lòng chọn đúng file sao lưu HappyGo.');return}setBusy(true);try{const parsed=JSON.parse(await file.text()) as Partial<BackupFile>;if(parsed.kind!=='happygo-admin-backup'||parsed.schemaVersion!==1||!parsed.data||typeof parsed.data!=='object'||Array.isArray(parsed.data))throw new Error('invalid');const accepted:Record<string,string>={},entries=Object.entries(parsed.data),skipped:string[]=[];entries.forEach(([key,value])=>{if(safeKey(key)&&typeof value==='string')accepted[key]=value;else skipped.push(key)});if(!Object.keys(accepted).length)throw new Error('empty');const checksumOk=Boolean(parsed.checksum)&&parsed.checksum===await digest(parsed.data as Record<string,string>),summary=Object.values(accepted).reduce((result,value)=>({keys:result.keys+1,bytes:result.bytes+bytes(value),records:result.records+records(value)}),{keys:0,bytes:0,records:0});setPreview({fileName:file.name,createdAt:String(parsed.createdAt||''),checksumOk,data:accepted,...summary,skipped:skipped.length});if(!checksumOk)setMessage('File không vượt qua kiểm tra toàn vẹn. Không thể khôi phục dữ liệu từ file này.')}catch{setMessage('File không đúng định dạng sao lưu HappyGo hoặc đã bị hỏng.')}finally{setBusy(false);setFileInput(value=>value+1)}}
 async function restore(){if(!preview||!preview.checksumOk||busy)return;if(!confirm(`Khôi phục ${preview.records} bản ghi theo chế độ ${mode==='merge'?'Gộp an toàn':'Ghi đè'}? Một bản sao hiện tại sẽ được tải xuống trước khi thực hiện.`))return;setBusy(true);setMessage('');try{await makeBackup('truoc-khoi-phuc',false);Object.entries(preview.data).forEach(([key,value])=>localStorage.setItem(key,mode==='merge'?mergeValue(localStorage.getItem(key),value):value));log({id:`restore_${Date.now()}`,action:'import',at:new Date().toISOString(),fileName:preview.fileName,keys:preview.keys,records:preview.records,mode});window.dispatchEvent(new Event('storage'));window.dispatchEvent(new Event('tn-bookings-updated'));window.dispatchEvent(new Event('happygo-customer-vouchers-updated'));window.dispatchEvent(new Event('happygo-supplier-orders-updated'));setMessage(`Đã khôi phục ${preview.records} bản ghi. Trang sẽ tải lại để đồng bộ dữ liệu.`);setTimeout(()=>window.location.reload(),900)}catch{setMessage('Không thể khôi phục dữ liệu. Bản sao trước khôi phục đã được tải xuống.');setBusy(false)}}

 return <section className="admin-panel backup-center">
  <div className="admin-panel-head"><div><small>SAO LƯU CỤC BỘ · CHƯA CẦN VERCEL</small><h2>Bảo vệ dữ liệu quản trị HappyGo</h2><p>Tải toàn bộ dữ liệu nghiệp vụ về máy và khôi phục khi đổi trình duyệt hoặc thiết bị.</p></div><span className="backup-security">Không xuất mật khẩu, phiên đăng nhập hoặc khóa API</span></div>
  {message&&<p className="admin-api-note backup-message">{message}</p>}
  <div className="service-kpis"><article><small>NHÓM DỮ LIỆU</small><b>{Object.keys(groups).length}</b></article><article><small>KHÓA DỮ LIỆU</small><b>{stats.keys}</b></article><article><small>BẢN GHI ƯỚC TÍNH</small><b>{stats.records}</b></article><article><small>DUNG LƯỢNG</small><b>{formatBytes(stats.bytes)}</b></article></div>
  <div className="backup-actions"><article><div><span>1</span><div><b>Xuất bản sao lưu</b><p>Booking, khách hàng, đơn NCC, thanh toán, voucher, nội dung và cấu hình được đóng gói vào một file JSON.</p></div></div><button className="admin-primary" disabled={busy||!stats.keys} onClick={exportNow}>{busy?'Đang xử lý…':'Tải file sao lưu'}</button></article><article><div><span>2</span><div><b>Chọn file để khôi phục</b><p>Hệ thống kiểm tra đúng định dạng và mã toàn vẹn trước khi cho phép nhập dữ liệu.</p></div></div><input key={fileInput} ref={inputRef} type="file" accept="application/json,.json" onChange={chooseFile} hidden/><button disabled={busy} onClick={()=>inputRef.current?.click()}>Chọn file JSON</button></article></div>
  <div className="backup-group-grid">{Object.entries(groups).sort((a,b)=>b[1].records-a[1].records).map(([name,value])=><article key={name}><small>{name}</small><b>{value.records} bản ghi</b><span>{value.keys} nhóm · {formatBytes(value.bytes)}</span></article>)}</div>
  {preview&&<section className={`backup-preview ${preview.checksumOk?'valid':'invalid'}`}><header><div><small>FILE ĐANG CHỜ KHÔI PHỤC</small><h3>{preview.fileName}</h3><p>{preview.createdAt?`Tạo lúc ${time(preview.createdAt)}`:'Không có thời gian tạo'} · {formatBytes(preview.bytes)}</p></div><strong>{preview.checksumOk?'✓ File hợp lệ':'× File không hợp lệ'}</strong></header>{preview.checksumOk&&<><div className="backup-preview-stats"><span><b>{preview.keys}</b> nhóm dữ liệu</span><span><b>{preview.records}</b> bản ghi</span><span><b>{preview.skipped}</b> mục nhạy cảm đã bỏ qua</span></div><fieldset><legend>Cách khôi phục</legend><label><input type="radio" name="backup-mode" checked={mode==='merge'} onChange={()=>setMode('merge')}/><span><b>Gộp an toàn</b><small>Giữ dữ liệu hiện có; chỉ bổ sung các bản ghi còn thiếu.</small></span></label><label><input type="radio" name="backup-mode" checked={mode==='replace'} onChange={()=>setMode('replace')}/><span><b>Ghi đè theo file</b><small>Thay các nhóm có trong máy bằng dữ liệu từ file sao lưu.</small></span></label></fieldset><div className="backup-preview-actions"><button onClick={()=>setPreview(null)}>Hủy</button><button className="admin-primary" disabled={busy} onClick={restore}>{busy?'Đang khôi phục…':'Khôi phục dữ liệu'}</button></div></>}</section>}
  <section className="backup-history"><div><small>LỊCH SỬ TRÊN THIẾT BỊ NÀY</small><b>{activity.length?`${activity.length} hoạt động gần nhất`:'Chưa có hoạt động sao lưu'}</b></div>{activity.slice(0,8).map(item=><article key={item.id}><span className={item.action}>{item.action==='export'?'↓':'↑'}</span><div><b>{item.action==='export'?'Đã xuất bản sao lưu':'Đã khôi phục dữ liệu'}</b><small>{item.fileName} · {item.records} bản ghi{item.mode?` · ${item.mode==='merge'?'Gộp':'Ghi đè'}`:''}</small></div><time>{time(item.at)}</time></article>)}</section>
 </section>
}
