'use client';

import {useEffect,useMemo,useState} from 'react';

type ProposalStatus='draft'|'pending'|'changes_requested'|'approved'|'rejected';
type Audit={id:string;at:string;byId:string;byName:string;action:string;detail?:string};
type Proposal={id:string;title:string;campaign:string;month:string;channel:string;objective:string;startDate:string;endDate:string;requestedAmount:number;approvedAmount:number;expectedLeads:number;expectedRevenue:number;justification:string;note:string;status:ProposalStatus;createdById:string;createdByName:string;createdAt:string;updatedAt:string;submittedAt?:string;approvedAt?:string;approvedBy?:string;rejectedAt?:string;rejectedBy?:string;audit:Audit[]};
type Expense={id:string;proposalId:string;campaign:string;month:string;date:string;category:string;channel:string;vendor:string;amount:number;documentRef:string;note:string;createdById:string;createdByName:string;createdAt:string};
type Capabilities={work:boolean;manage:boolean;actorId:string;actorName:string};
type ProposalDraft={id:string;title:string;campaign:string;month:string;channel:string;objective:string;startDate:string;endDate:string;requestedAmount:string;expectedLeads:string;expectedRevenue:string;justification:string;note:string};
type ExpenseDraft={proposalId:string;campaign:string;date:string;category:string;channel:string;vendor:string;amount:string;documentRef:string;note:string};
type Tab='overview'|'proposals'|'expenses';

const channels=['Facebook Ads','TikTok Ads','Google Ads','SEO / Content','KOL / KOC','Email / CRM','Sự kiện / Offline','Thiết kế / Sản xuất','Khác'];
const categories=['Chi phí quảng cáo','Sản xuất nội dung','Thiết kế','KOL / KOC','Công cụ / Phần mềm','Sự kiện','In ấn / POSM','Khác'];
const statusLabel:Record<ProposalStatus,string>={draft:'Nháp',pending:'Chờ duyệt',changes_requested:'Cần bổ sung',approved:'Đã duyệt',rejected:'Từ chối'};
const money=(value:number)=>new Intl.NumberFormat('vi-VN').format(Math.round(Number(value)||0))+'đ';
const currentMonth=()=>new Date().toISOString().slice(0,7);const today=()=>new Date().toISOString().slice(0,10);const num=(value:unknown)=>Math.max(0,Number(String(value??'').replace(/[^\d.-]/g,''))||0);
function blankProposal():ProposalDraft{return{id:'',title:'',campaign:'',month:currentMonth(),channel:channels[0],objective:'Tăng booking',startDate:today(),endDate:'',requestedAmount:'',expectedLeads:'',expectedRevenue:'',justification:'',note:''}}
function blankExpense():ExpenseDraft{return{proposalId:'',campaign:'',date:today(),category:categories[0],channel:channels[0],vendor:'',amount:'',documentRef:'',note:''}}

export function AdminMarketingBudget(){
 const[proposals,setProposals]=useState<Proposal[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[cap,setCap]=useState<Capabilities>({work:false,manage:false,actorId:'',actorName:''}),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[month,setMonth]=useState(currentMonth()),[tab,setTab]=useState<Tab>('overview'),[proposalOpen,setProposalOpen]=useState(false),[expenseOpen,setExpenseOpen]=useState(false),[proposalDraft,setProposalDraft]=useState<ProposalDraft>(blankProposal()),[expenseDraft,setExpenseDraft]=useState<ExpenseDraft>(blankExpense()),[selectedId,setSelectedId]=useState<string|null>(null);
 async function load(){setLoading(true);try{const res=await fetch('/api/admin/marketing-budget',{cache:'no-store'}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không đọc được ngân sách Marketing.');setProposals(Array.isArray(json.proposals)?json.proposals:[]);setExpenses(Array.isArray(json.expenses)?json.expenses:[]);setCap(json.capabilities||{work:false,manage:false,actorId:'',actorName:''})}catch(error){setMessage(error instanceof Error?error.message:'Không đọc được ngân sách Marketing.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function post(body:Record<string,unknown>){const res=await fetch('/api/admin/marketing-budget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),json=await res.json();if(!res.ok)throw new Error(json.error||'Không thể cập nhật ngân sách Marketing.');return json}
 const monthProposals=useMemo(()=>proposals.filter(item=>item.month===month).sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt)),[proposals,month]);const monthExpenses=useMemo(()=>expenses.filter(item=>item.month===month).sort((a,b)=>b.date.localeCompare(a.date)),[expenses,month]);
 const kpi=useMemo(()=>{const requested=monthProposals.filter(item=>item.status!=='rejected').reduce((sum,item)=>sum+Number(item.requestedAmount||0),0),approved=monthProposals.filter(item=>item.status==='approved').reduce((sum,item)=>sum+Number(item.approvedAmount||0),0),spent=monthExpenses.reduce((sum,item)=>sum+Number(item.amount||0),0);return{requested,approved,spent,remaining:approved-spent,pending:monthProposals.filter(item=>item.status==='pending').length}},[monthProposals,monthExpenses]);
 const selected=proposals.find(item=>item.id===selectedId)||null;const selectedSpent=selected?expenses.filter(item=>item.proposalId===selected.id).reduce((sum,item)=>sum+Number(item.amount||0),0):0;
 function openProposal(item?:Proposal){if(item)setProposalDraft({id:item.id,title:item.title,campaign:item.campaign,month:item.month,channel:item.channel,objective:item.objective,startDate:item.startDate,endDate:item.endDate,requestedAmount:String(item.requestedAmount),expectedLeads:String(item.expectedLeads),expectedRevenue:String(item.expectedRevenue),justification:item.justification,note:item.note});else setProposalDraft({...blankProposal(),month});setProposalOpen(true);setTab('proposals')}
 async function saveProposal(submit:boolean){try{await post({action:'saveProposal',...proposalDraft,requestedAmount:num(proposalDraft.requestedAmount),expectedLeads:num(proposalDraft.expectedLeads),expectedRevenue:num(proposalDraft.expectedRevenue),submit});setMessage(submit?'Đã gửi đề xuất ngân sách chờ duyệt.':'Đã lưu đề xuất production.');setProposalOpen(false);setProposalDraft(blankProposal());await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể lưu đề xuất.')}}
 async function decision(item:Proposal,kind:'approved'|'changes_requested'|'rejected'){try{if(kind==='approved'){const raw=prompt('Ngân sách được duyệt',String(item.requestedAmount));if(raw===null)return;const approvedAmount=num(raw);if(!approvedAmount)return setMessage('Ngân sách duyệt phải lớn hơn 0.');await post({action:'decision',id:item.id,decision:kind,approvedAmount})}else{const reason=prompt(kind==='rejected'?'Lý do từ chối':'Nội dung cần bổ sung',item.note||'');if(reason===null||!reason.trim())return;await post({action:'decision',id:item.id,decision:kind,reason:reason.trim()})}setMessage(kind==='approved'?'Đã duyệt ngân sách.':kind==='rejected'?'Đã từ chối đề xuất.':'Đã yêu cầu bổ sung.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể xử lý đề xuất.')}}
 function chooseProposal(id:string){const item=proposals.find(proposal=>proposal.id===id);setExpenseDraft(current=>({...current,proposalId:id,campaign:item?.campaign||current.campaign,channel:item?.channel||current.channel}))}
 async function saveExpense(){try{await post({action:'addExpense',...expenseDraft,amount:num(expenseDraft.amount)});setMessage('Đã ghi chi phí Marketing production.');setExpenseDraft(blankExpense());setExpenseOpen(false);await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể ghi chi phí.')}}
 async function removeExpense(item:Expense){if(!confirm(`Xóa chi phí ${money(item.amount)} · ${item.vendor}?`))return;try{await post({action:'deleteExpense',id:item.id});setMessage('Đã xóa khoản chi phí.');await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể xóa chi phí.')}}
 const approvedOptions=proposals.filter(item=>item.status==='approved').sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt));
 return <section className="admin-panel marketing-budget">
  <div className="admin-panel-head"><div><small>MARKETING & NGÂN SÁCH · PRODUCTION</small><h2>Đề xuất · Duyệt · Theo dõi chi phí</h2><p>Trạng thái duyệt và quyền xóa chi phí được kiểm soát trực tiếp ở server; shared-data cũ chỉ còn dùng để đọc tương thích.</p></div><div>{cap.work&&<button className="admin-primary" onClick={()=>openProposal()}>+ Đề xuất ngân sách</button>}{cap.work&&<button className="admin-secondary" onClick={()=>{setExpenseOpen(value=>!value);setTab('expenses')}}>+ Ghi chi phí</button>}</div></div>
  {message&&<p className="admin-api-note">{message}</p>}
  <div className="admin-list-toolbar"><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/><button className={tab==='overview'?'admin-primary':'admin-secondary'} onClick={()=>setTab('overview')}>Tổng quan</button><button className={tab==='proposals'?'admin-primary':'admin-secondary'} onClick={()=>setTab('proposals')}>Đề xuất ({monthProposals.length})</button><button className={tab==='expenses'?'admin-primary':'admin-secondary'} onClick={()=>setTab('expenses')}>Chi phí ({monthExpenses.length})</button><button className="admin-secondary" onClick={()=>void load()} disabled={loading}>↻ Tải lại</button></div>
  <div className="payment-kpis"><article><small>ĐỀ XUẤT</small><b>{money(kpi.requested)}</b></article><article><small>ĐÃ DUYỆT</small><b>{money(kpi.approved)}</b></article><article><small>ĐÃ CHI</small><b>{money(kpi.spent)}</b></article><article><small>CÒN LẠI</small><b>{money(kpi.remaining)}</b><span>{kpi.pending} đề xuất chờ duyệt</span></article></div>
  {proposalOpen&&<div className="receipt-form"><h3>{proposalDraft.id?'Cập nhật đề xuất':'Đề xuất ngân sách mới'}</h3><div className="receipt-grid"><label>Tên đề xuất<input value={proposalDraft.title} onChange={e=>setProposalDraft({...proposalDraft,title:e.target.value})}/></label><label>Chiến dịch<input value={proposalDraft.campaign} onChange={e=>setProposalDraft({...proposalDraft,campaign:e.target.value})}/></label><label>Tháng<input type="month" value={proposalDraft.month} onChange={e=>setProposalDraft({...proposalDraft,month:e.target.value})}/></label><label>Kênh<select value={proposalDraft.channel} onChange={e=>setProposalDraft({...proposalDraft,channel:e.target.value})}>{channels.map(item=><option key={item}>{item}</option>)}</select></label><label>Mục tiêu<input value={proposalDraft.objective} onChange={e=>setProposalDraft({...proposalDraft,objective:e.target.value})}/></label><label>Ngày bắt đầu<input type="date" value={proposalDraft.startDate} onChange={e=>setProposalDraft({...proposalDraft,startDate:e.target.value})}/></label><label>Ngày kết thúc<input type="date" value={proposalDraft.endDate} onChange={e=>setProposalDraft({...proposalDraft,endDate:e.target.value})}/></label><label>Ngân sách đề xuất<input inputMode="numeric" value={proposalDraft.requestedAmount} onChange={e=>setProposalDraft({...proposalDraft,requestedAmount:e.target.value})}/></label><label>Lead kỳ vọng<input inputMode="numeric" value={proposalDraft.expectedLeads} onChange={e=>setProposalDraft({...proposalDraft,expectedLeads:e.target.value})}/></label><label>Doanh thu kỳ vọng<input inputMode="numeric" value={proposalDraft.expectedRevenue} onChange={e=>setProposalDraft({...proposalDraft,expectedRevenue:e.target.value})}/></label><label>Lý do / kế hoạch<textarea value={proposalDraft.justification} onChange={e=>setProposalDraft({...proposalDraft,justification:e.target.value})}/></label><label>Ghi chú<textarea value={proposalDraft.note} onChange={e=>setProposalDraft({...proposalDraft,note:e.target.value})}/></label></div><div className="receipt-actions"><button className="admin-secondary" onClick={()=>void saveProposal(false)}>Lưu</button><button className="admin-primary" onClick={()=>void saveProposal(true)}>Lưu & trình duyệt</button><button className="admin-secondary" onClick={()=>setProposalOpen(false)}>Hủy</button></div></div>}
  {expenseOpen&&<div className="receipt-form"><h3>Ghi chi phí thực tế</h3><div className="receipt-grid"><label>Đề xuất đã duyệt<select value={expenseDraft.proposalId} onChange={e=>chooseProposal(e.target.value)}><option value="">{cap.manage?'Không thuộc đề xuất (Quản trị)':'Chọn đề xuất'}</option>{approvedOptions.map(item=><option key={item.id} value={item.id}>{item.campaign} · còn {money(Number(item.approvedAmount||0)-expenses.filter(x=>x.proposalId===item.id).reduce((s,x)=>s+Number(x.amount||0),0))}</option>)}</select></label><label>Ngày chi<input type="date" value={expenseDraft.date} onChange={e=>setExpenseDraft({...expenseDraft,date:e.target.value})}/></label><label>Chiến dịch<input value={expenseDraft.campaign} onChange={e=>setExpenseDraft({...expenseDraft,campaign:e.target.value})}/></label><label>Hạng mục<select value={expenseDraft.category} onChange={e=>setExpenseDraft({...expenseDraft,category:e.target.value})}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Kênh<select value={expenseDraft.channel} onChange={e=>setExpenseDraft({...expenseDraft,channel:e.target.value})}>{channels.map(item=><option key={item}>{item}</option>)}</select></label><label>Nhà cung cấp<input value={expenseDraft.vendor} onChange={e=>setExpenseDraft({...expenseDraft,vendor:e.target.value})}/></label><label>Số tiền<input inputMode="numeric" value={expenseDraft.amount} onChange={e=>setExpenseDraft({...expenseDraft,amount:e.target.value})}/></label><label>Chứng từ<input value={expenseDraft.documentRef} onChange={e=>setExpenseDraft({...expenseDraft,documentRef:e.target.value})}/></label><label>Ghi chú<input value={expenseDraft.note} onChange={e=>setExpenseDraft({...expenseDraft,note:e.target.value})}/></label></div><div className="receipt-actions"><button className="admin-primary" onClick={()=>void saveExpense()}>Ghi chi phí</button><button className="admin-secondary" onClick={()=>setExpenseOpen(false)}>Hủy</button></div></div>}
  {loading?<div className="admin-empty-state">Đang tải ngân sách Marketing production...</div>:tab==='overview'?<div className="receipt-list">{monthProposals.slice(0,8).map(item=><article key={item.id} onClick={()=>setSelectedId(item.id)}><div><b>{item.campaign}</b><span>{item.title} · {item.channel}</span></div><strong>{money(item.requestedAmount)}</strong><div><b>{statusLabel[item.status]}</b><span>{item.status==='approved'?`Duyệt ${money(item.approvedAmount)}`:`Tạo bởi ${item.createdByName}`}</span></div></article>)}{!monthProposals.length&&<div className="admin-empty-state">Tháng này chưa có đề xuất.</div>}</div>:tab==='proposals'?<div className="receipt-list">{monthProposals.map(item=><article key={item.id}><div><b>{item.campaign}</b><span>{item.title} · {item.channel}</span></div><strong>{money(item.requestedAmount)}</strong><div><b>{statusLabel[item.status]}</b><span>{item.createdByName}</span></div><div className="receipt-actions">{['draft','changes_requested'].includes(item.status)&&<button className="admin-secondary" onClick={()=>openProposal(item)}>Sửa</button>}{cap.manage&&item.status==='pending'&&<><button className="admin-primary" onClick={()=>void decision(item,'approved')}>Duyệt</button><button className="admin-secondary" onClick={()=>void decision(item,'changes_requested')}>Cần bổ sung</button><button className="admin-secondary" onClick={()=>void decision(item,'rejected')}>Từ chối</button></>}<button className="admin-secondary" onClick={()=>setSelectedId(item.id)}>Chi tiết</button></div></article>)}{!monthProposals.length&&<div className="admin-empty-state">Chưa có đề xuất.</div>}</div>:<div className="receipt-list">{monthExpenses.map(item=><article key={item.id}><div><b>{item.campaign}</b><span>{item.date} · {item.category}</span></div><strong>{money(item.amount)}</strong><div><b>{item.vendor}</b><span>{item.channel}{item.documentRef?` · ${item.documentRef}`:''}</span></div><div><b>{item.createdByName}</b><span>{item.note||'Không có ghi chú'}</span></div>{cap.manage&&<button className="admin-secondary" onClick={()=>void removeExpense(item)}>Xóa</button>}</article>)}{!monthExpenses.length&&<div className="admin-empty-state">Chưa có chi phí Marketing trong tháng.</div>}</div>}
  {selected&&<details open className="admin-api-note"><summary>{selected.title} · {statusLabel[selected.status]}</summary><p>Chiến dịch: <b>{selected.campaign}</b> · Đề xuất {money(selected.requestedAmount)}{selected.status==='approved'?` · Duyệt ${money(selected.approvedAmount)} · Đã chi ${money(selectedSpent)}`:''}</p><p>{selected.justification}</p>{selected.note&&<p>Ghi chú: {selected.note}</p>}<div>{(selected.audit||[]).slice().reverse().slice(0,20).map(item=><p key={item.id}><small>{new Date(item.at).toLocaleString('vi-VN')} · {item.byName}</small><br/>{item.action}{item.detail?` · ${item.detail}`:''}</p>)}</div></details>}
 </section>
}
