'use client';

import {useEffect,useMemo,useState} from 'react';

type StaffRole='admin'|'sales'|'content'|'operations'|'accounting';
type Department='marketing'|'resa'|'product'|'sales'|'accounting';
type StaffStatus='active'|'inactive';
type Staff={id:string;name:string;email:string;phone:string;role:StaffRole;department:Department;status:StaffStatus;permissions:string[];note:string;createdAt:string};
const KEY='tn_admin_staff_v1';
const roleLabels:Record<StaffRole,string>={admin:'Quản trị viên',sales:'Nhân viên Sale',content:'Nội dung / Marketing',operations:'Điều hành',accounting:'Kế toán'};
const departmentLabels:Record<Department,string>={marketing:'Marketing',resa:'Resa / Đặt phòng',product:'Sản phẩm',sales:'Kinh doanh',accounting:'Kế toán'};
const permissionOptions=[['dashboard','Tổng quan'],['customers','Khách hàng / CRM'],['bookings','Đơn đặt dịch vụ'],['email','Email & Marketing'],['products','Sản phẩm'],['rates','Lịch giá & tồn phòng'],['tours','Tour du lịch'],['stays','Villa / Khách sạn'],['cruises','Du thuyền'],['content','Bài viết / Cẩm nang'],['media','Media'],['settings','Cài đặt']];
const defaults:Record<StaffRole,string[]>={admin:permissionOptions.map(([id])=>id),sales:['dashboard','customers','bookings','email'],content:['dashboard','email','content','media','tours','products'],operations:['dashboard','bookings','products','rates','tours','stays','cruises'],accounting:['dashboard','bookings','customers']};
const defaultDepartment:Record<StaffRole,Department>={admin:'sales',sales:'sales',content:'marketing',operations:'resa',accounting:'accounting'};
const blank=():Staff=>({id:'',name:'',email:'',phone:'',role:'sales',department:'sales',status:'active',permissions:[...defaults.sales],note:'',createdAt:''});
function normalizeStaff(raw:any):Staff{return {...blank(),...raw,department:raw?.department||defaultDepartment[raw?.role as StaffRole]||'sales'}}
function read():Staff[]{try{return (JSON.parse(localStorage.getItem(KEY)||'[]') as any[]).map(normalizeStaff)}catch{return []}}
function save(items:Staff[]){localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new Event('tn-staff-updated'))}

export function AdminStaffManager(){
 const[items,setItems]=useState<Staff[]>([]);const[editing,setEditing]=useState<Staff|null>(null);const[q,setQ]=useState('');const[dept,setDept]=useState('');const[msg,setMsg]=useState('');
 useEffect(()=>{const load=()=>setItems(read());load();window.addEventListener('tn-staff-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('tn-staff-updated',load);window.removeEventListener('storage',load)}},[]);
 const visible=useMemo(()=>{const needle=q.trim().toLowerCase();return items.filter(x=>(!dept||x.department===dept)&&(!needle||`${x.name} ${x.email} ${x.phone} ${roleLabels[x.role]} ${departmentLabels[x.department]}`.toLowerCase().includes(needle)))},[items,q,dept]);
 const startNew=()=>{setEditing(blank());setMsg('')};const edit=(staff:Staff)=>{setEditing({...staff,permissions:[...staff.permissions]});setMsg('')};
 const changeRole=(role:StaffRole)=>setEditing(x=>x?{...x,role,department:defaultDepartment[role],permissions:[...defaults[role]]}:x);
 const togglePermission=(id:string)=>setEditing(x=>x?{...x,permissions:x.permissions.includes(id)?x.permissions.filter(p=>p!==id):[...x.permissions,id]}:x);
 const persist=()=>{if(!editing)return;if(editing.name.trim().length<2){setMsg('Vui lòng nhập họ tên nhân viên.');return}if(editing.email&&!/^\S+@\S+\.\S+$/.test(editing.email)){setMsg('Email nhân viên chưa đúng định dạng.');return}const next={...editing,id:editing.id||`staff_${Date.now()}`,createdAt:editing.createdAt||new Date().toISOString()};const list=items.some(x=>x.id===next.id)?items.map(x=>x.id===next.id?next:x):[next,...items];save(list);setItems(list);setEditing(null);setMsg('Đã lưu nhân viên và phòng ban.')};
 const remove=(staff:Staff)=>{if(!confirm(`Xóa nhân viên “${staff.name}”?`))return;const list=items.filter(x=>x.id!==staff.id);save(list);setItems(list)};
 const toggleStatus=(staff:Staff)=>{const list=items.map(x=>x.id===staff.id?{...x,status:(x.status==='active'?'inactive':'active') as StaffStatus}:x);save(list);setItems(list)};
 const counts=useMemo(()=>Object.keys(departmentLabels).reduce((acc,k)=>({...acc,[k]:items.filter(x=>x.department===k&&x.status==='active').length}),{} as Record<string,number>),[items]);
 return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Nhân viên & phòng ban</h2><p>Gán mỗi nhân viên vào Marketing, Resa, Sản phẩm, Kinh doanh hoặc Kế toán để tổ chức công việc và chat nội bộ theo bộ phận.</p></div><button type="button" className="admin-primary" onClick={startNew}>+ Tạo nhân viên</button></div>
  <div className="staff-department-summary">{Object.entries(departmentLabels).map(([id,label])=><button type="button" key={id} onClick={()=>setDept(dept===id?'':id)} className={dept===id?'active':''}><b>{label}</b><span>{counts[id]||0} đang hoạt động</span></button>)}</div>
  {msg&&<p className="admin-api-note">{msg}</p>}
  {!editing&&<><div className="admin-form-row"><label>Tìm nhân viên<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tên, email, số điện thoại, vai trò, phòng ban"/></label><label>Phòng ban<select value={dept} onChange={e=>setDept(e.target.value)}><option value="">Tất cả phòng ban</option>{Object.entries(departmentLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></div><div className="admin-customer-grid">{visible.length?visible.map(staff=><article className="admin-customer-card" key={staff.id}><div><b>{staff.name}</b><span>{staff.email||'Chưa có email'}</span><small>{staff.phone||'Chưa có số điện thoại'}</small></div><div><b>{departmentLabels[staff.department]}</b><small>{roleLabels[staff.role]} · {staff.permissions.length} quyền</small></div><div><span className={staff.status==='active'?'status-confirmed':'status-cancelled'}>{staff.status==='active'?'Đang hoạt động':'Đã khóa'}</span><small>Tạo {new Date(staff.createdAt).toLocaleDateString('vi-VN')}</small></div><div className="pm-actions"><button type="button" onClick={()=>edit(staff)}>Sửa</button><button type="button" onClick={()=>toggleStatus(staff)}>{staff.status==='active'?'Khóa':'Mở lại'}</button><button type="button" className="danger-action" onClick={()=>remove(staff)}>Xóa</button></div></article>):<div className="admin-empty-state"><b>Chưa có nhân viên phù hợp</b></div>}</div></>}
  {editing&&<div className="tour-editor-grid"><label>Họ và tên<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Nguyễn Văn A"/></label><label>Phòng ban<select value={editing.department} onChange={e=>setEditing({...editing,department:e.target.value as Department})}>{Object.entries(departmentLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Vai trò<select value={editing.role} onChange={e=>changeRole(e.target.value as StaffRole)}>{Object.entries(roleLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>Email<input type="email" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})} placeholder="nhanvien@happygo.vn"/></label><label>Số điện thoại<input value={editing.phone} onChange={e=>setEditing({...editing,phone:e.target.value})} placeholder="09xx xxx xxx"/></label><label>Trạng thái<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as StaffStatus})}><option value="active">Đang hoạt động</option><option value="inactive">Tạm khóa</option></select></label><label className="span-2">Ghi chú<textarea rows={3} value={editing.note} onChange={e=>setEditing({...editing,note:e.target.value})} placeholder="Khu vực phụ trách, ca làm việc, ghi chú nội bộ..."/></label><div className="span-2"><b>Quyền truy cập</b><p style={{fontSize:11,color:'#71869a'}}>Có thể bật/tắt từng quyền cho nhân viên.</p><div className="quick-create-grid">{permissionOptions.map(([id,label])=><button type="button" key={id} onClick={()=>togglePermission(id)} className={editing.permissions.includes(id)?'admin-primary':''}><b>{editing.permissions.includes(id)?'✓ ':'○ '}{label}</b><span>{editing.permissions.includes(id)?'Được phép truy cập':'Không có quyền'}</span></button>)}</div></div><div className="span-2 editor-actions"><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button type="button" className="admin-primary" onClick={persist}>Lưu nhân viên</button></div></div>}
 </section>
}
