'use client';

import {useEffect,useState} from 'react';
import {AdminMediaPicker} from '@/components/AdminMediaLibrary';

type Day={title:string;morning:string;afternoon:string;evening:string;meals:string};
type Tour={id:string;name:string;cover:string;category:string;duration:string;departure:string;airline:string;route:string;transport:string;summary:string;status:string;price:string;salePrice:string;childPrice:string;singleCharge:string;departures:string;gallery:string;highlights:string;itinerary:string;days:Day[];included:string;excluded:string;policies:string;promotion:string;rating:string;reviewCount:string;faq:string;seoTitle:string;seoDescription:string;slug:string};
type ApiResult={ok?:boolean;items?:Tour[];item?:Tour;error?:string};

const KEY='tn_cms_tours_v3';
const newDay=(title=''):Day=>({title,morning:'',afternoon:'',evening:'',meals:''});
const blank:Tour={id:'',name:'',cover:'',category:'Tour Trung Quốc',duration:'',departure:'Hà Nội',airline:'',route:'',transport:'Máy bay, Ô tô',summary:'',status:'draft',price:'',salePrice:'',childPrice:'',singleCharge:'',departures:'',gallery:'',highlights:'',itinerary:'',days:[newDay()],included:'',excluded:'',policies:'',promotion:'',rating:'',reviewCount:'',faq:'',seoTitle:'',seoDescription:'',slug:''};
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const normalize=(x:any):Tour=>({...blank,...x,cover:x?.cover||'',days:Array.isArray(x?.days)&&x.days.length?x.days:[newDay()]});
const parseQuick=(text:string):Day[]=>{const chunks=text.replace(/\r/g,'').split(/\n(?=\s*(?:ngày|day)\s*\d+)/i).map(x=>x.trim()).filter(Boolean);return chunks.map((chunk,index)=>{const ls=chunk.split('\n').map(x=>x.trim()).filter(Boolean);const first=ls.shift()||'';const d=newDay(first.replace(/^\s*(?:ngày|day)\s*\d+\s*[:.\-–]?\s*/i,'').trim()||`Ngày ${index+1}`);const free:string[]=[];for(const line of ls){const m=line.match(/^(sáng|buổi sáng|chiều|buổi chiều|tối|buổi tối|bữa ăn|ăn)\s*[:\-–]\s*(.*)$/i);if(!m){free.push(line);continue}const k=m[1].toLowerCase();if(k.includes('sáng'))d.morning=m[2];else if(k.includes('chiều'))d.afternoon=m[2];else if(k.includes('tối'))d.evening=m[2];else d.meals=m[2]}if(free.length&&!d.morning)d.morning=free.join('\n');return d})};
const itineraryText=(days:Day[])=>days.map((d,i)=>[`Ngày ${i+1}: ${d.title}`,d.morning&&`Sáng: ${d.morning}`,d.afternoon&&`Chiều: ${d.afternoon}`,d.evening&&`Tối: ${d.evening}`,d.meals&&`Bữa ăn: ${d.meals}`].filter(Boolean).join('\n')).join('\n\n');
function mirror(items:Tour[]){try{localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new Event('tn-tours-updated'));window.dispatchEvent(new Event('storage'))}catch{}}
async function request(body?:unknown){const response=await fetch(body?'/api/admin/cms-content':'/api/admin/cms-content?kind=tours',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await response.json().catch(()=>({})) as ApiResult;if(!response.ok)throw new Error(response.status===401?'Phiên quản trị đã hết hạn.':response.status===403?'Tài khoản chưa có quyền quản lý Tour.':data.error||'Không thể xử lý Tour production.');return data}

export function AdminTourEditorSimple(){
 const[items,setItems]=useState<Tour[]>([]);const[mode,setMode]=useState<'list'|'edit'>('list');const[form,setForm]=useState<Tour>(blank);const[msg,setMsg]=useState('');const[quick,setQuick]=useState('');const[quickOpen,setQuickOpen]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{const data=await request(),next=(Array.isArray(data.items)?data.items:[]).map(normalize);setItems(next);mirror(next)}catch(error){setMsg(error instanceof Error?error.message:'Không đọc được Tour production.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const set=<K extends keyof Tour>(k:K,v:Tour[K])=>setForm(f=>({...f,[k]:v}));
 const setDay=(i:number,k:keyof Day,v:string)=>setForm(f=>({...f,days:f.days.map((d,n)=>n===i?{...d,[k]:v}:d)}));
 const edit=(t:Tour)=>{setForm(normalize(t));setQuick(itineraryText(normalize(t).days));setMode('edit');setMsg('');setQuickOpen(false)};
 const add=()=>{setForm({...blank,days:[newDay()]});setQuick('');setMode('edit');setMsg('');setQuickOpen(false)};
 const remove=async(t:Tour)=>{if(!confirm(`Xóa tour “${t.name}” khỏi production?`))return;setBusy(true);setMsg('');try{const data=await request({kind:'tours',action:'delete',id:t.id}),next=(Array.isArray(data.items)?data.items:items.filter(x=>x.id!==t.id)).map(normalize);setItems(next);mirror(next);setMsg(`✓ Đã xóa ${t.name} khỏi production.`);setMode('list')}catch(error){setMsg(error instanceof Error?error.message:'Không xóa được Tour production.')}finally{setBusy(false)}};
 const duplicate=(t:Tour)=>{const copy={...normalize(t),id:`tour_${Date.now()}`,name:`${t.name} - Bản sao`,slug:`${t.slug||slugify(t.name)}-copy`,status:'draft',days:t.days.map(d=>({...d}))};setForm(copy);setQuick(itineraryText(copy.days));setMode('edit');setMsg('Bản sao chưa được lưu production.');setQuickOpen(false)};
 const addDay=()=>setForm(f=>({...f,days:[...f.days,newDay()]}));
 const duplicateDay=(i:number)=>setForm(f=>({...f,days:[...f.days.slice(0,i+1),{...f.days[i]},...f.days.slice(i+1)]}));
 const deleteDay=(i:number)=>setForm(f=>({...f,days:f.days.length===1?[newDay()]:f.days.filter((_,n)=>n!==i)}));
 const applyQuick=()=>{const parsed=parseQuick(quick);if(!parsed.length){setMsg('Không nhận được lịch trình. Hãy bắt đầu bằng “Ngày 1: ...”.');return}setForm(f=>({...f,days:parsed}));setQuickOpen(false);setMsg(`Đã tách thành ${parsed.length} ngày. Kiểm tra các ô bên dưới rồi đăng.`)};
 const save=async(status:'draft'|'published')=>{if(!form.name.trim()){setMsg('Vui lòng nhập tên Tour.');return}const days=form.days,next={...form,id:form.id||`tour_${Date.now()}`,slug:form.slug||slugify(form.name),status,itinerary:itineraryText(days),days};setBusy(true);setMsg('');try{const data=await request({kind:'tours',action:'save',item:next}),list=(Array.isArray(data.items)?data.items:(items.some(x=>x.id===next.id)?items.map(x=>x.id===next.id?next:x):[next,...items])).map(normalize);setItems(list);mirror(list);setForm(normalize(data.item||next));setMsg(status==='published'?'✓ Đã cập nhật và đăng Tour trên production.':'✓ Đã lưu bản nháp trên production.')}catch(error){setMsg(error instanceof Error?error.message:'Không lưu được Tour production.')}finally{setBusy(false)}};
 if(mode==='list')return <section className="admin-panel tour-editor-admin"><div className="admin-panel-head"><div><small>CMS · PRODUCTION</small><h2>Tour du lịch</h2><p>Tour được đọc và ghi trực tiếp trên server; cache trình duyệt chỉ phục vụ giao diện public.</p></div><button type="button" className="admin-primary" onClick={add}>+ Thêm Tour mới</button></div>{msg&&<p className="admin-api-note">{msg}</p>}<div className="pm-list">{loading?<div className="unit-empty">Đang tải Tour production...</div>:items.map(t=><article key={t.id}>{t.cover?<img src={t.cover} alt={t.name}/>:<div className="pm-placeholder">✈</div>}<div className="pm-info"><b>{t.name}</b><span>{t.category} · {t.duration||'Chưa nhập thời lượng'}</span><small>{t.route||'Chưa nhập tuyến'}</small></div><strong>{t.salePrice||t.price||'Liên hệ'}</strong><em className={`pm-status ${t.status}`}>{t.status==='published'?'Đang bán':t.status==='hidden'?'Đang ẩn':'Bản nháp'}</em><div className="pm-actions"><button type="button" onClick={()=>edit(t)}>Sửa</button><button type="button" onClick={()=>duplicate(t)}>Nhân bản</button><button type="button" className="danger-action" disabled={busy} onClick={()=>void remove(t)}>Xóa</button></div></article>)}</div></section>;
 return <section className="admin-panel tour-editor-admin simple-tour-editor"><div className="admin-panel-head"><div><button type="button" className="editor-back" onClick={()=>setMode('list')}>← Danh sách Tour</button><h2>{form.id?'Chỉnh sửa Tour':'Thêm Tour mới'}</h2><p>{msg||'Nhập từ trên xuống dưới rồi bấm Đăng Tour.'}</p></div><div><button type="button" disabled={busy} onClick={()=>void save('draft')}>Lưu nháp</button><button type="button" className="admin-primary" disabled={busy} onClick={()=>void save('published')}>{busy?'Đang lưu...':'Đăng Tour'}</button></div></div>
 <section className="pm-section"><h3>1. Thông tin Tour</h3><div className="tour-editor-grid"><label className="span-2">Tên Tour<input value={form.name} onChange={e=>{const old=form.name;set('name',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}} placeholder="Ví dụ: Bắc Kinh - Thượng Hải - Hàng Châu"/></label><label>Danh mục<select value={form.category} onChange={e=>set('category',e.target.value)}><option>Tour Trung Quốc</option><option>Tour trong nước</option><option>Tour Hàn Quốc</option><option>Tour Nhật Bản</option><option>Tour Đông Nam Á</option><option>Tour Châu Âu</option><option>Tour Mỹ</option><option>Tour Úc</option></select></label><label>Thời lượng<input value={form.duration} onChange={e=>set('duration',e.target.value)} placeholder="7N6Đ"/></label><label>Khởi hành từ<input value={form.departure} onChange={e=>set('departure',e.target.value)} placeholder="Hà Nội"/></label><label>Hãng bay<input value={form.airline} onChange={e=>set('airline',e.target.value)} placeholder="Vietjet Air"/></label><label className="span-2">Tuyến điểm đến<input value={form.route} onChange={e=>set('route',e.target.value)} placeholder="Hà Nội - Bắc Kinh - Hàng Châu - Thượng Hải"/></label><label className="span-2">Mô tả ngắn<textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)} placeholder="Mô tả ngắn để hiển thị ngoài danh sách Tour"/></label></div></section>
 <section className="pm-section"><h3>2. Giá & ngày khởi hành</h3><div className="tour-editor-grid"><label>Giá gốc<input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="21.680.000đ"/></label><label>Giá bán từ<input value={form.salePrice} onChange={e=>set('salePrice',e.target.value)} placeholder="21.180.000đ"/></label><label>Giá trẻ em<input value={form.childPrice} onChange={e=>set('childPrice',e.target.value)} placeholder="Theo độ tuổi"/></label><label>Phụ thu phòng đơn<input value={form.singleCharge} onChange={e=>set('singleCharge',e.target.value)} placeholder="3.000.000đ"/></label><label className="span-2">Ngày khởi hành — mỗi dòng một ngày<textarea rows={6} value={form.departures} onChange={e=>set('departures',e.target.value)} placeholder={'06/09/2026\n13/09/2026\n04/10/2026\n18/10/2026'}/></label><p className="span-2 pm-section-note">Ngoài website chỉ cho khách chọn đúng các ngày bạn nhập ở đây.</p></div></section>
 <section className="pm-section"><div className="tour-days-head"><div><h3>3. Lịch trình từng ngày</h3><p>Mỗi ngày là một khối riêng. Chỉ cần nhập nội dung có phát sinh.</p></div><div><button type="button" onClick={()=>setQuickOpen(v=>!v)}>📋 Dán lịch trình có sẵn</button><button type="button" className="admin-primary" onClick={addDay}>+ Thêm ngày</button></div></div>{quickOpen&&<div className="tour-quick-import"><textarea rows={14} value={quick} onChange={e=>setQuick(e.target.value)} placeholder={'Ngày 1: Hà Nội - Bắc Kinh\nSáng: Tập trung tại sân bay\nChiều: Bay đi Bắc Kinh\nTối: Nhận phòng khách sạn\nBữa ăn: Tối\n\nNgày 2: Vạn Lý Trường Thành\nSáng: Tham quan...'} /><div><button type="button" className="admin-primary" onClick={applyQuick}>Tách thành từng ngày</button></div></div>}
 <div className="simple-tour-days">{form.days.map((d,i)=><article className="tour-day-card" key={i}><div className="tour-day-title"><div><b>Ngày {i+1}</b><small>{d.title||'Chưa nhập tiêu đề ngày'}</small></div><div><button type="button" onClick={()=>duplicateDay(i)}>Nhân bản</button><button type="button" className="danger-action" onClick={()=>deleteDay(i)}>Xóa</button></div></div><label>Tiêu đề ngày<input value={d.title} onChange={e=>setDay(i,'title',e.target.value)} placeholder="Ví dụ: Hà Nội - Bắc Kinh"/></label><div className="tour-day-grid"><label>🌅 Buổi sáng<textarea rows={3} value={d.morning} onChange={e=>setDay(i,'morning',e.target.value)} placeholder="Ăn sáng, khởi hành tham quan..."/></label><label>☀️ Buổi chiều<textarea rows={3} value={d.afternoon} onChange={e=>setDay(i,'afternoon',e.target.value)} placeholder="Tham quan, di chuyển..."/></label><label>🌙 Buổi tối<textarea rows={3} value={d.evening} onChange={e=>setDay(i,'evening',e.target.value)} placeholder="Ăn tối, nhận phòng, tự do..."/></label><label>🍽 Bữa ăn<input value={d.meals} onChange={e=>setDay(i,'meals',e.target.value)} placeholder="Sáng, Trưa, Tối"/></label></div></article>)}</div><button type="button" className="admin-primary" onClick={addDay}>+ Thêm ngày tiếp theo</button></section>
 <section className="pm-section"><h3>4. Ảnh Tour</h3><div className="media-product-grid"><div><b>Ảnh đại diện</b><AdminMediaPicker value={form.cover} onChange={v=>set('cover',v)} label="Chọn ảnh đại diện"/></div><div><b>Album</b><AdminMediaPicker multiple value={form.gallery} onChange={v=>set('gallery',v)} label="Chọn ảnh Album"/></div></div></section>
 <section className="pm-section"><h3>5. Dịch vụ & nội dung bán hàng</h3><div className="tour-editor-grid"><label>Điểm nổi bật<textarea rows={7} value={form.highlights} onChange={e=>set('highlights',e.target.value)} placeholder="Mỗi dòng một điểm nổi bật"/></label><label>Ưu đãi<textarea rows={7} value={form.promotion} onChange={e=>set('promotion',e.target.value)}/></label><label>Giá bao gồm<textarea rows={8} value={form.included} onChange={e=>set('included',e.target.value)}/></label><label>Không bao gồm<textarea rows={8} value={form.excluded} onChange={e=>set('excluded',e.target.value)}/></label><label className="span-2">Chính sách<textarea rows={8} value={form.policies} onChange={e=>set('policies',e.target.value)}/></label></div></section>
 <section className="pm-section"><h3>6. SEO (không bắt buộc)</h3><div className="tour-editor-grid"><label className="span-2">SEO Title<input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></label><label className="span-2">Meta description<textarea rows={3} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></label><label className="span-2">Slug<input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></label></div></section>
 <div className="tour-editor-publish-bottom"><button type="button" disabled={busy} onClick={()=>void save('draft')}>Lưu nháp</button><button type="button" className="admin-primary" disabled={busy} onClick={()=>void save('published')}>{busy?'Đang lưu...':'✓ Đăng Tour'}</button></div></section>;
}
