'use client';

import {useEffect,useMemo,useRef,useState} from 'react';

export type MediaImage={id:string;url:string;title:string;createdAt:string};
export const MEDIA_KEY='tn_cms_media_images_v2';
const LEGACY_KEY='tn_cms_media_v1';

function readMedia():MediaImage[]{try{const current=JSON.parse(localStorage.getItem(MEDIA_KEY)||'[]');if(Array.isArray(current)&&current.length)return current;const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||'[]');if(Array.isArray(legacy))return legacy.filter((x:any)=>x?.type!=='video'&&x?.url).map((x:any)=>({id:x.id||`media_${Date.now()}`,url:x.url,title:x.title||'Ảnh',createdAt:x.createdAt||''}))}catch{}return []}
function writeMedia(items:MediaImage[]){try{localStorage.setItem(MEDIA_KEY,JSON.stringify(items));window.dispatchEvent(new Event('tn-media-updated'));return true}catch{return false}}
async function compressImage(file:File):Promise<string>{const source=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error);r.readAsDataURL(file)});const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=reject;el.src=source});const max=1200;let w=img.naturalWidth,h=img.naturalHeight;if(Math.max(w,h)>max){const scale=max/Math.max(w,h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)return source;ctx.drawImage(img,0,0,w,h);return canvas.toDataURL('image/jpeg',.72)}

export function AdminMediaPicker({value,onChange,multiple=false,label='Chọn ảnh từ thư viện'}:{value:string;onChange:(value:string)=>void;multiple?:boolean;label?:string}){
 const [items,setItems]=useState<MediaImage[]>([]);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const inputRef=useRef<HTMLInputElement|null>(null);const selected=useMemo(()=>new Set((multiple?value.split(/\n+/):[value]).map(x=>x.trim()).filter(Boolean)),[value,multiple]);const load=()=>setItems(readMedia());useEffect(()=>{load();const fn=()=>load();window.addEventListener('tn-media-updated',fn);return()=>window.removeEventListener('tn-media-updated',fn)},[]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setMsg('');try{const next=[...readMedia()];const addedUrls:string[]=[];for(const file of Array.from(files)){if(!file.type.startsWith('image/'))continue;if(file.size>12*1024*1024){setMsg(`Bỏ qua ${file.name}: ảnh lớn hơn 12MB.`);continue}const url=await compressImage(file);next.unshift({id:`img_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,url,title:file.name.replace(/\.[^.]+$/,''),createdAt:new Date().toLocaleString('vi-VN')});addedUrls.push(url)}if(!writeMedia(next)){setMsg('Bộ nhớ ảnh demo trên trình duyệt đã đầy. Hãy xóa bớt ảnh cũ hoặc chờ chuyển sang hosting để lưu ảnh trên server.');return}setItems(next);if(addedUrls.length){if(multiple){const existing=(value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);onChange([...new Set([...existing,...addedUrls])].join('\n'));setOpen(true)}else{onChange(addedUrls[0]);setOpen(false)}setMsg(`Đã tải và chọn ${addedUrls.length} ảnh.`)}else setMsg('Không có ảnh hợp lệ để tải.')}catch{setMsg('Không thể xử lý ảnh. Hãy thử ảnh JPG/PNG khác.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 function choose(url:string){if(multiple){const values=[...selected];const next=selected.has(url)?values.filter(x=>x!==url):[...values,url];onChange(next.join('\n'))}else{onChange(url);setOpen(false)}}const preview=(multiple?value.split(/\n+/):[value]).map(x=>x.trim()).filter(Boolean);
 return <div className="media-picker"><div className="media-picker-actions"><button type="button" onClick={()=>setOpen(v=>!v)}>▧ {label}</button><label className="media-upload-btn">⬆ {busy?'Đang tải...':'Tải ảnh lên'}<input ref={inputRef} type="file" accept="image/*" multiple={multiple} onChange={e=>upload(e.target.files)} disabled={busy}/></label></div>{msg&&<small className="media-picker-msg">{msg}</small>}{preview.length>0&&<div className="media-selected-preview">{preview.slice(0,multiple?8:1).map((src,i)=><div key={`${src.slice(0,30)}_${i}`}><img src={src} alt="Ảnh đã chọn"/><button type="button" onClick={()=>multiple?onChange(preview.filter((_,n)=>n!==i).join('\n')):onChange('')}>×</button></div>)}</div>}{open&&<div className="media-picker-library"><div className="media-picker-head"><b>Thư viện ảnh</b><span>{items.length} ảnh</span></div>{items.length?<div className="media-picker-grid">{items.map(item=><button type="button" key={item.id} className={selected.has(item.url)?'selected':''} onClick={()=>choose(item.url)}><img src={item.url} alt={item.title}/><span>{item.title}</span><i>{selected.has(item.url)?'✓':''}</i></button>)}</div>:<div className="unit-empty">Chưa có ảnh. Bấm “Tải ảnh lên” để thêm ảnh từ điện thoại hoặc máy tính.</div>}{multiple&&<button type="button" className="admin-primary media-picker-done" onClick={()=>setOpen(false)}>Xong ({selected.size} ảnh)</button>}</div>}</div>
}

export function AdminMediaManager(){const [items,setItems]=useState<MediaImage[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const ref=useRef<HTMLInputElement|null>(null);const load=()=>setItems(readMedia());useEffect(()=>{load()},[]);async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setMsg('');try{const next=[...readMedia()];let added=0;for(const file of Array.from(files)){if(!file.type.startsWith('image/'))continue;if(file.size>12*1024*1024){setMsg(`Bỏ qua ${file.name}: ảnh lớn hơn 12MB.`);continue}next.unshift({id:`img_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,url:await compressImage(file),title:file.name.replace(/\.[^.]+$/,''),createdAt:new Date().toLocaleString('vi-VN')});added++}if(!writeMedia(next)){setMsg('Bộ nhớ ảnh demo trên trình duyệt đã đầy. Hãy xóa bớt ảnh cũ. Khi website lên hosting, ảnh sẽ được lưu trên server/cloud.');return}setItems(next);setMsg(added?`Đã tải ${added} ảnh.`:'Không có ảnh hợp lệ để tải.')}catch{setMsg('Không thể tải ảnh. Hãy thử JPG/PNG khác.')}finally{setBusy(false);if(ref.current)ref.current.value=''}}function remove(id:string){if(!confirm('Xóa ảnh này khỏi thư viện?'))return;const next=items.filter(x=>x.id!==id);if(!writeMedia(next)){setMsg('Không thể cập nhật thư viện ảnh.');return}setItems(next)}return <section className="admin-panel"><div className="admin-panel-head"><div><h2>Thư viện ảnh</h2><p>Tải ảnh trực tiếp từ máy/điện thoại. Ảnh được nén tự động để bản demo GitHub Pages nhẹ hơn.</p></div><label className="admin-primary media-upload-main">⬆ {busy?'Đang tải ảnh...':'Tải nhiều ảnh'}<input ref={ref} type="file" accept="image/*" multiple onChange={e=>upload(e.target.files)} disabled={busy}/></label></div>{msg&&<p className="cms-message">{msg}</p>}<div className="media-library-grid">{items.map(item=><article key={item.id}><img src={item.url} alt={item.title}/><div><b>{item.title}</b><small>{item.createdAt}</small><button type="button" className="danger-action" onClick={()=>remove(item.id)}>Xóa ảnh</button></div></article>)}{!items.length&&<div className="unit-empty">Chưa có ảnh trong thư viện.</div>}</div></section>}
