'use client';

import {useEffect,useMemo,useState} from 'react';
import {hasPermission,isAdminStaff,isOwner,money,readCurrentStaff,type AdminStaff} from '@/components/AdminSalesAccess';

type ProposalStatus='draft'|'pending'|'changes_requested'|'approved'|'rejected';
type Audit={id:string;at:string;byId:string;byName:string;action:string;detail?:string};
type Proposal={id:string;title:string;campaign:string;month:string;channel:string;objective:string;startDate:string;endDate:string;requestedAmount:number;approvedAmount:number;expectedLeads:number;expectedRevenue:number;justification:string;note:string;status:ProposalStatus;createdById:string;createdByName:string;createdAt:string;updatedAt:string;submittedAt?:string;approvedAt?:string;approvedBy?:string;rejectedAt?:string;rejectedBy?:string;audit:Audit[]};
type Expense={id:string;proposalId:string;campaign:string;month:string;date:string;category:string;channel:string;vendor:string;amount:number;documentRef:string;note:string;createdById:string;createdByName:string;createdAt:string};
type ProposalDraft={id:string;title:string;campaign:string;month:string;channel:string;objective:string;startDate:string;endDate:string;requestedAmount:string;expectedLeads:string;expectedRevenue:string;justification:string;note:string};
type ExpenseDraft={proposalId:string;campaign:string;date:string;category:string;channel:string;vendor:string;amount:string;documentRef:string;note:string};
type Tab='overview'|'proposals'|'expenses';

const PROPOSALS='happygo_marketing_budget_proposals_v1',EXPENSES='happygo_marketing_expenses_v1';
const channels=['Facebook Ads','TikTok Ads','Google Ads','SEO / Content','KOL / KOC','Email / CRM','Sự kiện / Offline','Thiết kế / Sản xuất','Khác'];
const categories=['Chi phí quảng cáo','Sản xuất nội dung','Thiết kế','KOL / KOC','Công cụ / Phần mềm','Sự kiện','In ấn / POSM','Khác'];
const statusLabel:Record<ProposalStatus,string>={draft:'Nháp',pending:'Chờ duyệt',changes_requested:'Cần bổ sung',approved:'Đã duyệt',rejected:'Từ chối'};
function currentMonth(){return new Date().toISOString().slice(0,7)}
function today(){return new Date().toISOString().slice(0,10)}
function blankProposal():ProposalDraft{return{id:'',title:'',campaign:'',month:currentMonth(),channel:channels[0],objective:'Tăng booking',startDate:today(),endDate:'',requestedAmount:'',expectedLeads:'',expectedRevenue:'',justification:'',note:''}}
function blankExpense():ExpenseDraft{return{proposalId:'',campaign:'',date:today(),category:categories[0],channel:channels[0],vendor:'',amount:'',documentRef:'',note:''}}
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}
function store<T>(key:string,value:T,event:string){localStorage.setItem(key,JSON.stringify(value));window.dispatchEvent(new Event(event))}
function num(value:unknown){const parsed=Number(String(value??'').replace(/[^d.-]/g,''));return Number.isFinite(parsed)?parsed:0}
function time(value?:string){if(!value)return'—';const parsed=new Date(value);return Number.isNaN(+parsed)?value:parsed.toLocaleString('vi-VN')}
function date(value?:string){if(!value)return'—';const parsed=new Date(`${value.slice(0,10)}T00:00:00`);return Number.isNaN(+parsed)?value:parsed.toLocaleDateString('vi-VN')}
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]||char))}

export function AdminMarketingBudget(){
 const[staff,setStaff]=useState<AdminStaff|null>(null),[proposals,setProposals]=useState<Proposal[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[month,setMonth]=useState(currentMonth()),[tab,setTab]=useState<Tab>('overview'),[proposalOpen,setProposalOpen]=useState(false),[expenseOpen,setExpenseOpen]=useState(false),[proposalDraft,setProposalDraft]=useState<ProposalDraft>(blankProposal()),[expenseDraft,setExpenseDraft]=useState<ExpenseDraft>(blankExpense()),[selectedId,setSelectedId]=useState<string|null>(null),[message,setMessage]=useState('');
 const load=()=>{setStaff(readCurrentStaff());setProposals(read(PROPOSALS,[]));setExpenses(read(EXPENSES,[]))};
 useEffect(()=>{load();const events=['storage','happygo-admin-auth','happygo-marketing-budget-updated'];events.forEach(event=>window.addEventListener(event,load));return()=>events.forEach(event=>window.removeEventListener(event,load))},[]);
 const manager=Boolean(staff&&(isOwner(staff)||isAdminStaff(staff))),canWork=Boolean(staff&&hasPermission(staff,'email'));
 const monthProposals=useMemo(()=>proposals.filter(item=>item.month===month).sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt)),[proposals,month]);
 const monthExpenses=useMemo(()=>expenses.filter(item=>item.month===month).sort((a,b)=>+new Date(b.date)-+new Date(a.date)),[expenses,month]);
 const kpi=useMemo(()=>{const requested=monthProposals.filter(item=>item.status!=='rejected').reduce((sum,item)=>sum+item.requestedAmount,0),approved=monthProposals.filter(item=>item.status==='approved').reduce((sum,item)=>sum+item.approvedAmount,0),spent=monthExpenses.reduce((sum,item)=>sum+item.amount,0),pending=monthProposals.filter(item=>item.status==='pending').length;return{requested,approved,spent,pending,remaining:approved-spent}},[monthProposals,monthExpenses]);
 const selected=proposals.find(item=>item.id===selectedId)||null,selectedSpent=selected?expenses.filter(item=>item.proposalId===selected.id).reduce((sum,item)=>sum+item.amount,0):0;
 const audit=(action:string,detail?:string):Audit=>({id:`mkt_aud_${Date.now()}_${Math.random().toString(36).slice(2,5)}`,at:new Date().toISOString(),byId:staff?.id||'',byName:staff?.name||'Hệ thống',action,detail});
 function resetProposal(){setProposalOpen(false);setProposalDraft(blankProposal())}
 function openProposal(item?:Proposal){setMessage('');if(item){setProposalDraft({id:item.id,title:item.title,campaign:item.campaign,month:item.month,channel:item.channel,objective:item.objective,startDate:item.startDate,endDate:item.endDate,requestedAmount:String(item.requestedAmount),expectedLeads:String(item.expectedLeads),expectedRevenue:String(item.expectedRevenue),justification:item.justification,note:item.note})}else setProposalDraft({...blankProposal(),month});setProposalOpen(true);setTab('proposals')}
 function saveProposal(submit:boolean){if(!staff||!canWork)return alert('Bạn không có quyền lập đề xuất Marketing.');const amount=num(proposalDraft.requestedAmount),leads=num(proposalDraft.expectedLeads),revenue=num(proposalDraft.expectedRevenue);if(!proposalDraft.title.trim()||!proposalDraft.campaign.trim()||!proposalDraft.month||amount<=0||!proposalDraft.justification.trim())return alert('Vui lòng nhập tên đề xuất, chiến dịch, tháng, ngân sách và lý do đề xuất.');if(proposalDraft.endDate&&proposalDraft.startDate&&proposalDraft.endDate<proposalDraft.startDate)return alert('Ngày kết thúc phải sau ngày bắt đầu.');const now=new Date().toISOString(),current=proposals.find(item=>item.id===proposalDraft.id);if(current&&!['draft','changes_requested'].includes(current.status)&&!manager)return alert('Đề xuất đã trình duyệt nên không thể sửa.');const status:ProposalStatus=submit?'pending':current?.status==='changes_requested'?'changes_requested':'draft',entry:Proposal=current?{...current,title:proposalDraft.title.trim(),campaign:proposalDraft.campaign.trim(),month:proposalDraft.month,channel:proposalDraft.channel,objective:proposalDraft.objective.trim(),startDate:proposalDraft.startDate,endDate:proposalDraft.endDate,requestedAmount:amount,expectedLeads:leads,expectedRevenue:revenue,justification:proposalDraft.justification.trim(),note:proposalDraft.note.trim(),status,updatedAt:now,...(submit?{submittedAt:now}:{}) ,audit:[...(current.audit||[]),audit(submit?'Cập nhật và trình duyệt':'Cập nhật đề xuất',`${money(amount)} · ${proposalDraft.channel}`)]}:{id:`mkt_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,title:proposalDraft.title.trim(),campaign:proposalDraft.campaign.trim(),month:proposalDraft.month,channel:proposalDraft.channel,objective:proposalDraft.objective.trim(),startDate:proposalDraft.startDate,endDate:proposalDraft.endDate,requestedAmount:amount,approvedAmount:0,expectedLeads:leads,expectedRevenue:revenue,justification:proposalDraft.justification.trim(),note:proposalDraft.note.trim(),status,createdById:staff.id,createdByName:staff.name,createdAt:now,updatedAt:now,...(submit?{submittedAt:now}:{}),audit:[audit(submit?'Tạo và trình duyệt':'Tạo đề xuất nháp',`${money(amount)} · ${proposalDraft.channel}`)]};const next=current?proposals.map(item=>item.id===entry.id?entry:item):[entry,...proposals];store(PROPOSALS,next,'happygo-marketing-budget-updated');setProposals(next);setMonth(entry.month);setMessage(submit?'Đã gửi đề xuất ngân sách chờ duyệt.':'Đã lưu đề xuất nháp.');resetProposal()}
 function patchProposal(item:Proposal,changes:Partial<Proposal>,action:string,detail?:string){if(!staff||!manager)return alert('Chỉ Chủ tài khoản hoặc Quản trị viên được duyệt ngân sách.');const next=proposals.map(current=>current.id===item.id?{...current,...changes,updatedAt:new Date().toISOString(),audit:[...(current.audit||[]),audit(action,detail)]}:current);store(PROPOSALS,next,'happygo-marketing-budget-updated');setProposals(next);setMessage(`${action}: ${item.title}.`)}
 function approve(item:Proposal){const raw=prompt('Ngân sách được duyệt',String(item.requestedAmount));if(raw===null)return;const amount=num(raw);if(amount<=0)return alert('Ngân sách duyệt phải lớn hơn 0.');if(confirm(`Duyệt ${money(amount)} cho “${item.title}”?`))patchProposal(item,{status:'approved',approvedAmount:amount,approvedAt:new Date().toISOString(),approvedBy:staff?.name||''},'Đã duyệt ngân sách',money(amount))}
 function requestChanges(item:Proposal){const note=prompt('Nội dung cần Marketing bổ sung',item.note||'');if(note===null||!note.trim())return;patchProposal(item,{status:'changes_requested',note:note.trim()},'Yêu cầu bổ sung',note.trim())}
 function reject(item:Proposal){const reason=prompt('Lý do từ chối','');if(reason===null||!reason.trim())return;patchProposal(item,{status:'rejected',rejectedAt:new Date().toISOString(),rejectedBy:staff?.name||'',note:reason.trim()},'Từ chối đề xuất',reason.trim())}
 function chooseProposal(id:string){const item=proposals.find(proposal=>proposal.id===id);setExpenseDraft(current=>({...current,proposalId:id,campaign:item?.campaign||current.campaign,channel:item?.channel||current.channel}))}
 function saveExpense(){if(!staff||!canWork)return alert('Bạn không có quyền báo cáo chi phí Marketing.');const amount=num(expenseDraft.amount),proposal=proposals.find(item=>item.id===expenseDraft.proposalId);if(!expenseDraft.date||!expenseDraft.campaign.trim()||!expenseDraft.vendor.trim()||amount<=0)return alert('Vui lòng nhập ngày chi, chiến dịch, nhà cung cấp và số tiền.');if(proposal&&proposal.status!=='approved')return alert('Chỉ được ghi chi phí vào đề xuất đã duyệt.');const entry:Expense={id:`mkt_exp_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,proposalId:expenseDraft.proposalId,campaign:expenseDraft.campaign.trim(),month:expenseDraft.date.slice(0,7),date:expenseDraft.date,category:expenseDraft.category,channel:expenseDraft.channel,vendor:expenseDraft.vendor.trim(),amount,documentRef:expenseDraft.documentRef.trim(),note:expenseDraft.note.trim(),createdById:staff.id,createdByName:staff.name,createdAt:new Date().toISOString()},next=[entry,...expenses];store(EXPENSES,next,'happygo-marketing-budget-updated');setExpenses(next);setMonth(entry.month);setExpenseDraft(blankExpense());setExpenseOpen(false);setMessage(`Đã ghi nhận chi phí ${money(amount)} cho ${entry.campaign}.`)}
 function removeExpense(item:Expense){if(!manager)return alert('Chỉ Chủ tài khoản hoặc Quản trị viên được xóa chi phí.');if(!confirm(`Xóa chi phí ${money(item.amount)} · ${item.vendor}?`))return;const next=expenses.filter(expense=>expense.id!==item.id);store(EXPENSES,next,'happygo-marketing-budget-updated');setExpenses(next);setMessage('Đã xóa khoản chi phí.')}
 function printReport(){const proposalsRows=monthProposals.map(item=>`<tr><td>${esc(item.campaign)}</td><td>${esc(item.channel)}</td><td>${esc(statusLabel[item.status])}</td><td>${esc(money(item.requestedAmount))}</td><td>${esc(item.status==='approved'?money(item.approvedAmount):'—')}</td></tr>`).join(''),expenseRows=monthExpenses.map(item=>`<tr><td>${esc(date(item.date))}</td><td>${esc(item.campaign)}</td><td>${esc(item.category)}</td><td>${esc(item.vendor)}</td><td>${esc(money(item.amount))}</td></tr>`).join(''),popup=window.open('','_blank','width=980,height=800');if(!popup)return alert('Vui lòng cho phép cửa sổ pop-up để in báo cáo.');popup.opener=null;popup.document.write(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Báo cáo Marketing ${esc(month)}</title><style>@page{size:A4;margin:14mm}body{font:13px Arial;color:#17324d}header{display:flex;justify-content:space-between;border-bottom:3px solid #0d67ac;padding-bottom:14px}h1{font-size:22px;margin:22px 0 6px}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:18px 0}.kpis div{border:1px solid #dce6ed;padding:10px}.kpis small,.kpis b{display:block}.kpis b{margin-top:5px;font-size:16px}h2{font-size:15px;margin-top:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #dce6ed;padding:8px;text-align:left}th{background:#f3f7fa}.right{text-align:right}.foot{margin-top:28px;text-align:right}</style></head><body><header><b>HAPPYGO TRAVEL</b><span>Phòng Marketing</span></header><h1>BÁO CÁO CHI PHÍ & NGÂN SÁCH</h1><b>Tháng ${esc(month)}</b><div class="kpis"><div><small>Đề xuất</small><b>${esc(money(kpi.requested))}</b></div><div><small>Đã duyệt</small><b>${esc(money(kpi.approved))}</b></div><div><small>Đã chi</small><b>${esc(money(kpi.spent))}</b></div><div><small>Còn lại</small><b>${esc(money(kpi.remaining))}</b></div></div><h2>ĐỀ XUẤT NGÂN SÁCH</h2><table><thead><tr><th>Chiến dịch</th><th>Kênh</th><th>Trạng thái</th><th>Đề xuất</th><th>Duyệt</th></tr></thead><tbody>${proposalsRows||'<tr><td colspan="5">Chưa có dữ liệu</td></tr>'}</tbody></table><h2>CHI PHÍ THỰC TẾ</h2><table><thead><tr><th>Ngày</th><th>Chiến dịch</th><th>Hạng mục</th><th>Nhà cung cấp</th><th>Số tiền</th></tr></thead><tbody>${expenseRows||'<tr><td colspan="5">Chưa có dữ liệu</td></tr>'}</tbody></table><div class="foot">Lập lúc ${esc(new Date().toLocaleString('vi-VN'))}</div><script>window.onload=()=>window.print()<\/script></body></html>`);popup.document.close()}

 return <section className="admin-panel marketing-budget">
  <div className="admin-panel-head"><div><small>MARKETING WORKSPACE</small><h2>Chi phí & đề xuất ngân sách</h2><p>Lập kế hoạch, trình duyệt và đối chiếu chi tiêu thực tế theo từng chiến dịch.</p></div><div className="marketing-head-actions"><label>Tháng<input type="month" value={month} onChange={event=>setMonth(event.target.value)}/></label><button onClick={printReport}>In báo cáo tháng</button></div></div>
  {message&&<p className="admin-api-note marketing-message">{message}</p>}
  <div className="service-kpis marketing-kpis"><article><small>NGÂN SÁCH ĐỀ XUẤT</small><b>{money(kpi.requested)}</b></article><article><small>ĐÃ ĐƯỢC DUYỆT</small><b>{money(kpi.approved)}</b></article><article className={kpi.spent>kpi.approved?'warning':''}><small>CHI PHÍ THỰC TẾ</small><b>{money(kpi.spent)}</b></article><article className={kpi.remaining<0?'danger':''}><small>{kpi.remaining<0?'VƯỢT NGÂN SÁCH':'NGÂN SÁCH CÒN LẠI'}</small><b>{money(Math.abs(kpi.remaining))}</b></article></div>
  <div className="marketing-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Tổng quan</button><button className={tab==='proposals'?'active':''} onClick={()=>setTab('proposals')}>Đề xuất ({monthProposals.length})</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>Chi phí ({monthExpenses.length})</button><span></span>{canWork&&<button className="admin-primary" onClick={()=>openProposal()}>+ Đề xuất ngân sách</button>}{canWork&&<button onClick={()=>{setExpenseDraft({...blankExpense(),date:month===currentMonth()?today():`${month}-01`});setExpenseOpen(true);setTab('expenses')}}>+ Ghi chi phí</button>}</div>
  {proposalOpen&&<div className="marketing-editor"><div className="marketing-editor-title"><div><small>{proposalDraft.id?'CẬP NHẬT ĐỀ XUẤT':'ĐỀ XUẤT MỚI'}</small><h3>Thông tin ngân sách chiến dịch</h3></div><button onClick={resetProposal}>×</button></div><div className="tour-editor-grid"><label>Tiêu đề đề xuất<input value={proposalDraft.title} onChange={event=>setProposalDraft({...proposalDraft,title:event.target.value})} placeholder="VD: Ngân sách quảng cáo tour hè"/></label><label>Tên chiến dịch<input value={proposalDraft.campaign} onChange={event=>setProposalDraft({...proposalDraft,campaign:event.target.value})}/></label><label>Tháng ngân sách<input type="month" value={proposalDraft.month} onChange={event=>setProposalDraft({...proposalDraft,month:event.target.value})}/></label><label>Kênh chính<select value={proposalDraft.channel} onChange={event=>setProposalDraft({...proposalDraft,channel:event.target.value})}>{channels.map(item=><option key={item}>{item}</option>)}</select></label><label>Mục tiêu<input value={proposalDraft.objective} onChange={event=>setProposalDraft({...proposalDraft,objective:event.target.value})}/></label><label>Ngân sách đề xuất<input inputMode="numeric" value={proposalDraft.requestedAmount} onChange={event=>setProposalDraft({...proposalDraft,requestedAmount:event.target.value})} placeholder="VD: 30000000"/></label><label>Ngày bắt đầu<input type="date" value={proposalDraft.startDate} onChange={event=>setProposalDraft({...proposalDraft,startDate:event.target.value})}/></label><label>Ngày kết thúc<input type="date" value={proposalDraft.endDate} onChange={event=>setProposalDraft({...proposalDraft,endDate:event.target.value})}/></label><label>Lead dự kiến<input inputMode="numeric" value={proposalDraft.expectedLeads} onChange={event=>setProposalDraft({...proposalDraft,expectedLeads:event.target.value})}/></label><label>Doanh thu kỳ vọng<input inputMode="numeric" value={proposalDraft.expectedRevenue} onChange={event=>setProposalDraft({...proposalDraft,expectedRevenue:event.target.value})}/></label><label className="span-2">Lý do và kế hoạch sử dụng<textarea rows={4} value={proposalDraft.justification} onChange={event=>setProposalDraft({...proposalDraft,justification:event.target.value})}/></label><label className="span-2">Ghi chú nội bộ<textarea rows={3} value={proposalDraft.note} onChange={event=>setProposalDraft({...proposalDraft,note:event.target.value})}/></label><div className="span-2 editor-actions"><button onClick={resetProposal}>Hủy</button><button onClick={()=>saveProposal(false)}>Lưu nháp</button><button className="admin-primary" onClick={()=>saveProposal(true)}>Gửi duyệt</button></div></div></div>}
  {expenseOpen&&<div className="marketing-editor"><div className="marketing-editor-title"><div><small>BÁO CÁO CHI PHÍ</small><h3>Ghi nhận khoản chi thực tế</h3></div><button onClick={()=>setExpenseOpen(false)}>×</button></div><div className="tour-editor-grid"><label>Đề xuất đã duyệt<select value={expenseDraft.proposalId} onChange={event=>chooseProposal(event.target.value)}><option value="">— Chi phí chung / không gắn đề xuất —</option>{proposals.filter(item=>item.status==='approved').map(item=><option key={item.id} value={item.id}>{item.campaign} · còn {money(item.approvedAmount-expenses.filter(expense=>expense.proposalId===item.id).reduce((sum,expense)=>sum+expense.amount,0))}</option>)}</select></label><label>Ngày chi<input type="date" value={expenseDraft.date} onChange={event=>setExpenseDraft({...expenseDraft,date:event.target.value})}/></label><label>Chiến dịch<input value={expenseDraft.campaign} onChange={event=>setExpenseDraft({...expenseDraft,campaign:event.target.value})}/></label><label>Kênh<select value={expenseDraft.channel} onChange={event=>setExpenseDraft({...expenseDraft,channel:event.target.value})}>{channels.map(item=><option key={item}>{item}</option>)}</select></label><label>Hạng mục<select value={expenseDraft.category} onChange={event=>setExpenseDraft({...expenseDraft,category:event.target.value})}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Nhà cung cấp / đơn vị nhận tiền<input value={expenseDraft.vendor} onChange={event=>setExpenseDraft({...expenseDraft,vendor:event.target.value})}/></label><label>Số tiền<input inputMode="numeric" value={expenseDraft.amount} onChange={event=>setExpenseDraft({...expenseDraft,amount:event.target.value})}/></label><label>Số hóa đơn / chứng từ<input value={expenseDraft.documentRef} onChange={event=>setExpenseDraft({...expenseDraft,documentRef:event.target.value})}/></label><label className="span-2">Ghi chú<textarea rows={3} value={expenseDraft.note} onChange={event=>setExpenseDraft({...expenseDraft,note:event.target.value})}/></label><div className="span-2 editor-actions"><button onClick={()=>setExpenseOpen(false)}>Hủy</button><button className="admin-primary" onClick={saveExpense}>Lưu chi phí</button></div></div></div>}
  {(tab==='overview'||tab==='proposals')&&<div className="marketing-proposal-list">{monthProposals.map(item=>{const spent=expenses.filter(expense=>expense.proposalId===item.id).reduce((sum,expense)=>sum+expense.amount,0),limit=item.status==='approved'?item.approvedAmount:item.requestedAmount,pct=limit?Math.min(100,Math.round(spent*100/limit)):0;return <article key={item.id} className="marketing-proposal-card"><div className="marketing-proposal-main"><div><small>{item.campaign} · {item.channel}</small><b>{item.title}</b><span>{item.objective}</span></div><span className={`marketing-status ${item.status}`}>{statusLabel[item.status]}</span></div><div className="marketing-budget-row"><span><small>Đề xuất</small><b>{money(item.requestedAmount)}</b></span><span><small>Được duyệt</small><b>{item.status==='approved'?money(item.approvedAmount):'—'}</b></span><span><small>Đã chi</small><b>{money(spent)}</b></span><span><small>Doanh thu kỳ vọng</small><b>{money(item.expectedRevenue)}</b></span></div>{item.status==='approved'&&<div className="marketing-progress"><span style={{width:`${pct}%`}}></span><small>{pct}% ngân sách đã sử dụng · còn {money(item.approvedAmount-spent)}</small></div>}<div className="marketing-card-actions"><button onClick={()=>setSelectedId(item.id)}>Chi tiết</button>{canWork&&['draft','changes_requested'].includes(item.status)&&<button onClick={()=>openProposal(item)}>Chỉnh sửa</button>}{manager&&item.status==='pending'&&<><button onClick={()=>requestChanges(item)}>Yêu cầu bổ sung</button><button className="danger-action" onClick={()=>reject(item)}>Từ chối</button><button className="admin-primary" onClick={()=>approve(item)}>Duyệt ngân sách</button></>}</div></article>})}{!monthProposals.length&&<div className="admin-empty-state"><b>Chưa có đề xuất trong tháng {month}</b><span>Tạo đề xuất để bắt đầu kế hoạch ngân sách Marketing.</span></div>}</div>}
  {(tab==='overview'||tab==='expenses')&&<section className="marketing-expenses"><div className="marketing-section-head"><div><small>CHI PHÍ THỰC TẾ · {month}</small><b>{monthExpenses.length} khoản chi</b></div><strong>{money(kpi.spent)}</strong></div><div className="marketing-expense-list">{monthExpenses.map(item=><article key={item.id}><div><b>{item.campaign}</b><span>{item.category} · {item.channel}</span><small>{date(item.date)} · {item.vendor}{item.documentRef?` · CT: ${item.documentRef}`:''}</small></div><strong>{money(item.amount)}</strong><div><small>{item.createdByName}</small>{manager&&<button className="danger-action" onClick={()=>removeExpense(item)}>Xóa</button>}</div></article>)}{!monthExpenses.length&&<div className="admin-empty-state"><b>Chưa ghi nhận chi phí tháng này</b></div>}</div></section>}
  {selected&&<div className="supplier-detail-overlay" onClick={()=>setSelectedId(null)}><section className="supplier-detail marketing-detail" role="dialog" aria-modal="true" aria-labelledby="marketing-detail-title" onClick={event=>event.stopPropagation()}><header><div><small>ĐỀ XUẤT NGÂN SÁCH · {selected.month}</small><h2 id="marketing-detail-title">{selected.title}</h2><p>{selected.campaign} · {selected.channel}</p></div><button aria-label="Đóng" onClick={()=>setSelectedId(null)}>×</button></header><div className="supplier-detail-grid"><article><small>TRẠNG THÁI</small><b>{statusLabel[selected.status]}</b><span>{selected.approvedBy||selected.rejectedBy||selected.createdByName}</span></article><article><small>ĐỀ XUẤT / DUYỆT</small><b>{money(selected.requestedAmount)}</b><span>{selected.status==='approved'?money(selected.approvedAmount):'Chưa duyệt'}</span></article><article><small>ĐÃ CHI</small><b>{money(selectedSpent)}</b><span>{selected.status==='approved'?`Còn ${money(selected.approvedAmount-selectedSpent)}`:'Chưa có hạn mức'}</span></article><article><small>KỲ VỌNG</small><b>{selected.expectedLeads} lead</b><span>{money(selected.expectedRevenue)} doanh thu</span></article></div><div className="marketing-justification"><small>LÝ DO & KẾ HOẠCH SỬ DỤNG</small><p>{selected.justification}</p>{selected.note&&<><small>GHI CHÚ / PHẢN HỒI</small><p>{selected.note}</p></>}</div><section className="supplier-timeline"><div><small>NHẬT KÝ PHÊ DUYỆT</small><b>{selected.audit.length} hoạt động</b></div>{[...selected.audit].reverse().map(item=><article key={item.id}><i></i><div><b>{item.action}</b>{item.detail&&<span>{item.detail}</span>}<small>{item.byName} · {time(item.at)}</small></div></article>)}</section></section></div>}
 </section>
}
