'use client';
import {useEffect,useMemo,useState} from 'react';
import {isAdminStaff,isOwner,readCurrentStaff,type AdminStaff} from '@/components/AdminSalesAccess';

type Booking={id:number;code:string;status:string};
type Ops={operatorId?:string;operatorName?:string;handoffAcceptedAt?:string;handoffAcceptedBy?:string;closedAt?:string};
type StaffOption={id:string;name:string;role:string;department?:string;status?:string;permissions?:string[]};
type OperatorLog={id:string;bookingId:number;bookingCode:string;action:'assign'|'reassign'|'unassign'|'self_accept';fromId:string;fromName:string;toId:string;toName:string;changedById:string;changedByName:string;at:string};
type MonthStat={id:string;name:string;assigned:number;selfAccepted:number;handoffs:number;completed:number;transfersIn:number;transfersOut:number;currentActive:number};

const BOOKINGS='tn_local_bookings_v1',OPS='happygo_booking_ops_checklist_v1',STAFF='tn_admin_staff_v1',OPERATOR_LOG='happygo_booking_operator_history_v1';
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'')??fallback}catch{return fallback}}
function monthKey(value?:string){if(!value)return'';const d=new Date(value);if(Number.isNaN(+d))return'';return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function currentMonth(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthLabel(value:string){const[y,m]=value.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('vi-VN',{month:'long',year:'numeric'})}
function recentMonths(count=12){const now=new Date();return Array.from({length:count},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-i,1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})}
function isOperator(x:StaffOption){const role=String(x.role||'').toLowerCase(),dept=String(x.department||'').toLowerCase();return x.status!=='inactive'&&(role==='operations'||role==='admin'||dept==='resa'||dept==='operations')&&(role==='admin'||x.permissions?.includes('bookings'))}

export function AdminOperatorMonthlyReport(){
 const[staff,setStaff]=useState<AdminStaff|null>(null),[bookings,setBookings]=useState<Booking[]>([]),[ops,setOps]=useState<Record<string,Ops>>({}),[staffList,setStaffList]=useState<StaffOption[]>([]),[logs,setLogs]=useState<OperatorLog[]>([]),[month,setMonth]=useState(currentMonth());
 useEffect(()=>{const load=()=>{setStaff(readCurrentStaff());setBookings(read(BOOKINGS,[]));setOps(read(OPS,{}));setStaffList(read(STAFF,[]));setLogs(read(OPERATOR_LOG,[]))};load();const ev=['storage','tn-bookings-updated','happygo-booking-ops-updated','happygo-booking-operator-history-updated','tn-staff-updated','happygo-admin-auth'];ev.forEach(e=>window.addEventListener(e,load));return()=>ev.forEach(e=>window.removeEventListener(e,load))},[]);
 const manager=Boolean(staff&&(isOwner(staff)||isAdminStaff(staff)));
 const people=useMemo(()=>staffList.filter(isOperator).filter(x=>manager||x.id===staff?.id),[staffList,manager,staff]);
 const stats=useMemo<MonthStat[]>(()=>people.map(p=>{const periodLogs=logs.filter(l=>monthKey(l.at)===month),assigned=periodLogs.filter(l=>l.toId===p.id&&(l.action==='assign'||l.action==='reassign'||l.action==='self_accept')).length,selfAccepted=periodLogs.filter(l=>l.toId===p.id&&l.action==='self_accept').length,transfersIn=periodLogs.filter(l=>l.toId===p.id&&l.action==='reassign').length,transfersOut=periodLogs.filter(l=>l.fromId===p.id&&l.action==='reassign').length,handoffs=Object.values(ops).filter(o=>monthKey(o.handoffAcceptedAt)===month&&(o.handoffAcceptedBy===p.name||o.operatorId===p.id&&o.handoffAcceptedBy===p.name)).length,completed=Object.values(ops).filter(o=>monthKey(o.closedAt)===month&&o.operatorId===p.id).length,currentActive=bookings.filter(b=>!['completed','cancelled'].includes(b.status)&&ops[String(b.id)]?.operatorId===p.id).length;return{id:p.id,name:p.name,assigned,selfAccepted,handoffs,completed,transfersIn,transfersOut,currentActive}}).sort((a,b)=>b.completed-a.completed||b.assigned-a.assigned||b.handoffs-a.handoffs||a.name.localeCompare(b.name,'vi')),[people,logs,ops,bookings,month]);
 const total=stats.reduce((a,s)=>({assigned:a.assigned+s.assigned,handoffs:a.handoffs+s.handoffs,completed:a.completed+s.completed,transfers:a.transfers+s.transfersOut}),{assigned:0,handoffs:0,completed:0,transfers:0});
 if(!staff||!people.length)return null;
 return <details className="admin-api-note"><summary><b>{manager?'Báo cáo Điều hành theo tháng':'Báo cáo Điều hành của tôi theo tháng'}</b></summary><div style={{marginTop:12}}><div className="admin-form-row"><label>Kỳ báo cáo<select value={month} onChange={e=>setMonth(e.target.value)}>{recentMonths().map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></label><label>Phạm vi<input disabled value={manager?'Toàn đội Điều hành':'Chỉ tài khoản đang đăng nhập'}/></label></div><div className="service-kpis"><article><small>PHÂN/CHUYỂN VÀO KỲ</small><b>{total.assigned}</b></article><article><small>ĐÃ NHẬN BÀN GIAO</small><b>{total.handoffs}</b></article><article><small>HOÀN TẤT TRONG KỲ</small><b>{total.completed}</b></article><article className={total.transfers?'warning':''}><small>CHUYỂN NGƯỜI PHỤ TRÁCH</small><b>{total.transfers}</b></article></div><div className="admin-customer-grid" style={{marginTop:12}}>{stats.map(s=><article className="admin-customer-card" key={s.id}><div><b>{s.name}</b><span>{s.currentActive} booking đang phụ trách hiện tại</span><small>Kỳ {monthLabel(month)}</small></div><div><b>{s.assigned} booking nhận trong kỳ</b><small>{s.selfAccepted} tự nhận · {s.transfersIn} chuyển vào</small></div><div><b>{s.handoffs} bàn giao · {s.completed} hoàn tất</b><small>{s.transfersOut} lần chuyển sang người khác</small></div><div><span className={s.transfersOut?'status-contacting':'status-confirmed'}>{s.transfersOut?'Có chuyển việc':'Không chuyển việc'}</span></div></article>)}</div><p style={{marginTop:10}}>Báo cáo tháng dùng thời gian từ nhật ký phân công, thời điểm nhận bàn giao và thời điểm đóng booking. Dữ liệu lịch sử chỉ đầy đủ từ khi các nhật ký này được bật trên hệ thống; hiện vẫn lưu trên trình duyệt cho đến khi chuyển sang backend/database.</p></div></details>
}
