'use client';

import {useMemo,useState} from 'react';

type ProductType='Sản phẩm'|'Tour du lịch'|'Villa & Resort'|'Khách sạn'|'Du thuyền';
type Product={name:string;slug:string;place:string;price:string;salePrice:string;summary:string;content:string;cover:string;gallery:string;status:string;seoTitle:string;seoDescription:string;amenities:string;policies:string;duration:string;itinerary:string;roomTypes:string;cabins:string;checkin:string;checkout:string;stars:string;bedrooms:string;capacity:string;area:string;view:string;breakfast:string;childrenPolicy:string;extraCharge:string;address:string;pickup:string;boarding:string;meals:string;activities:string;faq:string;rating:string;category:string};
const blank:Product={name:'',slug:'',place:'',price:'',salePrice:'',summary:'',content:'',cover:'',gallery:'',status:'draft',seoTitle:'',seoDescription:'',amenities:'',policies:'',duration:'',itinerary:'',roomTypes:'',cabins:'',checkin:'14:00',checkout:'12:00',stars:'',bedrooms:'',capacity:'',area:'',view:'',breakfast:'',childrenPolicy:'',extraCharge:'',address:'',pickup:'',boarding:'',meals:'',activities:'',faq:'',rating:'',category:''};
function slugify(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
const sample={'Tour du lịch':['Tour Bắc Kinh - Thượng Hải','Tour Đà Nẵng - Hội An'],'Villa & Resort':['Oceanami Villas & Beach Club','NovaWorld Phan Thiết'],'Khách sạn':['Vinpearl Resort Nha Trang','FLC Hotels & Resorts'],'Du thuyền':['Ambassador Hạ Long','Ambassador Signature'],'Sản phẩm':['Oceanami Villas & Beach Club','Ambassador Hạ Long']};

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="cms-field"><span>{label}</span>{children}</label>}
function Box({title,desc,children}:{title:string;desc?:string;children:React.ReactNode}){return <div className="editor-box product-section-box"><div className="editor-box-head"><div><h3>{title}</h3>{desc&&<p>{desc}</p>}</div></div>{children}</div>}

export function AdminProductEditor({type}:{type:ProductType}){
 const [mode,setMode]=useState<'list'|'edit'>('list');const [form,setForm]=useState<Product>(blank);const [saved,setSaved]=useState('');
 const typeLabel=type==='Sản phẩm'?'sản phẩm':type.toLowerCase();
 const score=useMemo(()=>[form.name,form.place,form.price,form.cover,form.summary,form.content,form.seoTitle,form.seoDescription].filter(Boolean).length,[form]);
 function set<K extends keyof Product>(k:K,v:Product[K]){setForm(f=>({...f,[k]:v}))}
 function add(){setForm(blank);setSaved('');setMode('edit')}
 function save(status:string){const next={...form,status};localStorage.setItem(`tn_cms_product_${type}`,JSON.stringify(next));setForm(next);setSaved(status==='published'?'Đã đăng bản xem thử trên thiết bị này.':'Đã lưu bản nháp.');}
 if(mode==='list')return <section className="admin-panel wp-list-panel"><div className="admin-panel-head"><div><h2>{type}</h2><p>Danh sách {typeLabel}. Mỗi nhóm có bộ trường riêng theo đúng nghiệp vụ bán dịch vụ.</p></div><button className="admin-primary" onClick={add}>+ Đăng {typeLabel} mới</button></div><div className="admin-list-toolbar"><input placeholder={`Tìm ${typeLabel}...`}/><select><option>Tất cả trạng thái</option><option>Đang bán</option><option>Bản nháp</option><option>Ẩn</option></select><button>Lọc</button></div><div className="wp-product-list">{sample[type].map((name,i)=><article key={name}><div className="product-thumb">{type==='Du thuyền'?'🛳':type==='Tour du lịch'?'✈':type==='Khách sạn'?'🏨':'🏝'}</div><div><b>{name}</b><span>{type} · {i%2===0?'Đang bán':'Bản nháp'}</span></div><strong>{i%2===0?'Từ 2.900.000đ':'Liên hệ'}</strong><button onClick={()=>{setForm({...blank,name,slug:slugify(name),place:i%2===0?'Phan Thiết':'Nha Trang'});setMode('edit')}}>Sửa</button></article>)}</div></section>;

 return <section className="admin-editor-shell product-editor-shell"><div className="admin-editor-main"><div className="editor-title-row"><button className="editor-back" onClick={()=>setMode('list')}>← Danh sách {typeLabel}</button><span>{saved}</span></div><input className="post-title-input" value={form.name} onChange={e=>{set('name',e.target.value);if(!form.slug)set('slug',slugify(e.target.value))}} placeholder={`Tên ${typeLabel}`}/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div>

 <Box title="1. Thông tin cơ bản" desc="Thông tin hiển thị ở đầu trang chi tiết và kết quả tìm kiếm."><div className="product-basic-grid"><Field label="Điểm đến / khu vực"><input value={form.place} onChange={e=>set('place',e.target.value)} placeholder="Phan Thiết, Hạ Long, Nha Trang..."/></Field><Field label="Giá từ"><input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="4.500.000đ"/></Field><Field label="Giá khuyến mãi"><input value={form.salePrice} onChange={e=>set('salePrice',e.target.value)} placeholder="Nếu có"/></Field><Field label="Điểm đánh giá"><input value={form.rating} onChange={e=>set('rating',e.target.value)} placeholder="9.0"/></Field></div><Field label="Mô tả ngắn"><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)} placeholder="Tóm tắt nổi bật hiển thị trên card và đầu trang..."/></Field></Box>

 {type==='Villa & Resort'&&<>
 <Box title="2. Thông tin Villa / Resort" desc="Các trường khách thường cần trước khi quyết định đặt."><div className="product-basic-grid"><Field label="Loại hình"><select value={form.category} onChange={e=>set('category',e.target.value)}><option value="">Chọn loại</option><option>Villa nguyên căn</option><option>Resort</option><option>Villa beachfront</option><option>Villa hồ bơi riêng</option></select></Field><Field label="Số phòng ngủ"><input value={form.bedrooms} onChange={e=>set('bedrooms',e.target.value)} placeholder="3 phòng ngủ"/></Field><Field label="Sức chứa"><input value={form.capacity} onChange={e=>set('capacity',e.target.value)} placeholder="6 người lớn + 2 trẻ em"/></Field><Field label="Diện tích"><input value={form.area} onChange={e=>set('area',e.target.value)} placeholder="350 m²"/></Field><Field label="View"><input value={form.view} onChange={e=>set('view',e.target.value)} placeholder="Biển / vườn / hồ bơi"/></Field><Field label="Địa chỉ chi tiết"><input value={form.address} onChange={e=>set('address',e.target.value)} placeholder="Địa chỉ đầy đủ"/></Field></div></Box>
 <Box title="3. Hạng Villa & bảng giá" desc="Mỗi dòng có thể dùng: Tên hạng | sức chứa | giá ngày thường | cuối tuần | lễ."><textarea rows={8} value={form.roomTypes} onChange={e=>set('roomTypes',e.target.value)} placeholder="Villa 3PN | 6 khách | 4.500.000đ | 5.500.000đ\nVilla 4PN Beachfront | 8 khách | ..."/></Box>
 <Box title="4. Nhận phòng & phụ thu"><div className="product-basic-grid"><Field label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></Field><Field label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></Field><Field label="Phụ thu"><input value={form.extraCharge} onChange={e=>set('extraCharge',e.target.value)} placeholder="Cuối tuần, lễ, thêm người..."/></Field><Field label="Chính sách trẻ em"><input value={form.childrenPolicy} onChange={e=>set('childrenPolicy',e.target.value)} placeholder="Dưới 6 tuổi..."/></Field></div></Box></>}

 {type==='Khách sạn'&&<>
 <Box title="2. Thông tin khách sạn"><div className="product-basic-grid"><Field label="Hạng sao"><select value={form.stars} onChange={e=>set('stars',e.target.value)}><option value="">Chọn</option><option>3 sao</option><option>4 sao</option><option>5 sao</option></select></Field><Field label="Địa chỉ"><input value={form.address} onChange={e=>set('address',e.target.value)} placeholder="Địa chỉ khách sạn"/></Field><Field label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></Field><Field label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></Field><Field label="Ăn sáng"><select value={form.breakfast} onChange={e=>set('breakfast',e.target.value)}><option value="">Chọn</option><option>Có ăn sáng</option><option>Không ăn sáng</option><option>Tùy gói giá</option></select></Field><Field label="Chính sách trẻ em"><input value={form.childrenPolicy} onChange={e=>set('childrenPolicy',e.target.value)} placeholder="Theo độ tuổi"/></Field></div></Box>
 <Box title="3. Hạng phòng & giá" desc="Tên phòng | diện tích | giường | sức chứa | view | ăn sáng | giá."><textarea rows={10} value={form.roomTypes} onChange={e=>set('roomTypes',e.target.value)} placeholder="Deluxe Ocean View | 38m² | King | 2NL+1TE | Biển | Ăn sáng | 2.500.000đ\nSuite | ..."/></Box>
 <Box title="4. Điều kiện giá"><div className="product-basic-grid"><Field label="Phụ thu"><input value={form.extraCharge} onChange={e=>set('extraCharge',e.target.value)} placeholder="Giường phụ, lễ Tết..."/></Field><Field label="Hoàn hủy"><input value={form.policies} onChange={e=>set('policies',e.target.value)} placeholder="Miễn phí trước ... ngày"/></Field></div></Box></>}

 {type==='Du thuyền'&&<>
 <Box title="2. Thông tin du thuyền"><div className="product-basic-grid"><Field label="Vịnh / tuyến"><input value={form.place} onChange={e=>set('place',e.target.value)} placeholder="Vịnh Hạ Long / Lan Hạ"/></Field><Field label="Thời lượng"><input value={form.duration} onChange={e=>set('duration',e.target.value)} placeholder="2 ngày 1 đêm"/></Field><Field label="Điểm đón / bến"><input value={form.pickup} onChange={e=>set('pickup',e.target.value)} placeholder="Cảng tàu quốc tế Hạ Long"/></Field><Field label="Giờ lên tàu"><input value={form.boarding} onChange={e=>set('boarding',e.target.value)} placeholder="11:30"/></Field></div></Box>
 <Box title="3. Hạng cabin & giá" desc="Tên cabin | diện tích | sức chứa | ban công | bồn tắm | giá."><textarea rows={9} value={form.cabins} onChange={e=>set('cabins',e.target.value)} placeholder="Deluxe Cabin | 30m² | 2 khách | Không | Shower | 4.500.000đ\nSuite Balcony | 38m² | ..."/></Box>
 <Box title="4. Lịch trình hành trình"><textarea rows={10} value={form.itinerary} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1\n11:30 Check-in...\n14:30 Tham quan...\nNgày 2..."/></Box>
 <Box title="5. Ẩm thực & hoạt động"><div className="two-col-box"><Field label="Bữa ăn"><textarea rows={6} value={form.meals} onChange={e=>set('meals',e.target.value)} placeholder="Bữa trưa buffet\nBữa tối set menu..."/></Field><Field label="Hoạt động"><textarea rows={6} value={form.activities} onChange={e=>set('activities',e.target.value)} placeholder="Kayak\nHang động\nSunset party..."/></Field></div></Box></>}

 {type==='Tour du lịch'&&<><Box title="Thông tin Tour"><div className="product-basic-grid"><Field label="Thời lượng"><input value={form.duration} onChange={e=>set('duration',e.target.value)} placeholder="5 ngày 4 đêm"/></Field></div><Field label="Lịch trình"><textarea rows={9} value={form.itinerary} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1: ...\nNgày 2: ..."/></Field></Box></>}

 <Box title="Nội dung giới thiệu"><div className="classic-editor"><div className="editor-toolbar"><button><b>B</b></button><button><i>I</i></button><button>H2</button><button>H3</button><button>☷</button><button>🔗 Link</button><button>🖼 Ảnh</button><button>🎬 Video</button></div><textarea value={form.content} onChange={e=>set('content',e.target.value)} placeholder="Giới thiệu chi tiết, vị trí, trải nghiệm, điểm nổi bật..."/></div></Box>
 <Box title="Tiện ích / Dịch vụ bao gồm"><textarea rows={7} value={form.amenities} onChange={e=>set('amenities',e.target.value)} placeholder="Mỗi dòng một tiện ích hoặc dịch vụ..."/></Box>
 <Box title="Chính sách"><textarea rows={7} value={form.policies} onChange={e=>set('policies',e.target.value)} placeholder="Đặt cọc, hoàn hủy, phụ thu, trẻ em..."/></Box>
 <Box title="FAQ & câu hỏi thường gặp"><textarea rows={7} value={form.faq} onChange={e=>set('faq',e.target.value)} placeholder="Câu hỏi: ...\nTrả lời: ...\n\nCâu hỏi: ..."/></Box>
 <Box title="SEO sản phẩm"><div className="editor-box-head"><b className={score>=6?'seo-good':''}>{score}/8 mục cơ bản</b></div><Field label="SEO Title"><input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)} placeholder={form.name||'Tiêu đề Google'}/></Field><Field label="Meta description"><textarea rows={3} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></Field></Box>
 </div>

 <aside className="admin-editor-side"><div className="editor-box publish-box"><h3>Xuất bản</h3><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="draft">Bản nháp</option><option value="published">Đang bán</option><option value="hidden">Ẩn</option></select></label><div className="publish-actions"><button onClick={()=>save('draft')}>Lưu nháp</button><button className="admin-primary" onClick={()=>save('published')}>Đăng sản phẩm</button></div></div><div className="editor-box"><h3>Ảnh đại diện</h3><div className="media-picker">{form.cover?<img src={form.cover} alt={form.name}/>:<span>🖼</span>}<input value={form.cover} onChange={e=>set('cover',e.target.value)} placeholder="URL ảnh đại diện"/><button>Chọn từ Media</button></div></div><div className="editor-box"><h3>Album ảnh</h3><textarea rows={8} value={form.gallery} onChange={e=>set('gallery',e.target.value)} placeholder="Mỗi dòng một URL ảnh\nhoặc chọn nhiều ảnh từ Media"/><button className="side-media-btn">+ Chọn nhiều ảnh</button></div><div className="editor-box"><h3>Đánh giá</h3><Field label="Điểm tổng"><input value={form.rating} onChange={e=>set('rating',e.target.value)} placeholder="9.0"/></Field></div></aside></section>;
}
