'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';

type Assignment={affiliateId:string;salesOwnerId:string;salesOwnerName:string};
type Sale={id:string;name:string;email:string;department:string};
type Affiliate={id:string;name:string;email:string;phone:string;referralCode:string;status:string};
type Payload={canAssign:boolean;currentStaffId:string;sales:Sale[];assignments:Assignment[]};
type OwnerFilter='all'|'unassigned'|string;

export function AdminAffiliateAssignments(){
 const[data,setData]=useState<Payload|null>(null),[affiliates,setAffiliates]=useState<Affiliate[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[q,setQ]=useState(''),[ownerFilter,setOwnerFilter]=useState<OwnerFilter>('all');
 const load=useCallback(async()=>{setBusy(true);try{const[a,b]=await Promise.all([fetch('/api/admin/affiliate-assignments',{cache:'no-store'}),fetch('/api/admin/affiliates',{cache:'no-store'})]);const ad=await a.json().catch(()=>({})),bd=await b.json().catch(()=>({}));if(!a.ok)throw new Error(ad.error||'Không đọc được phân công CTV.');if(!b.ok)throw new Error(bd.error||'Không đọc được danh sách CTV.');setData(ad);setAffiliates(Array.isArray(bd.affiliates)?bd.affiliates:[]);setMsg('')}catch(error){setMsg(error instanceof Error?error.message:'Không kết nối được phân công CTV.')}finally{setBusy(false)}},[]);
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('happygo-network-updated',refresh);window.addEventListener('focus',refresh);return()=>{window.removeEventListener('happygo-network-updated',refresh);window.removeEventListener('focus',refresh)}},[load]);
 const assignmentMap=useMemo(()=>new Map((data?.assignments||[]).map(x=>[x.affiliateId,x])),[data]);
 const scoped=useMemo(()=>affiliates.filter(a=>assignmentMap.has(a.id)),[affiliates,assignmentMap]);
 const stats=useMemo(()=>({total:scoped.length,unassigned:scoped.filter(a=>!assignmentMap.get(a.id)?.salesOwnerId).length,active:scoped.filter(a=>a.status==='active').length,pending:scoped.filter(a=>a.status==='pending').length}),[scoped,assignmentMap]);
 const visible=useMemo(()=>{const n=q.trim().toLowerCase();return scoped.filter(a=>{const assignment=assignmentMap.get(a.id);const ownerOk=!data?.canAssign||ownerFilter==='all'||(ownerFilter==='unassigned'?!assignment?.salesOwnerId:assignment?.salesOwnerId===ownerFilter);const text=`${a.name} ${a.email} ${a.phone} ${a.referralCode} ${assignment?.salesOwnerName||''}`.toLowerCase();return ownerOk&&(!n||text.includes(n))})},[scoped,assignmentMap,q,ownerFilter,data?.canAssign]);
 const saleCounts=useMemo(()=>new Map((data?.sales||[]).map(s=>[s.id,scoped.filter(a=>assignmentMap.get(a.id)?.salesOwnerId===s.id).length])),[data?.sales,scoped,assignmentMap]);
 async function assign(affiliateId:string,salesOwnerId:string){if(!data?.canAssign)return;setBusy(true);setMsg('');try{const r=await fetch('/api/admin/affiliate-assignments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({affiliateId,salesOwnerId})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Không thể cập nhật Sale phụ trách.');setMsg('Đã cập nhật Sale phụ trách CTV trên production.');await load();window.dispatchEvent(new Event('happygo-network-updated'))}catch(error){setMsg(error instanceof Error?error.message:'Không cập nhật được Sale phụ trách.')}finally{setBusy(false)}}
 if(!data&&busy)return <section className="admin-panel"><div className="admin-empty-state">Đang tải phân công Sale → CTV...</div></section>;
 return <section className="admin-panel affiliate-admin"><div className="admin-panel-head"><div><small>PHÂN CÔNG SALE · PRODUCTION</small><h2>Sale phụ trách CTV</h2><p>{data?.canAssign?'Admin/Owner giao, chuyển và rà soát tải chăm sóc CTV theo từng Sale. Mọi thay đổi được ghi audit log.':'Bạn chỉ nhìn thấy CTV đang được phân công cho tài khoản Sale của mình.'}</p></div><button type="button" className="admin-secondary" onClick={()=>void load()} disabled={busy}>↻ Làm mới</button></div>{msg&&<p className="admin-api-note">{msg}</p>}<div className="admin-partner-kpis"><article><span>CTV trong phạm vi</span><b>{stats.total}</b><small>{stats.active} đang hoạt động</small></article>{data?.canAssign&&<article><span>Chưa phân công</span><b>{stats.unassigned}</b><small>Cần giao Sale phụ trách</small></article>}<article><span>CTV chờ duyệt</span><b>{stats.pending}</b><small>Cần xử lý hồ sơ</small></article></div><div className="affiliate-admin-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên, email, SĐT, mã CTV hoặc Sale phụ trách"/>{data?.canAssign&&<select value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)}><option value="all">Tất cả Sale</option><option value="unassigned">Chưa phân công ({stats.unassigned})</option>{(data.sales||[]).map(s=><option key={s.id} value={s.id}>{s.name} ({saleCounts.get(s.id)||0})</option>)}</select>}<span>{visible.length} CTV hiển thị</span></div><div className="affiliate-admin-table"><table><thead><tr><th>CTV</th><th>Liên hệ</th><th>Trạng thái</th><th>Sale phụ trách</th></tr></thead><tbody>{visible.map(a=>{const assignment=assignmentMap.get(a.id);return <tr key={a.id}><td><b>{a.name}</b><br/><small>{a.referralCode} · {a.email}</small></td><td>{a.phone||'Chưa có SĐT'}</td><td>{a.status==='active'?'Đang hoạt động':a.status==='pending'?'Chờ duyệt':'Đã khóa'}</td><td>{data?.canAssign?<select value={assignment?.salesOwnerId||''} onChange={e=>void assign(a.id,e.target.value)} disabled={busy}><option value="">Chưa phân công</option>{(data.sales||[]).map(s=><option key={s.id} value={s.id}>{s.name} · {s.department||'Nhân viên'}</option>)}</select>:<b>{assignment?.salesOwnerName||'Chưa phân công'}</b>}</td></tr>})}{!visible.length&&<tr><td colSpan={4}>Chưa có CTV phù hợp với bộ lọc hiện tại.</td></tr>}</tbody></table></div></section>;
}
