'use client';

import {useEffect,useState} from 'react';

const sections=['Thông tin cơ bản','Giá & lịch khởi hành','Album ảnh','Điểm nổi bật','Lịch trình','Dịch vụ','Chính sách','Ưu đãi','Đánh giá & FAQ','SEO'];
type Tour={id:string;name:string;category:string;duration:string;departure:string;airline:string;route:string;transport:string;summary:string;status:string;price:string;salePrice:string;childPrice:string;singleCharge:string;departures:string;gallery:string;highlights:string;itinerary:string;included:string;excluded:string;policies:string;promotion:string;rating:string;reviewCount:string;faq:string;seoTitle:string;seoDescription:string;slug:string};
const blank:Tour={id:'',name:'',category:'Tour Trung Quốc',duration:'',departure:'Hà Nội',airline:'',route:'',transport:'Máy bay, Ô tô',summary:'',status:'draft',price:'',salePrice:'',childPrice:'',singleCharge:'',departures:'',gallery:'',highlights:'',itinerary:'',included:'',excluded:'',policies:'',promotion:'',rating:'',reviewCount:'',faq:'',seoTitle:'',seoDescription:'',slug:''};
const seed:Tour[]=[{...blank,id:'tour_bac_kinh',name:'Bắc Kinh - Vạn Lý Trường Thành',duration:'5N4Đ',route:'Hà Nội - Bắc Kinh - Vạn Lý Trường Thành',airline:'Vietjet Air',summary:'Khám phá Bắc Kinh và Vạn Lý Trường Thành.',status:'published',salePrice:'15.990.000đ',departures:'30/08\n21/09\n27/09',rating:'9.2',reviewCount:'23',slug:'bac-kinh-van-ly-truong-thanh',itinerary:'Ngày 1: Hà Nội - Bắc Kinh\nNgày 2: Thiên An Môn - Tử Cấm Thành\nNgày 3: Vạn Lý Trường Thành\nNgày 4: Tự do mua sắm\nNgày 5: Bắc Kinh - Hà Nội'},{...blank,id:'tour_thuong_hai',name:'Thượng Hải - Hàng Châu - Ô Trấn',duration:'6N5Đ',route:'Thượng Hải - Hàng Châu - Ô Trấn',summary:'Hành trình Giang Nam kết hợp đô thị hiện đại và cổ trấn.',status:'published',salePrice:'Liên hệ',slug:'thuong-hai-hang-chau-o-tran'},{...blank,id:'tour_danang',name:'Đà Nẵng - Hội An - Bà Nà',category:'Tour trong nước',duration:'4N3Đ',route:'Đà Nẵng - Hội An - Bà Nà',summary:'Tour miền Trung kết hợp biển, phố cổ và Bà Nà.',status:'published',salePrice:'Liên hệ',slug:'da-nang-hoi-an-ba-na'}];
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

export function AdminTourEditor(){
 const key='tn_cms_tours_v2';const [items,setItems]=useState<Tour[]>([]);const [mode,setMode]=useState<'list'|'edit'>('list');const [form,setForm]=useState<Tour>(blank);const [tab,setTab]=useState(sections[0]);const [message,setMessage]=useState('');
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(key)||'null')||seed)}catch{setItems(seed)}},[]);
 const persist=(next:Tour[])=>{setItems(next);localStorage.setItem(key,JSON.stringify(next))};
 function edit(t:Tour){setForm({...t});setTab(sections[0]);setMessage('');setMode('edit')}
 function add(){setForm(blank);setTab(sections[0]);setMessage('');setMode('edit')}
 function dup(t:Tour){const copy={...t,id:`tour_${Date.now()}`,name:`${t.name} - Bản sao`,slug:`${t.slug}-copy`,status:'draft'};persist([...items,copy]);edit(copy)}
 function set<K extends keyof Tour>(k:K,v:Tour[K]){setForm(f=>({...f,[k]:v}))}
 function save(status:string){if(!form.name.trim()){setMessage('Vui lòng nhập tên tour.');return}const next={...form,id:form.id||`tour_${Date.now()}`,slug:form.slug||slugify(form.name),status};const exists=items.some(x=>x.id===next.id);persist(exists?items.map(x=>x.id===next.id?next:x):[...items,next]);setForm(next);setMessage(exists?'Đã cập nhật tour cũ.':'Đã thêm tour mới.');}
 if(mode==='list')return <section className="admin-panel tour-editor-admin"><div className="admin-panel-head"><div><h2>Tour du lịch</h2><p>Chỉnh sửa tour cũ hoặc thêm mới. Form chi tiết giữ cấu trúc giống trang bán tour chuyên nghiệp.</p></div><button className="admin-primary" onClick={add}>+ Thêm tour mới</button></div><div className="pm-list">{items.map(t=><article key={t.id}><div className="pm-placeholder">✈</div><div className="pm-info"><b>{t.name}</b><span>{t.category} · {t.duration||'Chưa nhập thời lượng'}</span><small>{t.route}</small></div><strong>{t.salePrice||t.price||'Liên hệ'}</strong><em className={`pm-status ${t.status}`}>{t.status==='published'?'Đang bán':t.status==='hidden'?'Đang ẩn':'Bản nháp'}</em><div className="pm-actions"><button onClick={()=>edit(t)}>Sửa</button><button onClick={()=>dup(t)}>Nhân bản</button></div></article>)}</div></section>;
 return <section className="admin-panel tour-editor-admin"><div className="admin-panel-head"><div><button className="editor-back" onClick={()=>setMode('list')}>← Danh sách Tour</button><h2>{form.id?'Chỉnh sửa Tour':'Thêm Tour mới'}</h2><p>{message||'Các trường được chia theo đúng cấu trúc trang chi tiết tour ngoài website.'}</p></div><div><button onClick={()=>save('draft')}>Lưu nháp</button> <button className="admin-primary" onClick={()=>save('published')}>{form.id?'Cập nhật & đăng':'Thêm & đăng'}</button></div></div><div className="tour-editor-tabs">{sections.map(s=><button key={s} className={tab===s?'active':''} onClick={()=>setTab(s)}>{s}</button>)}</div>
 {tab==='Thông tin cơ bản'&&<div className="tour-editor-grid"><label>Tên tour<input value={form.name} onChange={e=>{const old=form.name;set('name',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}}/></label><label>Danh mục<select value={form.category} onChange={e=>set('category',e.target.value)}><option>Tour Trung Quốc</option><option>Tour trong nước</option></select></label><label>Thời lượng<input value={form.duration} onChange={e=>set('duration',e.target.value)}/></label><label>Khởi hành từ<input value={form.departure} onChange={e=>set('departure',e.target.value)}/></label><label>Hãng bay<input value={form.airline} onChange={e=>set('airline',e.target.value)}/></label><label>Tuyến điểm đến<input value={form.route} onChange={e=>set('route',e.target.value)}/></label><label>Phương tiện<input value={form.transport} onChange={e=>set('transport',e.target.value)}/></label><label>Trạng thái<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="published">Đang bán</option><option value="draft">Nháp</option><option value="hidden">Ẩn</option></select></label><label className="span-2">Mô tả ngắn<textarea rows={5} value={form.summary} onChange={e=>set('summary',e.target.value)}/></label></div>}
 {tab==='Giá & lịch khởi hành'&&<div className="tour-editor-grid"><label>Giá gốc<input value={form.price} onChange={e=>set('price',e.target.value)}/></label><label>Giá bán từ<input value={form.salePrice} onChange={e=>set('salePrice',e.target.value)}/></label><label>Giá trẻ em<input value={form.childPrice} onChange={e=>set('childPrice',e.target.value)}/></label><label>Phụ thu phòng đơn<input value={form.singleCharge} onChange={e=>set('singleCharge',e.target.value)}/></label><label className="span-2">Lịch khởi hành<textarea rows={8} value={form.departures} onChange={e=>set('departures',e.target.value)} placeholder="Mỗi dòng một ngày khởi hành"/></label></div>}
 {tab==='Album ảnh'&&<div className="tour-editor-grid"><label className="span-2">Album ảnh<textarea rows={10} value={form.gallery} onChange={e=>set('gallery',e.target.value)} placeholder="Mỗi dòng một URL ảnh; sau này chọn trực tiếp từ Media/Drive"/></label></div>}
 {tab==='Điểm nổi bật'&&<div className="tour-editor-grid"><label className="span-2">Mỗi dòng một điểm nổi bật<textarea rows={10} value={form.highlights} onChange={e=>set('highlights',e.target.value)}/></label></div>}
 {tab==='Lịch trình'&&<div className="tour-editor-grid"><label className="span-2">Lịch trình từng ngày<textarea rows={18} value={form.itinerary} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1: ...\nNgày 2: ..."/></label></div>}
 {tab==='Dịch vụ'&&<div className="tour-editor-grid"><label>Giá bao gồm<textarea rows={12} value={form.included} onChange={e=>set('included',e.target.value)}/></label><label>Không bao gồm<textarea rows={12} value={form.excluded} onChange={e=>set('excluded',e.target.value)}/></label></div>}
 {tab==='Chính sách'&&<div className="tour-editor-grid"><label className="span-2">Đặt cọc / hoàn hủy / trẻ em<textarea rows={15} value={form.policies} onChange={e=>set('policies',e.target.value)}/></label></div>}
 {tab==='Ưu đãi'&&<div className="tour-editor-grid"><label className="span-2">Nội dung ưu đãi<textarea rows={10} value={form.promotion} onChange={e=>set('promotion',e.target.value)}/></label></div>}
 {tab==='Đánh giá & FAQ'&&<div className="tour-editor-grid"><label>Điểm đánh giá<input value={form.rating} onChange={e=>set('rating',e.target.value)}/></label><label>Số đánh giá<input value={form.reviewCount} onChange={e=>set('reviewCount',e.target.value)}/></label><label className="span-2">FAQ<textarea rows={12} value={form.faq} onChange={e=>set('faq',e.target.value)} placeholder="Hỏi: ...\nĐáp: ..."/></label></div>}
 {tab==='SEO'&&<div className="tour-editor-grid"><label className="span-2">SEO Title<input value={form.seoTitle} onChange={e=>set('seoTitle',e.target.value)}/></label><label className="span-2">Meta description<textarea rows={5} value={form.seoDescription} onChange={e=>set('seoDescription',e.target.value)}/></label><label>Slug<input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></label></div>}
 </section>;
}
