'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {readCurrentStaff} from '@/components/AdminSalesAccess';

type Department='all'|'marketing'|'resa'|'product'|'sales'|'accounting';
type StaffDepartment=Exclude<Department,'all'>;
type ChatScope='room'|'direct';
type Msg={id:string;senderId:string;senderName:string;scope:ChatScope;room?:Department;targetId?:string;targetName?:string;text:string;createdAt:string};
type Staff={id:string;name:string;email:string;status:string;role:string;department:StaffDepartment};

const CHAT='happygo_admin_team_chat_v4';
const OLD_CHAT='happygo_admin_team_chat_v3';
const STAFF='tn_admin_staff_v1';
const ROOM='happygo_admin_chat_room_v4';
const TARGET='happygo_admin_chat_target_v4';
const MODE='happygo_admin_chat_mode_v4';
const labels:Record<Department,string>={all:'Toàn công ty',marketing:'Marketing',resa:'Resa / Đặt phòng',product:'Sản phẩm',sales:'Kinh doanh',accounting:'Kế toán'};
const rooms:Department[]=['all','marketing','resa','product','sales','accounting'];
const initials=(name:string)=>name.trim().split(/\s+/).slice(-2).map(x=>x[0]?.toUpperCase()||'').join('').slice(0,2)||'HG';

function staffDept(role:string,department:unknown):StaffDepartment{
 if(department==='marketing'||department==='resa'||department==='product'||department==='sales'||department==='accounting')return department;
 if(role==='content')return'marketing';if(role==='operations')return'resa';if(role==='accounting')return'accounting';return'sales';
}
function loadStaff():Staff[]{
 try{const parsed=JSON.parse(localStorage.getItem(STAFF)||'[]');if(!Array.isArray(parsed))return[];return parsed.map((x:any)=>({id:String(x?.id||''),name:String(x?.name||''),email:String(x?.email||''),status:String(x?.status||'active'),role:String(x?.role||'sales'),department:staffDept(String(x?.role||'sales'),x?.department)})).filter((x:Staff)=>x.id&&x.name&&x.status==='active')}catch{return[]}
}
function migrateOld():Msg[]{try{const old=JSON.parse(localStorage.getItem(OLD_CHAT)||'[]');if(!Array.isArray(old))return[];return old.map((x:any):Msg=>({id:String(x.id||`old_${Date.now()}`),senderId:String(x.staffId||''),senderName:String(x.name||'Nhân viên'),scope:'room',room:rooms.includes(x.department as Department)?x.department as Department:'all',text:String(x.text||''),createdAt:String(x.createdAt||new Date().toISOString())})).filter((x:Msg)=>x.senderId&&x.text)}catch{return[]}}
function loadMessages():Msg[]{
 try{const parsed=JSON.parse(localStorage.getItem(CHAT)||'[]');if(Array.isArray(parsed)&&parsed.length)return parsed.filter((x:any)=>x&&typeof x==='object').map((x:any):Msg=>({id:String(x.id||''),senderId:String(x.senderId||''),senderName:String(x.senderName||''),scope:x.scope==='direct'?'direct':'room',room:rooms.includes(x.room as Department)?x.room as Department:'all',targetId:x.targetId?String(x.targetId):undefined,targetName:x.targetName?String(x.targetName):undefined,text:String(x.text||''),createdAt:String(x.createdAt||new Date().toISOString())})).filter((x:Msg)=>x.id&&x.senderId&&x.text);const migrated=migrateOld();if(migrated.length)localStorage.setItem(CHAT,JSON.stringify(migrated));return migrated}catch{return[]}
}
function saveMessages(items:Msg[]){try{localStorage.setItem(CHAT,JSON.stringify(items.slice(-1500)));window.dispatchEvent(new Event('happygo-team-chat-v4'))}catch{}}
function timeLabel(value:string){const d=new Date(value),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'});return d.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'})}

export function AdminTeamChat(){
 const[staff,setStaff]=useState<Staff[]>([]);const[messages,setMessages]=useState<Msg[]>([]);const[me,setMe]=useState<Staff|null>(null);const[scope,setScope]=useState<ChatScope>('direct');const[room,setRoom]=useState<Department>('all');const[targetId,setTargetId]=useState('');const[text,setText]=useState('');const[q,setQ]=useState('');const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{const refresh=()=>{const s=loadStaff();const current=readCurrentStaff();setStaff(s);setMe(current?{id:current.id,name:current.name,email:current.email||'',status:current.status||'active',role:current.role||'sales',department:staffDept(current.role||'sales',current.department)}:null);setMessages(loadMessages());const r=localStorage.getItem(ROOM) as Department|null;if(r&&rooms.includes(r))setRoom(r);const mode=localStorage.getItem(MODE);if(mode==='room'||mode==='direct')setScope(mode);const savedTarget=localStorage.getItem(TARGET)||'';if(savedTarget)setTargetId(savedTarget)};refresh();window.addEventListener('storage',refresh);window.addEventListener('tn-staff-updated',refresh);window.addEventListener('happygo-admin-auth',refresh);window.addEventListener('happygo-team-chat-v4',refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener('tn-staff-updated',refresh);window.removeEventListener('happygo-admin-auth',refresh);window.removeEventListener('happygo-team-chat-v4',refresh)}},[]);
 const colleagues=useMemo(()=>staff.filter(x=>x.id!==me?.id),[staff,me?.id]);
 useEffect(()=>{if(scope==='direct'&&!targetId&&colleagues.length)setTargetId(colleagues[0].id)},[scope,targetId,colleagues]);
 useEffect(()=>{try{end.current?.scrollIntoView({block:'end'})}catch{}},[messages.length,scope,room,targetId]);
 const target=colleagues.find(x=>x.id===targetId)||null;
 const directThreads=useMemo(()=>colleagues.map(person=>{const thread=messages.filter(m=>m.scope==='direct'&&((m.senderId===me?.id&&m.targetId===person.id)||(m.senderId===person.id&&m.targetId===me?.id))).sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());const last=thread[thread.length-1];return{person,last,count:thread.length}}).sort((a,b)=>new Date(b.last?.createdAt||0).getTime()-new Date(a.last?.createdAt||0).getTime()||a.person.name.localeCompare(b.person.name,'vi')),[colleagues,messages,me?.id]);
 const filteredThreads=useMemo(()=>{const n=q.trim().toLowerCase();return directThreads.filter(x=>!n||`${x.person.name} ${x.person.email} ${labels[x.person.department]}`.toLowerCase().includes(n))},[directThreads,q]);
 const visibleMessages=useMemo(()=>messages.filter(m=>scope==='room'?m.scope==='room'&&m.room===room:m.scope==='direct'&&target&&((m.senderId===me?.id&&m.targetId===target.id)||(m.senderId===target.id&&m.targetId===me?.id))).sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()),[messages,scope,room,target,me?.id]);
 const roomMembers=scope==='room'?(room==='all'?staff:staff.filter(x=>x.department===room)):[];
 function pickRoom(r:Department){setScope('room');setRoom(r);localStorage.setItem(MODE,'room');localStorage.setItem(ROOM,r)}
 function pickPerson(id:string){setScope('direct');setTargetId(id);localStorage.setItem(MODE,'direct');localStorage.setItem(TARGET,id)}
 function send(){const value=text.trim();if(!me||!value)return;if(scope==='direct'&&!target)return;const msg:Msg=scope==='room'?{id:`msg_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,senderId:me.id,senderName:me.name,scope:'room',room,text:value,createdAt:new Date().toISOString()}:{id:`msg_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,senderId:me.id,senderName:me.name,scope:'direct',targetId:target!.id,targetName:target!.name,text:value,createdAt:new Date().toISOString()};const next=[...messages,msg].slice(-1500);setMessages(next);setText('');saveMessages(next)}
 function resetChat(){if(!confirm('Xóa toàn bộ lịch sử chat nội bộ trên trình duyệt này?'))return;localStorage.removeItem(CHAT);setMessages([]);window.dispatchEvent(new Event('happygo-team-chat-v4'))}
 if(!me)return <section className="admin-panel team-chat-v4"><div className="admin-empty-state"><b>Chưa xác định nhân viên đang đăng nhập</b><p>Hãy đăng nhập lại tài khoản Admin/nhân viên để sử dụng chat nội bộ.</p></div></section>;
 return <section className="admin-panel team-chat-v4"><div className="admin-panel-head chat-v4-title"><div><h2>💬 HappyGo Chat</h2><p>Nhắn riêng giữa nhân viên hoặc trao đổi theo phòng ban, giao diện tối ưu như ứng dụng chat công việc.</p></div><div className="chat-v4-me"><span className="chat-avatar">{initials(me.name)}</span><div><small>ĐANG ĐĂNG NHẬP</small><b>{me.name}</b><em>● Đang hoạt động</em></div></div></div>
 <div className="chat-v4-shell"><aside className="chat-v4-sidebar"><div className="chat-v4-search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm nhân viên..."/></div><div className="chat-v4-tabs"><button className={scope==='direct'?'active':''} onClick={()=>setScope('direct')}>Tin nhắn</button><button className={scope==='room'?'active':''} onClick={()=>setScope('room')}>Nhóm</button></div>{scope==='direct'?<div className="chat-v4-thread-list">{filteredThreads.map(({person,last})=><button key={person.id} className={targetId===person.id?'active':''} onClick={()=>pickPerson(person.id)}><span className="chat-avatar">{initials(person.name)}<i/></span><div><b>{person.name}</b><small>{last?(last.senderId===me.id?'Bạn: ':'')+last.text:`${labels[person.department]} · ${person.role}`}</small></div><time>{last?timeLabel(last.createdAt):''}</time></button>)}{!filteredThreads.length&&<div className="chat-v4-empty-list">Không có nhân viên phù hợp</div>}</div>:<div className="chat-v4-room-list">{rooms.map(r=><button key={r} className={room===r?'active':''} onClick={()=>pickRoom(r)}><span>{r==='all'?'🏢':'👥'}</span><div><b>{labels[r]}</b><small>{r==='all'?staff.length:staff.filter(x=>x.department===r).length} thành viên</small></div></button>)}</div>}<div className="chat-v4-sidebar-foot"><button className="admin-secondary" onClick={resetChat}>Xóa lịch sử chat</button><small>Dữ liệu demo hiện lưu trong trình duyệt.</small></div></aside>
 <div className="chat-v4-conversation"><header className="chat-v4-conversation-head">{scope==='direct'&&target?<><span className="chat-avatar large">{initials(target.name)}<i/></span><div><b>{target.name}</b><small>● Đang hoạt động · {labels[target.department]} · {target.email||target.role}</small></div><div className="chat-v4-head-actions"><a href={target.email?`mailto:${target.email}`:'#'} aria-label="Gửi email">✉</a><button type="button" title="Thông tin nhân viên">ⓘ</button></div></>:<><span className="chat-avatar large group">{room==='all'?'HG':'#'}</span><div><b>{labels[room]}</b><small>{roomMembers.length} thành viên · Kênh trao đổi chung</small></div></>}</header>
 <div className="chat-v4-feed">{visibleMessages.length?visibleMessages.map((m,i)=>{const mine=m.senderId===me.id;const prev=visibleMessages[i-1];const showName=scope==='room'&&!mine&&prev?.senderId!==m.senderId;return <div className={`chat-v4-message-row ${mine?'mine':''}`} key={m.id}>{!mine&&<span className="chat-avatar mini">{initials(m.senderName)}</span>}<div className="chat-v4-bubble-wrap">{showName&&<small className="chat-v4-sender">{m.senderName}</small>}<div className="chat-v4-bubble"><p>{m.text}</p><time>{new Date(m.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time></div></div></div>}):<div className="chat-v4-welcome"><div>{scope==='direct'&&target?initials(target.name):'💬'}</div><b>{scope==='direct'&&target?`Bắt đầu trò chuyện với ${target.name}`:`Kênh ${labels[room]}`}</b><p>{scope==='direct'?'Trao đổi nhanh công việc, hỗ trợ xử lý booking, khách hàng và vận hành.':'Chia sẻ thông tin chung cho các thành viên trong nhóm.'}</p></div>}<div ref={end}/></div>
 <div className="chat-v4-compose"><div className="chat-v4-tools"><button type="button" title="Đính kèm file" disabled>📎</button><button type="button" title="Ảnh" disabled>▧</button><span>Enter để gửi · Shift+Enter xuống dòng</span></div><div className="chat-v4-compose-row"><textarea rows={2} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={scope==='direct'&&target?`Nhắn tin cho ${target.name}...`:`Nhắn vào ${labels[room]}...`}/><button type="button" className="admin-primary" disabled={!text.trim()||(scope==='direct'&&!target)} onClick={send}>Gửi ➤</button></div></div></div>
 {scope==='direct'&&target&&<aside className="chat-v4-info"><span className="chat-avatar profile">{initials(target.name)}<i/></span><h3>{target.name}</h3><p>● Đang hoạt động</p><dl><div><dt>Phòng ban</dt><dd>{labels[target.department]}</dd></div><div><dt>Vai trò</dt><dd>{target.role}</dd></div><div><dt>Email</dt><dd>{target.email||'Chưa cập nhật'}</dd></div></dl><div className="chat-v4-help"><b>Hỗ trợ công việc</b><span>Dùng chat riêng để phối hợp booking, CRM, sản phẩm và điều hành giữa các nhân viên.</span></div></aside>}
 </div><p className="admin-api-note">Chat riêng và chat nhóm đã tách theo đúng tài khoản nhân viên đang đăng nhập. Trên GitHub Pages, dữ liệu vẫn chỉ đồng bộ trong cùng trình duyệt/thiết bị; khi chuyển backend sẽ thay localStorage bằng chat realtime dùng database/WebSocket.</p></section>
}
