export type AdminStaffRole='owner'|'admin'|'sales'|'content'|'operations'|'accounting';
export type AdminStaff={id:string;name:string;email?:string;phone?:string;password?:string;role:string;department?:string;status?:string;permissions?:string[]};
export type SalesAssignment={customerKey:string;staffId:string;staffName:string;assignedAt:string;source?:'manual'|'round_robin'};
export const STAFF_KEY='tn_admin_staff_v1';export const CURRENT_STAFF_KEY='happygo_admin_current_staff_v3';export const ADMIN_SESSION_KEY='happygo_admin_session_v1';export const SALES_ASSIGNMENTS_KEY='happygo_crm_sales_assignments_v1';export const SALES_AUTO_KEY='happygo_crm_auto_assignment_v1';export const OWNER_ID='happygo_owner';
export type SalesAutoSettings={enabled:boolean;lastStaffId:string;assignedCount:number;updatedAt:string};
export function customerKey(phone?:string|null,email?:string|null){const p=String(phone||'').replace(/\D/g,'');if(p)return`phone:${p}`;return`email:${String(email||'').trim().toLowerCase()}`}
export function readStaff():AdminStaff[]{try{const raw=JSON.parse(localStorage.getItem(STAFF_KEY)||'[]');return Array.isArray(raw)?raw.filter((x:any)=>x&&x.id&&x.status!=='inactive'):[]}catch{return[]}}
export function ownerStaff():AdminStaff{return{id:OWNER_ID,name:'Chủ tài khoản HappyGo',role:'owner',department:'sales',status:'active',permissions:['*']}}
export function readCurrentStaff():AdminStaff{try{const session=JSON.parse(sessionStorage.getItem(ADMIN_SESSION_KEY)||'null');const id=String(session?.staffId||'');if(!id)return{id:'',name:'Chưa đăng nhập',role:'guest',status:'inactive',permissions:[]};if(id===OWNER_ID)return ownerStaff();return readStaff().find(x=>x.id===id)||{id:'',name:'Phiên đăng nhập không hợp lệ',role:'guest',status:'inactive',permissions:[]}}catch{return{id:'',name:'Chưa đăng nhập',role:'guest',status:'inactive',permissions:[]}}}
export function isOwner(staff?:AdminStaff|null){return Boolean(staff&&(staff.id===OWNER_ID||staff.role==='owner'))}
export function readAssignments():Record<string,SalesAssignment>{try{const raw=JSON.parse(localStorage.getItem(SALES_ASSIGNMENTS_KEY)||'{}');return raw&&typeof raw==='object'?raw:{}}catch{return{}}}
export function writeAssignments(next:Record<string,SalesAssignment>){localStorage.setItem(SALES_ASSIGNMENTS_KEY,JSON.stringify(next));window.dispatchEvent(new Event('happygo-crm-assignment'))}
export function canViewCustomer(staff:AdminStaff,key:string,assignments=readAssignments()){return isOwner(staff)||Boolean(staff?.id&&assignments[key]?.staffId===staff.id)}
export function salesStaff(){return readStaff().filter(x=>(x.role==='sales'||x.department==='sales')&&x.status!=='inactive').sort((a,b)=>a.id.localeCompare(b.id))}
export function readSalesAutoSettings():SalesAutoSettings{try{return{enabled:false,lastStaffId:'',assignedCount:0,updatedAt:'',...JSON.parse(localStorage.getItem(SALES_AUTO_KEY)||'{}')}}catch{return{enabled:false,lastStaffId:'',assignedCount:0,updatedAt:''}}}
export function writeSalesAutoSettings(v:SalesAutoSettings){localStorage.setItem(SALES_AUTO_KEY,JSON.stringify(v));window.dispatchEvent(new Event('happygo-crm-auto-assignment'))}
export function setSalesAutoEnabled(enabled:boolean){const s=readSalesAutoSettings();writeSalesAutoSettings({...s,enabled,updatedAt:new Date().toISOString()})}
export function nextRoundRobinSale(list=salesStaff()){if(!list.length)return null;const state=readSalesAutoSettings();const i=list.findIndex(x=>x.id===state.lastStaffId);return list[(i+1+list.length)%list.length]||list[0]}
export function autoAssignCustomer(phone?:string|null,email?:string|null){const key=customerKey(phone,email);if(!key||key==='email:')return null;const assignments=readAssignments();if(assignments[key])return assignments[key];const state=readSalesAutoSettings();if(!state.enabled)return null;const sale=nextRoundRobinSale();if(!sale)return null;const assignment:SalesAssignment={customerKey:key,staffId:sale.id,staffName:sale.name,assignedAt:new Date().toISOString(),source:'round_robin'};assignments[key]=assignment;writeAssignments(assignments);writeSalesAutoSettings({...state,lastStaffId:sale.id,assignedCount:(state.assignedCount||0)+1,updatedAt:new Date().toISOString()});return assignment}
export function autoAssignCustomers(customers:Array<{phone?:string|null;email?:string|null}>){let count=0;customers.forEach(c=>{if(autoAssignCustomer(c.phone,c.email))count++});return count}
export function parseMoney(value:unknown){const s=String(value||'').trim().toLowerCase();if(!s)return 0;let n=Number(s.replace(/[^\d]/g,''))||0;if(/triệu|tr\b/.test(s)&&n<1000000)n*=1000000;return n}
export function bookingRevenue(b:any){if(Number.isFinite(Number(b?.revenue)))return Number(b.revenue);const note=String(b?.note||'');const match=note.match(/TỔNG (?:GIÁ TRỊ \/ )?TẠM TÍNH:\s*([^\n]+)/i)||note.match(/TỔNG[^:\n]*:\s*([^\n]+)/i);return parseMoney(match?.[1]||b?.total||b?.amount||b?.price)}
export function money(v:number){return new Intl.NumberFormat('vi-VN').format(Math.round(v))+'đ'}
