'use client';

import {useEffect,useMemo,useState} from 'react';
import {useSiteSettings} from '@/components/useSiteSettings';
import {addCartItem,readCart,writeCart,type GuestType} from '@/components/BookingCart';
import type {PricingBasis} from '@/components/ProductModel';
import {bookingUnitLabel} from '@/lib/booking-unit-selection';
import {marketingBookingSource} from '@/lib/marketing-attribution';
import {parsePricingDate,seasonalUnitPrice} from '@/lib/pricing-calendar';
import {rateForDate,ratePriceForDate,type PublicRateRange} from '@/lib/public-rate-utils';

const API_BASE=(process.env.NEXT_PUBLIC_API_BASE_URL||'').replace(/\/$/,'');
const LOCAL_KEY='tn_local_bookings_v1';
type BookingMode='auto'|'cabin'|'ticket';
type SelectedUnit={id?:string;code?:string;name?:string;pricingBasis?:PricingBasis;guestType?:GuestType;priceGroup?:string};
type PricingDatesDetail={checkin?:string;checkout?:string};
type QuoteUnit={id:string;code?:string;name?:string;status?:string;pricingBasis?:PricingBasis;guestType?:GuestType;priceGroup?:string;ageLabel?:string;ageMin?:string|number;ageMax?:string|number;weekdayPrice?:string;weekendPrice?:string;holidayPrice?:string;lowWeekdayPrice?:string;lowWeekendPrice?:string;highWeekdayPrice?:string;highWeekendPrice?:string;highSeasonRanges?:string;lowSeasonRanges?:string};
function normalizeVietnamPhone(raw:string){const digits=raw.replace(/\D/g,'');if(digits.startsWith('84')&&digits.length===11)return `0${digits.slice(2)}`;return digits}
function saveLocalBooking(payload:any){try{const list=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');const now=new Date();const code=`TN${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(Date.now()).slice(-5)}`;const item={id:Date.now(),code,kind:payload.kind,product:payload.product,customer_name:payload.customerName,phone:payload.phone,email:payload.email||'',start_date:payload.startDate||null,end_date:payload.endDate||null,adults:payload.adults,children:payload.children,rooms:payload.rooms,note:payload.note||'',status:'new',admin_note:'',created_at:now.toISOString(),source:payload.source||'website'};localStorage.setItem(LOCAL_KEY,JSON.stringify([item,...list].slice(0,500)));window.dispatchEvent(new Event('tn-bookings-updated'));return code}catch{return''}}
function nextDay(value:string){if(!value)return'';const d=new Date(value+'T12:00:00');d.setDate(d.getDate()+1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
const fmtMoney=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
const priceGroupFor=(u?:QuoteUnit|null)=>String(u?.priceGroup||u?.name?.split('·')[0]||u?.code?.replace(/-(?:ADULT|C\d+)$/i,'')||'').trim();
const childLabel=(u:QuoteUnit)=>String(u.ageLabel||u.name?.match(/Trẻ\s*(.+)$/i)?.[1]||u.name||'Trẻ em').trim();
function quoteUnitPrice(unit:QuoteUnit|undefined,date:string,rates:PublicRateRange[]){if(!unit||!date)return 0;const parsed=parsePricingDate(date);const rate=rateForDate(rates,unit.id,date);if(rate){if(rate.status!=='available'||Number(rate.quantity||0)<=0)return 0;return ratePriceForDate(rate,parsed)}return seasonalUnitPrice(unit,parsed)}

export function BookingInquiry({product,productId,productSlug,kind='dịch vụ',mode='auto',units=[],initialRates=[]}:{product:string;productId?:string;productSlug?:string;kind?:string;mode?:BookingMode;units?:QuoteUnit[];initialRates?:PublicRateRange[]}){
 const settings=useSiteSettings();const zaloDigits=settings.zalo.replace(/\D/g,'');
 const[state,setState]=useState<'idle'|'sending'|'saved'|'fallback'>('idle');const[code,setCode]=useState('');const[message,setMessage]=useState('');const[selectedUnit,setSelectedUnit]=useState<SelectedUnit|null>(null);
 const normalized=kind.toLowerCase();const isTour=normalized.includes('tour');const isCruise=normalized.includes('du thuyền')||normalized.includes('cruise');const isTicket=isCruise&&mode==='ticket';const isStay=!isTour&&!isCruise;const usesExactCalendar=isStay||isCruise;
 const selectedUnitText=bookingUnitLabel(selectedUnit?.code,selectedUnit?.name);
 const today=useMemo(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},[]);
 const[from,setFrom]=useState('');const[to,setTo]=useState('');const[adults,setAdults]=useState(2);const[children,setChildren]=useState(0);const[rooms,setRooms]=useState(1);const[childCounts,setChildCounts]=useState<Record<string,number>>({});
 useEffect(()=>{if(!usesExactCalendar)return;const read=(event?:Event)=>{const detail=(event as CustomEvent<PricingDatesDetail>|undefined)?.detail;if(detail&&typeof detail==='object'&&('checkin'in detail||'checkout'in detail)){setFrom(String(detail.checkin||''));setTo(isStay?String(detail.checkout||''):'');return}const query=new URLSearchParams(window.location.search);setFrom(query.get('checkin')||'');setTo(isStay?(query.get('checkout')||''):'')};const handle=(event:Event)=>read(event);read();window.addEventListener('popstate',handle);window.addEventListener('tn-pricing-dates-updated',handle);return()=>{window.removeEventListener('popstate',handle);window.removeEventListener('tn-pricing-dates-updated',handle)}},[usesExactCalendar,isStay]);
 useEffect(()=>{const select=(event:Event)=>{const detail=(event as CustomEvent<{id?:string;unitId?:string;code?:string;name?:string;pricingBasis?:PricingBasis;guestType?:GuestType;priceGroup?:string}>).detail||{};const next={id:detail.unitId||detail.id,code:detail.code,name:detail.name,pricingBasis:detail.pricingBasis,guestType:detail.guestType,priceGroup:detail.priceGroup};if(next.id||next.code||next.name)setSelectedUnit(next)};window.addEventListener('tn:select-unit',select as EventListener);try{const stored=JSON.parse(localStorage.getItem('tn_selected_unit')||'null');if(stored?.product===product){const next={id:stored.unitId||stored.id,code:stored.code,name:stored.unit||stored.name,pricingBasis:stored.pricingBasis,guestType:stored.guestType,priceGroup:stored.priceGroup} as SelectedUnit;if(next.id||next.code||next.name)setSelectedUnit(next);localStorage.removeItem('tn_selected_unit')}}catch{}return()=>window.removeEventListener('tn:select-unit',select as EventListener)},[product]);
 const quoteUnits=useMemo(()=>Array.isArray(units)?units.filter(u=>u.status!=='hidden'):[],[units]);
 const selectedQuoteUnit=useMemo(()=>quoteUnits.find(u=>u.id===selectedUnit?.id)||quoteUnits.find(u=>u.code&&u.code===selectedUnit?.code)||null,[quoteUnits,selectedUnit]);
 const selectedGroup=priceGroupFor(selectedQuoteUnit);
 const childUnits=useMemo(()=>selectedQuoteUnit?.guestType==='adult'?quoteUnits.filter(u=>u.guestType==='child'&&priceGroupFor(u)===selectedGroup):[],[quoteUnits,selectedQuoteUnit,selectedGroup]);
 const hasChildPricing=isTicket&&selectedQuoteUnit?.pricingBasis==='guest'&&childUnits.length>0;
 const childCount=hasChildPricing?childUnits.reduce((sum,u)=>sum+Math.max(0,Number(childCounts[u.id]||0)),0):children;
 const quote=useMemo(()=>{if(!isTicket||!from||!selectedQuoteUnit||selectedQuoteUnit.pricingBasis!=='guest')return null;const adultPrice=quoteUnitPrice(selectedQuoteUnit,from,initialRates);const childLines=childUnits.map(unit=>{const count=Math.max(0,Number(childCounts[unit.id]||0));const price=quoteUnitPrice(unit,from,initialRates);return{unit,count,price,total:count*price}});const complete=adultPrice>0&&childLines.every(line=>!line.count||line.price>0);const total=complete?adultPrice*Math.max(1,adults)+childLines.reduce((sum,line)=>sum+line.total,0):0;return{adultPrice,childLines,total,complete}},[isTicket,from,selectedQuoteUnit,initialRates,childUnits,childCounts,adults]);
 useEffect(()=>{setChildCounts(current=>{const next:Record<string,number>={};for(const unit of childUnits)next[unit.id]=Math.max(0,Number(current[unit.id]||0));return next})},[selectedGroup]);
 const syncPricingDates=(nextFrom:string,nextTo='')=>{if(!usesExactCalendar)return;const query=new URLSearchParams(window.location.search);if(nextFrom)query.set('checkin',nextFrom);else query.delete('checkin');if(isStay&&nextTo)query.set('checkout',nextTo);else query.delete('checkout');const search=query.toString();window.history.replaceState(window.history.state,'',`${window.location.pathname}${search?`?${search}`:''}${window.location.hash}`);window.dispatchEvent(new CustomEvent<PricingDatesDetail>('tn-pricing-dates-updated',{detail:{checkin:nextFrom,checkout:isStay?nextTo:''}}))};
 const changeFrom=(value:string)=>{setFrom(value);if(isStay){const corrected=!to||to<=value?nextDay(value):to;setTo(corrected);syncPricingDates(value,corrected)}else if(isCruise)syncPricingDates(value)};
 const changeTo=(value:string)=>{setTo(value);if(isStay)syncPricingDates(from,value)};
 const clearUnit=()=>{setSelectedUnit(null);try{localStorage.removeItem('tn_selected_unit')}catch{}};
 function addToCart(form:HTMLFormElement){setMessage('');const data=new FormData(form);const start=String(data.get('from')||'');const end=String(data.get('to')||'');if((isStay||isCruise)&&!selectedUnit){setMessage(isStay?'Chọn đúng hạng phòng/căn trước khi vào phiếu tạm tính.':'Chọn đúng cabin/vé trước khi vào phiếu tạm tính.');return}if(!start){setMessage(isStay?'Chọn ngày nhận phòng trước khi thêm vào giỏ.':isTour?'Chọn ngày khởi hành trước khi thêm vào giỏ.':'Chọn ngày đi trước khi thêm vào giỏ.');return}if(start<today){setMessage('Ngày đi không thể ở trong quá khứ.');return}if(isStay&&(!end||end<=start)){setMessage('Chọn ngày trả phòng hợp lệ trước khi thêm vào giỏ.');return}const before=readCart();const common={kind,product,productId,productSlug,startDate:start,endDate:isStay?end:'',rooms:isTour?1:rooms};const primary=addCartItem({...common,unit:selectedUnitText,unitId:selectedUnit?.id,adults,children:hasChildPricing?0:childCount,pricingBasis:selectedUnit?.pricingBasis,guestType:selectedUnit?.guestType,explicitQuantity:selectedUnit?.pricingBasis==='guest'?Math.max(1,adults):undefined});if(!primary){setMessage('Hạng đã chọn không còn đủ tồn hoặc chưa có giá hợp lệ cho ngày này. Vui lòng kiểm tra lại.');return}if(hasChildPricing){for(const unit of childUnits){const count=Math.max(0,Number(childCounts[unit.id]||0));if(!count)continue;const added=addCartItem({...common,unit:bookingUnitLabel(unit.code,unit.name),unitId:unit.id,adults:0,children:count,rooms:1,pricingBasis:unit.pricingBasis,guestType:'child',explicitQuantity:count});if(!added){writeCart(before);setMessage('Một nhóm giá trẻ em chưa có giá hoặc không còn đủ chỗ cho ngày này. Vui lòng kiểm tra lại.');return}}}setMessage(quote?.complete?'✓ Đã thêm vào giỏ · tạm tính '+fmtMoney(quote.total):'✓ Đã thêm đúng hạng đã chọn vào giỏ đặt dịch vụ.');setState('idle')}
 async function send(form:HTMLFormElement){setMessage('');setState('idle');const data=new FormData(form);const name=String(data.get('name')||'').trim();const phone=normalizeVietnamPhone(String(data.get('phone')||''));const start=String(data.get('from')||'');const end=String(data.get('to')||'');if(name.length<2){setMessage('Vui lòng nhập họ tên đầy đủ.');return}if(!/^0\d{9}$/.test(phone)){setMessage('Số điện thoại chưa đúng định dạng Việt Nam.');return}if(!start){setMessage(isStay?'Vui lòng chọn ngày nhận phòng.':isTour?'Vui lòng chọn ngày khởi hành.':'Vui lòng chọn ngày đi.');return}if(start<today){setMessage('Ngày đi/nhận phòng không thể ở trong quá khứ.');return}if(isStay&&(!end||end<=start)){setMessage('Ngày trả phòng phải sau ngày nhận phòng.');return}const rawNote=String(data.get('note')||'').trim();const childBreakdown=hasChildPricing?childUnits.map(unit=>{const count=Math.max(0,Number(childCounts[unit.id]||0));return count?childLabel(unit)+': '+count:''}).filter(Boolean).join(' · '):'';const quoteNote=quote?.complete?'Tạm tính tự động: '+fmtMoney(quote.total)+' ('+adults+' người lớn'+(childBreakdown?' · '+childBreakdown:'')+')':'';const note=[selectedUnitText?(isTicket?'Hành trình / hạng':'Căn/phòng/cabin')+' đã chọn: '+selectedUnitText:'',childBreakdown?'Trẻ em: '+childBreakdown:'',quoteNote,rawNote].filter(Boolean).join('\n');const payload={kind,product,productId,productSlug,unitId:selectedUnit?.id,customerName:name,phone,email:String(data.get('email')||'').trim(),startDate:start,endDate:isStay?end:null,adults,children:childCount,rooms:isTour?1:rooms,note,website:String(data.get('website')||''),source:marketingBookingSource()};try{setState('sending');const response=await fetch(API_BASE+'/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(response.ok){setCode(result.code||'');setState('saved');clearUnit();return}if(response.status<500){setState('idle');setMessage(String(result.error||'Không thể gửi yêu cầu lúc này. Vui lòng kiểm tra thông tin và thử lại.'));return}throw new Error('Booking API '+response.status)}catch(error){console.error(error)}const localCode=saveLocalBooking(payload);setCode(localCode);setState('fallback');setMessage('Máy chủ chưa nhận được yêu cầu nên hệ thống đã lưu tạm trên thiết bị này. Vui lòng thử lại hoặc liên hệ Zalo để được xác nhận.');clearUnit()}
 const bookingTitle=isStay?'Đặt phòng & kiểm tra giá':isTicket?'Kiểm tra chỗ & giá':isCruise?'Giữ cabin & kiểm tra giá':'Đăng ký tour & giữ chỗ';
 const headerLabel=isStay?'ĐẶT PHÒNG TRỰC TIẾP':isTicket?'YÊU CẦU ĐẶT VÉ / GÓI':isCruise?'YÊU CẦU ĐẶT CABIN':'YÊU CẦU ĐẶT TOUR';
 const unitLabel=isStay?'Hạng phòng / căn':isTicket?(hasChildPricing?'Hành trình / hạng':'Vé / gói dịch vụ'):isCruise?'Hạng cabin':'Chương trình tour';
 const unitHint=isStay?'Chọn hạng phòng/căn phía trên để xem giá xác nhận đúng ngày.':isTicket?(hasChildPricing?'Chọn hành trình/hạng phía trên. Giá ngoài sản phẩm là giá người lớn; giá trẻ em tự cộng theo nhóm tuổi.':'Chọn vé / gói phía trên để kiểm tra đúng giá ngày khởi hành.'):isCruise?'Chọn cabin cụ thể để kiểm tra đúng giá ngày khởi hành.':'Tour sẽ được giữ theo lịch khởi hành.';
 const submitLabel=isStay?'Gửi yêu cầu đặt phòng':isTicket?'Gửi yêu cầu giữ chỗ':isCruise?'Gửi yêu cầu giữ cabin':'Gửi yêu cầu giữ chỗ';
 return <form className={`inquiry-form inquiry-pro ${isStay?'stay-booking':''}`} onSubmit={e=>{e.preventDefault();send(e.currentTarget)}}><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:'absolute',left:'-10000px',width:1,height:1}}/><div className="inquiry-head-pro"><div className="inquiry-head-icon">{isStay?'🏨':isCruise?'🛳':'✈'}</div><div><small>{headerLabel}</small><h3>{bookingTitle}</h3><p>{product}</p></div></div><div className="inquiry-trust"><span>✓ Chưa thanh toán</span><span>✓ Giá theo lịch thật</span><span>✓ Xác nhận tồn</span></div>
 <section className="inquiry-step"><div className="inquiry-step-title"><b>1</b><div><strong>{unitLabel}</strong><small>{selectedUnitText?'Đã khóa đúng hạng cho phiếu tạm tính':'Có thể chọn hạng ở danh sách phía trên'}</small></div></div>{selectedUnitText?<div className="inquiry-selected"><span>ĐANG CHỌN</span><b>{selectedUnitText}</b><button type="button" onClick={clearUnit}>Đổi hạng</button></div>:<div className="inquiry-no-unit"><span>⌂</span><div><b>{product}</b><small>{unitHint}</small></div></div>}</section>
 <section className="inquiry-step"><div className="inquiry-step-title"><b>2</b><div><strong>{isStay?'Ngày ở & số khách':isCruise?'Ngày đi & số khách':'Ngày khởi hành & số khách'}</strong><small>{usesExactCalendar?'Chọn ngày sẽ cập nhật ngay giá xác nhận ở danh sách hạng phía trên.':'Nhập đúng nhu cầu để kiểm tra nhanh hơn.'}</small></div></div><div className={isStay?'inquiry-two inquiry-date-grid':'inquiry-one inquiry-date-grid'}><label><span>{isStay?'Nhận phòng':isTour?'Ngày khởi hành':'Ngày đi'}</span><input name="from" type="date" min={today} required value={from} onChange={e=>changeFrom(e.target.value)}/></label>{isStay&&<label><span>Trả phòng</span><input name="to" type="date" min={from||today} required value={to} onChange={e=>changeTo(e.target.value)}/></label>}</div>{usesExactCalendar&&from&&<a className="inquiry-price-jump" href="#units">↑ Xem giá xác nhận cho ngày đã chọn</a>}<div className="inquiry-three inquiry-guest-grid"><label><span>Người lớn</span><input name="adults" type="number" min="1" max="50" value={adults} onChange={e=>setAdults(Math.max(1,Number(e.target.value)||1))}/></label>{hasChildPricing?childUnits.map(unit=><label key={unit.id}><span>Trẻ {childLabel(unit)}</span><input type="number" min="0" max="50" value={childCounts[unit.id]||0} onChange={e=>setChildCounts(current=>({...current,[unit.id]:Math.max(0,Number(e.target.value)||0)}))}/></label>):<label><span>Trẻ em</span><input name="children" type="number" min="0" max="50" value={children} onChange={e=>setChildren(Math.max(0,Number(e.target.value)||0))}/></label>}{!isTour&&<label><span>{isTicket?'Số lượng':isCruise?'Số cabin':'Số phòng/căn'}</span><input name="rooms" type="number" min="1" max="20" value={rooms} onChange={e=>setRooms(Math.max(1,Number(e.target.value)||1))}/></label>}</div>{hasChildPricing&&<div className="inquiry-auto-quote">{quote?.complete?<><small>TẠM TÍNH TỰ ĐỘNG</small><strong>{fmtMoney(quote.total)}</strong><p>{adults} người lớn × {fmtMoney(quote.adultPrice)}{quote.childLines.filter(line=>line.count>0).map(line=><span key={line.unit.id}> · {line.count} trẻ {childLabel(line.unit)} × {fmtMoney(line.price)}</span>)}</p></>:<><small>TẠM TÍNH</small><strong>Chọn ngày để tính giá</strong><p>Giá trẻ em được cộng tự động theo đúng nhóm tuổi.</p></>}</div>}</section>
 <section className="inquiry-step"><div className="inquiry-step-title"><b>3</b><div><strong>Thông tin người đặt</strong><small>Dùng để xác nhận booking; chưa thu tiền ở bước này</small></div></div><div className="inquiry-contact-grid"><label><span>Họ và tên *</span><input name="name" autoComplete="name" placeholder="Nguyễn Văn A"/></label><label><span>Số điện thoại *</span><input name="phone" type="tel" inputMode="tel" autoComplete="tel" placeholder="09xx xxx xxx"/></label></div><label><span>Email</span><input name="email" type="email" autoComplete="email" placeholder="email@example.com"/></label><label><span>Yêu cầu thêm</span><textarea name="note" rows={3} placeholder={isTour?'Điểm đón, yêu cầu ăn uống, tuổi trẻ em...':isTicket?'Loại vé/gói, tuổi trẻ em, yêu cầu riêng...':isCruise?'Hạng cabin, tuổi trẻ em, yêu cầu riêng...':'Giường phụ, view, tầng, tuổi trẻ em, giờ đến dự kiến...'}/></label></section>
 {message&&<p className={message.startsWith('✓')||state==='saved'?'inquiry-success':'inquiry-error'}>{message}</p>}<div className="inquiry-primary-actions"><button className="inquiry-submit" type="submit" disabled={state==='sending'||state==='saved'}>{state==='sending'?'Đang gửi yêu cầu...':state==='saved'?`Đã gửi · ${code}`:submitLabel}</button><small>Miễn phí gửi yêu cầu · chưa phát sinh thanh toán</small></div>{state==='saved'&&<p className="inquiry-success inquiry-success-code">✓ Đã ghi nhận yêu cầu. Mã booking: <b>{code}</b>.</p>}<div className="inquiry-secondary-actions"><button className="inquiry-add-cart" type="button" onClick={e=>addToCart(e.currentTarget.form!)}>＋ Thêm vào giỏ</button><a href="/checkout">Xem giỏ / Xác nhận</a></div>{zaloDigits&&<div className="inquiry-support"><div><small>Cần hỗ trợ nhanh?</small><b>Chat với HappyGo</b></div><a className="inquiry-zalo" href={`https://zalo.me/${zaloDigits}`} target="_blank" rel="noreferrer">Zalo</a></div>}</form>;
}
