'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {resolveCommerce} from '@/components/ProductCommerce';import {defaultPricingBasis,type PricingBasis,type ProductType} from '@/components/ProductModel';import {inventoryAllowsStay,resolveInventory} from '@/components/ProductInventory';
export type GuestType='adult'|'child'|'all';export type CartItem={id:string;kind:string;product:string;productId?:string;productSlug?:string;unit?:string;unitId?:string;startDate?:string;endDate?:string;adults:number;children:number;rooms:number;pricingBasis?:PricingBasis;guestType?:GuestType;explicitQuantity?:number;priceLabel?:string;sellingPrice?:number;costPrice?:number|null;availableQuantity?:number|null;inventorySource?:string;inventoryStatus?:string;minStay?:number;sellingSource?:string;costSource?:string;priceSourceLabel?:string;priceCalculatedAt?:string;createdAt:string};
type StoredUnit={id?:string;code?:string;name?:string;pricingBasis?:PricingBasis};type StoredProduct={id?:string;slug?:string;name?:string;pricingBasis?:PricingBasis;units?:StoredUnit[]};
const KEY='tn_booking_cart_v1',PRODUCTS_KEY='tn_cms_products_v3_units';export function readCart():CartItem[]{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}export function writeCart(items:CartItem[]){localStorage.setItem(KEY,JSON.stringify(items));window.dispatchEvent(new Event('tn-cart-updated'))}
function storedBasis(item:Omit<CartItem,'id'|'createdAt'>):PricingBasis|undefined{try{const all=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'[]') as StoredProduct[];const p=(Array.isArray(all)?all:[]).find(x=>item.productId&&x.id===item.productId)||(Array.isArray(all)?all:[]).find(x=>item.productSlug&&x.slug===item.productSlug)||(Array.isArray(all)?all:[]).find(x=>x.name===item.product);if(!p)return;const u=(p.units||[]).find(x=>item.unitId&&x.id===item.unitId)||(p.units||[]).find(x=>item.unit&&(item.unit.includes(x.code||'')||item.unit.includes(x.name||'')));return u?.pricingBasis||p.pricingBasis}catch{return undefined}}
function basisFor(item:Omit<CartItem,'id'|'createdAt'>):PricingBasis{if(item.pricingBasis)return item.pricingBasis;const stored=storedBasis(item);if(stored)return stored;const k=String(item.kind||'').toLowerCase();const type:ProductType=k.includes('tour')?'Tour':k.includes('du thuyền')||k.includes('cruise')?'Du thuyền':k.includes('villa')||k.includes('resort')?'Villa & Resort':'Khách sạn';return defaultPricingBasis(type)}
function guestQuantity(item:Pick<CartItem,'adults'|'children'|'guestType'|'explicitQuantity'>){if(Number(item.explicitQuantity)>0)return Math.max(1,Math.floor(Number(item.explicitQuantity)));if(item.guestType==='adult')return Math.max(1,item.adults||0);if(item.guestType==='child')return Math.max(1,item.children||0);return Math.max(1,(item.adults||0)+(item.children||0))}
export function cartItemQuantity(item:Pick<CartItem,'adults'|'children'|'rooms'|'guestType'|'explicitQuantity'|'pricingBasis'>,nights=1){if(item.pricingBasis==='guest')return guestQuantity(item);if(item.pricingBasis==='package')return Math.max(1,Number(item.explicitQuantity)||item.rooms||1);return Math.max(1,nights)*Math.max(1,item.rooms||1)}
export function addCartItem(item:Omit<CartItem,'id'|'createdAt'>){const snapshot=resolveCommerce({productId:item.productId,unitId:item.unitId,date:item.startDate,manualSelling:item.sellingPrice||item.priceLabel,manualCost:item.costPrice??undefined}),pricingBasis=basisFor(item),requested=pricingBasis==='guest'?guestQuantity(item):Math.max(1,Number(item.explicitQuantity)||item.rooms||1),inventory=resolveInventory({productId:item.productId,unitId:item.unitId,date:item.startDate});if(!snapshot.isAvailable||!inventoryAllowsStay({productId:item.productId,unitId:item.unitId,startDate:item.startDate,endDate:item.endDate,pricingBasis,quantity:requested}))return null;const items=readCart();const next:CartItem={...item,pricingBasis,sellingPrice:snapshot.sellingPrice||item.sellingPrice||undefined,costPrice:item.costPrice??snapshot.costPrice,availableQuantity:item.availableQuantity??inventory.remaining??snapshot.availableQuantity,inventorySource:item.inventorySource||inventory.source||snapshot.inventorySource,inventoryStatus:inventory.status,minStay:inventory.minStay,sellingSource:snapshot.sellingSource||item.sellingSource,costSource:snapshot.costSource||item.costSource,priceSourceLabel:snapshot.sourceLabel||item.priceSourceLabel,priceCalculatedAt:new Date().toISOString(),id:`cart_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,createdAt:new Date().toISOString()};writeCart([...items,next]);return next}
export function BookingCartBadge(){const[count,setCount]=useState(0);useEffect(()=>{const load=()=>setCount(readCart().length);load();window.addEventListener('tn-cart-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('tn-cart-updated',load);window.removeEventListener('storage',load)}},[]);return <Link className="booking-cart-badge" href="/thanh-toan" aria-label={`Giỏ đặt dịch vụ có ${count} mục`}><span>🧳</span><b>Đặt dịch vụ</b>{count>0&&<em>{count}</em>}</Link>}
