'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';

type Booking={id:number;code:string;kind:string;product:string;customer_name:string;phone:string;email?:string;start_date?:string|null;end_date?:string|null;adults:number;children:number;rooms:number;note?:string;status:'new'|'contacting'|'confirmed'|'completed'|'cancelled';created_at:string};
const KEY='tn_local_bookings_v1';const PROFILE='tn_customer_profile_v1';const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';const labels:Record<Booking['status'],string>={new:'Đã tiếp nhận',contacting:'Đang tư vấn',confirmed:'Đã xác nhận',completed:'Hoàn thành',cancelled:'Đã hủy'};const steps:Booking['status'][]=['new','contacting','confirmed','completed'];const phone=(v:string)=>{const d=v.replace(/\D/g,'');return d.startsWith('84')&&d.length===11?`0${d.slice(2)}`:d};function read(){try{return JSON.parse(localStorage.getItem(KEY)||'[]') as Booking[]}catch{return[]}}
export function BookingLookup({account=false}:{account?:boolean}){const settings=useSiteSettings();const supportPhone=settings.hotline.replace(/\D/g,'');const supportLabel=formatPhone(settings.hotline);const[items,setItems]=useState<Booking[]>([]);const[code,setCode]=useState('');const[phoneInput,setPhoneInput]=useState('');const[name,setName]=useState('');const[email,setEmail]=useState('');const[searched,setSearched]=useState(account);const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false);
 useEffect(()=>{setItems(read());try{const p=JSON.parse(localStorage.getItem(PROFILE)||'null');if(p){setPhoneInput(p.phone||'');setName(p.name||'');setEmail(p.email||'')}}catch{}},[]);
 const localResult=useMemo(()=>{const p=phone(phoneInput);return items.filter(x=>(!code.trim()||x.code.toLowerCase()===code.trim().toLowerCase())&&(!p||phone(x.phone)===p))},[items,code,phoneInput]);
 async function lookup(){const p=phone(phoneInput);if(p.length<10){setMsg('Vui lòng nhập đúng số điện thoại đã dùng khi đặt dịch vụ.');return}setMsg('');setSearched(true);if(!API_BASE)return;setLoading(true);try{const endpoint=account?`/api/public/bookings/by-phone?phone=${encodeURIComponent(p)}`:`/api/public/bookings/lookup?code=${encodeURIComponent(code.trim())}&phone=${encodeURIComponent(p)}`;const r=await fetch(`${API_BASE.replace(/\/$/,'')}${endpoint}`);if(r.ok){const d=await r.json();setItems(account?(d.items||[]):(d.item?[d.item]:[]));return}setItems([]);setMsg('Không tìm thấy booking trên hệ thống.')}catch{setMsg('Chưa kết nối được máy chủ, đang hiển thị dữ liệu trên thiết bị này.');setItems(read())}finally{setLoading(false)}}
 const saveProfile=async()=>{const p=phone(phoneInput);if(p.length<10){setMsg('Vui lòng nhập số điện thoại hợp lệ.');return}localStorage.setItem(PROFILE,JSON.stringify({phone:p,name,email}));setPhoneInput(p);setMsg(API_BASE?'Đã lưu thông tin trên thiết bị. Đang tải lịch sử từ hệ thống...':'Đã lưu thông tin khách hàng trên thiết bị này.');setSearched(true);if(API_BASE)await lookup()};
 const result=API_BASE&&searched?items:localResult;
 return <section className="customer-portal"><div className="container customer-portal-wrap"><div className="customer-portal-head"><small>{account?'KHU VỰC KHÁCH HÀNG':'TRA CỨU ĐƠN ĐẶT DỊCH VỤ'}</small><h1>{account?'Lịch sử đặt dịch vụ':'Tra cứu booking của bạn'}</h1><p>{account?(API_BASE?'Lịch sử booking được tải từ hệ thống theo số điện thoại.':'Lưu thông tin liên hệ để xem nhanh các yêu cầu đã gửi trên thiết bị này.'):'Nhập mã booking và số điện thoại để xem trạng thái xử lý yêu cầu.'}</p></div><div className="customer-portal-grid"><aside className="customer-lookup-card">{account&&<><label>Họ và tên<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn A"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/></label></>}{!account&&<label>Mã booking<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="VD: TN20260823-12345"/></label>}<label>Số điện thoại<input value={phoneInput} onChange={e=>setPhoneInput(e.target.value)} placeholder="0969 973 949"/></label><button onClick={account?saveProfile:lookup} disabled={loading}>{loading?'Đang tải...':account?'Lưu & xem lịch sử':'Tra cứu booking'}</button>{msg&&<p className="portal-message">{msg}</p>}<div className="portal-help"><b>Cần hỗ trợ?</b><p>{API_BASE?'Booking được tra cứu từ hệ thống trung tâm.':'Bản GitHub Pages hiện lưu dữ liệu theo từng trình duyệt; khi có hosting trang này sẽ tự đọc database chung.'}</p><a href={`tel:${supportPhone}`}>☎ {supportLabel}</a><Link href="/checkout">Tạo yêu cầu mới →</Link></div></aside><main className="customer-bookings">{searched&&result.length===0&&<div className="portal-empty"><span>⌕</span><h2>Chưa tìm thấy booking</h2><p>Kiểm tra lại mã đơn và số điện thoại.</p><Link href="/">Quay lại tìm dịch vụ</Link></div>}{searched&&result.map(b=><article className="customer-booking-card" key={b.id}><div className="customer-booking-top"><div><small>MÃ BOOKING</small><b>{b.code}</b></div><span className={`customer-status ${b.status}`}>{labels[b.status]}</span></div><h2>{b.product}</h2><div className="customer-booking-meta"><span>{b.kind}</span><span>Ngày đi: {b.start_date||'Chưa xác định'}</span>{b.end_date&&<span>Ngày trả: {b.end_date}</span>}<span>{b.adults} người lớn · {b.children} trẻ em · {b.rooms} phòng/cabin</span></div>{b.status!=='cancelled'&&<div className="booking-progress">{steps.map((s,i)=>{const current=steps.indexOf(b.status);return <div className={i<=current?'done':''} key={s}><i>{i<current?'✓':i+1}</i><span>{labels[s]}</span></div>})}</div>}{b.note&&<div className="customer-booking-note"><b>Thông tin yêu cầu</b><p>{b.note}</p></div>}<div className="customer-booking-actions"><Link href="/">Đặt thêm dịch vụ</Link><Link href={`/payment?code=${encodeURIComponent(b.code)}&phone=${encodeURIComponent(b.phone)}`}>Thanh toán</Link><a href={`tel:${supportPhone}`}>Gọi {supportLabel}</a></div></article>)}</main></div></div></section>}
