'use client';

import { useEffect, useMemo, useState } from 'react';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';
import {addCartItem} from '@/components/BookingCart';
import {marketingBookingSource} from '@/lib/marketing-attribution';

const API_BASE = (process.env.NEXT_PUBLIC_API_BASE_URL || '').replace(/\/$/,'');
const LOCAL_KEY='tn_local_bookings_v1';
function normalizeVietnamPhone(raw:string){const digits=raw.replace(/\D/g,'');if(digits.startsWith('84')&&digits.length===11)return `0${digits.slice(2)}`;return digits}
function saveLocalBooking(payload:any){try{const list=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');const now=new Date();const code=`TN${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(Date.now()).slice(-5)}`;const item={id:Date.now(),code,kind:payload.kind,product:payload.product,customer_name:payload.customerName,phone:payload.phone,email:payload.email||'',start_date:payload.startDate||null,end_date:payload.endDate||null,adults:payload.adults,children:payload.children,rooms:payload.rooms,note:payload.note||'',status:'new',admin_note:'',created_at:now.toISOString(),source:payload.source||'website'};localStorage.setItem(LOCAL_KEY,JSON.stringify([item,...list].slice(0,500)));window.dispatchEvent(new Event('tn-bookings-updated'));return code}catch{return ''}}

export function BookingInquiry({product,kind='dịch vụ'}:{product:string;kind?:string}){
  const [state,setState]=useState<'idle'|'sending'|'saved'|'fallback'>('idle');const [code,setCode]=useState('');const [message,setMessage]=useState('');const [selectedUnit,setSelectedUnit]=useState('');const settings=useSiteSettings();const phoneDigits=settings.hotline.replace(/\D/g,'');const phoneLabel=formatPhone(settings.hotline);const zaloDigits=settings.zalo.replace(/\D/g,'')||phoneDigits;const normalized=kind.toLowerCase();const isTour=normalized.includes('tour');const isCruise=normalized.includes('du thuyền')||normalized.includes('cruise');const isStay=!isTour&&!isCruise;const today=useMemo(()=>{const d=new Date();const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`},[]);
  useEffect(()=>{const select=(event:Event)=>{const detail=(event as CustomEvent<{code?:string;name?:string}>).detail||{};const value=[detail.code,detail.name].filter(Boolean).join(' · ');if(value)setSelectedUnit(value)};window.addEventListener('tn:select-unit',select as EventListener);try{const stored=JSON.parse(localStorage.getItem('tn_selected_unit')||'null');if(stored?.product===product){const value=[stored.code,stored.unit].filter(Boolean).join(' · ');if(value)setSelectedUnit(value);localStorage.removeItem('tn_selected_unit')}}catch{}return()=>window.removeEventListener('tn:select-unit',select as EventListener)},[product]);
  const clearUnit=()=>{setSelectedUnit('');try{localStorage.removeItem('tn_selected_unit')}catch{}};
  function addToCart(form:HTMLFormElement){setMessage('');const data=new FormData(form);const from=String(data.get('from')||'');const to=String(data.get('to')||'');if(!from){setMessage(isStay?'Chọn ngày nhận phòng trước khi thêm vào giỏ.':isTour?'Chọn ngày khởi hành trước khi thêm vào giỏ.':'Chọn ngày đi trước khi thêm vào giỏ.');return}if(from<today){setMessage('Ngày đi không thể ở trong quá khứ.');return}if(isStay&&(!to||to<=from)){setMessage('Chọn ngày trả phòng hợp lệ trước khi thêm vào giỏ.');return}addCartItem({kind,product,unit:selectedUnit,startDate:from,endDate:isStay?to:'',adults:Number(data.get('adults')||2),children:Number(data.get('children')||0),rooms:isTour?1:Number(data.get('rooms')||1)});setMessage('✓ Đã thêm vào giỏ đặt dịch vụ. Anh/chị có thể chọn thêm dịch vụ hoặc sang bước xác nhận.');setState('idle')}
  async function send(form:HTMLFormElement){setMessage('');setState('idle');const data=new FormData(form);const name=String(data.get('name')||'').trim();const phone=normalizeVietnamPhone(String(data.get('phone')||''));const from=String(data.get('from')||'');const to=String(data.get('to')||'');if(name.length<2){setMessage('Vui lòng nhập họ tên đầy đủ.');return}if(!/^0\d{9}$/.test(phone)){setMessage('Số điện thoại chưa đúng. Có thể nhập 0969 973 949, 0969.973.949 hoặc +84 969 973 949.');return}if(!from){setMessage(isStay?'Vui lòng chọn ngày nhận phòng.':isTour?'Vui lòng chọn ngày khởi hành.':'Vui lòng chọn ngày đi.');return}if(from<today){setMessage('Ngày đi/nhận phòng không thể ở trong quá khứ.');return}if(isStay&&!to){setMessage('Vui lòng chọn ngày trả phòng.');return}if(isStay&&to<=from){setMessage('Ngày trả phòng phải sau ngày nhận phòng.');return}const rawNote=String(data.get('note')||'').trim();const note=[selectedUnit?`Căn/phòng/cabin đã chọn: ${selectedUnit}`:'',rawNote].filter(Boolean).join('\n');const payload={kind,product,customerName:name,phone,email:String(data.get('email')||'').trim(),startDate:from,endDate:isStay?to:null,adults:Number(data.get('adults')||2),children:Number(data.get('children')||0),rooms:isTour?1:Number(data.get('rooms')||1),note,source:marketingBookingSource()};try{setState('sending');const response=await fetch(`${API_BASE}/api/bookings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Booking API error');const result=await response.json();setCode(result.code||'');setState('saved');form.reset();clearUnit();return}catch(error){console.error(error)}const localCode=saveLocalBooking(payload);setCode(localCode);setState('fallback');setMessage('Máy chủ chưa nhận được yêu cầu nên hệ thống đã lưu tạm trên thiết bị này. Vui lòng gọi hotline nếu cần xác nhận ngay.');form.reset();clearUnit();}
  const bookingTitle=isStay?'Đặt phòng & nhận giá tốt':isCruise?'Giữ cabin & nhận tư vấn':'Đăng ký tour & giữ chỗ';
  return <form className={`inquiry-form inquiry-pro ${isStay?'stay-booking':''}`} onSubmit={e=>{e.preventDefault();send(e.currentTarget)}}>
    <div className="inquiry-head-pro"><div className="inquiry-head-icon">{isStay?'🏨':isCruise?'🛳':'✈'}</div><div><small>{isStay?'ĐẶT PHÒNG TRỰC TIẾP':isCruise?'YÊU CẦU ĐẶT CABIN':'YÊU CẦU ĐẶT TOUR'}</small><h3>{bookingTitle}</h3><p>{product}</p></div></div>
    <div className="inquiry-trust"><span>✓ Chưa thanh toán</span><span>✓ Kiểm tra tồn thực tế</span><span>✓ Sale xác nhận giá</span></div><section className="inquiry-step"><div className="inquiry-step-title"><b>1</b><div><strong>{isStay?'Hạng phòng / căn':isCruise?'Hạng cabin':'Chương trình tour'}</strong><small>{selectedUnit?'Đã chọn dịch vụ cụ thể':'Có thể chọn hạng ở danh sách phía trên'}</small></div></div>{selectedUnit?<div className="inquiry-selected"><span>ĐANG CHỌN</span><b>{selectedUnit}</b><button type="button" onClick={clearUnit}>Đổi hạng</button></div>:<div className="inquiry-no-unit"><span>⌂</span><div><b>{product}</b><small>{isStay?'Chưa chọn hạng phòng/căn cụ thể — sale sẽ tư vấn theo số khách.':isCruise?'Chưa chọn cabin cụ thể — sale sẽ tư vấn hạng phù hợp.':'Tour đã chọn sẽ được giữ theo lịch khởi hành.'}</small></div></div>}</section><section className="inquiry-step"><div className="inquiry-step-title"><b>2</b><div><strong>{isStay?'Ngày ở & số khách':isCruise?'Ngày đi & số khách':'Ngày khởi hành & số khách'}</strong><small>Nhập đúng nhu cầu để kiểm tra giá và tình trạng nhanh hơn</small></div></div><div className={isStay?'inquiry-two inquiry-date-grid':'inquiry-one inquiry-date-grid'}><label><span>{isStay?'Nhận phòng':isTour?'Ngày khởi hành':'Ngày đi'}</span><input name="from" type="date" min={today} required/></label>{isStay&&<label><span>Trả phòng</span><input name="to" type="date" min={today} required/></label>}</div><div className="inquiry-three inquiry-guest-grid"><label><span>Người lớn</span><input name="adults" type="number" min="1" max="50" defaultValue="2"/></label><label><span>Trẻ em</span><input name="children" type="number" min="0" max="50" defaultValue="0"/></label>{!isTour&&<label><span>{isCruise?'Số cabin':'Số phòng/căn'}</span><input name="rooms" type="number" min="1" max="20" defaultValue="1"/></label>}</div></section><section className="inquiry-step"><div className="inquiry-step-title"><b>3</b><div><strong>Thông tin người đặt</strong><small>Chúng tôi dùng thông tin này để gọi xác nhận, không thu tiền ở bước này</small></div></div><div className="inquiry-contact-grid"><label><span>Họ và tên *</span><input name="name" autoComplete="name" placeholder="Nguyễn Văn A"/></label><label><span>Số điện thoại *</span><input name="phone" type="tel" inputMode="tel" autoComplete="tel" placeholder={phoneLabel}/></label></div><label><span>Email</span><input name="email" type="email" autoComplete="email" placeholder="email@example.com"/></label><label><span>Yêu cầu thêm</span><textarea name="note" rows={3} placeholder={isTour?'Điểm đón, yêu cầu ăn uống, tuổi trẻ em...':isCruise?'Hạng cabin, tuổi trẻ em, yêu cầu riêng...':'Giường phụ, view, tầng, tuổi trẻ em, giờ đến dự kiến...'}/></label></section>
    {message&&<p className={message.startsWith('✓')||state==='saved'?'inquiry-success':'inquiry-error'}>{message}</p>}
    <div className="inquiry-primary-actions"><button className="inquiry-submit" type="submit" disabled={state==='sending'||state==='saved'}>{state==='sending'?'Đang gửi yêu cầu...':state==='saved'?`Đã gửi · ${code}`:isStay?'Gửi yêu cầu đặt phòng':isCruise?'Gửi yêu cầu giữ cabin':'Gửi yêu cầu giữ chỗ'}</button><small>Miễn phí gửi yêu cầu · chưa phát sinh thanh toán</small></div>
    {state==='saved'&&<p className="inquiry-success inquiry-success-code">✓ Đã ghi nhận yêu cầu. Mã booking: <b>{code}</b>. Tư vấn viên sẽ liên hệ để chốt giá và xác nhận.</p>}
    <div className="inquiry-secondary-actions"><button className="inquiry-add-cart" type="button" onClick={e=>addToCart(e.currentTarget.form!)}>＋ Thêm vào giỏ</button><a href="/checkout">Xem giỏ / Xác nhận</a></div><div className="inquiry-support"><div><small>Cần chốt nhanh?</small><b>Sale hỗ trợ trực tiếp</b></div><a className="inquiry-call" href={`tel:${phoneDigits}`}>☎ {phoneLabel}</a><a className="inquiry-zalo" href={`https://zalo.me/${zaloDigits}`} target="_blank" rel="noreferrer">Zalo</a></div>
  </form>;
}
