'use client';

import Link from 'next/link';
import {useEffect,useState} from 'react';
import {BookingInquiry} from '@/components/BookingInquiry';

type Day={title:string;morning:string;afternoon:string;evening:string;meals:string};
type Tour={id:string;name:string;slug:string;category:string;duration:string;departure:string;airline:string;route:string;transport:string;summary:string;status:string;price:string;salePrice:string;childPrice:string;singleCharge:string;departures:string;gallery:string;highlights:string;days:Day[];included:string;excluded:string;policies:string;promotion:string;rating:string;reviewCount:string;faq:string};

export function CmsTourDetail(){
 const [tour,setTour]=useState<Tour|null|undefined>(undefined);
 useEffect(()=>{try{const slug=new URLSearchParams(window.location.search).get('slug')||'';const items=JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]') as Tour[];setTour(items.find(x=>x.slug===slug&&x.status==='published')||null)}catch{setTour(null)}},[]);
 if(tour===undefined)return <div className="sub-section white"><div className="container"><div className="article-state">Đang tải tour...</div></div></div>;
 if(!tour)return <div className="sub-section white"><div className="container"><div className="article-state"><h2>Không tìm thấy Tour</h2><p>Tour có thể đang ở bản nháp, đã bị ẩn hoặc đã bị xóa.</p><Link href="/tours">← Quay lại Tour du lịch</Link></div></div></div>;
 const images=(tour.gallery||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,5);const departures=(tour.departures||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);const highlights=(tour.highlights||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
 return <div className="cms-product-public"><section className="sub-section white"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / <Link href="/tours">Tour du lịch</Link> / {tour.name}</div><div className="cms-product-head"><div><span className="sub-kicker">{tour.category}</span><h1>{tour.name}</h1><p>📍 {tour.route||'Lịch trình đang cập nhật'}</p><div className="cms-product-meta">{tour.duration&&<span>{tour.duration}</span>}{tour.departure&&<span>Khởi hành: {tour.departure}</span>}{tour.airline&&<span>{tour.airline}</span>}{tour.transport&&<span>{tour.transport}</span>}{tour.rating&&<span>★ {tour.rating}/10</span>}</div></div><div className="cms-product-price"><small>Giá từ</small><strong>{tour.salePrice||tour.price||'Liên hệ'}</strong><a href="#booking">Đặt tour / Nhận tư vấn</a></div></div>{images.length>0&&<div className={`cms-gallery count-${images.length}`}>{images.map((src,i)=><a key={i} href={src} target="_blank" rel="noreferrer"><img src={src} alt={`${tour.name} ${i+1}`}/></a>)}</div>}</div></section><section className="sub-section"><div className="container cms-detail-layout"><main><section className="detail-block"><h2>Tổng quan</h2><p>{tour.summary||'Thông tin tour đang được cập nhật.'}</p>{highlights.length>0&&<ul className="cms-highlights">{highlights.map((x,i)=><li key={i}>✓ {x}</li>)}</ul>}</section>{departures.length>0&&<section className="detail-block"><h2>Lịch khởi hành</h2><div className="cms-departures">{departures.map((x,i)=><span key={i}>{x}</span>)}</div></section>}{tour.days?.length>0&&<section className="detail-block"><h2>Lịch trình từng ngày</h2><div className="cms-tour-days">{tour.days.map((d,i)=><article key={i}><div className="cms-day-badge">Ngày {i+1}</div><div><h3>{d.title||`Ngày ${i+1}`}</h3>{d.morning&&<p><b>Sáng:</b> {d.morning}</p>}{d.afternoon&&<p><b>Chiều:</b> {d.afternoon}</p>}{d.evening&&<p><b>Tối:</b> {d.evening}</p>}{d.meals&&<small>🍽 Bữa ăn: {d.meals}</small>}</div></article>)}</div></section>}{(tour.included||tour.excluded)&&<section className="detail-block"><h2>Dịch vụ</h2><div className="cms-service-grid">{tour.included&&<div><h3>Giá bao gồm</h3><p className="cms-preline">{tour.included}</p></div>}{tour.excluded&&<div><h3>Không bao gồm</h3><p className="cms-preline">{tour.excluded}</p></div>}</div></section>}{tour.policies&&<section className="detail-block"><h2>Chính sách</h2><p className="cms-preline">{tour.policies}</p></section>}{tour.promotion&&<section className="detail-block"><h2>Ưu đãi</h2><p className="cms-preline">{tour.promotion}</p></section>}{tour.faq&&<section className="detail-block"><h2>Hỏi đáp</h2><p className="cms-preline">{tour.faq}</p></section>}</main><aside id="booking"><BookingInquiry product={tour.name} kind="Tour du lịch"/></aside></div></section></div>;
}
