'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {BookingLookup} from '@/components/BookingLookup';
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';const TOKEN='tn_customer_token_v1';
type User={name?:string;customer_name?:string;phone:string;email?:string|null};type Booking={id:number;code:string;kind:string;product:string;start_date?:string|null;end_date?:string|null;adults:number;children:number;rooms:number;status:string;created_at:string};
export function CustomerAccountPortal(){const[mode,setMode]=useState<'login'|'register'>('login');const[token,setToken]=useState('');const[user,setUser]=useState<User|null>(null);const[bookings,setBookings]=useState<Booking[]>([]);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{if(!API_BASE)return;const t=localStorage.getItem(TOKEN)||'';if(t){setToken(t);loadAccount(t)}},[]);
 async function loadAccount(t:string){try{const h={Authorization:`Bearer ${t}`};const[r1,r2]=await Promise.all([fetch(`${API_BASE.replace(/\/$/,'')}/api/account/me`,{headers:h}),fetch(`${API_BASE.replace(/\/$/,'')}/api/account/bookings`,{headers:h})]);if(!r1.ok)throw new Error('Phiên đăng nhập đã hết hạn');const me=await r1.json();const hist=r2.ok?await r2.json():{items:[]};setUser(me.user);setBookings(hist.items||[])}catch(e){localStorage.removeItem(TOKEN);setToken('');setUser(null);setMsg(e instanceof Error?e.message:'Không tải được tài khoản')}}
 async function auth(){setMsg('');if(phone.replace(/\D/g,'').length<10||password.length<8||(mode==='register'&&name.trim().length<2)){setMsg('Vui lòng nhập đầy đủ thông tin; mật khẩu tối thiểu 8 ký tự.');return}setBusy(true);try{const body=mode==='register'?{name:name.trim(),phone,email:email.trim(),password}:{phone,password};const r=await fetch(`${API_BASE.replace(/\/$/,'')}/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error==='Phone already registered'?'Số điện thoại này đã có tài khoản. Hãy đăng nhập.':'Thông tin đăng nhập chưa đúng hoặc chưa hợp lệ.');localStorage.setItem(TOKEN,d.token);setToken(d.token);setUser(d.user);setPassword('');await loadAccount(d.token)}catch(e){setMsg(e instanceof Error?e.message:'Có lỗi xảy ra')}finally{setBusy(false)}}
 async function logout(){if(token)fetch(`${API_BASE.replace(/\/$/,'')}/api/auth/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});localStorage.removeItem(TOKEN);setToken('');setUser(null);setBookings([])}
 if(!API_BASE)return <BookingLookup account/>;
 if(!user)return <section className="customer-portal account-auth-page"><div className="container customer-portal-wrap"><div className="customer-portal-head"><small>TÀI KHOẢN THÚY NGUYÊN TRAVEL</small><h1>{mode==='login'?'Đăng nhập tài khoản':'Tạo tài khoản khách hàng'}</h1><p>Lưu lịch sử booking trên mọi thiết bị và theo dõi trạng thái dịch vụ đã đặt.</p></div><div className="account-auth-card"><div className="account-auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Đăng nhập</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Đăng ký</button></div>{mode==='register'&&<label>Họ và tên<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn A"/></label>}<label>Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="0969 973 949"/></label>{mode==='register'&&<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="email@example.com"/></label>}<label>Mật khẩu<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Tối thiểu 8 ký tự"/></label>{msg&&<p className="portal-message">{msg}</p>}<button className="account-auth-submit" disabled={busy} onClick={auth}>{busy?'Đang xử lý...':mode==='login'?'Đăng nhập':'Tạo tài khoản'}</button><p className="account-security-note">🔒 Mật khẩu được hash ở backend, không lưu trực tiếp trong trình duyệt.</p></div></div></section>;
 return <section className="customer-portal"><div className="container customer-portal-wrap"><div className="account-dashboard-head"><div><small>TÀI KHOẢN KHÁCH HÀNG</small><h1>Xin chào, {user.customer_name||user.name}</h1><p>{user.phone}{user.email?` · ${user.email}`:''}</p></div><button onClick={logout}>Đăng xuất</button></div><div className="account-summary"><div><span>Tổng booking</span><b>{bookings.length}</b></div><div><span>Đang xử lý</span><b>{bookings.filter(x=>['new','contacting'].includes(x.status)).length}</b></div><div><span>Đã xác nhận</span><b>{bookings.filter(x=>x.status==='confirmed').length}</b></div><div><span>Hoàn thành</span><b>{bookings.filter(x=>x.status==='completed').length}</b></div></div><div className="customer-bookings account-booking-list">{bookings.map(b=><article className="customer-booking-card" key={b.id}><div className="customer-booking-top"><div><small>MÃ BOOKING</small><b>{b.code}</b></div><span className={`customer-status ${b.status}`}>{b.status==='new'?'Đã tiếp nhận':b.status==='contacting'?'Đang tư vấn':b.status==='confirmed'?'Đã xác nhận':b.status==='completed'?'Hoàn thành':'Đã hủy'}</span></div><h2>{b.product}</h2><div className="customer-booking-meta"><span>{b.kind}</span><span>{b.start_date||'Chưa chọn ngày'}{b.end_date?` → ${b.end_date}`:''}</span><span>{b.adults} NL · {b.children} TE · {b.rooms} phòng/cabin</span></div><div className="customer-booking-actions"><Link href={`/payment?code=${encodeURIComponent(b.code)}&phone=${encodeURIComponent(user.phone)}`}>Thanh toán</Link><Link href={`/booking-lookup`}>Tra cứu chi tiết</Link></div></article>)}{!bookings.length&&<div className="portal-empty"><span>🧳</span><h2>Chưa có booking</h2><p>Các đơn đặt dịch vụ bằng số điện thoại này sẽ xuất hiện tại đây.</p><Link href="/">Khám phá dịch vụ</Link></div>}</div></div></section>}
