'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Review={id:string;customerName:string;rating:number;comment:string;createdAt:string;verified:boolean;bookingCode?:string};
type Mine={id:string;rating:number;comment:string}|null;
type ReviewData={ok?:boolean;reviews?:Review[];average?:number|null;count?:number;authenticated?:boolean;accountName?:string;eligible?:boolean;bookingCode?:string;mine?:Mine;setupRequired?:boolean;error?:string};

export function CustomerReviews({slug,productName}:{slug:string;productName:string}){
 const[data,setData]=useState<ReviewData>({reviews:[],average:null,count:0,authenticated:false,eligible:false,mine:null});
 const[rating,setRating]=useState(0);const[comment,setComment]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`/api/reviews?slug=${encodeURIComponent(slug)}&name=${encodeURIComponent(productName)}`,{cache:'no-store'});const next=await response.json() as ReviewData;if(!response.ok)throw new Error(next.error||'Không tải được đánh giá.');setData(next);if(next.mine){setRating(next.mine.rating);setComment(next.mine.comment||'')}else{setRating(0);setComment('')}}catch(error){setData({reviews:[],average:null,count:0,authenticated:false,eligible:false,mine:null,error:error instanceof Error?error.message:'Không tải được đánh giá.'})}finally{setLoading(false)}},[slug,productName]);
 useEffect(()=>{void load()},[load]);
 const reviews=data.reviews||[];const avg=useMemo(()=>reviews.length?reviews.reduce((sum,item)=>sum+item.rating,0)/reviews.length:null,[reviews]);
 async function submit(){setMsg('');if(!rating){setMsg('Vui lòng chọn điểm đánh giá.');return}if(comment.trim().length<10){setMsg('Nội dung đánh giá cần ít nhất 10 ký tự.');return}setBusy(true);try{const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,productName,rating,comment:comment.trim()})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Không lưu được đánh giá.');setMsg(data.mine?'Đã cập nhật đánh giá của bạn.':'Cảm ơn bạn đã chia sẻ trải nghiệm thực tế.');await load()}catch(error){setMsg(error instanceof Error?error.message:'Không lưu được đánh giá.')}finally{setBusy(false)}}
 return <section id="reviews" className="pd-block customer-reviews"><div className="review-heading"><div><h2>Đánh giá của khách hàng</h2><p>Chỉ hiển thị đánh giá do khách đã hoàn thành booking tại HappyGo gửi.</p></div><div className="review-score"><b>{avg!==null?`${avg.toFixed(1)}/10`:'—'}</b><small>{reviews.length?`${reviews.length} đánh giá xác thực`:'Chưa có đánh giá'}</small></div></div>{loading?<div className="review-login-required"><b>Đang tải đánh giá...</b></div>:data.error?<div className="review-login-required"><b>Chưa tải được đánh giá</b><p>{data.error}</p></div>:data.authenticated?data.eligible?<div className="review-form"><div className="review-login-state"><b>✓ Khách đã hoàn thành chuyến đi · {data.accountName}</b><span>{data.mine?'Bạn có thể cập nhật đánh giá đã gửi.':data.bookingCode?`Booking ${data.bookingCode} đã được xác minh.`:'Booking đã được xác minh.'}</span></div><label>Điểm đánh giá<select value={rating} onChange={e=>setRating(Number(e.target.value))}><option value={0}>Chọn điểm</option>{[10,9,8,7,6,5,4,3,2,1].map(n=><option key={n} value={n}>{n}/10</option>)}</select></label><label>Nhận xét<textarea rows={4} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Chia sẻ trải nghiệm thực tế về phòng, dịch vụ, tiện ích, hành trình..."/></label><button type="button" onClick={submit} disabled={busy}>{busy?'Đang gửi...':data.mine?'Cập nhật đánh giá':'Gửi đánh giá'}</button>{msg&&<small className="review-message">{msg}</small>}</div>:<div className="review-login-required"><b>Chưa đủ điều kiện đánh giá</b><p>Tài khoản này chưa có booking <strong>{productName}</strong> ở trạng thái <strong>Hoàn thành</strong>. Chỉ khách thực tế mới được để lại đánh giá.</p></div>:<div className="review-login-required"><b>Đăng nhập để đánh giá</b><p>Mọi người đều có thể đọc đánh giá. Chỉ khách đã đăng nhập và có booking hoàn thành mới được viết đánh giá.</p><Link href={`/account?next=${encodeURIComponent(`/product?slug=${slug}#reviews`)}`}>Đăng nhập / Tạo tài khoản</Link></div>}{reviews.length>0?<div className="review-list">{reviews.map(r=><article key={r.id}><div className="review-avatar">{r.customerName.trim().charAt(0).toUpperCase()||'K'}</div><div><div className="review-user"><b>{r.customerName} {r.verified&&<em className="verified-review">✓ Khách đã sử dụng dịch vụ</em>}</b><span>{r.rating}/10</span></div><small>{new Date(r.createdAt).toLocaleDateString('vi-VN')}</small><p>{r.comment}</p></div></article>)}</div>:!loading&&<div className="review-login-required"><b>Chưa có đánh giá khách hàng</b><p>Điểm số sẽ chỉ xuất hiện sau khi có khách đã hoàn thành booking gửi đánh giá.</p></div>}</section>;
}
