'use client';
import Link from 'next/link';import {FormEvent,useMemo,useState} from 'react';import {useSiteSettings} from '@/components/useSiteSettings';import {HappyGoLogo} from '@/components/HappyGoLogo';

function safeExternalUrl(value:string){try{const url=new URL(value);return url.protocol==='https:'||url.protocol==='http:'?url.toString():''}catch{return ''}}

export function Footer(){
 const settings=useSiteSettings();const[email,setEmail]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[ok,setOk]=useState(false);const zaloDigits=settings.zalo.replace(/\D/g,'');
 const socials=useMemo(()=>[{label:'f',name:'Facebook',href:safeExternalUrl(settings.facebookUrl)},{label:'▶',name:'YouTube',href:safeExternalUrl(settings.youtubeUrl)},{label:'♪',name:'TikTok',href:safeExternalUrl(settings.tiktokUrl)},{label:'Zalo',name:'Zalo',href:zaloDigits?`https://zalo.me/${zaloDigits}`:''}].filter(item=>item.href),[settings.facebookUrl,settings.youtubeUrl,settings.tiktokUrl,zaloDigits]);
 async function subscribe(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const website=String(new FormData(form).get('website')||'');const value=email.trim();if(!value)return;setBusy(true);setMsg('');setOk(false);try{const response=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:value,website})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.error||'Chưa thể đăng ký nhận ưu đãi.');setEmail('');setOk(true);setMsg(json.idempotent?'Email này đã có trong danh sách nhận ưu đãi.':'✓ Đã đăng ký nhận ưu đãi thành công.')}catch(error){setMsg(error instanceof Error?error.message:'Chưa thể đăng ký nhận ưu đãi.')}finally{setBusy(false)}}
 return <footer className="happygo-footer"><div className="container happygo-footer-grid"><section className="happygo-footer-brand"><Link href="/" className="footer-happygo-logo happygo-link"><HappyGoLogo/></Link><p><strong>{settings.brand}</strong> – Hành trình hạnh phúc<br/>Kết nối yêu thương. Chúng tôi mang đến cho bạn những hành trình ý nghĩa, dịch vụ chất lượng và trải nghiệm đáng nhớ.</p>{socials.length>0&&<div className="happygo-socials">{socials.map(item=><a key={item.name} href={item.href} target="_blank" rel="noreferrer" aria-label={item.name}>{item.label}</a>)}</div>}</section><section className="happygo-footer-col"><h4>LIÊN HỆ</h4><a href={`mailto:${settings.email}`}><span>✉</span>{settings.email}</a><p><span>⌖</span>Phục vụ khách hàng trên toàn quốc</p><p><span>◷</span>Thứ 2 - Chủ nhật: 08:00 - 21:00</p></section><section className="happygo-footer-col"><h4>VỀ HAPPYGO</h4><Link href="/gioi-thieu">Giới thiệu</Link><Link href="/dieu-khoan">Điều khoản sử dụng</Link><Link href="/chinh-sach-bao-mat">Chính sách bảo mật</Link><Link href="/huong-dan-thanh-toan">Hướng dẫn thanh toán</Link><Link href="/lien-he">Liên hệ</Link></section><section className="happygo-footer-col"><h4>DỊCH VỤ</h4><Link href="/tour-du-lich">Tour du lịch</Link><Link href="/villa-resort">Villa &amp; Resort</Link><Link href="/khach-san">Khách sạn</Link><Link href="/du-thuyen">Du thuyền</Link><Link href="/tim-kiem">Vé máy bay</Link></section><section className="happygo-footer-newsletter"><h4>ĐĂNG KÝ NHẬN ƯU ĐÃI</h4><p>Nhận thông tin khuyến mãi và ưu đãi mới nhất từ {settings.brand}</p><form onSubmit={subscribe}><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:'absolute',left:'-10000px',width:1,height:1}}/><input type="email" value={email} onChange={e=>{setEmail(e.target.value);setMsg('');setOk(false)}} placeholder="Nhập email của bạn" required maxLength={254}/><button type="submit" disabled={busy}>{busy?'Đang đăng ký...':'Đăng ký'}</button></form>{msg&&<small role="status" aria-live="polite" className={ok?'newsletter-success':'newsletter-error'}>{msg}</small>}</section></div><div className="happygo-footer-bottom"><div className="container"><span>© 2026 HappyGo Travel. All rights reserved.</span><span>Thiết kế bởi <b>HappyGo</b> Travel Team</span></div></div><a className="happygo-backtop" href="#top">↑</a></footer>
}
