'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {cruises,stays,tours} from '@/data/catalog';
import {internationalTours} from '@/data/internationalTours';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';

type CmsProduct={id:string;type:string;name:string;slug:string;place:string;summary:string;cover:string;status:string;duration?:string;rating?:string;price?:string};
type CmsTour={id:string;name:string;slug:string;cover?:string;category:string;duration:string;route:string;summary:string;status:string;gallery:string;salePrice:string;price:string};

export function GlobalSearchResults(){
 const params=useSearchParams();const settings=useSiteSettings();const raw=(params.get('q')||'').trim();const q=raw.toLowerCase();const adults=params.get('adults')||'2';const children=params.get('children')||'0';const [cmsProducts,setCmsProducts]=useState<CmsProduct[]>([]);const [cmsTours,setCmsTours]=useState<CmsTour[]>([]);
 useEffect(()=>{const loadProducts=()=>{try{setCmsProducts(JSON.parse(localStorage.getItem('tn_cms_products_v3_units')||'[]') as CmsProduct[])}catch{setCmsProducts([])}};const loadTours=()=>{try{setCmsTours(JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]') as CmsTour[])}catch{setCmsTours([])}};loadProducts();loadTours();window.addEventListener('tn-products-updated',loadProducts);window.addEventListener('tn-tours-updated',loadTours);window.addEventListener('storage',loadProducts);window.addEventListener('storage',loadTours);return()=>{window.removeEventListener('tn-products-updated',loadProducts);window.removeEventListener('tn-tours-updated',loadTours);window.removeEventListener('storage',loadProducts);window.removeEventListener('storage',loadTours)}},[]);
 const match=(text:string)=>!q||text.toLowerCase().includes(q);
 const mergedStays=useMemo(()=>{const map=new Map(cmsProducts.map(x=>[x.slug,x]));const rows=stays.flatMap(x=>{const c=map.get(x.slug);if(c&&c.status!=='published')return[];return [{slug:x.slug,name:c?.name||x.name,type:c?.type||x.type,place:c?.place||x.location,summary:c?.summary||x.summary,image:c?.cover||x.image,rating:c?.rating||String(x.rating),href:`/stay/${x.slug}`}]} as {slug:string;name:string;type:string;place:string;summary:string;image:string;rating:string;href:string}[]);const staticSet=new Set(stays.map(x=>x.slug));for(const c of cmsProducts){if(c.status==='published'&&c.type!=='Du thuyền'&&!staticSet.has(c.slug))rows.push({slug:c.slug,name:c.name,type:c.type,place:c.place,summary:c.summary,image:c.cover||'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',rating:c.rating||'Mới',href:`/product?slug=${encodeURIComponent(c.slug)}`})}return rows},[cmsProducts]);
 const mergedCruises=useMemo(()=>{const map=new Map(cmsProducts.map(x=>[x.slug,x]));const rows=cruises.flatMap(x=>{const c=map.get(x.slug);if(c&&c.status!=='published')return[];return [{slug:x.slug,name:c?.name||x.name,place:c?.place||x.bay,duration:c?.duration||x.duration,summary:c?.summary||x.summary,image:c?.cover||x.image,href:`/cruises/${x.slug}`}]} as {slug:string;name:string;place:string;duration:string;summary:string;image:string;href:string}[]);const staticSet=new Set(cruises.map(x=>x.slug));for(const c of cmsProducts){if(c.status==='published'&&c.type==='Du thuyền'&&!staticSet.has(c.slug))rows.push({slug:c.slug,name:c.name,place:c.place||'Du thuyền',duration:c.duration||'Lịch trình linh hoạt',summary:c.summary,image:c.cover||'https://images.unsplash.com/photo-1544551763-46a013bb70d5e?auto=format&fit=crop&w=1000&q=85',href:`/product?slug=${encodeURIComponent(c.slug)}`})}return rows},[cmsProducts]);
 const mergedTours=useMemo(()=>{const staticTours=[...tours,...internationalTours];const map=new Map(cmsTours.map(x=>[x.slug,x]));const rows=staticTours.flatMap(x=>{const c=map.get(x.slug);if(c&&c.status!=='published')return[];return [{slug:x.slug,name:c?.name||x.name,category:c?.category||x.category,duration:c?.duration||x.duration,route:c?.route||x.route,summary:c?.summary||x.summary,image:c?.cover||x.image,href:`/tours/${x.slug}`}]} as {slug:string;name:string;category:string;duration:string;route:string;summary:string;image:string;href:string}[]);const staticSet=new Set(staticTours.map(x=>x.slug));for(const c of cmsTours){if(c.status==='published'&&!staticSet.has(c.slug)){const image=c.cover||(c.gallery||'').split(/\n+/).find(Boolean)||'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1000&q=85';rows.push({slug:c.slug,name:c.name,category:c.category,duration:c.duration||'Đang cập nhật',route:c.route,summary:c.summary,image,href:`/tour-product?slug=${encodeURIComponent(c.slug)}`})}}return rows},[cmsTours]);
 const stayResults=mergedStays.filter(x=>match(`${x.name} ${x.place} ${x.type} ${x.summary}`));const tourResults=mergedTours.filter(x=>match(`${x.name} ${x.route} ${x.category} ${x.summary}`));const cruiseResults=mergedCruises.filter(x=>match(`${x.name} ${x.place} ${x.duration} ${x.summary}`));const total=stayResults.length+tourResults.length+cruiseResults.length;
 return <div className="global-search-results"><div className="search-summary"><div><b>{raw?`${total} kết quả cho “${raw}”`:`${total} dịch vụ đang có`}</b><span>{adults} người lớn · {children} trẻ em · Tour, lưu trú và du thuyền</span></div><Link href="/">Đổi tìm kiếm</Link></div>
 {tourResults.length>0&&<section className="global-result-section"><div className="section-heading"><div><small>TOUR DU LỊCH</small><h2>Tour phù hợp</h2></div><Link href={`/tours${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{tourResults.slice(0,4).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.category} · {item.duration}</small><h3>{item.name}</h3><p>📍 {item.route||'Đang cập nhật lịch trình'}</p><div className="catalog-actions"><Link className="main" href={item.href}>Xem tour</Link></div></div></article>)}</div></section>}
 {stayResults.length>0&&<section className="global-result-section"><div className="section-heading"><div><small>LƯU TRÚ</small><h2>Villa, Resort & Khách sạn</h2></div><Link href={`/stay${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{stayResults.slice(0,4).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.type} · {item.rating==='Mới'?'Mới':`${item.rating}/10`}</small><h3>{item.name}</h3><p>📍 {item.place||'Đang cập nhật'}</p><div className="catalog-actions"><Link className="main" href={item.href}>Xem phòng</Link></div></div></article>)}</div></section>}
 {cruiseResults.length>0&&<section className="global-result-section"><div className="section-heading"><div><small>DU THUYỀN</small><h2>Hành trình trên vịnh</h2></div><Link href={`/cruises${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{cruiseResults.slice(0,4).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.place} · {item.duration}</small><h3>{item.name}</h3><p>{item.summary}</p><div className="catalog-actions"><Link className="main" href={item.href}>Xem du thuyền</Link></div></div></article>)}</div></section>}
 {total===0&&<div className="empty-results"><b>Chưa có dịch vụ phù hợp</b><p>Hãy thử tên địa điểm khác hoặc gọi {formatPhone(settings.hotline)} để được tìm giúp.</p><a href={`tel:${settings.hotline.replace(/\D/g,'')}`}>☎ Gọi tư vấn ngay</a></div>}
 </div>
}
