'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {cruises,stays,tours} from '@/data/catalog';
import {guidePosts} from '@/data/guides';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';

type CmsProduct={id:string;type:string;name:string;slug:string;place:string;summary:string;cover:string;status:string;duration?:string;rating?:string;price?:string};
type CmsTour={id:string;name:string;slug:string;cover?:string;category:string;duration:string;route:string;summary:string;status:string;gallery:string;salePrice:string;price:string;departure?:string};
type CmsArticle={id:string;title:string;slug:string;category:string;excerpt:string;cover:string;status:string;content?:string;date?:string};
const publishedArticles=(value:unknown)=>Array.isArray(value)?(value as CmsArticle[]).filter(x=>x.status==='published'&&x.slug&&x.title&&!x.id.startsWith('seo_')):[];

export function GlobalSearchResults(){
 const params=useSearchParams();const settings=useSiteSettings();const raw=(params.get('q')||'').trim();const q=raw.toLowerCase();const adults=params.get('adults')||'2';const children=params.get('children')||'0';const [cmsProducts,setCmsProducts]=useState<CmsProduct[]>([]);const [cmsTours,setCmsTours]=useState<CmsTour[]>([]);const [cmsArticles,setCmsArticles]=useState<CmsArticle[]>([]);
 useEffect(()=>{let alive=true;const apply=(products:unknown,tourItems:unknown,articleItems:unknown)=>{if(!alive)return;setCmsProducts(Array.isArray(products)?products as CmsProduct[]:[]);setCmsTours(Array.isArray(tourItems)?tourItems as CmsTour[]:[]);setCmsArticles(publishedArticles(articleItems))};const loadCache=()=>{try{apply(JSON.parse(localStorage.getItem('tn_cms_products_v3_units')||'[]'),JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]'),JSON.parse(localStorage.getItem('tn_cms_articles_v3')||localStorage.getItem('tn_cms_articles_v4')||'[]'))}catch{apply([],[],[])}};const loadRemote=async()=>{try{const response=await fetch('/api/catalog/site-state',{cache:'no-store'});if(!response.ok)return;const data=await response.json() as {state?:Record<string,unknown>};const state=data.state||{};try{if(Array.isArray(state.tn_cms_products_v3_units))localStorage.setItem('tn_cms_products_v3_units',JSON.stringify(state.tn_cms_products_v3_units));if(Array.isArray(state.tn_cms_tours_v3))localStorage.setItem('tn_cms_tours_v3',JSON.stringify(state.tn_cms_tours_v3));if(Array.isArray(state.tn_cms_articles_v3))localStorage.setItem('tn_cms_articles_v3',JSON.stringify(state.tn_cms_articles_v3))}catch{}apply(state.tn_cms_products_v3_units,state.tn_cms_tours_v3,state.tn_cms_articles_v3)}catch{}};loadCache();void loadRemote();const refresh=()=>{loadCache();void loadRemote()};window.addEventListener('tn-products-updated',refresh);window.addEventListener('tn-tours-updated',refresh);window.addEventListener('tn-articles-updated',refresh);window.addEventListener('storage',refresh);return()=>{alive=false;window.removeEventListener('tn-products-updated',refresh);window.removeEventListener('tn-tours-updated',refresh);window.removeEventListener('tn-articles-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
 const match=(text:string)=>!q||text.toLowerCase().includes(q);
 const stayMerged=useMemo(()=>stays.flatMap(item=>{const c=cmsProducts.find(x=>x.slug===item.slug);if(c&&c.status!=='published')return[];return [{...item,name:c?.name||item.name,location:c?.place||item.location,summary:c?.summary||item.summary,image:c?.cover||item.image}]}),[cmsProducts]);
 const cruiseMerged=useMemo(()=>cruises.flatMap(item=>{const c=cmsProducts.find(x=>x.slug===item.slug);if(c&&c.status!=='published')return[];return [{...item,name:c?.name||item.name,bay:c?.place||item.bay,duration:c?.duration||item.duration,summary:c?.summary||item.summary,image:c?.cover||item.image,priceFrom:c?.price||item.priceFrom}]}),[cmsProducts]);
 const tourMerged=useMemo(()=>tours.flatMap(item=>{const c=cmsTours.find(x=>x.slug===item.slug);if(c&&c.status!=='published')return[];return [{...item,name:c?.name||item.name,category:(c?.category||item.category) as typeof item.category,duration:c?.duration||item.duration,route:c?.route||item.route,summary:c?.summary||item.summary,image:c?.cover||item.image,priceFrom:c?.salePrice||c?.price||item.priceFrom,departureFrom:c?.departure||item.departureFrom}]}),[cmsTours]);
 const staticProductSlugs=useMemo(()=>new Set([...stays.map(x=>x.slug),...cruises.map(x=>x.slug)]),[]);const staticTourSlugs=useMemo(()=>new Set(tours.map(x=>x.slug)),[]);
 const cmsOnlyProducts=cmsProducts.filter(x=>x.status==='published'&&x.slug&&!staticProductSlugs.has(x.slug));const cmsOnlyTours=cmsTours.filter(x=>x.status==='published'&&x.slug&&!staticTourSlugs.has(x.slug));
 const stayResults=stayMerged.filter(x=>match(`${x.name} ${x.location} ${x.type} ${x.summary}`));const tourResults=tourMerged.filter(x=>match(`${x.name} ${x.route} ${x.category} ${x.summary}`));const cruiseResults=cruiseMerged.filter(x=>match(`${x.name} ${x.bay} ${x.duration} ${x.summary}`));const cmsStayResults=cmsOnlyProducts.filter(x=>x.type!=='Du thuyền'&&match(`${x.name} ${x.place} ${x.type} ${x.summary}`));const cmsCruiseResults=cmsOnlyProducts.filter(x=>x.type==='Du thuyền'&&match(`${x.name} ${x.place} ${x.duration||''} ${x.summary}`));const cmsTourResults=cmsOnlyTours.filter(x=>match(`${x.name} ${x.route} ${x.category} ${x.summary}`));const staticArticleResults=guidePosts.filter(x=>match(`${x.title} ${x.category} ${x.excerpt} ${x.keywords.join(' ')}`));const cmsArticleResults=cmsArticles.filter(x=>match(`${x.title} ${x.category} ${x.excerpt} ${x.content||''}`));const total=stayResults.length+tourResults.length+cruiseResults.length+cmsStayResults.length+cmsCruiseResults.length+cmsTourResults.length+staticArticleResults.length+cmsArticleResults.length;
 return <div className="global-search-results"><div className="search-summary"><div><b>{raw?`${total} kết quả cho “${raw}”`:`${total} nội dung & dịch vụ đang có`}</b><span>{adults} người lớn · {children} trẻ em · Tour, lưu trú, du thuyền và Cẩm nang</span></div><Link href="/">Đổi tìm kiếm</Link></div>
 {(tourResults.length+cmsTourResults.length)>0&&<section className="global-result-section"><div className="section-heading"><div><small>TOUR DU LỊCH</small><h2>Tour phù hợp</h2></div><Link href={`/tour-du-lich${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{tourResults.slice(0,3).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.category} · {item.duration}</small><h3>{item.name}</h3><p>📍 {item.route}</p><div className="catalog-actions"><Link className="main" href={`/tour-du-lich/${item.slug}`}>Xem tour</Link></div></div></article>)}{cmsTourResults.slice(0,Math.max(0,4-Math.min(3,tourResults.length))).map(item=>{const image=item.cover||(item.gallery||'').split(/\n+/).find(Boolean)||'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1000&q=85';return <article className="catalog-card cms-public-card" key={item.id}><div className="catalog-image" style={{backgroundImage:`url(${image})`}}/><div className="catalog-body"><small>{item.category} · {item.duration||'Đang cập nhật'}</small><h3>{item.name}</h3><p>📍 {item.route||'Đang cập nhật lịch trình'}</p><div className="catalog-actions"><Link className="main" href={`/tour-du-lich/${encodeURIComponent(item.slug)}`}>Xem tour</Link></div></div></article>})}</div></section>}
 {(stayResults.length+cmsStayResults.length)>0&&<section className="global-result-section"><div className="section-heading"><div><small>LƯU TRÚ</small><h2>Villa, Resort & Khách sạn</h2></div><Link href={`/luu-tru${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{stayResults.slice(0,3).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.type}</small><h3>{item.name}</h3><p>📍 {item.location}</p><div className="catalog-actions"><Link className="main" href={`/luu-tru/${item.slug}`}>Xem phòng</Link></div></div></article>)}{cmsStayResults.slice(0,Math.max(0,4-Math.min(3,stayResults.length))).map(item=><article className="catalog-card cms-public-card" key={item.id}><div className="catalog-image" style={{backgroundImage:`url(${item.cover||'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80'})`}}/><div className="catalog-body"><small>{item.type}</small><h3>{item.name}</h3><p>📍 {item.place}</p><div className="catalog-actions"><Link className="main" href={`/san-pham/${encodeURIComponent(item.slug)}`}>Xem phòng</Link></div></div></article>)}</div></section>}
 {(cruiseResults.length+cmsCruiseResults.length)>0&&<section className="global-result-section"><div className="section-heading"><div><small>DU THUYỀN</small><h2>Hành trình trên vịnh</h2></div><Link href={`/du-thuyen${raw?`?q=${encodeURIComponent(raw)}`:''}`}>Xem tất cả →</Link></div><div className="catalog-grid">{cruiseResults.slice(0,3).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.bay} · {item.duration}</small><h3>{item.name}</h3><p>{item.summary}</p><div className="catalog-actions"><Link className="main" href={`/du-thuyen/${item.slug}`}>Xem du thuyền</Link></div></div></article>)}{cmsCruiseResults.slice(0,Math.max(0,4-Math.min(3,cruiseResults.length))).map(item=><article className="catalog-card cms-public-card" key={item.id}><div className="catalog-image" style={{backgroundImage:`url(${item.cover||'https://images.unsplash.com/photo-1544551763-46a013bb70d5e?auto=format&fit=crop&w=1000&q=85'})`}}/><div className="catalog-body"><small>{item.place||'Du thuyền'} · {item.duration||'Lịch trình linh hoạt'}</small><h3>{item.name}</h3><p>{item.summary}</p><div className="catalog-actions"><Link className="main" href={`/san-pham/${encodeURIComponent(item.slug)}`}>Xem du thuyền</Link></div></div></article>)}</div></section>}
 {(staticArticleResults.length+cmsArticleResults.length)>0&&<section className="global-result-section"><div className="section-heading"><div><small>CẨM NANG</small><h2>Bài viết liên quan</h2></div><Link href="/cam-nang">Xem Cẩm nang →</Link></div><div className="catalog-grid">{cmsArticleResults.slice(0,3).map(item=><article className="catalog-card cms-public-card" key={item.id}><div className="catalog-image" style={{backgroundImage:`url(${item.cover||'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=85'})`}}/><div className="catalog-body"><small>{item.category||'Cẩm nang'} · {item.date||''}</small><h3>{item.title}</h3><p>{item.excerpt}</p><div className="catalog-actions"><Link className="main" href={`/cam-nang/bai-viet/${encodeURIComponent(item.slug)}`}>Đọc bài</Link></div></div></article>)}{staticArticleResults.slice(0,Math.max(0,3-cmsArticleResults.length)).map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.category} · {item.readTime}</small><h3>{item.title}</h3><p>{item.excerpt}</p><div className="catalog-actions"><Link className="main" href={`/cam-nang/${item.slug}`}>Đọc bài</Link></div></div></article>)}</div></section>}
 {total===0&&<div className="empty-results"><b>Chưa có nội dung phù hợp</b><p>Hãy thử tên địa điểm khác hoặc gọi {formatPhone(settings.hotline)} để được tìm giúp.</p><a href={`tel:${settings.hotline.replace(/\D/g,'')}`}>☎ Gọi tư vấn ngay</a></div>}
 </div>
}
