'use client';

import Link from 'next/link';
import {useMemo} from 'react';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';
import {usePublicGuideArticles} from '@/components/usePublicGuideArticles';

const happyGoText=(value:string)=>value.replace(/Thúy Nguyên Travel/gi,'HappyGo Travel').replace(/THÚY NGUYÊN TRAVEL/g,'HAPPYGO TRAVEL').replace(/Thúy Nguyên/gi,'HappyGo');
function sanitizeEditorHtml(value:string){return happyGoText(value).replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi,'').replace(/<object[\s\S]*?>[\s\S]*?<\/object>/gi,'').replace(/<embed[^>]*>/gi,'').replace(/\son\w+\s*=\s*(["']).*?\1/gi,'').replace(/javascript:/gi,'')}
export function GuideArticleReader(){const settings=useSiteSettings();const items=usePublicGuideArticles();const slug=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('slug')||'':'';const article=items.find(item=>item.slug===slug)||null;const safeHtml=useMemo(()=>sanitizeEditorHtml(article?.content||''),[article?.content]);const internalLinks=useMemo(()=>{const text=`${article?.category||''} ${article?.title||''} ${article?.excerpt||''} ${article?.content||''}`.toLowerCase();const links:{href:string;label:string}[]=[];if(/du thuyền|cabin|hạ long|lan hạ/.test(text))links.push({href:'/du-thuyen',label:'Xem du thuyền phù hợp'});if(/villa|resort/.test(text))links.push({href:'/villa-resort',label:'Xem Villa & Resort phù hợp'});if(/khách sạn|phòng|hotel/.test(text))links.push({href:'/khach-san',label:'Xem khách sạn phù hợp'});if(/tour|trung quốc|nhật bản|hàn quốc|châu âu|mỹ|úc|ấn độ|maldives/.test(text))links.push({href:'/tour-du-lich',label:'Xem tour phù hợp'});return links.slice(0,3)},[article]);if(!slug)return <div className="article-state"><h2>Chưa chọn bài viết</h2><p>Vui lòng quay lại Cẩm nang và chọn bài bạn muốn đọc.</p><Link href="/cam-nang">← Quay lại Cẩm nang</Link></div>;if(!article&&items.length===0)return <div className="article-state">Đang tải bài viết...</div>;if(!article)return <div className="article-state"><h2>Không tìm thấy bài viết</h2><p>Bài có thể đang ở bản nháp, đã bị xóa hoặc chưa được xuất bản.</p><Link href="/cam-nang">← Quay lại Cẩm nang</Link></div>;const phone=settings.hotline.replace(/\D/g,''),zalo=settings.zalo.replace(/\D/g,'')||phone,title=happyGoText(article.title),excerpt=happyGoText(article.excerpt||'');return <article className="public-article"><div className="article-meta"><span>{happyGoText(article.category||'Cẩm nang du lịch')}</span><span>{article.date||''}</span></div><h1>{title}</h1>{excerpt&&<p className="article-lead">{excerpt}</p>}{article.cover&&<img className="article-cover" src={article.cover} alt={title}/>}<div className="article-content">{safeHtml?<div dangerouslySetInnerHTML={{__html:safeHtml}}/>:<p>Nội dung bài viết đang được cập nhật.</p>}</div>{internalLinks.length>0&&<div className="article-internal-links"><b>Gợi ý dịch vụ liên quan</b><div>{internalLinks.map(link=><Link key={link.href} href={link.href}>{link.label} →</Link>)}</div></div>}<div className="article-actions"><a href={`tel:${phone}`}>☎ Gọi {formatPhone(settings.hotline)}</a><a href={`https://zalo.me/${zalo}`} target="_blank" rel="noreferrer">Zalo</a><Link href="/cam-nang">Xem thêm Cẩm nang</Link></div></article>}
