'use client';

import Link from 'next/link';
import { PropertyCard } from '@/components/PropertyCard';
import {SafeBackground,travelFallback} from '@/components/SafeImage';
import {destinationVisual,productVisual} from '@/components/ProductVisuals';
import { cruises,destinations,stays,tours } from '@/data/catalog';
import {guidePosts} from '@/data/guides';
import { useHomeCms } from '@/components/HomeCmsHero';
import {useEffect,useMemo,useState} from 'react';

type CmsUnit={weekdayPrice?:string;weekendPrice?:string;holidayPrice?:string;lowWeekdayPrice?:string;lowWeekendPrice?:string;highWeekdayPrice?:string;highWeekendPrice?:string;status?:string};
type CmsProduct={id:string;type:string;name:string;slug:string;place:string;price:string;status:string;summary:string;cover:string;rating?:string|number;duration?:string;units?:CmsUnit[]};
type CmsTour={id:string;name:string;slug:string;cover?:string;category:string;duration:string;route:string;summary:string;status:string;salePrice?:string;gallery?:string};
type CmsArticle={id:string;title:string;slug:string;category:string;excerpt:string;cover:string;status:string;date:string;readTime?:string};
const serviceCards=[['✈','Tour du lịch','Tour trong nước & quốc tế','/tour-du-lich'],['🏡','Villa & Resort','Nghỉ dưỡng cao cấp','/luu-tru?type=villa'],['🏨','Khách sạn','Đặt phòng toàn quốc','/luu-tru?type=hotel'],['🛳','Du thuyền','Hải trình tuyệt vời','/du-thuyen'],['🧭','Điểm đến','Khám phá Việt Nam','/diem-den']];
const destinationSlug=(name:string)=>name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const destinationHref=(name:string)=>`/diem-den/${destinationSlug(name)}`;
const homeType=(type:string)=>type==='Villa & Resort'?'Villa':type==='Khách sạn'?'Khách sạn':type;
const priceNumber=(value?:string)=>{const digits=String(value||'').replace(/[^0-9]/g,'');return digits?Number(digits):0};
const displayPrice=(value?:string)=>{const raw=String(value||'').trim();if(!raw)return 'Liên hệ';const cleaned=raw.replace(/^(?:từ\s*)+/i,'').trim();if(!cleaned||/^liên\s*hệ$/i.test(cleaned))return 'Liên hệ';return `Từ ${cleaned}`};
const startingProductPrice=(product:CmsProduct)=>{const units=Array.isArray(product.units)?product.units.filter(unit=>unit?.status!=='hidden'):[];const prices=units.flatMap(unit=>[unit.lowWeekdayPrice,unit.lowWeekendPrice,unit.weekdayPrice,unit.weekendPrice,unit.highWeekdayPrice,unit.highWeekendPrice,unit.holidayPrice]).map(value=>({value:String(value||'').trim(),amount:priceNumber(value)})).filter(item=>item.value&&item.amount>0).sort((a,b)=>a.amount-b.amount);return prices[0]?.value||product.price||''};
const ratingNumber=(value?:string|number)=>{const number=typeof value==='number'?value:Number(String(value||'').replace(',','.').match(/\d+(?:\.\d+)?/)?.[0]||0);return Number.isFinite(number)?Math.min(5,Math.max(0,number)):0};
const ratingStars=(value?:string|number)=>{const rating=ratingNumber(value);if(!rating)return null;const filled=Math.round(rating);return <div className="mock-stars" aria-label={`${rating} trên 5 sao`}>{'★'.repeat(filled)}{'☆'.repeat(5-filled)}<span>{Number.isInteger(rating)?`${rating} sao`:`${rating.toFixed(1)} / 5`}</span></div>};

export function HomeCmsSections(){
 const cms=useHomeCms();
 const [cmsProducts,setCmsProducts]=useState<CmsProduct[]>([]);const [cmsTours,setCmsTours]=useState<CmsTour[]>([]);const [cmsArticles,setCmsArticles]=useState<CmsArticle[]>([]);
 useEffect(()=>{let alive=true;const apply=(products:unknown,tourItems:unknown,articles:unknown)=>{if(!alive)return;if(Array.isArray(products))setCmsProducts((products as CmsProduct[]).filter(x=>x.status==='published'));if(Array.isArray(tourItems))setCmsTours((tourItems as CmsTour[]).filter(x=>x.status==='published'));if(Array.isArray(articles))setCmsArticles((articles as CmsArticle[]).filter(x=>x.status==='published'&&x.title&&x.slug&&!x.id.startsWith('seo_')))};const loadCache=()=>{try{apply(JSON.parse(localStorage.getItem('tn_cms_products_v3_units')||'[]'),JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]'),JSON.parse(localStorage.getItem('tn_cms_articles_v3')||'[]'))}catch{}};const loadRemote=async()=>{try{const response=await fetch('/api/catalog/site-state',{cache:'no-store'});if(!response.ok)return;const data=await response.json() as {state?:Record<string,unknown>};const state=data.state||{};try{if(Array.isArray(state.tn_cms_products_v3_units))localStorage.setItem('tn_cms_products_v3_units',JSON.stringify(state.tn_cms_products_v3_units));if(Array.isArray(state.tn_cms_tours_v3))localStorage.setItem('tn_cms_tours_v3',JSON.stringify(state.tn_cms_tours_v3));if(Array.isArray(state.tn_cms_articles_v3))localStorage.setItem('tn_cms_articles_v3',JSON.stringify(state.tn_cms_articles_v3))}catch{}apply(state.tn_cms_products_v3_units,state.tn_cms_tours_v3,state.tn_cms_articles_v3)}catch{}};loadCache();void loadRemote();const refresh=()=>{loadCache();void loadRemote()};window.addEventListener('tn-products-updated',refresh);window.addEventListener('tn-tours-updated',refresh);window.addEventListener('tn-articles-updated',refresh);window.addEventListener('storage',refresh);return()=>{alive=false;window.removeEventListener('tn-products-updated',refresh);window.removeEventListener('tn-tours-updated',refresh);window.removeEventListener('tn-articles-updated',refresh);window.removeEventListener('storage',refresh)}},[]);
 const staticStaySlugs=useMemo(()=>new Set(stays.map(x=>x.slug)),[]);const staticCruiseSlugs=useMemo(()=>new Set(cruises.map(x=>x.slug)),[]);const staticTourSlugs=useMemo(()=>new Set(tours.map(x=>x.slug)),[]);const newStays=useMemo(()=>cmsProducts.filter(x=>x.type!=='Du thuyền'&&!staticStaySlugs.has(x.slug)),[cmsProducts,staticStaySlugs]);const newCruises=useMemo(()=>cmsProducts.filter(x=>x.type==='Du thuyền'&&!staticCruiseSlugs.has(x.slug)),[cmsProducts,staticCruiseSlugs]);const newTours=useMemo(()=>cmsTours.filter(x=>!staticTourSlugs.has(x.slug)),[cmsTours,staticTourSlugs]);const fallback=travelFallback();
 const guideCards=useMemo(()=>{const cmsFirst=cmsArticles.slice(0,3).map(a=>({key:`cms_${a.id}`,href:`/cam-nang/doc?slug=${encodeURIComponent(a.slug)}`,image:a.cover||fallback,category:a.category||'Cẩm nang du lịch',readTime:a.readTime||a.date||'Bài mới',title:a.title,excerpt:a.excerpt||'Kinh nghiệm và thông tin du lịch mới từ HappyGo Travel.'}));if(cmsFirst.length>=3)return cmsFirst;const staticFill=guidePosts.filter(p=>!cmsArticles.some(a=>a.slug===p.slug)).slice(0,3-cmsFirst.length).map(p=>({key:`static_${p.slug}`,href:`/cam-nang/${p.slug}`,image:p.image,category:p.category,readTime:p.readTime,title:p.title,excerpt:p.excerpt}));return [...cmsFirst,...staticFill]},[cmsArticles,fallback]);
 return <>
 {cms.servicesEnabled&&<section className="mock-section mock-services-section"><div className="container"><div className="mock-section-heading center"><h2>{cms.servicesTitle}</h2><p>{cms.servicesSubtitle}</p></div><div className="mock-service-grid">{serviceCards.map(([icon,title,desc,href])=><Link href={href} className="mock-service-card" key={title}><span>{icon}</span><h3>{title}</h3><p>{desc}</p></Link>)}</div></div></section>}
 {cms.destinationsEnabled&&<section className="mock-section"><div className="container"><div className="mock-section-heading"><div><h2>{cms.destinationsTitle}</h2><div className="mock-pills"><Link className="active" href="/diem-den">Trong nước</Link><Link href="/tour-du-lich?category=china">Tour Trung Quốc</Link></div></div><Link href="/diem-den">Xem tất cả →</Link></div><div className="mock-destination-grid">{destinations.slice(0,6).map(([name,meta,image])=><Link href={destinationHref(name)} className="mock-destination-card" key={name}><SafeBackground src={destinationVisual(name,image)} fallback={travelFallback('destination')} className="mock-destination-image" ariaLabel={name}><div><h3>{name}</h3><p>{meta}</p></div></SafeBackground></Link>)}</div></div></section>}
 {cms.productsEnabled&&<section className="mock-section mock-soft"><div className="container"><div className="mock-section-heading"><div><h2>{cms.productsTitle}</h2><div className="mock-pills"><Link className="active" href="/luu-tru">Tất cả lưu trú</Link><Link href="/luu-tru?type=villa">Villa & Resort</Link><Link href="/luu-tru?type=hotel">Khách sạn</Link><Link href="/du-thuyen">Du thuyền</Link></div></div><Link href="/luu-tru">Xem tất cả →</Link></div><div className="mock-product-grid">{newStays.slice(0,2).map(item=>{const href=`/san-pham/${encodeURIComponent(item.slug)}`;const type=homeType(item.type);return <article className="property-card mock-product-card" key={item.id}><Link href={href}><SafeBackground src={item.cover} fallback={travelFallback(item.type)} className="property-image mock-product-image" ariaLabel={item.name}><span className="mock-badge">{type}</span></SafeBackground></Link><div className="property-body mock-product-body"><Link href={href}><h3>{item.name}</h3></Link><p className="property-location">{item.place||'Đang cập nhật địa điểm'}</p>{ratingStars(item.rating)}<div className="mock-price">{displayPrice(startingProductPrice(item))}</div><Link className="mock-detail-btn" href={href}>Xem chi tiết</Link></div></article>})}{stays.slice(0,Math.max(3,5-newStays.slice(0,2).length)).map(stay=><PropertyCard stay={stay} key={stay.slug}/>)}</div></div></section>}
 {cms.cruisesEnabled&&<section className="mock-section"><div className="container"><div className="mock-section-heading"><div><h2>{cms.cruisesTitle}</h2><p>{cms.cruisesSubtitle}</p></div><Link href="/du-thuyen">Xem tất cả →</Link></div><div className="mock-tour-grid">{newCruises.slice(0,1).map(item=><Link href={`/san-pham/${encodeURIComponent(item.slug)}`} className="mock-tour-card" key={item.id}><SafeBackground src={item.cover} fallback={travelFallback('cruise')} className="mock-tour-image" ariaLabel={item.name}/><div><h3>{item.name}</h3><p>{item.summary}</p></div></Link>)}{cruises.slice(0,newCruises.length?2:3).map(item=><Link href={`/du-thuyen/${item.slug}`} className="mock-tour-card" key={item.slug}><SafeBackground src={productVisual(item.slug,item.image)} fallback={travelFallback('cruise')} className="mock-tour-image" ariaLabel={item.name}/><div><h3>{item.name}</h3><p>{item.summary}</p></div></Link>)}</div></div></section>}
 {cms.toursEnabled&&<section className="mock-section mock-soft"><div className="container"><div className="mock-section-heading"><div><h2>{cms.toursTitle}</h2></div><Link href="/tour-du-lich">Xem tất cả →</Link></div><div className="mock-tour-grid">{newTours.slice(0,1).map(item=><Link href={`/tour-du-lich/${encodeURIComponent(item.slug)}`} className="mock-tour-card" key={item.id}><SafeBackground src={item.cover||(item.gallery||'').split(/\n+/).find(Boolean)} fallback={travelFallback('tour')} className="mock-tour-image" ariaLabel={item.name}/><div><h3>{item.name}</h3><p>{item.summary||item.route}</p></div></Link>)}{tours.slice(0,newTours.length?2:3).map(item=><Link href={`/tour-du-lich/${item.slug}`} className="mock-tour-card" key={item.slug}><SafeBackground src={productVisual(item.slug,item.image)} fallback={travelFallback('tour')} className="mock-tour-image" ariaLabel={item.name}/><div><h3>{item.name}</h3><p>{item.summary}</p></div></Link>)}</div></div></section>}
 <section className="mock-section home-guide-section"><div className="container"><div className="mock-section-heading"><div><small>CẨM NANG DU LỊCH</small><h2>Bài viết & kinh nghiệm mới</h2><p>Thông tin hữu ích để chọn điểm đến và đặt dịch vụ phù hợp.</p></div><Link href="/cam-nang">Xem tất cả bài viết →</Link></div><div className="mock-tour-grid home-guide-grid">{guideCards.map(p=><Link href={p.href} className="mock-tour-card home-guide-card" key={p.key}><SafeBackground src={p.image} fallback={travelFallback('destination')} className="mock-tour-image" ariaLabel={p.title}/><div><small>{p.category} · {p.readTime}</small><h3>{p.title}</h3><p>{p.excerpt}</p><b>Đọc bài →</b></div></Link>)}</div></div></section>
 {cms.ctaEnabled&&<section className="mock-section"><div className="container mock-cta-strip"><div><span>{cms.ctaEyebrow}</span><h2>{cms.ctaTitle}</h2><p>{cms.ctaText}</p></div><div><a href={`https://zalo.me/${cms.zalo}`} className="mock-zalo-cta">Zalo</a></div></div></section>}
 </>;
}
