'use client';

import {ChangeEvent,useMemo,useState} from 'react';

type ProductType='Villa & Resort'|'Khách sạn'|'Du thuyền'|'Tour du lịch';
type ProductLike={id?:string;type:ProductType;name:string;slug:string;place:string;address:string;price:string;summary:string;cover:string;gallery:string;amenities:string;policies:string;checkin:string;checkout:string;unitsText:string;[key:string]:any};

type Props={form:ProductLike;setForm:(next:any)=>void;onCancel:()=>void;onSaveDraft:()=>void;onSubmit:()=>void;slugify:(v:string)=>string;setMessage?:(v:string)=>void};
const lines=(v?:string)=>String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
async function compressImage(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Không đọc được ảnh'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Ảnh không hợp lệ'));img.onload=()=>{const max=1920,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');if(!ctx)return reject(new Error('Không xử lý được ảnh'));ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);const alpha=file.type==='image/png'||file.type==='image/webp';resolve(c.toDataURL(alpha?'image/webp':'image/jpeg',alpha?.86:.84))};img.src=String(r.result||'')};r.readAsDataURL(file)})}
function F({label,children,wide=false,hint}:{label:string;children:React.ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'partner-field wide':'partner-field'}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
const typeInfo:Record<ProductType,{icon:string,title:string,desc:string}>={
 'Villa & Resort':{icon:'🏝️',title:'Villa & Resort',desc:'Căn villa, số phòng ngủ, sức chứa, tiện ích và chính sách lưu trú'},
 'Khách sạn':{icon:'🏨',title:'Khách sạn',desc:'Hạng phòng, loại giường, bữa ăn, check-in/out và tiện ích'},
 'Du thuyền':{icon:'🛳️',title:'Du thuyền',desc:'Cabin, vịnh/bến, thời lượng, lịch trình và dịch vụ trên tàu'},
 'Tour du lịch':{icon:'✈️',title:'Tour du lịch',desc:'Tuyến điểm, lịch khởi hành, phương tiện, lịch trình và dịch vụ tour'}
};

export function PartnerProductEditor({form,setForm,onCancel,onSaveDraft,onSubmit,slugify,setMessage}:Props){
 const[uploading,setUploading]=useState(false);const photos=useMemo(()=>lines(form.gallery),[form.gallery]);
 const set=(k:string,v:any)=>setForm((s:any)=>({...s,[k]:v}));
 const type=form.type;
 function changeType(t:ProductType){setForm((s:any)=>({...s,type:t,checkin:t==='Tour du lịch'?'':(s.checkin||'14:00'),checkout:t==='Tour du lịch'?'':(s.checkout||'12:00')}))}
 async function upload(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;const selected=files.slice(0,Math.max(0,30-photos.length)).slice(0,12);setUploading(true);try{const urls:string[]=[];let skipped=0;for(const f of selected){if(!f.type.startsWith('image/')){skipped++;continue}if(f.size>30*1024*1024){skipped++;continue}urls.push(await compressImage(f))}const merged=[...photos,...urls];setForm((s:any)=>({...s,gallery:merged.join('\n'),cover:s.cover||merged[0]||''}));setMessage?.(`Đã tối ưu ${urls.length} ảnh về tối đa 1920px, giữ độ nét cao${skipped?` · bỏ qua ${skipped} ảnh không hợp lệ/quá 30MB`:''}.`)}catch(err){setMessage?.(err instanceof Error?err.message:'Không tải được ảnh')}finally{setUploading(false)}}
 function removePhoto(i:number){const target=photos[i],next=photos.filter((_,n)=>n!==i);setForm((s:any)=>({...s,gallery:next.join('\n'),cover:s.cover===target?(next[0]||''):s.cover}))}
 function submitForReview(){if(!String(form.serviceStars||'').trim()){setMessage?.('Vui lòng chọn hạng dịch vụ từ 1 đến 5 sao trước khi gửi HappyGo duyệt.');return}onSubmit()}
 return <div className="partner-editor partner-product-editor-v2">
  <div className="partner-editor-head"><div><button type="button" onClick={onCancel}>← Danh sách</button><div><h2>{form.id?'Chỉnh sửa sản phẩm':'Đăng sản phẩm mới'}</h2><p>Chọn loại hình để HappyGo hiển thị đúng mẫu nhập như trong trang quản trị.</p></div></div></div>
  <section className="partner-editor-section"><h3>1. Chọn loại sản phẩm</h3><div className="partner-type-picker">{(Object.keys(typeInfo) as ProductType[]).map(t=><button type="button" key={t} className={type===t?'active':''} onClick={()=>changeType(t)}><span>{typeInfo[t].icon}</span><b>{typeInfo[t].title}</b><small>{typeInfo[t].desc}</small></button>)}</div></section>
  <section className="partner-editor-section"><h3>2. Thông tin chung · {typeInfo[type].title}</h3><div className="partner-form two"><F label="Tên sản phẩm"><input value={form.name} onChange={e=>setForm((s:any)=>({...s,name:e.target.value,slug:s.id?s.slug:slugify(e.target.value)}))}/></F><F label="Đường dẫn / slug"><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></F><F label={type==='Du thuyền'?'Vịnh / khu vực':type==='Tour du lịch'?'Điểm đến chính':'Khu vực'}><input value={form.place} onChange={e=>set('place',e.target.value)}/></F><F label={type==='Du thuyền'?'Bến / địa chỉ tập trung':type==='Tour du lịch'?'Điểm tập trung':'Địa chỉ'}><input value={form.address} onChange={e=>set('address',e.target.value)}/></F><F label="Phân loại"><input value={form.category||''} onChange={e=>set('category',e.target.value)} placeholder={type==='Villa & Resort'?'Villa biển / Resort / Villa nguyên căn':type==='Khách sạn'?'Resort biển / City hotel':type==='Du thuyền'?'Trong ngày / ngủ đêm':'Trong nước / quốc tế'}/></F><F label="Hạng dịch vụ / số sao *" hint="Bắt buộc chọn trước khi gửi duyệt"><select value={form.serviceStars||''} onChange={e=>set('serviceStars',e.target.value)} required><option value="">— Chọn hạng dịch vụ —</option><option value="1">★ 1 sao</option><option value="2">★★ 2 sao</option><option value="3">★★★ 3 sao</option><option value="4">★★★★ 4 sao</option><option value="5">★★★★★ 5 sao</option></select></F><F label="Giá tham khảo"><input value={form.price} onChange={e=>set('price',e.target.value)} placeholder="Giá chính thức thiết lập ở Giá & tình trạng"/></F>{type!=='Tour du lịch'&&<><F label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></F><F label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></F></>}{(type==='Du thuyền'||type==='Tour du lịch')&&<F label="Thời lượng"><input value={form.duration||''} onChange={e=>set('duration',e.target.value)} placeholder="VD: 2 ngày 1 đêm / 4N3Đ"/></F>}{type==='Du thuyền'&&<F label="Bến lên tàu"><input value={form.boarding||''} onChange={e=>set('boarding',e.target.value)}/></F>}{type==='Tour du lịch'&&<><F label="Khởi hành từ"><input value={form.departure||''} onChange={e=>set('departure',e.target.value)} placeholder="Hà Nội / TP.HCM"/></F><F label="Tuyến hành trình"><input value={form.route||''} onChange={e=>set('route',e.target.value)} placeholder="Hà Nội - Đà Nẵng - Hội An"/></F><F label="Hãng bay"><input value={form.airline||''} onChange={e=>set('airline',e.target.value)}/></F><F label="Phương tiện"><input value={form.transport||''} onChange={e=>set('transport',e.target.value)} placeholder="Máy bay, ô tô, tàu..."/></F></>}<F label="Mô tả ngắn" wide><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)}/></F></div></section>
  <section className="partner-editor-section"><h3>3. Ảnh đại diện & Album</h3><div className="partner-form two"><F label="Ảnh đại diện URL"><input value={String(form.cover||'').startsWith('data:')?'':form.cover||''} onChange={e=>set('cover',e.target.value)} placeholder="Không bắt buộc nếu đã tải album"/></F><div className="partner-upload-card"><b>Upload nhiều ảnh</b><small>Tối đa 12 ảnh/lần, 30 ảnh/sản phẩm. Ảnh lớn tự động thu về tối đa 1920px và nén chất lượng cao để website tải nhanh nhưng vẫn rõ nét.</small><label className="partner-upload-button">{uploading?'Đang tối ưu ảnh...':'+ Chọn nhiều ảnh'}<input type="file" multiple accept="image/*" onChange={upload} disabled={uploading}/></label></div></div>{photos.length>0&&<div className="partner-photo-grid">{photos.map((src,i)=><figure key={`${i}_${src.slice(0,20)}`}><img src={src} alt={`Ảnh ${i+1}`}/><button type="button" onClick={()=>removePhoto(i)}>×</button>{form.cover===src&&<em>Ảnh đại diện</em>}</figure>)}</div>}<F label="Hoặc dán URL album — mỗi URL một dòng" wide><textarea rows={3} value={form.gallery} onChange={e=>set('gallery',e.target.value)}/></F></section>
  {(type==='Villa & Resort'||type==='Khách sạn')&&<section className="partner-editor-section"><h3>4. {type==='Villa & Resort'?'Căn Villa & cấu hình lưu trú':'Hạng phòng & cấu hình khách sạn'}</h3><div className="partner-form two"><F label={type==='Villa & Resort'?'Danh sách căn / loại Villa':'Danh sách hạng phòng'} wide hint="Mỗi dòng một loại, có thể ghi mã | tên | phòng ngủ/giường | sức chứa | số lượng"><textarea rows={7} value={form.unitsText} onChange={e=>set('unitsText',e.target.value)} placeholder={type==='Villa & Resort'?'OCA-A12 | Villa 3PN | 3 phòng ngủ | 6 NL + 2 TE | 5 căn':'DLX-01 | Deluxe Ocean | King/Twin | 2 khách | 10 phòng'}/></F><F label="Tiện ích chung" wide><textarea rows={4} value={form.amenities} onChange={e=>set('amenities',e.target.value)} placeholder="Hồ bơi, wifi, buffet sáng, bãi biển..."/></F><F label="Chính sách trẻ em"><textarea rows={3} value={form.childrenPolicy||''} onChange={e=>set('childrenPolicy',e.target.value)}/></F><F label="Phụ thu"><textarea rows={3} value={form.extraCharge||''} onChange={e=>set('extraCharge',e.target.value)}/></F><F label="Chính sách hủy / đặt cọc" wide><textarea rows={4} value={form.policies} onChange={e=>set('policies',e.target.value)}/></F></div></section>}
  {type==='Du thuyền'&&<section className="partner-editor-section"><h3>4. Cabin & hành trình du thuyền</h3><div className="partner-form two"><F label="Danh sách cabin" wide hint="Mỗi dòng: mã cabin | tên cabin | giường | sức chứa | diện tích | số cabin"><textarea rows={7} value={form.unitsText} onChange={e=>set('unitsText',e.target.value)} placeholder="DLX-01 | Deluxe Bay View | Double/Twin | 2 khách | 28m² | 8 cabin"/></F><F label="Lịch trình" wide><textarea rows={6} value={form.itinerary||''} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1: Hạ Long - Hang Sửng Sốt..."/></F><F label="Dịch vụ / tiện ích" wide><textarea rows={4} value={form.amenities} onChange={e=>set('amenities',e.target.value)} placeholder="Các bữa ăn, kayak, vé tham quan, lớp nấu ăn..."/></F><F label="Chính sách trẻ em"><textarea rows={3} value={form.childrenPolicy||''} onChange={e=>set('childrenPolicy',e.target.value)}/></F><F label="Phụ thu"><textarea rows={3} value={form.extraCharge||''} onChange={e=>set('extraCharge',e.target.value)}/></F><F label="Chính sách hủy" wide><textarea rows={4} value={form.policies} onChange={e=>set('policies',e.target.value)}/></F></div></section>}
  {type==='Tour du lịch'&&<section className="partner-editor-section"><h3>4. Chương trình Tour</h3><div className="partner-form two"><F label="Lịch khởi hành" wide hint="Mỗi ngày một dòng, VD: 05/09/2026"><textarea rows={4} value={form.departures||''} onChange={e=>set('departures',e.target.value)}/></F><F label="Lịch trình chi tiết" wide><textarea rows={8} value={form.itinerary||''} onChange={e=>set('itinerary',e.target.value)} placeholder="Ngày 1: ...\nNgày 2: ..."/></F><F label="Điểm nổi bật" wide><textarea rows={4} value={form.highlights||''} onChange={e=>set('highlights',e.target.value)}/></F><F label="Giá bao gồm" wide><textarea rows={4} value={form.included||form.amenities||''} onChange={e=>{set('included',e.target.value);set('amenities',e.target.value)}}/></F><F label="Không bao gồm" wide><textarea rows={4} value={form.excluded||''} onChange={e=>set('excluded',e.target.value)}/></F><F label="Khuyến mại / quà tặng" wide><textarea rows={3} value={form.promotions||''} onChange={e=>set('promotions',e.target.value)}/></F><F label="Chính sách Tour" wide><textarea rows={5} value={form.policies} onChange={e=>set('policies',e.target.value)}/></F><F label="Hỏi đáp thường gặp" wide><textarea rows={4} value={form.faq||''} onChange={e=>set('faq',e.target.value)} placeholder="Mỗi dòng một câu hỏi / câu trả lời"/></F></div></section>}
  <section className="partner-editor-section"><h3>5. Nội dung chi tiết</h3><div className="partner-form"><F label="Nội dung giới thiệu sản phẩm" wide><textarea rows={7} value={form.content||''} onChange={e=>set('content',e.target.value)} placeholder="Giới thiệu chi tiết, lợi thế, trải nghiệm nổi bật..."/></F></div></section>
  <div className="partner-editor-actions partner-editor-actions-sticky"><button type="button" onClick={onSaveDraft}>Lưu nháp</button><button type="button" className="partner-primary" onClick={submitForReview}>Gửi HappyGo duyệt</button></div>
 </div>
}
