'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Ticket={id:string;partnerId:string;partnerName:string;subject:string;category:string;status:'new'|'processing'|'waiting'|'resolved';createdAt:string;updatedAt:string;messages:{id:string;from:'partner'|'admin';name:string;text:string;at:string}[]};
const labels:Record<string,string>={new:'Mới',processing:'Đang xử lý',waiting:'Chờ đối tác',resolved:'Hoàn tất'};

export function PartnerSupportCenter(){
 const[items,setItems]=useState<Ticket[]>([]),[selected,setSelected]=useState(''),[text,setText]=useState(''),[filter,setFilter]=useState('open'),[msg,setMsg]=useState(''),[authorized,setAuthorized]=useState(true),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/admin/partner-support',{cache:'no-store'});if(r.status===401){setAuthorized(false);setMsg('Tài khoản hiện tại không có quyền hỗ trợ đối tác.');return}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Không đọc được hỗ trợ đối tác.');setItems(Array.isArray(data.tickets)?data.tickets:[]);setAuthorized(true)}catch(error){setMsg(error instanceof Error?error.message:'Không kết nối được hệ thống hỗ trợ.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[load]);
 const list=useMemo(()=>items.filter(x=>filter==='all'||(filter==='open'?x.status!=='resolved':x.status===filter)).sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt)),[items,filter]);const current=items.find(x=>x.id===selected)||list[0];
 async function request(method:'POST'|'PATCH',body:any){setBusy(true);setMsg('');try{const r=await fetch('/api/admin/partner-support',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(r.status===401){setAuthorized(false);throw new Error('Tài khoản hiện tại không có quyền hỗ trợ đối tác.')}if(!r.ok)throw new Error(data.error||'Không thể cập nhật.');setItems(Array.isArray(data.tickets)?data.tickets:[])}catch(error){setMsg(error instanceof Error?error.message:'Không thể cập nhật hỗ trợ đối tác.')}finally{setBusy(false)}}
 async function patch(id:string,status:Ticket['status']){await request('PATCH',{ticketId:id,status})}
 async function send(){if(!current||!text.trim())return;await request('POST',{ticketId:current.id,text:text.trim()});setText('')}
 if(loading&&!items.length)return <section className="admin-panel partner-support-admin"><div className="admin-empty-state"><b>Đang tải hỗ trợ đối tác production...</b><p>Đang đọc dữ liệu bằng phiên Admin hiện tại.</p></div></section>;
 if(!authorized)return <section className="admin-panel partner-support-admin"><div className="admin-panel-head"><div><h2>Hỗ trợ & trao đổi đối tác</h2><p>Module này yêu cầu quyền “partners” hoặc tài khoản Admin/Owner.</p></div><button onClick={()=>void load()}>↻ Kiểm tra lại</button></div>{msg&&<div className="admin-connect-error">{msg}</div>}</section>;
 return <section className="admin-panel partner-support-admin"><div className="admin-panel-head"><div><small>PRODUCTION SUPPORT</small><h2>Hỗ trợ & trao đổi đối tác</h2><p>Yêu cầu từ /partner được lưu trên Neon và hiển thị ở đây theo thời gian thực.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Đang xử lý</option><option value="new">Mới</option><option value="processing">Đang xử lý</option><option value="waiting">Chờ đối tác</option><option value="resolved">Hoàn tất</option><option value="all">Tất cả</option></select></div><div className="partner-support-grid"><div className="partner-support-list">{list.map(t=><button key={t.id} className={current?.id===t.id?'active':''} onClick={()=>setSelected(t.id)}><b>{t.subject}</b><span>{t.partnerName} · {t.category}</span><small>{new Date(t.updatedAt).toLocaleString('vi-VN')} · {labels[t.status]}</small></button>)}{!list.length&&<div className="admin-empty-state">Chưa có yêu cầu hỗ trợ production.</div>}</div><div className="partner-support-thread">{current?<><header><div><b>{current.subject}</b><small>{current.partnerName} · {current.category}</small></div><select value={current.status} onChange={e=>void patch(current.id,e.target.value as Ticket['status'])} disabled={busy}><option value="new">Mới</option><option value="processing">Đang xử lý</option><option value="waiting">Chờ đối tác</option><option value="resolved">Hoàn tất</option></select></header><div className="partner-support-messages">{current.messages.map(m=><article key={m.id} className={m.from==='admin'?'mine':''}><b>{m.name}</b><p>{m.text}</p><small>{new Date(m.at).toLocaleString('vi-VN')}</small></article>)}</div><div className="partner-support-compose"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Trả lời đối tác..." onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button className="admin-primary" onClick={()=>void send()} disabled={busy}>{busy?'Đang gửi...':'Gửi trả lời'}</button></div></>:<div className="admin-empty-state">Chọn một yêu cầu để xem trao đổi.</div>}</div></div>{msg&&<div className="admin-production-message">{msg}</div>}</section>
}
