'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {HappyGoLogo} from '@/components/HappyGoLogo';
import {PartnerProductEditor} from '@/components/PartnerProductEditor';
import {PartnerRateManager,PARTNER_PRICING_KEY} from '@/components/PartnerRateManager';
import {PartnerSupportBadge,PartnerSupportPortal} from '@/components/PartnerSupportPortal';

type ProductType='Villa & Resort'|'Khách sạn'|'Du thuyền'|'Tour du lịch';
type ProductStatus='draft'|'review'|'approved'|'rejected';
type Tab='overview'|'products'|'rates'|'messages'|'finance'|'api'|'profile';
type Partner={id:string;name:string;contact:string;phone:string;email:string;website:string;taxCode:string;address:string;status:string;commissionPercent?:number;createdAt?:string};
type PartnerProduct={id:string;partnerId:string;partnerName:string;type:ProductType;name:string;slug:string;place:string;address:string;price:string;summary:string;cover:string;gallery:string;amenities:string;policies:string;checkin:string;checkout:string;unitsText:string;status:ProductStatus;source:'manual'|'api';updatedAt:string;[key:string]:any};

type ApiConfig={url:string;token:string;itemsPath:string};
const PRODUCT_CACHE='happygo_partner_products_v1';
const nav:{id:Tab;icon:string;label:string}[]=[
  {id:'overview',icon:'⌂',label:'Tổng quan'},
  {id:'products',icon:'▦',label:'Sản phẩm'},
  {id:'rates',icon:'▤',label:'Giá & tình trạng'},
  {id:'messages',icon:'✉',label:'Hỗ trợ'},
  {id:'finance',icon:'₫',label:'Tài chính'},
  {id:'api',icon:'↔',label:'Kết nối API'},
  {id:'profile',icon:'⚙',label:'Hồ sơ doanh nghiệp'},
];
const blankPartner:Partner={id:'',name:'',contact:'',phone:'',email:'',website:'',taxCode:'',address:'',status:'pending'};
const blankProduct=(partner:Partner):PartnerProduct=>({id:'',partnerId:partner.id,partnerName:partner.name,type:'Villa & Resort',name:'',slug:'',place:'',address:'',price:'',summary:'',cover:'',gallery:'',amenities:'',policies:'',checkin:'14:00',checkout:'12:00',unitsText:'',units:[],status:'draft',source:'manual',updatedAt:'',category:'',duration:'',boarding:'',departure:'',route:'',airline:'',transport:'',departures:'',itinerary:'',highlights:'',included:'',excluded:'',promotions:'',faq:'',childrenPolicy:'',extraCharge:'',content:''});
const slugify=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const getPath=(obj:any,path:string)=>path.trim()?path.split('.').filter(Boolean).reduce((v,k)=>v?.[k],obj):obj;
const normalizeType=(v:unknown):ProductType=>{const s=String(v||'').toLowerCase();if(s.includes('tour'))return'Tour du lịch';if(s.includes('cruise')||s.includes('du thuy'))return'Du thuyền';if(s.includes('hotel')||s.includes('khach'))return'Khách sạn';return'Villa & Resort'};
function fromApi(raw:any,partner:Partner):PartnerProduct{const name=String(raw?.name||raw?.title||raw?.product_name||'Sản phẩm đối tác');const rawUnits=raw?.units||raw?.rooms||[];return{...blankProduct(partner),partnerId:partner.id,partnerName:partner.name,type:normalizeType(raw?.type||raw?.product_type||raw?.category),name,slug:String(raw?.slug||slugify(name)),place:String(raw?.place||raw?.location||raw?.destination||''),address:String(raw?.address||''),price:String(raw?.price_text||raw?.price||raw?.from_price||''),summary:String(raw?.summary||raw?.description||''),cover:String(raw?.cover_url||raw?.image||raw?.thumbnail||''),gallery:Array.isArray(raw?.gallery)?raw.gallery.join('\n'):String(raw?.gallery||''),amenities:Array.isArray(raw?.amenities)?raw.amenities.join(', '):String(raw?.amenities||''),policies:String(raw?.policies||raw?.policy||''),checkin:String(raw?.checkin||'14:00'),checkout:String(raw?.checkout||'12:00'),unitsText:JSON.stringify(rawUnits,null,2),units:Array.isArray(rawUnits)?rawUnits:[],status:'review',source:'api',updatedAt:new Date().toISOString(),category:String(raw?.category||''),duration:String(raw?.duration||''),departure:String(raw?.departure||raw?.departure_from||''),route:String(raw?.route||''),airline:String(raw?.airline||''),departures:Array.isArray(raw?.departures)?raw.departures.join('\n'):String(raw?.departures||''),itinerary:Array.isArray(raw?.itinerary)?raw.itinerary.map((x:any)=>typeof x==='string'?x:(x?.title||JSON.stringify(x))).join('\n'):String(raw?.itinerary||''),highlights:Array.isArray(raw?.highlights)?raw.highlights.join('\n'):String(raw?.highlights||''),included:Array.isArray(raw?.included)?raw.included.join('\n'):String(raw?.included||''),excluded:Array.isArray(raw?.excluded)?raw.excluded.join('\n'):String(raw?.excluded||''),promotions:Array.isArray(raw?.promotions)?raw.promotions.join('\n'):String(raw?.promotions||''),content:String(raw?.content||'')}}

export function PartnerProductionPortal(){
  const[ready,setReady]=useState(false),[partner,setPartner]=useState<Partner|null>(null),[products,setProducts]=useState<PartnerProduct[]>([]),[tab,setTab]=useState<Tab>('overview'),[editing,setEditing]=useState(false),[form,setForm]=useState<PartnerProduct>(blankProduct(blankPartner)),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[authMode,setAuthMode]=useState<'login'|'register'>('login'),[login,setLogin]=useState({email:'',password:''}),[register,setRegister]=useState({companyName:'',contactName:'',phone:'',email:'',password:'',confirm:''}),[api,setApi]=useState<ApiConfig>({url:'',token:'',itemsPath:'items'});

  async function loadProducts(){const r=await fetch('/api/partner/products',{cache:'no-store'});if(r.status===401){setPartner(null);setProducts([]);return}if(!r.ok)return;const data=await r.json();const list=Array.isArray(data?.products)?data.products:[];setProducts(list);try{localStorage.setItem(PRODUCT_CACHE,JSON.stringify(list))}catch{}}
  async function loadRates(){try{const r=await fetch('/api/partner/rates',{cache:'no-store'});if(!r.ok)return;const data=await r.json();const rates=Array.isArray(data?.rates)?data.rates:[];localStorage.setItem(PARTNER_PRICING_KEY,JSON.stringify(rates));window.dispatchEvent(new Event('happygo-partner-rates-updated'))}catch{}}
  async function loadSession(){try{const r=await fetch('/api/partner/me',{cache:'no-store'});if(r.ok){const data=await r.json();setPartner(data.partner);setForm(blankProduct(data.partner));await Promise.all([loadProducts(),loadRates()])}else setPartner(null)}finally{setReady(true)}}
  useEffect(()=>{void loadSession()},[]);
  useEffect(()=>{if(!partner)return;let timer:number|undefined;const syncRates=()=>{if(timer)window.clearTimeout(timer);timer=window.setTimeout(async()=>{try{const all=JSON.parse(localStorage.getItem(PARTNER_PRICING_KEY)||'[]');const mine=Array.isArray(all)?all.filter((x:any)=>products.some(p=>p.id===x?.productId)):[];await fetch('/api/partner/rates',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({rates:mine})})}catch{}},500)};window.addEventListener('happygo-partner-rates-updated',syncRates);return()=>{window.removeEventListener('happygo-partner-rates-updated',syncRates);if(timer)window.clearTimeout(timer)}},[partner,products]);

  const mine=products;
  const completed=partner?[Boolean(partner.name),Boolean(partner.taxCode),Boolean(partner.phone&&partner.email),mine.length>0].filter(Boolean).length:0;
  const statusLabel:Record<string,string>={pending:'Chờ HappyGo duyệt',active:'Đang hoạt động',rejected:'Cần bổ sung hồ sơ',blocked:'Tạm khóa'};

  async function auth(endpoint:string,payload:unknown){setBusy(true);setMsg('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){setMsg(data.error||'Không thể xử lý yêu cầu.');return false}setPartner(data.partner);setForm(blankProduct(data.partner));setTab('overview');await Promise.all([loadProducts(),loadRates()]);return true}catch{setMsg('Không kết nối được máy chủ. Vui lòng thử lại.');return false}finally{setBusy(false)}}
  async function doLogin(e:FormEvent){e.preventDefault();await auth('/api/partner/auth/login',login)}
  async function doRegister(e:FormEvent){e.preventDefault();if(register.password!==register.confirm){setMsg('Mật khẩu xác nhận chưa khớp.');return}await auth('/api/partner/auth/register',{companyName:register.companyName,contactName:register.contactName,phone:register.phone,email:register.email,password:register.password})}
  async function logout(){await fetch('/api/partner/auth/logout',{method:'POST'});setPartner(null);setProducts([]);setEditing(false);setLogin({email:'',password:''});setAuthMode('login')}
  async function saveProfile(e:FormEvent){e.preventDefault();if(!partner)return;setBusy(true);setMsg('');try{const r=await fetch('/api/partner/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(partner)});const data=await r.json();if(!r.ok)return setMsg(data.error||'Không thể lưu hồ sơ.');setPartner(data.partner);setForm(s=>({...s,partnerName:data.partner.name,partnerId:data.partner.id}));setMsg('Đã lưu hồ sơ doanh nghiệp trên hệ thống HappyGo.')}finally{setBusy(false)}}
  function startNew(){if(!partner)return;setForm(blankProduct(partner));setEditing(true);setTab('products');setMsg('')}
  function edit(p:PartnerProduct){if(!partner)return;setForm({...blankProduct(partner),...p});setEditing(true);setTab('products');setMsg('')}
  async function persist(status:'draft'|'review') {if(!partner)return;if(!form.name.trim())return setMsg('Vui lòng nhập tên sản phẩm.');setBusy(true);setMsg('');try{const payload={...form,partnerId:partner.id,partnerName:partner.name,slug:form.slug||slugify(form.name),status,updatedAt:new Date().toISOString()};const r=await fetch('/api/partner/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:payload})});const data=await r.json();if(!r.ok)return setMsg(data.error||'Không thể lưu sản phẩm.');setForm(data.product);setEditing(false);await loadProducts();setMsg(status==='review'?'Đã gửi sản phẩm lên hệ thống HappyGo để duyệt.':'Đã lưu bản nháp trên hệ thống.')}finally{setBusy(false)}}
  async function remove(p:PartnerProduct){if(!confirm(`Xóa “${p.name}”?`))return;const r=await fetch(`/api/partner/products?id=${encodeURIComponent(p.id)}`,{method:'DELETE'});const data=await r.json().catch(()=>({}));if(!r.ok)return setMsg(data.error||'Không thể xóa sản phẩm.');await loadProducts();setMsg('Đã xóa sản phẩm.')}
  async function syncApi(){if(!partner||!api.url.trim())return setMsg('Vui lòng nhập API endpoint.');setBusy(true);setMsg('');try{const headers:Record<string,string>={Accept:'application/json'};if(api.token.trim())headers.Authorization=`Bearer ${api.token.trim()}`;const r=await fetch(api.url,{headers});if(!r.ok)throw new Error(`API trả về ${r.status}`);const data=await r.json();const raw=getPath(data,api.itemsPath);if(!Array.isArray(raw))throw new Error(`Không tìm thấy mảng sản phẩm tại “${api.itemsPath||'(root)'}”`);let count=0;for(const item of raw){const product=fromApi(item,partner);const save=await fetch('/api/partner/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product})});if(save.ok)count++}await loadProducts();setMsg(`Đã đồng bộ ${count}/${raw.length} sản phẩm lên HappyGo. Tất cả được đưa vào trạng thái chờ duyệt.`)}catch(error){setMsg(error instanceof Error?error.message:'Không thể đồng bộ API.')}finally{setBusy(false)}}

  if(!ready)return <main className="partner-auth-wrap"><section className="partner-auth-card"><HappyGoLogo/><h2>Đang kết nối cổng đối tác...</h2><p>HappyGo đang kiểm tra phiên đăng nhập bảo mật.</p></section></main>;
  if(!partner)return <main className="partner-auth-wrap"><section className="partner-auth-intro"><HappyGoLogo/><small>CỔNG ĐỐI TÁC HAPPYGO</small><h1>Một tài khoản, quản lý sản phẩm và hợp tác trên mọi thiết bị.</h1><p>Dữ liệu đối tác được lưu trên hệ thống HappyGo thay vì chỉ nằm trong trình duyệt hiện tại.</p><div className="partner-auth-benefits"><div><b>✓ Sản phẩm tập trung</b><span>Gửi duyệt và theo dõi trạng thái trực tiếp.</span></div><div><b>✓ Giá & tồn phòng</b><span>Đồng bộ bảng giá lên tài khoản doanh nghiệp.</span></div><div><b>✓ Admin kết nối</b><span>HappyGo duyệt hồ sơ và sản phẩm trên cùng nguồn dữ liệu.</span></div></div><Link href="/">← Về website HappyGo</Link></section><section className="partner-auth-card"><small>HAPPYGO PARTNER</small><h2>{authMode==='login'?'Đăng nhập đối tác':'Đăng ký hợp tác'}</h2><p>{authMode==='login'?'Truy cập tài khoản doanh nghiệp của bạn.':'Tạo hồ sơ để gửi sản phẩm lên HappyGo duyệt.'}</p>{authMode==='login'?<form onSubmit={doLogin}><label>Email<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required autoComplete="email"/></label><label>Mật khẩu<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required autoComplete="current-password"/></label><button className="partner-primary" disabled={busy}>{busy?'Đang đăng nhập...':'Đăng nhập'}</button></form>:<form onSubmit={doRegister}><label>Tên doanh nghiệp<input value={register.companyName} onChange={e=>setRegister({...register,companyName:e.target.value})} required/></label><label>Người liên hệ<input value={register.contactName} onChange={e=>setRegister({...register,contactName:e.target.value})} required/></label><label>Số điện thoại<input value={register.phone} onChange={e=>setRegister({...register,phone:e.target.value})} required/></label><label>Email<input type="email" value={register.email} onChange={e=>setRegister({...register,email:e.target.value})} required/></label><div className="partner-auth-passwords"><label>Mật khẩu<input type="password" minLength={8} value={register.password} onChange={e=>setRegister({...register,password:e.target.value})} required/></label><label>Xác nhận<input type="password" minLength={8} value={register.confirm} onChange={e=>setRegister({...register,confirm:e.target.value})} required/></label></div><button className="partner-primary" disabled={busy}>{busy?'Đang tạo tài khoản...':'Đăng ký đối tác'}</button></form>}{msg&&<div className="partner-message">{msg}</div>}<button className="partner-auth-switch" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setMsg('')}}>{authMode==='login'?'Chưa có tài khoản? Đăng ký hợp tác':'Đã có tài khoản? Đăng nhập'}</button></section></main>;

  if(editing)return <div className="partner-hub partner-production"><header className="partner-hub-top"><Link href="/" className="partner-brand"><HappyGoLogo compact/></Link><div className="partner-hub-tools"><span>{partner.name}</span><button onClick={()=>setEditing(false)}>← Cổng đối tác</button></div></header><main className="partner-editor-workspace"><PartnerProductEditor form={form} setForm={setForm} onCancel={()=>setEditing(false)} onSaveDraft={()=>void persist('draft')} onSubmit={()=>void persist('review')} slugify={slugify} setMessage={setMsg}/>{msg&&<div className="partner-message portal-sticky-message">{msg}</div>}</main></div>;

  const reviewed=mine.filter(x=>x.status==='approved').length,waiting=mine.filter(x=>x.status==='review').length,drafts=mine.filter(x=>x.status==='draft').length;
  return <div className="partner-hub partner-production"><header className="partner-hub-top"><Link href="/" className="partner-brand"><HappyGoLogo compact/></Link><div className="partner-hub-tools"><Link href="/">Xem website</Link><div className="partner-user"><span>{partner.name}</span><small>{statusLabel[partner.status]||partner.status}</small></div><button onClick={()=>void logout()}>Đăng xuất</button></div></header><div className="partner-hub-layout"><aside className="partner-sidebar"><div className="partner-company"><small>ĐỐI TÁC HAPPYGO</small><b>{partner.name}</b><span className={`partner-account-state ${partner.status}`}>{statusLabel[partner.status]||partner.status}</span></div><nav>{nav.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>{setTab(item.id);setMsg('')}}><i>{item.icon}</i><span>{item.label}</span>{item.id==='messages'?<PartnerSupportBadge partnerId={partner.id}/>:null}</button>)}</nav><div className="partner-sidebar-foot"><Link href="/">← Website HappyGo</Link><small>Mã đối tác<br/><b>{partner.id.slice(0,8).toUpperCase()}</b></small></div></aside><main className="partner-workspace">{tab==='overview'&&<><div className="partner-page-head"><div><small>HAPPYGO PARTNER · PRODUCTION</small><h1>Tổng quan đối tác</h1><p>Hồ sơ, sản phẩm và bảng giá đang dùng dữ liệu tập trung của HappyGo.</p></div><button className="partner-primary" onClick={startNew}>＋ Thêm sản phẩm</button></div>{partner.status!=='active'&&<div className="partner-welcome partner-status-banner"><div><small>TRẠNG THÁI HỒ SƠ</small><h2>{statusLabel[partner.status]||partner.status}</h2><p>Bạn vẫn có thể hoàn thiện hồ sơ và gửi sản phẩm. Sản phẩm chỉ xuất hiện trên website sau khi HappyGo kích hoạt đối tác và duyệt sản phẩm.</p></div><button onClick={()=>setTab('profile')}>Hoàn thiện hồ sơ →</button></div>}<div className="partner-kpis"><article><span>Tổng sản phẩm</span><b>{mine.length}</b><small>Trên tài khoản production</small></article><article><span>Chờ duyệt</span><b>{waiting}</b><small>HappyGo đang kiểm tra</small></article><article><span>Đã duyệt</span><b>{reviewed}</b><small>Sẵn sàng lên catalog</small></article><article><span>Hoàn thiện hồ sơ</span><b>{completed}/4</b><small>Tên · MST · liên hệ · sản phẩm</small></article></div><section className="partner-panel"><div className="partner-panel-head"><div><h3>Luồng hợp tác đã chuẩn hóa</h3><p>Đối tác → HappyGo Admin → Website dùng chung một nguồn dữ liệu.</p></div></div><div className="portal-flow"><article><b>1</b><span>Đối tác cập nhật hồ sơ, sản phẩm và giá</span></article><article><b>2</b><span>Admin kiểm tra và duyệt trên production</span></article><article><b>3</b><span>Sản phẩm được đồng bộ vào catalog website</span></article></div></section></>}
      {tab==='products'&&<><div className="partner-page-head"><div><small>SẢN PHẨM</small><h1>Danh mục của doanh nghiệp</h1><p>Mọi thay đổi được lưu trên server và có thể tiếp tục ở thiết bị khác.</p></div><button className="partner-primary" onClick={startNew}>＋ Thêm sản phẩm</button></div><section className="partner-panel"><div className="partner-product-list">{mine.length?mine.map(p=><article key={p.id}><div className="partner-thumb">{p.cover?<img src={p.cover} alt=""/>:<span>{p.type.slice(0,2)}</span>}</div><div><b>{p.name}</b><small>{p.type} · {p.place||'Chưa nhập địa điểm'}</small><span>{p.summary||'Chưa có mô tả ngắn.'}</span></div><em className={`partner-status ${p.status}`}>{p.status==='approved'?'Đã duyệt':p.status==='review'?'Chờ duyệt':p.status==='rejected'?'Cần chỉnh sửa':'Bản nháp'}</em><div className="partner-actions"><button onClick={()=>edit(p)}>Chỉnh sửa</button>{p.status!=='approved'&&<button onClick={()=>void remove(p)}>Xóa</button>}</div></article>):<div className="partner-empty"><b>Chưa có sản phẩm</b><p>Tạo sản phẩm đầu tiên để bắt đầu quy trình duyệt.</p><button className="partner-primary" onClick={startNew}>＋ Tạo sản phẩm</button></div>}</div></section></>}
      {tab==='rates'&&<><div className="partner-page-head"><div><small>GIÁ & TÌNH TRẠNG</small><h1>Bảng giá đối tác</h1><p>Bảng giá được đồng bộ vào dữ liệu production sau khi bạn lưu.</p></div></div><PartnerRateManager products={mine}/></>}
      {tab==='messages'&&<PartnerSupportPortal partner={{id:partner.id,name:partner.name,contact:partner.contact}}/>}
      {tab==='finance'&&<><div className="partner-page-head"><div><small>TÀI CHÍNH</small><h1>Đối soát hợp tác</h1><p>Tổng quan thương mại dựa trên sản phẩm và cấu hình giá hiện tại.</p></div></div><div className="partner-kpis"><article><span>Sản phẩm đã duyệt</span><b>{reviewed}</b></article><article><span>Hoa hồng mặc định</span><b>{partner.commissionPercent||0}%</b></article><article><span>Đơn đối soát</span><b>0</b><small>Sẽ phát sinh khi booking partner được ghi nhận</small></article><article><span>Thanh toán chờ</span><b>0đ</b></article></div><section className="partner-panel"><h3>Chuẩn dữ liệu tài chính</h3><p>Giá net và commission chỉ nằm trong Partner + Admin; API catalog công khai không trả các trường nội bộ này.</p></section></>}
      {tab==='api'&&<><div className="partner-page-head"><div><small>KẾT NỐI API</small><h1>Nhập sản phẩm từ hệ thống của đối tác</h1><p>Dữ liệu sau khi nhập được lưu thẳng vào tài khoản production và đưa về trạng thái chờ duyệt.</p></div></div><section className="partner-panel partner-api-panel"><label>API endpoint<input value={api.url} onChange={e=>setApi({...api,url:e.target.value})} placeholder="https://example.com/api/products"/></label><label>Bearer token — chỉ giữ trong phiên hiện tại<input type="password" value={api.token} onChange={e=>setApi({...api,token:e.target.value})} autoComplete="off"/></label><label>Đường dẫn tới mảng sản phẩm<input value={api.itemsPath} onChange={e=>setApi({...api,itemsPath:e.target.value})} placeholder="items"/></label><button className="partner-primary" onClick={()=>void syncApi()} disabled={busy}>{busy?'Đang đồng bộ...':'Đồng bộ sản phẩm'}</button></section></>}
      {tab==='profile'&&<><div className="partner-page-head"><div><small>HỒ SƠ DOANH NGHIỆP</small><h1>Thông tin đối tác</h1><p>HappyGo Admin đọc trực tiếp hồ sơ này khi xét duyệt tài khoản.</p></div><span className={`partner-account-state ${partner.status}`}>{statusLabel[partner.status]||partner.status}</span></div><form className="partner-panel profile-form" onSubmit={saveProfile}><label>Tên doanh nghiệp<input value={partner.name} onChange={e=>setPartner({...partner,name:e.target.value})} required/></label><label>Người liên hệ<input value={partner.contact} onChange={e=>setPartner({...partner,contact:e.target.value})} required/></label><label>Số điện thoại<input value={partner.phone} onChange={e=>setPartner({...partner,phone:e.target.value})} required/></label><label>Email tài khoản<input value={partner.email} disabled/></label><label>Website<input value={partner.website} onChange={e=>setPartner({...partner,website:e.target.value})} placeholder="https://..."/></label><label>Mã số thuế<input value={partner.taxCode} onChange={e=>setPartner({...partner,taxCode:e.target.value})}/></label><label className="wide">Địa chỉ doanh nghiệp<input value={partner.address} onChange={e=>setPartner({...partner,address:e.target.value})}/></label><button className="partner-primary" disabled={busy}>{busy?'Đang lưu...':'Lưu hồ sơ production'}</button></form></>}
      {msg&&<div className="partner-message portal-sticky-message">{msg}</div>}</main></div></div>;
}
