'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {SafeBackground,SafeImage,travelFallback} from '@/components/SafeImage';
import {readPartnerPublic,partnerPublicPrice,type PartnerPublicProduct,type PartnerPublicPricing} from '@/components/PartnerPublicCatalog';
import {amenityMeta,inferAmenityTags} from '@/components/ProductAmenityModel';

type Kind='stay'|'cruise'|'tour';
const stars=(v?:string)=>{const n=Math.max(0,Math.min(5,Number(v)||0));return n?'★'.repeat(n):''};
const unitPrice=(p:PartnerPublicProduct)=>{const units=Array.isArray(p.units)?p.units.filter(u=>u.status!=='hidden'&&u.status!=='soldout'):[];const values=units.map(u=>Number(String(u.weekdayPrice||'').replace(/\D/g,''))).filter(Boolean);return values.length?`${new Intl.NumberFormat('vi-VN').format(Math.min(...values))}đ`:''};
const tagsOf=(p:PartnerPublicProduct)=>Array.isArray(p.amenityTags)&&p.amenityTags.length?p.amenityTags:inferAmenityTags(p.type,p.amenities);
export function PartnerCategoryCards({kind,q='',stayType='all',bay='all',category='all',amenityIds=[]}:{kind:Kind;q?:string;stayType?:string;bay?:string;category?:string;amenityIds?:string[]}){
 const[products,setProducts]=useState<PartnerPublicProduct[]>([]);const[pricing,setPricing]=useState<PartnerPublicPricing[]>([]);
 useEffect(()=>{let alive=true;const loadLegacy=()=>{const d=readPartnerPublic();if(alive){setPricing(d.pricing);if(d.products.length)setProducts(d.products)}};const loadRemote=async()=>{try{const response=await fetch('/api/catalog/partner-products',{cache:'no-store'});if(!response.ok)return;const data=await response.json() as {products?:PartnerPublicProduct[]};if(alive&&Array.isArray(data.products))setProducts(data.products)}catch{}};loadLegacy();void loadRemote();const onUpdate=()=>{loadLegacy();void loadRemote()};window.addEventListener('happygo-partner-products-updated',onUpdate);window.addEventListener('happygo-partner-rates-updated',loadLegacy);window.addEventListener('storage',loadLegacy);return()=>{alive=false;window.removeEventListener('happygo-partner-products-updated',onUpdate);window.removeEventListener('happygo-partner-rates-updated',loadLegacy);window.removeEventListener('storage',loadLegacy)}},[]);
 const items=useMemo(()=>products.filter(p=>{if(kind==='stay'&&!['Villa & Resort','Khách sạn'].includes(p.type))return false;if(kind==='cruise'&&p.type!=='Du thuyền')return false;if(kind==='tour'&&!['Tour du lịch','Tour'].includes(p.type))return false;const text=`${p.name} ${p.place} ${p.summary} ${p.route||''} ${p.category||''}`.toLowerCase();if(q&&!text.includes(q.toLowerCase()))return false;if(kind==='stay'&&stayType!=='all'){if(stayType==='villa'&&p.type!=='Villa & Resort')return false;if((stayType==='hotel'||stayType==='resort')&&p.type!=='Khách sạn'&&!(p.category||'').toLowerCase().includes('resort'))return false}if(kind==='stay'&&amenityIds.length&&!amenityIds.every(id=>tagsOf(p).includes(id)))return false;if(kind==='cruise'&&bay!=='all'){const place=(p.place||'').toLowerCase();if(bay==='halong'&&!place.includes('hạ long'))return false;if(bay==='lanha'&&!place.includes('lan hạ'))return false}if(kind==='tour'&&category!=='all'){const c=(p.category||'').toLowerCase();if(category==='china'&&!c.includes('trung quốc')&&!text.includes('trung quốc'))return false;if(category==='domestic'&&(c.includes('trung quốc')||c.includes('quốc tế')))return false}return true}),[products,kind,q,stayType,bay,category,amenityIds]);
 const amenityStrip=(p:PartnerPublicProduct)=>tagsOf(p).slice(0,4).map(id=>{const meta=amenityMeta(p.type,id);return meta?<span className="public-amenity-chip" key={id} title={p.amenityDetails?.[id]||meta.label}><b>{meta.icon}</b>{meta.label}</span>:null});
 if(!items.length)return null;
 if(kind==='stay')return <>{items.map(p=>{const roomPrice=unitPrice(p);const displayPrice=roomPrice||partnerPublicPrice(p,pricing);return <article className="booking-card partner-public-card" key={`partner_${p.id}`}><SafeImage src={p.cover} fallback={travelFallback(p.type)} alt={p.name}/><div><span className="meta">{p.type}{p.serviceStars?` · ${stars(p.serviceStars)} ${p.serviceStars} sao`:''}</span><h3>{p.name}</h3><p>📍 {p.place||'Đang cập nhật địa điểm'}</p><p className="summary">{p.summary||'Thông tin chi tiết đang được cập nhật.'}</p>{tagsOf(p).length?<div className="public-amenity-strip">{amenityStrip(p)}</div>:null}{p.type==='Villa & Resort'&&(p.checkin||p.checkout||p.extraPersonFee)?<div className="public-policy-mini"><span>🕑 {p.checkin||'14:00'} → {p.checkout||'12:00'} hôm sau</span>{p.extraPersonFee?<span>👤 Quá người: {p.extraPersonFee}</span>:null}</div>:null}<Link className="view-link" href={`/product?slug=${encodeURIComponent(p.slug)}`}>Xem tiện ích, phòng & chính sách →</Link></div><div className="booking-price"><small>Giá từ</small><strong>{displayPrice}</strong><Link href={`/product?slug=${encodeURIComponent(p.slug)}`}>Xem phòng</Link></div></article>})}</>;
 return <>{items.map(p=><article className="catalog-card cms-public-card partner-public-card" key={`partner_${p.id}`}><SafeBackground src={p.cover} fallback={travelFallback(p.type)} className="catalog-image" ariaLabel={p.name}/><div className="catalog-body"><small>{kind==='cruise'?`${p.place||'Du thuyền'} · ${p.duration||'Lịch trình linh hoạt'}`:`${p.category||'Tour du lịch'} · ${p.duration||'Đang cập nhật'}`}{p.serviceStars?` · ${stars(p.serviceStars)} ${p.serviceStars} sao`:''}</small><h3>{p.name}</h3>{kind==='tour'&&<p>📍 {p.route||p.place||'Đang cập nhật tuyến'}</p>}<p>{p.summary||'Thông tin sản phẩm đang được cập nhật.'}</p>{kind==='cruise'&&tagsOf(p).length?<div className="public-amenity-strip">{amenityStrip(p)}</div>:null}<p><b style={{color:'#f15a24'}}>Từ {partnerPublicPrice(p,pricing)}</b></p><div className="catalog-actions"><Link className="main" href={`/product?slug=${encodeURIComponent(p.slug)}`}>Xem chi tiết</Link></div></div></article>)}</>;
}
