'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ADMIN_API_KEY_STORAGE} from '@/lib/admin-shared-data';

type Ticket={id:string;partnerId:string;partnerName:string;subject:string;category:string;status:'new'|'processing'|'waiting'|'resolved';createdAt:string;updatedAt:string;messages:{id:string;from:'partner'|'admin';name:string;text:string;at:string}[]};
const labels:Record<string,string>={new:'Mới',processing:'Đang xử lý',waiting:'Chờ đối tác',resolved:'Hoàn tất'};

export function PartnerSupportCenter(){
 const[items,setItems]=useState<Ticket[]>([]),[selected,setSelected]=useState(''),[text,setText]=useState(''),[filter,setFilter]=useState('open'),[msg,setMsg]=useState(''),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false);
 const key=()=>localStorage.getItem(ADMIN_API_KEY_STORAGE)?.trim()||'';
 const load=useCallback(async()=>{const secret=key();if(!secret){setConnected(false);return}try{const r=await fetch('/api/admin/partner-support',{cache:'no-store',headers:{'x-admin-key':secret}});if(r.status===401){setConnected(false);setMsg('Khóa nội bộ chưa đúng.');return}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Không đọc được hỗ trợ đối tác.');setItems(Array.isArray(data.tickets)?data.tickets:[]);setConnected(true)}catch(error){setMsg(error instanceof Error?error.message:'Không kết nối được hệ thống hỗ trợ.')}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(load,30000);const sync=()=>void load();window.addEventListener('happygo-admin-shared-status',sync);return()=>{window.clearInterval(timer);window.removeEventListener('happygo-admin-shared-status',sync)}},[load]);
 const list=useMemo(()=>items.filter(x=>filter==='all'||(filter==='open'?x.status!=='resolved':x.status===filter)).sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt)),[items,filter]);const current=items.find(x=>x.id===selected)||list[0];
 async function request(method:'POST'|'PATCH',body:any){const secret=key();if(!secret)return setMsg('Chưa có khóa nội bộ trên thiết bị này.');setBusy(true);setMsg('');try{const r=await fetch('/api/admin/partner-support',{method,headers:{'Content-Type':'application/json','x-admin-key':secret},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Không thể cập nhật.');setItems(Array.isArray(data.tickets)?data.tickets:[])}catch(error){setMsg(error instanceof Error?error.message:'Không thể cập nhật hỗ trợ đối tác.')}finally{setBusy(false)}}
 async function patch(id:string,status:Ticket['status']){await request('PATCH',{ticketId:id,status})}
 async function send(){if(!current||!text.trim())return;await request('POST',{ticketId:current.id,text:text.trim(),name:'HappyGo Support'});setText('')}
 if(!connected)return <section className="admin-panel partner-support-admin"><div className="admin-panel-head"><div><h2>Hỗ trợ & trao đổi đối tác</h2><p>Module production cần khóa nội bộ để đọc yêu cầu từ cổng Đối tác.</p></div><button onClick={()=>void load()}>↻ Kiểm tra lại</button></div><div className="admin-connect-callout"><strong>!</strong><div><b>Chưa kết nối dữ liệu Support</b><span>Mở huy hiệu “Chưa kết nối” trên thanh trên cùng, nhập ADMIN_API_KEY rồi bấm Lưu & đồng bộ.</span></div></div>{msg&&<div className="admin-connect-error">{msg}</div>}</section>;
 return <section className="admin-panel partner-support-admin"><div className="admin-panel-head"><div><small>PRODUCTION SUPPORT</small><h2>Hỗ trợ & trao đổi đối tác</h2><p>Yêu cầu từ /partner được lưu trên Neon và hiển thị ở đây theo thời gian thực.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Đang xử lý</option><option value="new">Mới</option><option value="processing">Đang xử lý</option><option value="waiting">Chờ đối tác</option><option value="resolved">Hoàn tất</option><option value="all">Tất cả</option></select></div><div className="partner-support-grid"><div className="partner-support-list">{list.map(t=><button key={t.id} className={current?.id===t.id?'active':''} onClick={()=>setSelected(t.id)}><b>{t.subject}</b><span>{t.partnerName} · {t.category}</span><small>{new Date(t.updatedAt).toLocaleString('vi-VN')} · {labels[t.status]}</small></button>)}{!list.length&&<div className="admin-empty-state">Chưa có yêu cầu hỗ trợ production.</div>}</div><div className="partner-support-thread">{current?<><header><div><b>{current.subject}</b><small>{current.partnerName} · {current.category}</small></div><select value={current.status} onChange={e=>void patch(current.id,e.target.value as Ticket['status'])} disabled={busy}><option value="new">Mới</option><option value="processing">Đang xử lý</option><option value="waiting">Chờ đối tác</option><option value="resolved">Hoàn tất</option></select></header><div className="partner-support-messages">{current.messages.map(m=><article key={m.id} className={m.from==='admin'?'mine':''}><b>{m.name}</b><p>{m.text}</p><small>{new Date(m.at).toLocaleString('vi-VN')}</small></article>)}</div><div className="partner-support-compose"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Trả lời đối tác..." onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button className="admin-primary" onClick={()=>void send()} disabled={busy}>{busy?'Đang gửi...':'Gửi trả lời'}</button></div></>:<div className="admin-empty-state">Chọn một yêu cầu để xem trao đổi.</div>}</div></div>{msg&&<div className="admin-production-message">{msg}</div>}</section>
}
