'use client';

import {ChangeEvent,useMemo,useState} from 'react';
import {UnifiedProductUnitsEditor,type UnifiedUnit} from '@/components/UnifiedProductUnitsEditor';

type ProductType='Villa & Resort'|'Khách sạn'|'Du thuyền'|'Tour du lịch';
type ProductLike={id?:string;type:ProductType;name:string;slug:string;place:string;address:string;price:string;summary:string;cover:string;gallery:string;amenities:string;policies:string;checkin:string;checkout:string;unitsText:string;units?:UnifiedUnit[];[key:string]:any};
type Props={form:ProductLike;setForm:(next:any)=>void;onCancel:()=>void;onSaveDraft:()=>void;onSubmit:()=>void;slugify:(v:string)=>string;setMessage?:(v:string)=>void};
const lines=(v?:string)=>String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
async function compressImage(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Không đọc được ảnh'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Ảnh không hợp lệ'));img.onload=()=>{const max=1920,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const ctx=c.getContext('2d');if(!ctx)return reject(new Error('Không xử lý được ảnh'));ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL(file.type==='image/png'||file.type==='image/webp'?'image/webp':'image/jpeg',.85))};img.src=String(r.result||'')};r.readAsDataURL(file)})}
function F({label,children,wide=false,hint}:{label:string;children:React.ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'partner-field wide':'partner-field'}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
const typeInfo:Record<ProductType,{icon:string;desc:string}>={
 'Villa & Resort':{icon:'🏝️',desc:'Căn villa, số phòng ngủ, sức chứa, tiện ích và giá từng căn'},
 'Khách sạn':{icon:'🏨',desc:'Hạng phòng, loại giường, bữa ăn, sức chứa và giá từng hạng'},
 'Du thuyền':{icon:'🛳️',desc:'Cabin, sức chứa, diện tích, giá và lịch trình'},
 'Tour du lịch':{icon:'✈️',desc:'Tuyến điểm, lịch khởi hành, phương tiện và chương trình tour'}
};
export function PartnerProductEditor({form,setForm,onCancel,onSaveDraft,onSubmit,slugify,setMessage}:Props){
 const[uploading,setUploading]=useState(false);const photos=useMemo(()=>lines(form.gallery),[form.gallery]);const set=(k:string,v:any)=>setForm((s:any)=>({...s,[k]:v}));const type=form.type;
 function changeType(t:ProductType){setForm((s:any)=>({...s,type:t,checkin:t==='Tour du lịch'?'':(s.checkin||'14:00'),checkout:t==='Tour du lịch'?'':(s.checkout||'12:00'),units:Array.isArray(s.units)?s.units:[]}))}
 async function upload(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);e.target.value='';if(!files.length)return;setUploading(true);try{const urls:string[]=[];for(const f of files.slice(0,Math.min(12,30-photos.length))){if(!f.type.startsWith('image/')||f.size>30*1024*1024)continue;urls.push(await compressImage(f))}const merged=[...photos,...urls];setForm((s:any)=>({...s,gallery:merged.join('\n'),cover:s.cover||merged[0]||''}));setMessage?.(`Đã tối ưu và thêm ${urls.length} ảnh.`)}catch(err){setMessage?.(err instanceof Error?err.message:'Không tải được ảnh')}finally{setUploading(false)}}
 function removePhoto(i:number){const target=photos[i],next=photos.filter((_,n)=>n!==i);setForm((s:any)=>({...s,gallery:next.join('\n'),cover:s.cover===target?(next[0]||''):s.cover}))}
 function submit(){if(!String(form.serviceStars||'').trim()){setMessage?.('Vui lòng chọn hạng dịch vụ / số sao trước khi gửi duyệt.');return}onSubmit()}
 return <div className="partner-editor partner-product-editor-v2"><div className="partner-editor-head"><div><button type="button" onClick={onCancel}>← Danh sách</button><div><h2>{form.id?'Chỉnh sửa sản phẩm':'Đăng sản phẩm mới'}</h2><p>Biểu mẫu này dùng cùng chuẩn dữ liệu với trang Quản trị HappyGo.</p></div></div></div>
 <section className="partner-editor-section"><h3>1. Chọn loại sản phẩm</h3><div className="partner-type-picker">{(Object.keys(typeInfo) as ProductType[]).map(t=><button type="button" key={t} className={type===t?'active':''} onClick={()=>changeType(t)}><span>{typeInfo[t].icon}</span><b>{t}</b><small>{typeInfo[t].desc}</small></button>)}</div></section>
 <section className="partner-editor-section"><h3>2. Thông tin chung</h3><div className="partner-form two"><F label="Tên sản phẩm"><input value={form.name} onChange={e=>setForm((s:any)=>({...s,name:e.target.value,slug:s.id?s.slug:slugify(e.target.value)}))}/></F><F label="Đường dẫn / slug"><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></F><F label="Hạng dịch vụ / số sao *" hint="Bắt buộc trước khi gửi duyệt"><select value={form.serviceStars||''} onChange={e=>set('serviceStars',e.target.value)}><option value="">— Chọn số sao —</option><option value="1">★ 1 sao</option><option value="2">★★ 2 sao</option><option value="3">★★★ 3 sao</option><option value="4">★★★★ 4 sao</option><option value="5">★★★★★ 5 sao</option></select></F><F label="Phân loại"><input value={form.category||''} onChange={e=>set('category',e.target.value)}/></F><F label={type==='Tour du lịch'?'Điểm đến chính':'Khu vực'}><input value={form.place} onChange={e=>set('place',e.target.value)}/></F><F label={type==='Tour du lịch'?'Điểm tập trung':'Địa chỉ'}><input value={form.address} onChange={e=>set('address',e.target.value)}/></F><F label="Giá từ / tham khảo"><input value={form.price} onChange={e=>set('price',e.target.value)}/></F>{type!=='Tour du lịch'&&<><F label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></F><F label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></F></>}{(type==='Du thuyền'||type==='Tour du lịch')&&<F label="Thời lượng / hành trình"><input value={form.duration||''} onChange={e=>set('duration',e.target.value)}/></F>}{type==='Du thuyền'&&<F label="Điểm đón / bến"><input value={form.boarding||form.pickup||''} onChange={e=>{set('boarding',e.target.value);set('pickup',e.target.value)}}/></F>}{type==='Tour du lịch'&&<><F label="Khởi hành từ"><input value={form.departure||''} onChange={e=>set('departure',e.target.value)}/></F><F label="Tuyến hành trình"><input value={form.route||''} onChange={e=>set('route',e.target.value)}/></F><F label="Hãng bay"><input value={form.airline||''} onChange={e=>set('airline',e.target.value)}/></F><F label="Phương tiện"><input value={form.transport||''} onChange={e=>set('transport',e.target.value)}/></F></>}<F label="Mô tả ngắn" wide><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)}/></F></div></section>
 <section className="partner-editor-section"><h3>3. Ảnh đại diện & Album</h3><div className="partner-form two"><F label="Ảnh đại diện URL"><input value={String(form.cover||'').startsWith('data:')?'':form.cover||''} onChange={e=>set('cover',e.target.value)}/></F><div className="partner-upload-card"><b>Tải ảnh lên</b><small>Ảnh tự động nén tối đa 1920px, tối đa 12 ảnh/lần và 30 ảnh/sản phẩm.</small><label className="partner-upload-button">{uploading?'Đang tối ưu ảnh...':'+ Chọn nhiều ảnh'}<input type="file" multiple accept="image/*" onChange={upload} disabled={uploading}/></label></div></div>{photos.length>0&&<div className="partner-photo-grid">{photos.map((src,i)=><figure key={`${i}_${src.slice(0,20)}`}><img src={src} alt={`Ảnh ${i+1}`}/><button type="button" onClick={()=>removePhoto(i)}>×</button>{form.cover===src&&<em>Ảnh đại diện</em>}</figure>)}</div>}<F label="Hoặc dán URL album — mỗi URL một dòng" wide><textarea rows={3} value={form.gallery} onChange={e=>set('gallery',e.target.value)}/></F></section>
 {type!=='Tour du lịch'&&<section className="partner-editor-section"><UnifiedProductUnitsEditor units={Array.isArray(form.units)?form.units:[]} onChange={v=>set('units',v)} label={type==='Villa & Resort'?'4. Căn Villa / loại căn & giá':type==='Khách sạn'?'4. Hạng phòng & giá':'4. Cabin & giá'}/></section>}
 {type==='Tour du lịch'&&<section className="partner-editor-section"><h3>4. Chương trình Tour</h3><div className="partner-form two"><F label="Lịch khởi hành" wide><textarea rows={4} value={form.departures||''} onChange={e=>set('departures',e.target.value)}/></F><F label="Lịch trình chi tiết" wide><textarea rows={8} value={form.itinerary||''} onChange={e=>set('itinerary',e.target.value)}/></F><F label="Điểm nổi bật" wide><textarea rows={4} value={form.highlights||''} onChange={e=>set('highlights',e.target.value)}/></F><F label="Giá bao gồm" wide><textarea rows={4} value={form.included||form.amenities||''} onChange={e=>{set('included',e.target.value);set('amenities',e.target.value)}}/></F><F label="Không bao gồm" wide><textarea rows={4} value={form.excluded||''} onChange={e=>set('excluded',e.target.value)}/></F><F label="Khuyến mại / quà tặng" wide><textarea rows={3} value={form.promotions||''} onChange={e=>set('promotions',e.target.value)}/></F></div></section>}
 <section className="partner-editor-section"><h3>5. Nội dung & chính sách</h3><div className="partner-form two"><F label="Tiện ích / dịch vụ" wide><textarea rows={4} value={form.amenities||''} onChange={e=>set('amenities',e.target.value)}/></F><F label="Chính sách" wide><textarea rows={5} value={form.policies||''} onChange={e=>set('policies',e.target.value)}/></F><F label="Chính sách trẻ em" wide><textarea rows={3} value={form.childrenPolicy||''} onChange={e=>set('childrenPolicy',e.target.value)}/></F><F label="Phụ thu chung" wide><textarea rows={3} value={form.extraCharge||''} onChange={e=>set('extraCharge',e.target.value)}/></F><F label="Nội dung chi tiết" wide><textarea rows={7} value={form.content||''} onChange={e=>set('content',e.target.value)}/></F></div></section>
 <div className="partner-editor-actions partner-editor-actions-sticky"><button type="button" onClick={onSaveDraft}>Lưu nháp</button><button type="button" className="partner-primary" onClick={submit}>Gửi HappyGo duyệt</button></div></div>}
