'use client';

import {useEffect,useMemo,useState} from 'react';

export type PartnerPriceRule={date:string;agencyPrice:string;retailPrice:string;promoPrice:string;quantity:string;note:string};
export type PartnerPricing={productId:string;unitId?:string;commission:string;agencyPrice:string;retailPrice:string;promoPrice:string;rules:PartnerPriceRule[];updatedAt:string};
export type PartnerRateUnit={id:string;name:string;code?:string};
export type PartnerRateProduct={id:string;name:string;status:string;price?:string;units?:PartnerRateUnit[]};
export const PARTNER_PRICING_KEY='happygo_partner_pricing_v1';
type WeekRate={enabled:boolean;agencyPrice:string;retailPrice:string;promoPrice:string;quantity:string};
const WEEK=['Chủ nhật','Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7'];
const blank=(productId:string,unitId=''):PartnerPricing=>({productId,unitId:unitId||undefined,commission:'10',agencyPrice:'',retailPrice:'',promoPrice:'',rules:[],updatedAt:''});
function readAll():PartnerPricing[]{try{const raw=localStorage.getItem(PARTNER_PRICING_KEY);const v=raw?JSON.parse(raw):[];return Array.isArray(v)?v:[]}catch{return[]}}
function saveAll(v:PartnerPricing[]){try{localStorage.setItem(PARTNER_PRICING_KEY,JSON.stringify(v));window.dispatchEvent(new Event('happygo-partner-rates-updated'))}catch{}}
const money=(v:string)=>{const d=(v||'').replace(/\D/g,'');return d?Number(d):0};
const fmt=(v:string)=>{const n=money(v);return n?new Intl.NumberFormat('vi-VN').format(n)+'đ':'—'};
const iso=(d:Date)=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const initialWeek=(p:PartnerPricing):WeekRate[]=>WEEK.map(()=>({enabled:true,agencyPrice:p.agencyPrice,retailPrice:p.retailPrice,promoPrice:p.promoPrice,quantity:'5'}));
const sameScope=(p:PartnerPricing,productId:string,unitId:string)=>p.productId===productId&&(p.unitId||'')===unitId;

export function PartnerRateManager({products}:{products:PartnerRateProduct[]}){
 const[selected,setSelected]=useState('');const[selectedUnit,setSelectedUnit]=useState('');const[all,setAll]=useState<PartnerPricing[]>([]);const[form,setForm]=useState<PartnerPricing>(blank(''));const[msg,setMsg]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[week,setWeek]=useState<WeekRate[]>(initialWeek(blank('')));
 useEffect(()=>{const list=readAll();setAll(list);if(products.length){const id=products[0].id;const p=list.find(x=>sameScope(x,id,''))||blank(id);setSelected(id);setSelectedUnit('');setForm(p);setWeek(initialWeek(p))}},[products]);
 const product=useMemo(()=>products.find(x=>x.id===selected),[products,selected]);
 function loadScope(productId:string,unitId:string){const p=all.find(x=>sameScope(x,productId,unitId))||blank(productId,unitId);setSelected(productId);setSelectedUnit(unitId);setForm(p);setWeek(initialWeek(p));setMsg('')}
 function choose(id:string){loadScope(id,'')}
 function chooseUnit(unitId:string){loadScope(selected,unitId)}
 function save(){if(!selected)return;const next={...form,productId:selected,unitId:selectedUnit||undefined,updatedAt:new Date().toISOString()};const exists=all.some(x=>sameScope(x,selected,selectedUnit));const list=exists?all.map(x=>sameScope(x,selected,selectedUnit)?next:x):[...all,next];setAll(list);setForm(next);saveAll(list);setMsg(`Đã lưu cấu hình giá ${selectedUnit?'theo đơn vị':'mặc định sản phẩm'}.`)}
 function addRule(){const d=new Date();d.setDate(d.getDate()+1);setForm(s=>({...s,rules:[...s.rules,{date:iso(d),agencyPrice:s.agencyPrice,retailPrice:s.retailPrice,promoPrice:s.promoPrice,quantity:'5',note:''}]}))}
 function updateRule(i:number,k:keyof PartnerPriceRule,v:string){setForm(s=>({...s,rules:s.rules.map((r,n)=>n===i?{...r,[k]:v}:r)}))}
 function removeRule(i:number){setForm(s=>({...s,rules:s.rules.filter((_,n)=>n!==i)}))}
 function updateWeek(i:number,k:keyof WeekRate,v:string|boolean){setWeek(s=>s.map((r,n)=>n===i?{...r,[k]:v}:r))}
 function applyRange(){if(!from||!to)return setMsg('Vui lòng chọn ngày bắt đầu và ngày kết thúc.');const start=new Date(`${from}T12:00:00`),end=new Date(`${to}T12:00:00`);if(start>end)return setMsg('Ngày kết thúc phải sau ngày bắt đầu.');const days=Math.floor((end.getTime()-start.getTime())/86400000)+1;if(days>550)return setMsg('Mỗi lần áp dụng tối đa khoảng 18 tháng.');const map=new Map(form.rules.map(r=>[r.date,r]));let count=0;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const w=week[d.getDay()];if(!w.enabled)continue;const date=iso(d);map.set(date,{date,agencyPrice:w.agencyPrice||form.agencyPrice,retailPrice:w.retailPrice||form.retailPrice,promoPrice:w.promoPrice||form.promoPrice,quantity:w.quantity||'0',note:WEEK[d.getDay()]});count++}const rules=Array.from(map.values()).sort((a,b)=>a.date.localeCompare(b.date));setForm(s=>({...s,rules}));setMsg(`Đã áp dụng bảng giá theo thứ cho ${count} ngày. Bấm “Lưu bảng giá” để hoàn tất.`)}
 const commissionValue=Math.max(0,money(form.retailPrice)-money(form.agencyPrice));
 if(!products.length)return <section className="partner-panel"><div className="partner-empty"><b>Chưa có sản phẩm để thiết lập giá</b><p>Hãy tạo sản phẩm trước, sau đó quay lại mục Giá & tình trạng.</p></div></section>;
 return <section className="partner-panel partner-rate-manager"><div className="partner-panel-head"><div><h3>Giá, commission & tình trạng bán</h3><p>Giá đại lý là dữ liệu nội bộ. Có thể cấu hình mặc định cho sản phẩm hoặc riêng từng hạng/đơn vị.</p></div><button className="partner-primary" type="button" onClick={save}>Lưu bảng giá</button></div>
 <div className="partner-rate-product"><label>Sản phẩm<select value={selected} onChange={e=>choose(e.target.value)}>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.status==='approved'?'Đã duyệt':p.status==='review'?'Chờ duyệt':'Bản nháp'}</option>)}</select></label><label>Hạng / đơn vị<select value={selectedUnit} onChange={e=>chooseUnit(e.target.value)}><option value="">Mặc định toàn sản phẩm</option>{(product?.units||[]).map(u=><option value={u.id} key={u.id}>{u.name}{u.code?` · ${u.code}`:''}</option>)}</select></label>{product&&<span className={`partner-status ${product.status}`}>{product.status==='approved'?'Đã duyệt & sẵn sàng bán':product.status==='review'?'Đang chờ HappyGo duyệt':'Bản nháp'}</span>}</div>
 <div className="partner-price-grid"><label><span>Commission HappyGo (%)</span><input value={form.commission} onChange={e=>setForm({...form,commission:e.target.value})} inputMode="decimal"/><small>Ví dụ 10% hoặc 15%</small></label><label className="agency"><span>Giá đại lý / giá net</span><input value={form.agencyPrice} onChange={e=>setForm({...form,agencyPrice:e.target.value})} placeholder="2.200.000"/><small>🔒 Nội bộ Partner + Admin, không public</small></label><label><span>Giá bán lẻ</span><input value={form.retailPrice} onChange={e=>setForm({...form,retailPrice:e.target.value})} placeholder="2.500.000"/><small>Giá chuẩn hiển thị cho khách</small></label><label className="promo"><span>Giá khuyến mại</span><input value={form.promoPrice} onChange={e=>setForm({...form,promoPrice:e.target.value})} placeholder="2.350.000"/><small>Nếu có, giá này ưu tiên hiển thị public</small></label></div>
 <div className="partner-price-summary"><span><small>Phạm vi bảng giá</small><b>{selectedUnit?(product?.units||[]).find(u=>u.id===selectedUnit)?.name||'Đơn vị':'Toàn sản phẩm'}</b></span><span><small>Giá net nội bộ</small><b>{fmt(form.agencyPrice)}</b></span><span><small>Giá public hiện tại</small><b>{fmt(form.promoPrice||form.retailPrice)}</b></span><span><small>Chênh lệch retail - net</small><b>{commissionValue?new Intl.NumberFormat('vi-VN').format(commissionValue)+'đ':'—'}</b></span><span><small>Commission khai báo</small><b>{form.commission||'0'}%</b></span></div>
 <div className="partner-bulk-rate"><div className="partner-calendar-head"><div><h4>Nhập nhanh nhiều tháng theo thứ trong tuần</h4><p>Chọn khoảng ngày, nhập giá cho từng thứ một lần rồi áp dụng hàng loạt. Có thể chọn vài tháng hoặc hơn.</p></div></div><div className="partner-range-picker"><label>Từ ngày<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Đến ngày<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="partner-primary" type="button" onClick={applyRange}>Áp dụng cho khoảng ngày</button></div><div className="partner-week-grid">{week.map((r,i)=><article key={WEEK[i]} className={!r.enabled?'disabled':''}><label className="week-toggle"><input type="checkbox" checked={r.enabled} onChange={e=>updateWeek(i,'enabled',e.target.checked)}/><b>{WEEK[i]}</b></label><label>Giá net 🔒<input value={r.agencyPrice} onChange={e=>updateWeek(i,'agencyPrice',e.target.value)} placeholder={form.agencyPrice||'Giá mặc định'}/></label><label>Giá bán lẻ<input value={r.retailPrice} onChange={e=>updateWeek(i,'retailPrice',e.target.value)} placeholder={form.retailPrice||'Giá mặc định'}/></label><label>Khuyến mại<input value={r.promoPrice} onChange={e=>updateWeek(i,'promoPrice',e.target.value)} placeholder={form.promoPrice||'Không có'}/></label><label>Số lượng còn bán<input value={r.quantity} onChange={e=>updateWeek(i,'quantity',e.target.value)} inputMode="numeric"/></label></article>)}</div></div>
 <div className="partner-calendar-head"><div><h4>Chi tiết giá theo ngày</h4><p>Có thể sửa riêng từng ngày sau khi áp dụng hàng loạt, ví dụ ngày lễ hoặc sự kiện.</p></div><button type="button" onClick={addRule}>+ Thêm 1 ngày</button></div>
 <div className="partner-calendar-table"><div className="calendar-row head"><b>Ngày</b><b>Giá đại lý 🔒</b><b>Giá bán lẻ</b><b>Khuyến mại</b><b>Tồn</b><b>Ghi chú</b><b></b></div>{form.rules.length?form.rules.map((r,i)=><div className="calendar-row" key={`${r.date}_${i}`}><input type="date" value={r.date} onChange={e=>updateRule(i,'date',e.target.value)}/><input value={r.agencyPrice} onChange={e=>updateRule(i,'agencyPrice',e.target.value)}/><input value={r.retailPrice} onChange={e=>updateRule(i,'retailPrice',e.target.value)}/><input value={r.promoPrice} onChange={e=>updateRule(i,'promoPrice',e.target.value)}/><input value={r.quantity} onChange={e=>updateRule(i,'quantity',e.target.value)} inputMode="numeric"/><input value={r.note} onChange={e=>updateRule(i,'note',e.target.value)} placeholder="Cuối tuần / lễ..."/><button type="button" onClick={()=>removeRule(i)}>×</button></div>):<div className="partner-calendar-empty">Chưa thiết lập giá theo ngày. Hệ thống sẽ dùng giá mặc định phía trên.</div>}</div>{msg&&<div className="partner-message">{msg}</div>}
 </section>
}
