'use client';

import {AdminMediaPicker} from '@/components/AdminMediaLibrary';
import {UnifiedProductUnitsEditor,type UnifiedUnit} from '@/components/UnifiedProductUnitsEditor';

type ProductType='Villa & Resort'|'Khách sạn'|'Du thuyền'|'Tour du lịch';
type ProductLike={id?:string;type:ProductType;name:string;slug:string;place:string;address:string;price:string;summary:string;cover:string;gallery:string;amenities:string;policies:string;checkin:string;checkout:string;unitsText:string;units?:UnifiedUnit[];[key:string]:any};
type Props={form:ProductLike;setForm:(next:any)=>void;onCancel:()=>void;onSaveDraft:()=>void;onSubmit:()=>void;slugify:(v:string)=>string;setMessage?:(v:string)=>void};
function F({label,children,wide=false,hint}:{label:string;children:React.ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'pm-field wide':'pm-field'}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function PartnerProductEditor({form,setForm,onCancel,onSaveDraft,onSubmit,slugify,setMessage}:Props){
 const set=(k:string,v:any)=>setForm((s:any)=>({...s,[k]:v}));const type=form.type;
 function submit(){if(!String(form.serviceStars||'').trim()){setMessage?.('Vui lòng chọn hạng dịch vụ / số sao trước khi gửi duyệt.');return}onSubmit()}
 return <section className="admin-editor-shell product-manager-editor partner-admin-identical"><div className="admin-editor-main"><div className="editor-title-row"><button type="button" className="editor-back" onClick={onCancel}>← Danh sách</button><b>{form.id?'Chỉnh sửa sản phẩm':'Thêm sản phẩm mới'}</b><span>Đối tác · Chờ HappyGo duyệt</span></div><input className="post-title-input" value={form.name} onChange={e=>{const old=form.name;set('name',e.target.value);if(!form.slug||form.slug===slugify(old))set('slug',slugify(e.target.value))}} placeholder="Tên khu / sản phẩm"/><div className="slug-row"><span>Đường dẫn:</span><input value={form.slug} onChange={e=>set('slug',slugify(e.target.value))}/></div>
 <section className="pm-section"><h3>1. Thông tin chung</h3><div className="pm-grid"><F label="Loại"><select value={form.type} onChange={e=>set('type',e.target.value as ProductType)}><option>Villa & Resort</option><option>Khách sạn</option><option>Du thuyền</option><option>Tour du lịch</option></select></F><F label="Hạng dịch vụ / số sao *" hint="Bắt buộc trước khi gửi duyệt"><select value={form.serviceStars||''} onChange={e=>set('serviceStars',e.target.value)}><option value="">— Chọn số sao —</option><option value="1">★ 1 sao</option><option value="2">★★ 2 sao</option><option value="3">★★★ 3 sao</option><option value="4">★★★★ 4 sao</option><option value="5">★★★★★ 5 sao</option></select></F><F label="Phân loại"><input value={form.category||''} onChange={e=>set('category',e.target.value)}/></F><F label="Khu vực"><input value={form.place} onChange={e=>set('place',e.target.value)}/></F><F label="Địa chỉ"><input value={form.address} onChange={e=>set('address',e.target.value)}/></F><F label="Giá từ"><input value={form.price} onChange={e=>set('price',e.target.value)}/></F><F label="Điểm đánh giá"><input value={form.rating||''} onChange={e=>set('rating',e.target.value)}/></F>{type!=='Tour du lịch'&&<><F label="Check-in"><input value={form.checkin} onChange={e=>set('checkin',e.target.value)}/></F><F label="Check-out"><input value={form.checkout} onChange={e=>set('checkout',e.target.value)}/></F></>}<F label="Thời lượng / hành trình"><input value={form.duration||''} onChange={e=>set('duration',e.target.value)}/></F><F label="Điểm đón / bến"><input value={form.pickup||form.boarding||form.departure||''} onChange={e=>{set('pickup',e.target.value);if(type==='Du thuyền')set('boarding',e.target.value);if(type==='Tour du lịch')set('departure',e.target.value)}}/></F>{type==='Tour du lịch'&&<><F label="Tuyến hành trình"><input value={form.route||''} onChange={e=>set('route',e.target.value)}/></F><F label="Hãng bay"><input value={form.airline||''} onChange={e=>set('airline',e.target.value)}/></F><F label="Phương tiện"><input value={form.transport||''} onChange={e=>set('transport',e.target.value)}/></F></>}<F label="Mô tả ngắn" wide><textarea rows={4} value={form.summary} onChange={e=>set('summary',e.target.value)}/></F></div></section>
 <section className="pm-section"><h3>2. Ảnh đại diện & Album</h3><p className="pm-section-note">Giống trang Quản trị: có thể chọn ảnh đã có trong thư viện hoặc tải ảnh mới trực tiếp từ máy/điện thoại.</p><div className="media-product-grid"><div><b>Ảnh đại diện</b><AdminMediaPicker value={form.cover||''} onChange={v=>set('cover',v)} label="Chọn ảnh đại diện"/></div><div><b>Album sản phẩm</b><AdminMediaPicker multiple value={form.gallery||''} onChange={v=>set('gallery',v)} label="Chọn ảnh Album"/></div></div></section>
 {type!=='Tour du lịch'&&<section className="pm-section"><UnifiedProductUnitsEditor units={Array.isArray(form.units)?form.units:[]} onChange={v=>set('units',v)} /></section>}
 {type==='Tour du lịch'&&<section className="pm-section"><h3>3. Chương trình Tour & giá</h3><div className="pm-grid"><F label="Lịch khởi hành" wide><textarea rows={4} value={form.departures||''} onChange={e=>set('departures',e.target.value)}/></F><F label="Lịch trình chi tiết" wide><textarea rows={8} value={form.itinerary||''} onChange={e=>set('itinerary',e.target.value)}/></F><F label="Điểm nổi bật" wide><textarea rows={4} value={form.highlights||''} onChange={e=>set('highlights',e.target.value)}/></F><F label="Giá bao gồm" wide><textarea rows={4} value={form.included||form.amenities||''} onChange={e=>{set('included',e.target.value);set('amenities',e.target.value)}}/></F><F label="Không bao gồm" wide><textarea rows={4} value={form.excluded||''} onChange={e=>set('excluded',e.target.value)}/></F><F label="Khuyến mại / quà tặng" wide><textarea rows={3} value={form.promotions||''} onChange={e=>set('promotions',e.target.value)}/></F></div></section>}
 <section className="pm-section"><h3>4. Nội dung & chính sách</h3><div className="pm-grid"><F label="Tiện ích" wide><textarea rows={5} value={form.amenities||''} onChange={e=>set('amenities',e.target.value)}/></F><F label="Chính sách" wide><textarea rows={6} value={form.policies||''} onChange={e=>set('policies',e.target.value)}/></F><F label="Chính sách trẻ em" wide><textarea rows={4} value={form.childrenPolicy||''} onChange={e=>set('childrenPolicy',e.target.value)}/></F><F label="Phụ thu chung" wide><textarea rows={4} value={form.extraCharge||''} onChange={e=>set('extraCharge',e.target.value)}/></F><F label="Nội dung chi tiết" wide><textarea rows={8} value={form.content||''} onChange={e=>set('content',e.target.value)}/></F><F label="SEO title" wide><input value={form.seoTitle||''} onChange={e=>set('seoTitle',e.target.value)}/></F><F label="Meta description" wide><textarea rows={4} value={form.seoDescription||''} onChange={e=>set('seoDescription',e.target.value)}/></F></div></section></div><aside className="admin-editor-side"><div className="editor-box publish-box"><h3>Xuất bản</h3><label>Trạng thái<select value={form.status||'draft'} onChange={e=>set('status',e.target.value)}><option value="draft">Bản nháp</option><option value="review">Chờ HappyGo duyệt</option>{form.status==='approved'&&<option value="approved">Đã duyệt</option>}</select></label><div className="publish-actions"><button type="button" onClick={onSaveDraft}>Lưu nháp</button><button type="button" className="admin-primary" onClick={submit}>Gửi HappyGo duyệt</button></div></div><div className="editor-box"><h3>Ảnh đại diện</h3>{form.cover?<img className="admin-cover-preview" src={form.cover} alt=""/>:<small>Chưa chọn ảnh</small>}</div></aside></section>}
