'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';

type Partner={id:string;name:string;contact:string};
type Ticket={id:string;partnerId:string;partnerName:string;subject:string;category:string;status:'new'|'processing'|'waiting'|'resolved';createdAt:string;updatedAt:string;messages:{id:string;from:'partner'|'admin';name:string;text:string;at:string}[]};
const SEEN='happygo_partner_support_seen_v2';
const labels:Record<string,string>={new:'Mới gửi',processing:'Đang xử lý',waiting:'Chờ phản hồi của bạn',resolved:'Hoàn tất'};
function seenMap(){try{return JSON.parse(localStorage.getItem(SEEN)||'{}') as Record<string,string>}catch{return{}}}
function markSeen(partnerId:string){const x=seenMap();x[partnerId]=new Date().toISOString();localStorage.setItem(SEEN,JSON.stringify(x));window.dispatchEvent(new Event('happygo-partner-support-seen'))}
async function fetchTickets(){const r=await fetch('/api/partner/support',{cache:'no-store'});if(!r.ok)return[];const data=await r.json();return Array.isArray(data?.tickets)?data.tickets as Ticket[]:[]}

export function PartnerSupportBadge({partnerId}:{partnerId:string}){
 const[count,setCount]=useState(0);
 useEffect(()=>{let alive=true;const load=async()=>{const items=await fetchTickets();if(!alive)return;const last=+new Date(seenMap()[partnerId]||0);let n=0;items.filter(t=>t.partnerId===partnerId).forEach(t=>t.messages.forEach(m=>{if(m.from==='admin'&&+new Date(m.at)>last)n++}));setCount(n)};void load();const timer=window.setInterval(load,30000);const seen=()=>void load();window.addEventListener('happygo-partner-support-seen',seen);return()=>{alive=false;window.clearInterval(timer);window.removeEventListener('happygo-partner-support-seen',seen)}},[partnerId]);
 return count?<strong className="partner-support-badge">{count>99?'99+':count}</strong>:null
}

export function PartnerSupportPortal({partner}:{partner:Partner}){
 const[items,setItems]=useState<Ticket[]>([]),[selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[subject,setSubject]=useState(''),[category,setCategory]=useState('Booking / khách hàng'),[text,setText]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const list=await fetchTickets();setItems(list)},[]);
 useEffect(()=>{void load();markSeen(partner.id);const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[load,partner.id]);
 useEffect(()=>{markSeen(partner.id)},[items,selected,partner.id]);
 const mine=useMemo(()=>items.filter(x=>x.partnerId===partner.id).sort((a,b)=>+new Date(b.updatedAt)-+new Date(a.updatedAt)),[items,partner.id]);const current=mine.find(x=>x.id===selected)||mine[0];
 async function sendBody(body:any){setBusy(true);setMsg('');try{const r=await fetch('/api/partner/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok){setMsg(data.error||'Không thể gửi yêu cầu.');return false}setItems(Array.isArray(data.tickets)?data.tickets:[]);return true}catch{setMsg('Không kết nối được HappyGo Support.');return false}finally{setBusy(false)}}
 async function create(){if(!subject.trim()||!text.trim())return;const ok=await sendBody({action:'create',subject:subject.trim(),category,text:text.trim()});if(ok){setSubject('');setText('');setCreating(false);setSelected('')}}
 async function send(){if(!current||!text.trim())return;const ok=await sendBody({action:'reply',ticketId:current.id,text:text.trim()});if(ok)setText('')}
 return <section className="partner-support-portal"><div className="partner-page-head"><div><small>HAPPYGO SUPPORT · PRODUCTION</small><h2>Hỗ trợ & trao đổi</h2><p>Trao đổi được lưu trên hệ thống HappyGo và theo tài khoản trên mọi thiết bị.</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ Tạo yêu cầu</button></div>{creating&&<div className="partner-support-new"><h3>Tạo yêu cầu hỗ trợ mới</h3><label>Chủ đề<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ví dụ: Cần hỗ trợ booking HG-1024"/></label><label>Nhóm vấn đề<select value={category} onChange={e=>setCategory(e.target.value)}><option>Booking / khách hàng</option><option>Sản phẩm & nội dung</option><option>Giá & tình trạng</option><option>Thanh toán / đối soát</option><option>Kết nối API</option><option>Tài khoản</option><option>Khác</option></select></label><label>Nội dung<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Mô tả cụ thể để HappyGo hỗ trợ nhanh hơn..."/></label><div><button onClick={()=>setCreating(false)}>Hủy</button><button className="primary" onClick={()=>void create()} disabled={busy}>{busy?'Đang gửi...':'Gửi yêu cầu'}</button></div></div>}<div className="partner-support-grid partner-side"><div className="partner-support-list">{mine.map(t=><button key={t.id} className={current?.id===t.id?'active':''} onClick={()=>{setSelected(t.id);setCreating(false);markSeen(partner.id)}}><b>{t.subject}</b><span>{t.category}</span><small>{labels[t.status]} · {new Date(t.updatedAt).toLocaleString('vi-VN')}</small></button>)}{!mine.length&&!creating&&<div className="admin-empty-state">Bạn chưa có yêu cầu hỗ trợ nào.</div>}</div><div className="partner-support-thread">{current&&!creating?<><header><div><b>{current.subject}</b><small>{current.category}</small></div><em className={`support-status ${current.status}`}>{labels[current.status]}</em></header><div className="partner-support-messages">{current.messages.map(m=><article key={m.id} className={m.from==='partner'?'mine':''}><b>{m.from==='admin'?'HappyGo Support':m.name}</b><p>{m.text}</p><small>{new Date(m.at).toLocaleString('vi-VN')}</small></article>)}</div>{current.status==='resolved'?<div className="partner-support-resolved">✓ Yêu cầu đã hoàn tất. Gửi tin mới sẽ mở lại luồng xử lý.</div>:null}<div className="partner-support-compose"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Nhắn cho HappyGo Support..." onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><button className="primary" onClick={()=>void send()} disabled={busy}>{busy?'...':'Gửi'}</button></div></>:!creating&&<div className="admin-empty-state">Chọn một yêu cầu hoặc tạo yêu cầu mới.</div>}</div></div>{msg&&<div className="partner-message">{msg}</div>}</section>
}
