'use client';

import {amenityLines,amenityOptions,inferAmenityTags,unknownLegacyAmenities,type StructuredProductType} from '@/components/ProductAmenityModel';

type Props={type:StructuredProductType;form:any;setField:(key:string,value:any)=>void;part:'core'|'details';source?:'admin'|'partner'};
function F({label,children,wide=false,hint}:{label:string;children:React.ReactNode;wide?:boolean;hint?:string}){return <label className={wide?'pm-field wide':'pm-field'}><span>{label}</span>{children}{hint?<small>{hint}</small>:null}</label>}
function moneyInput(value:unknown,onChange:(v:string)=>void,placeholder:string){return <input inputMode="numeric" value={String(value||'')} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}

export function ProductFlowFields({type,form,setField,part,source='admin'}:Props){
 const selected=Array.isArray(form.amenityTags)?form.amenityTags.map(String):inferAmenityTags(type,form.amenities);
 const details=form.amenityDetails&&typeof form.amenityDetails==='object'?form.amenityDetails as Record<string,string>:{};
 const keepLegacy=unknownLegacyAmenities(type,form.amenities);
 const options=amenityOptions(type);
 const applyAmenities=(tags:string[],nextDetails=details)=>{setField('amenityTags',tags);setField('amenityDetails',nextDetails);setField('amenities',amenityLines(type,tags,nextDetails,keepLegacy).join('\n'))};
 const toggle=(id:string)=>applyAmenities(selected.includes(id)?selected.filter((x:string)=>x!==id):[...selected,id]);
 const detail=(id:string,value:string)=>{const next={...details,[id]:value};setField('amenityDetails',next);setField('amenities',amenityLines(type,selected,next,keepLegacy).join('\n'))};
 const villa=type==='Villa & Resort',hotel=type==='Khách sạn';
 if(part==='core')return <>
  <section className={`pm-section product-flow-section flow-${villa?'villa':hotel?'hotel':'cruise'}`}><div className="product-flow-heading"><div><small>{source==='partner'?'ĐỐI TÁC · NHẬP ĐÚNG LUỒNG':'HAPPYGO · LUỒNG SẢN PHẨM'}</small><h3>1. {villa?'Thông tin Villa / Resort':hotel?'Thông tin Khách sạn':'Thông tin Du thuyền'}</h3><p>{villa?'Thông tin cấp khu nghỉ/cụm Villa; từng căn và giá nhập ở bước 3.':hotel?'Thông tin cấp khách sạn; từng hạng phòng và giá nhập ở bước 3.':'Thông tin hành trình tàu; từng cabin và giá nhập ở bước 3.'}</p></div><span className="product-flow-badge">{villa?'🏝 Villa':hotel?'🏨 Hotel':'🛳 Cruise'}</span></div>
   <div className="product-flow-steps"><span><b>1</b>Thông tin bán</span><span><b>2</b>Hình ảnh</span><span><b>3</b>{villa?'Căn Villa':hotel?'Hạng phòng':'Cabin & giá'}</span><span><b>4</b>Tiện ích</span><span><b>5</b>Chính sách</span></div>
   <div className="pm-grid product-flow-grid">
    <F label="Hạng dịch vụ / số sao *"><select value={String(form.serviceStars||'')} onChange={e=>setField('serviceStars',e.target.value)}><option value="">— Chọn số sao —</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{'★'.repeat(n)} {n} sao</option>)}</select></F>
    <F label={villa?'Phân loại Villa / Resort':hotel?'Phân loại khách sạn':'Phân loại du thuyền'}><input value={String(form.category||'')} onChange={e=>setField('category',e.target.value)} placeholder={villa?'VD: Villa nguyên căn / Villa trong Resort':hotel?'VD: Boutique / Resort hotel / City hotel':'VD: Du thuyền 5 sao / overnight cruise'}/></F>
    <F label="Khu vực / điểm đến"><input value={String(form.place||'')} onChange={e=>setField('place',e.target.value)} placeholder={villa?'VD: Sóc Sơn, Hà Nội':hotel?'VD: Phú Quốc, Kiên Giang':'VD: Vịnh Hạ Long'}/></F>
    <F label={villa||hotel?'Địa chỉ':'Bến khởi hành'}><input value={String((villa||hotel)?form.address:(form.boarding||form.pickup)||'')} onChange={e=>{if(villa||hotel)setField('address',e.target.value);else{setField('boarding',e.target.value);setField('pickup',e.target.value)}}} placeholder={villa||hotel?'Địa chỉ chi tiết':'VD: Cảng Tuần Châu'}/></F>
    {!villa&&!hotel?<><F label="Hành trình / tuyến"><input value={String(form.route||'')} onChange={e=>setField('route',e.target.value)} placeholder="VD: Hạ Long - Hang Sửng Sốt - Titop"/></F><F label="Thời lượng"><input value={String(form.duration||'')} onChange={e=>setField('duration',e.target.value)} placeholder="VD: 2N1Đ"/></F></>:null}
    <F label="Giá hiển thị từ" hint="Giá chi tiết vẫn lấy theo căn/phòng/cabin ở bước 3."><input inputMode="numeric" value={String(form.price||'')} onChange={e=>setField('price',e.target.value)} placeholder="VD: 3.500.000đ"/></F>
    <F label="Mô tả ngắn" wide><textarea rows={4} value={String(form.summary||'')} onChange={e=>setField('summary',e.target.value)} placeholder="Tóm tắt điểm bán nổi bật để Sale và khách đọc nhanh..."/></F>
   </div>
  </section>
  <section className="pm-section product-flow-time"><h3>{villa||hotel?'Giờ nhận / trả phòng':'Giờ nhận / trả cabin'}</h3><div className="pm-grid"><F label="Check-in"><input type="time" value={String(form.checkin||'14:00')} onChange={e=>setField('checkin',e.target.value)}/></F><F label="Check-out"><input type="time" value={String(form.checkout||'12:00')} onChange={e=>setField('checkout',e.target.value)}/></F>{villa?<><F label="Phí phụ thu quá người" hint="Đơn vị nên ghi rõ /người/đêm">{moneyInput(form.extraPersonFee,v=>setField('extraPersonFee',v),'VD: 200.000đ/người/đêm')}</F><F label="Phụ thu nhận phòng sớm">{moneyInput(form.earlyCheckinFee,v=>setField('earlyCheckinFee',v),'VD: 300.000đ/giờ')}</F><F label="Phụ thu trả phòng muộn">{moneyInput(form.lateCheckoutFee,v=>setField('lateCheckoutFee',v),'VD: 300.000đ/giờ')}</F><F label="Điều kiện nhận sớm / trả muộn"><input value={String(form.earlyLatePolicy||'')} onChange={e=>setField('earlyLatePolicy',e.target.value)} placeholder="VD: Tùy tình trạng căn, cần báo trước"/></F></>:null}</div>{villa?<p className="pm-section-note strong">Mặc định Villa: nhận phòng 14:00 · trả phòng 12:00 hôm sau. Có thể sửa theo chính sách từng khu.</p>:null}</section>
 </>;
 return <>
  <section className="pm-section product-amenity-section"><div className="product-flow-heading"><div><small>DỮ LIỆU CÓ CẤU TRÚC · DÙNG CHO ICON & BỘ LỌC</small><h3>4. Tiện ích chọn nhanh</h3><p>Tick tiện ích thay vì gõ textarea. Dữ liệu được lưu thành mã để website và Sale lọc nhanh.</p></div><span className="product-flow-badge">{selected.length}/{options.length} đã chọn</span></div>
   <div className="amenity-check-grid">{options.map(item=>{const on=selected.includes(item.id);return <div key={item.id} className={`amenity-check-card ${on?'selected':''}`}><label><input type="checkbox" checked={on} onChange={()=>toggle(item.id)}/><span className="amenity-icon">{item.icon}</span><b>{item.label}</b><i>{on?'✓':''}</i></label>{on&&item.detailPlaceholder?<div className="amenity-detail"><input value={String(details[item.id]||'')} onChange={e=>detail(item.id,e.target.value)} placeholder={item.detailPlaceholder}/>{item.detailHint?<small>{item.detailHint}</small>:null}</div>:null}</div>})}</div>
   {keepLegacy.length?<div className="legacy-amenity-note"><b>Tiện ích cũ vẫn được giữ:</b> {keepLegacy.join(' · ')}</div>:null}
  </section>
  <section className="pm-section"><h3>5. Chính sách & phụ thu khác</h3><div className="pm-grid"><F label="Chính sách trẻ em" wide><textarea rows={3} value={String(form.childrenPolicy||'')} onChange={e=>setField('childrenPolicy',e.target.value)} placeholder="Quy định độ tuổi, ngủ chung/giường phụ, phụ thu..."/></F><F label="Phụ thu khác" wide><textarea rows={3} value={String(form.extraCharge||'')} onChange={e=>setField('extraCharge',e.target.value)} placeholder={villa?'VD: phụ thu cuối tuần, lễ/Tết, dọn dẹp, thú cưng nếu có...':'Các khoản phụ thu ngoài giá đơn vị bán...'}/></F><F label="Chính sách hoàn/hủy & lưu trú" wide><textarea rows={5} value={String(form.policies||'')} onChange={e=>setField('policies',e.target.value)} placeholder="Mỗi ý một dòng để hiển thị rõ trên website."/></F><F label="Nội dung chi tiết" wide><textarea rows={7} value={String(form.content||'')} onChange={e=>setField('content',e.target.value)} placeholder="Mô tả trải nghiệm, vị trí, điểm nổi bật, lưu ý quan trọng..."/></F></div></section>
  <section className="pm-section"><h3>6. SEO</h3><div className="pm-grid"><F label="SEO title" wide><input value={String(form.seoTitle||'')} onChange={e=>setField('seoTitle',e.target.value)} placeholder="Tiêu đề hiển thị trên Google"/></F><F label="Meta description" wide><textarea rows={3} value={String(form.seoDescription||'')} onChange={e=>setField('seoDescription',e.target.value)} placeholder="Mô tả ngắn hấp dẫn cho kết quả tìm kiếm"/></F></div></section>
 </>;
}
