'use client';
import {PARTNER_PRICING_KEY,type PartnerPricing} from '@/components/PartnerRateManager';
import {rateForDate} from '@/components/AdminRateCalendar';
export type CommerceSnapshot={sellingPrice:number;costPrice:number|null;availableQuantity:number|null;isAvailable:boolean;sellingSource:'partner_promo'|'partner_retail'|'unit_calendar'|'unit_base'|'product'|'manual'|'unknown';costSource:'partner_net'|'manual'|'unknown';inventorySource:'unit_calendar'|'partner_calendar'|'unknown';sourceLabel:string;date?:string};
const money=(v?:string|number|null)=>{if(typeof v==='number')return Number.isFinite(v)?Math.round(v):0;const d=String(v||'').replace(/\D/g,'');return d?Number(d):0};
const quantity=(v?:string|number|null)=>{if(v===undefined||v===null||String(v).trim()==='')return null;const n=Number(String(v).replace(/[^0-9-]/g,''));return Number.isFinite(n)?Math.max(0,Math.floor(n)):null};
function pricing():PartnerPricing[]{try{const v=JSON.parse(localStorage.getItem(PARTNER_PRICING_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
export function resolvePartnerCommerce(productId?:string,unitId?:string,date?:string):CommerceSnapshot|null{if(!productId)return null;const all=pricing();const p=(unitId?all.find(x=>x.productId===productId&&x.unitId===unitId):undefined)||all.find(x=>x.productId===productId&&!x.unitId);if(!p)return null;const rule=date?p.rules?.find(x=>x.date===date):undefined;const promo=money(rule?.promoPrice||p.promoPrice),retail=money(rule?.retailPrice||p.retailPrice),net=money(rule?.agencyPrice||p.agencyPrice),availableQuantity=rule?quantity(rule.quantity):null;const scope=p.unitId?'đơn vị':'sản phẩm';return{sellingPrice:promo||retail,costPrice:net||null,availableQuantity,isAvailable:availableQuantity===null||availableQuantity>0,sellingSource:promo?'partner_promo':retail?'partner_retail':'unknown',costSource:net?'partner_net':'unknown',inventorySource:rule?'partner_calendar':'unknown',sourceLabel:rule?`Bảng giá Partner ${scope} ${rule.date}`:`Bảng giá Partner ${scope} mặc định`,date}}
export function resolveCommerce(input:{productId?:string;unitId?:string;date?:string;unitPrice?:string|number;productPrice?:string|number;manualSelling?:string|number;manualCost?:string|number}):CommerceSnapshot{const partner=resolvePartnerCommerce(input.productId,input.unitId,input.date),daily=input.unitId&&input.date?rateForDate(input.unitId,input.date):null,dailyPrice=daily?.status==='available'?money(daily.price):0,dailyQty=daily?quantity(daily.quantity):null,dailyAvailable=!!daily&&daily.status==='available'&&(dailyQty===null||dailyQty>0),unit=money(input.unitPrice),product=money(input.productPrice),manual=money(input.manualSelling),manualCost=money(input.manualCost);const selling=daily?dailyPrice:(partner?.sellingPrice||unit||product||manual),availableQuantity=daily?dailyQty:(partner?.availableQuantity??null),isAvailable=daily?dailyAvailable:(partner?.isAvailable??true);return{sellingPrice:selling,costPrice:partner?.costPrice??(manualCost||null),availableQuantity,isAvailable,sellingSource:daily?'unit_calendar':partner?.sellingPrice?partner.sellingSource:unit?'unit_base':product?'product':manual?'manual':'unknown',costSource:partner?.costPrice?'partner_net':manualCost?'manual':'unknown',inventorySource:daily?'unit_calendar':partner?.inventorySource||'unknown',sourceLabel:daily?`Lịch giá đơn vị ${input.date}`:partner?.sellingPrice||partner?.costPrice||partner?.availableQuantity!==null&&partner?.availableQuantity!==undefined?partner.sourceLabel:unit?'Giá đơn vị sản phẩm':product?'Giá sản phẩm':manual?'Giá nhập thủ công':'Chưa có nguồn giá',date:input.date}}
export const commerceMoney=money;
