'use client';
import {RATE_KEY,type RateRange} from '@/components/AdminRateCalendar';
import {PARTNER_PRICING_KEY,type PartnerPricing} from '@/components/PartnerRateManager';
import type {PricingBasis} from '@/components/ProductModel';
export const INVENTORY_LEDGER_KEY='happygo_inventory_reservations_v1';
export type InventoryStatus='available'|'hold'|'soldout';
export type InventoryReservation={bookingCode:string;cartItemId?:string;productId?:string;unitId?:string;date:string;quantity:number;state:'reserved'|'released';updatedAt:string};
export type InventorySnapshot={productId?:string;unitId?:string;date:string;quantity:number|null;reserved:number;remaining:number|null;status:InventoryStatus;source:'unit_calendar'|'partner_calendar'|'unlimited';minStay:number;note?:string};
export type InventoryDemand={cartItemId?:string;productId?:string;unitId?:string;startDate?:string;endDate?:string;pricingBasis?:PricingBasis;quantity:number};
function json<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
const qty=(v?:string|number|null)=>{if(v==null||String(v).trim()==='')return null;const n=Number(String(v).replace(/[^0-9-]/g,''));return Number.isFinite(n)?Math.max(0,Math.floor(n)):null};
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function stayDates(start?:string,end?:string){if(!start)return[];if(!end||end<=start)return[start];const a=new Date(`${start}T12:00:00`),b=new Date(`${end}T12:00:00`),out:string[]=[];for(let d=new Date(a);d<b&&out.length<62;d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1,12))out.push(ymd(d));return out.length?out:[start]}
function demandDates(x:Pick<InventoryDemand,'startDate'|'endDate'|'pricingBasis'>){if(!x.startDate)return[];return x.pricingBasis==='guest'||x.pricingBasis==='package'?[x.startDate]:stayDates(x.startDate,x.endDate)}
function reservedFor(productId:string|undefined,unitId:string|undefined,date:string){return json<InventoryReservation[]>(INVENTORY_LEDGER_KEY,[]).filter(x=>x.state==='reserved'&&x.date===date&&((unitId&&x.unitId===unitId)||(!unitId&&productId&&x.productId===productId))).reduce((n,x)=>n+x.quantity,0)}
function withReservations(x:Omit<InventorySnapshot,'reserved'|'remaining'>){const reserved=reservedFor(x.productId,x.unitId,x.date);const remaining=x.quantity==null?null:Math.max(0,x.quantity-reserved);return{...x,reserved,remaining,status:remaining===0&&x.quantity!=null?'soldout' as InventoryStatus:x.status}}
export function unitInventory(unitId:string|undefined,date:string):InventorySnapshot|null{if(!unitId||!date)return null;const all=json<RateRange[]>(RATE_KEY,[]);const matches=(Array.isArray(all)?all:[]).filter(r=>r.unitId===unitId&&r.start&&r.end&&date>=r.start&&date<=r.end);const r=matches.length?matches[matches.length-1]:null;if(!r)return null;const quantity=qty(r.quantity);const status:InventoryStatus=r.status==='hold'?'hold':r.status==='soldout'||quantity===0?'soldout':'available';return withReservations({unitId,date,quantity,status,source:'unit_calendar',minStay:Math.max(1,Number(r.minStay||1)),note:r.note})}
export function partnerInventory(productId:string|undefined,date:string):InventorySnapshot|null{if(!productId||!date)return null;const all=json<PartnerPricing[]>(PARTNER_PRICING_KEY,[]);const p=(Array.isArray(all)?all:[]).find(x=>x.productId===productId);const r=p?.rules?.find(x=>x.date===date);if(!r)return null;const quantity=qty(r.quantity);const status:InventoryStatus=quantity===0?'soldout':'available';return withReservations({productId,date,quantity,status,source:'partner_calendar',minStay:1,note:r.note})}
export function resolveInventory(input:{productId?:string;unitId?:string;date?:string}):InventorySnapshot{const date=input.date||'';const unit=unitInventory(input.unitId,date);const partner=partnerInventory(input.productId,date);if(unit&&partner){const quantity=unit.quantity==null?partner.quantity:partner.quantity==null?unit.quantity:Math.min(unit.quantity,partner.quantity);const reserved=Math.max(unit.reserved,partner.reserved);const remaining=quantity==null?null:Math.max(0,quantity-reserved);const status:InventoryStatus=unit.status!=='available'?unit.status:partner.status!=='available'?partner.status:remaining===0&&quantity!=null?'soldout':'available';return{...unit,productId:input.productId,quantity,reserved,remaining,status,source:'unit_calendar',note:[unit.note,partner.note].filter(Boolean).join(' · ')}}if(unit)return{...unit,productId:input.productId};if(partner)return{...partner,unitId:input.unitId};return{productId:input.productId,unitId:input.unitId,date,quantity:null,reserved:0,remaining:null,status:'available',source:'unlimited',minStay:1}}
export function inventoryAllows(x:InventorySnapshot,requested:number,nights=1){return x.status==='available'&&nights>=x.minStay&&(x.remaining==null||requested<=x.remaining)}
export function inventoryAllowsStay(input:InventoryDemand){const dates=demandDates(input);if(!dates.length)return true;const nights=input.pricingBasis==='guest'||input.pricingBasis==='package'?1:dates.length;return dates.every(date=>inventoryAllows(resolveInventory({productId:input.productId,unitId:input.unitId,date}),input.quantity,nights))}
function expandedDemands(services:InventoryDemand[]){return services.flatMap(x=>demandDates(x).map(date=>({...x,date,quantity:Math.max(1,Math.floor(x.quantity))})))}
export function canReserveBookingInventory(services:InventoryDemand[]){const expanded=expandedDemands(services.filter(x=>x.startDate&&x.quantity>0));const grouped=new Map<string,{productId?:string;unitId?:string;date:string;quantity:number;nightly:boolean;nights:number}>();for(const x of expanded){const k=`${x.productId||''}|${x.unitId||''}|${x.date}`;const nightly=x.pricingBasis!=='guest'&&x.pricingBasis!=='package',nights=nightly?demandDates(x).length:1,old=grouped.get(k);if(old)old.quantity+=x.quantity;else grouped.set(k,{productId:x.productId,unitId:x.unitId,date:x.date,quantity:x.quantity,nightly,nights})}for(const x of grouped.values()){const inv=resolveInventory(x);if(!inventoryAllows(inv,x.quantity,x.nightly?x.nights:1))return false}return true}
export function reserveBookingInventory(bookingCode:string,services:InventoryDemand[]){if(!bookingCode||!canReserveBookingInventory(services))return false;try{const old=json<InventoryReservation[]>(INVENTORY_LEDGER_KEY,[]).filter(x=>x.bookingCode!==bookingCode);const now=new Date().toISOString();const rows:InventoryReservation[]=expandedDemands(services.filter(x=>x.startDate&&x.quantity>0)).map(x=>({bookingCode,cartItemId:x.cartItemId,productId:x.productId,unitId:x.unitId,date:x.date,quantity:x.quantity,state:'reserved',updatedAt:now}));localStorage.setItem(INVENTORY_LEDGER_KEY,JSON.stringify([...old,...rows]));window.dispatchEvent(new Event('tn-inventory-updated'));return true}catch{return false}}
export function releaseBookingInventory(bookingCode:string){const all=json<InventoryReservation[]>(INVENTORY_LEDGER_KEY,[]);let changed=false;const now=new Date().toISOString();const next=all.map(x=>{if(x.bookingCode!==bookingCode||x.state!=='reserved')return x;changed=true;return{...x,state:'released' as const,updatedAt:now}});if(changed){localStorage.setItem(INVENTORY_LEDGER_KEY,JSON.stringify(next));window.dispatchEvent(new Event('tn-inventory-updated'))}}
