import {blankUnifiedUnit,type UnifiedUnit,type UnifiedUnitKind} from '@/components/UnifiedProductUnitsEditor';
export const PRODUCT_STORAGE_KEY='tn_cms_products_v3_units';
export type ProductType='Tour'|'Villa & Resort'|'Khách sạn'|'Du thuyền';
export type ProductStatus='draft'|'published'|'hidden';
export type ProductSource='admin'|'partner'|'seed'|'api';
export type CanonicalProduct={id:string;type:ProductType;name:string;slug:string;place:string;price:string;status:ProductStatus;summary:string;cover:string;gallery:string;rating:string;serviceStars:string;category:string;address:string;checkin:string;checkout:string;amenities:string;policies:string;childrenPolicy:string;extraCharge:string;duration:string;pickup:string;boarding:string;itinerary:string;content:string;seoTitle:string;seoDescription:string;units:UnifiedUnit[];source:ProductSource;partnerId?:string;currency:'VND';createdAt?:string;updatedAt:string};
export const productSlug=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export function emptyProduct(type:ProductType):CanonicalProduct{return{id:'',type,name:'',slug:'',place:'',price:'',status:'draft',summary:'',cover:'',gallery:'',rating:'',serviceStars:'',category:'',address:'',checkin:type==='Tour'?'':'14:00',checkout:type==='Tour'?'':'12:00',amenities:'',policies:'',childrenPolicy:'',extraCharge:'',duration:'',pickup:'',boarding:'',itinerary:'',content:'',seoTitle:'',seoDescription:'',units:[],source:'admin',currency:'VND',updatedAt:''}}
export function normalizeProduct(p:any,fallbackType:ProductType='Villa & Resort'):CanonicalProduct{const type=(['Tour','Villa & Resort','Khách sạn','Du thuyền'].includes(p?.type)?p.type:fallbackType) as ProductType;return{...emptyProduct(type),...p,type,serviceStars:String(p?.serviceStars||p?.stars||''),source:p?.source||'admin',currency:'VND',units:Array.isArray(p?.units)?p.units.map((u:any)=>({...blankUnifiedUnit(),...u,id:u?.id||`u_${Date.now()}_${Math.random().toString(36).slice(2,7)}`})):[]}}
export function productUnitKind(type:ProductType):UnifiedUnitKind{return type==='Khách sạn'?'hotel':type==='Villa & Resort'?'villa':type==='Du thuyền'?'cruise':'tour'}
