'use client';
import {RATE_KEY,type RateRange} from '@/components/AdminRateCalendar';
import {PARTNER_PRICING_KEY,type PartnerPricing} from '@/components/PartnerRateManager';
export type InventoryStatus='available'|'hold'|'soldout';
export type InventorySnapshot={productId?:string;unitId?:string;date:string;quantity:number|null;status:InventoryStatus;source:'unit_calendar'|'partner_calendar'|'unlimited';minStay:number;note?:string};
function json<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}}
const qty=(v?:string|number|null)=>{if(v==null||String(v).trim()==='')return null;const n=Number(String(v).replace(/[^0-9-]/g,''));return Number.isFinite(n)?Math.max(0,Math.floor(n)):null};
export function unitInventory(unitId:string|undefined,date:string):InventorySnapshot|null{if(!unitId||!date)return null;const all=json<RateRange[]>(RATE_KEY,[]);const matches=(Array.isArray(all)?all:[]).filter(r=>r.unitId===unitId&&r.start&&r.end&&date>=r.start&&date<=r.end);const r=matches.length?matches[matches.length-1]:null;if(!r)return null;const quantity=qty(r.quantity);const status:InventoryStatus=r.status==='hold'?'hold':r.status==='soldout'||quantity===0?'soldout':'available';return{unitId,date,quantity,status,source:'unit_calendar',minStay:Math.max(1,Number(r.minStay||1)),note:r.note}}
export function partnerInventory(productId:string|undefined,date:string):InventorySnapshot|null{if(!productId||!date)return null;const all=json<PartnerPricing[]>(PARTNER_PRICING_KEY,[]);const p=(Array.isArray(all)?all:[]).find(x=>x.productId===productId);const r=p?.rules?.find(x=>x.date===date);if(!r)return null;const quantity=qty(r.quantity);const status:InventoryStatus=quantity===0?'soldout':'available';return{productId,date,quantity,status,source:'partner_calendar',minStay:1,note:r.note}}
export function resolveInventory(input:{productId?:string;unitId?:string;date?:string}):InventorySnapshot{const date=input.date||'';const unit=unitInventory(input.unitId,date);const partner=partnerInventory(input.productId,date);if(unit&&partner){const uq=unit.quantity;const pq=partner.quantity;const quantity=uq==null?pq:pq==null?uq:Math.min(uq,pq);const status:InventoryStatus=unit.status!=='available'?unit.status:partner.status!=='available'?partner.status:quantity===0?'soldout':'available';return{...unit,productId:input.productId,quantity,status,source:'unit_calendar',note:[unit.note,partner.note].filter(Boolean).join(' · ')}}if(unit)return{...unit,productId:input.productId};if(partner)return{...partner,unitId:input.unitId};return{productId:input.productId,unitId:input.unitId,date,quantity:null,status:'available',source:'unlimited',minStay:1}}
export function inventoryAllows(x:InventorySnapshot,requested:number,nights=1){return x.status==='available'&&nights>=x.minStay&&(x.quantity==null||requested<=x.quantity)}
