import {blankUnifiedUnit,type UnifiedUnit,type UnifiedUnitKind} from '@/components/UnifiedProductUnitsEditor';
export const PRODUCT_STORAGE_KEY='tn_cms_products_v3_units';
export type ProductType='Tour'|'Villa & Resort'|'Khách sạn'|'Du thuyền';
export type ProductStatus='draft'|'published'|'hidden';
export type ProductSource='admin'|'partner'|'seed'|'api';
export type PricingBasis='room_night'|'unit_night'|'cabin_night'|'guest'|'package';
export type CanonicalProduct={id:string;type:ProductType;name:string;slug:string;place:string;price:string;pricingBasis:PricingBasis;status:ProductStatus;summary:string;cover:string;gallery:string;rating:string;serviceStars:string;category:string;address:string;checkin:string;checkout:string;amenities:string;policies:string;childrenPolicy:string;extraCharge:string;duration:string;pickup:string;boarding:string;itinerary:string;content:string;seoTitle:string;seoDescription:string;units:UnifiedUnit[];source:ProductSource;partnerId?:string;currency:'VND';createdAt?:string;updatedAt:string};
export const productSlug=(v:string)=>v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export function defaultPricingBasis(type:ProductType):PricingBasis{return type==='Khách sạn'?'room_night':type==='Villa & Resort'?'unit_night':type==='Du thuyền'?'cabin_night':'guest'}
export function emptyProduct(type:ProductType):CanonicalProduct{return{id:'',type,name:'',slug:'',place:'',price:'',pricingBasis:defaultPricingBasis(type),status:'draft',summary:'',cover:'',gallery:'',rating:'',serviceStars:'',category:'',address:'',checkin:type==='Tour'?'':'14:00',checkout:type==='Tour'?'':'12:00',amenities:'',policies:'',childrenPolicy:'',extraCharge:'',duration:'',pickup:'',boarding:'',itinerary:'',content:'',seoTitle:'',seoDescription:'',units:[],source:'admin',currency:'VND',updatedAt:''}}
export function normalizeProduct(p:any,fallbackType:ProductType='Villa & Resort'):CanonicalProduct{const type=(['Tour','Villa & Resort','Khách sạn','Du thuyền'].includes(p?.type)?p.type:fallbackType) as ProductType;return{...emptyProduct(type),...p,type,pricingBasis:p?.pricingBasis||defaultPricingBasis(type),serviceStars:String(p?.serviceStars||p?.stars||''),source:p?.source||'admin',currency:'VND',units:Array.isArray(p?.units)?p.units.map((u:any)=>({...blankUnifiedUnit(),...u,id:u?.id||`u_${Date.now()}_${Math.random().toString(36).slice(2,7)}`})):[]}}
export function normalizePartnerProduct(p:any):CanonicalProduct{const type:ProductType=p?.type==='Tour du lịch'||p?.type==='Tour'?'Tour':['Villa & Resort','Khách sạn','Du thuyền'].includes(p?.type)?p.type:'Villa & Resort';return normalizeProduct({...p,type,status:p?.status==='approved'?'published':'draft',source:'partner',partnerId:p?.partnerId,slug:p?.slug||productSlug(p?.name||'')},type)}
export function syncPartnerProductToCatalog(partner:any,approved:boolean){if(typeof window==='undefined'||!partner?.id)return;try{const raw=JSON.parse(localStorage.getItem(PRODUCT_STORAGE_KEY)||'[]');const current:Array<any>=Array.isArray(raw)?raw:[];const without=current.filter(x=>!(x?.source==='partner'&&x?.id===partner.id));const next=approved?[...without,normalizePartnerProduct({...partner,status:'approved',updatedAt:new Date().toISOString()})]:without;localStorage.setItem(PRODUCT_STORAGE_KEY,JSON.stringify(next));window.dispatchEvent(new Event('tn-products-updated'))}catch{}}
export function productUnitKind(type:ProductType):UnifiedUnitKind{return type==='Khách sạn'?'hotel':type==='Villa & Resort'?'villa':type==='Du thuyền'?'cruise':'tour'}
