'use client';

import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {rateForDate,ratePriceCandidates,ratePriceForDate,ratesForUnit} from '@/components/AdminRateCalendar';
import {readPartnerPublic} from '@/components/PartnerPublicCatalog';
import {UnitPhotoGallery} from '@/components/UnitPhotoGallery';
import {fallbackUnitPrice,pricingDateKey,pricingMoney} from '@/lib/pricing-calendar';

type Unit={id:string;code:string;name:string;bedrooms?:string;beds?:string;capacity:string;area:string;view:string;meal:string;weekdayPrice:string;weekendPrice:string;holidayPrice:string;extraAdult?:string;extraChild?:string;status:string;images?:string;amenities?:string;pricingBasis?:'room_night'|'unit_night'|'cabin_night'|'guest'|'package';guestType?:'adult'|'child'|'all'};
type Product={slug:string;units?:Unit[]};
const money=pricingMoney;
const fmt=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
const seasonName=(value?:string)=>value==='low'?'Thấp điểm':value==='high'?'Cao điểm':value==='holiday'?'Lễ / Tết':value==='custom'?'Đặc biệt':'Mùa thường';

export function PublishedUnits({slug,label='Căn / hạng phòng',providedUnits}:{slug:string;label?:string;providedUnits?:Unit[]}){
 const params=useSearchParams();const checkin=params.get('checkin');const checkout=params.get('checkout');
 const[units,setUnits]=useState<Unit[]>([]);const[rev,setRev]=useState(0);
 useEffect(()=>{const load=()=>{if(Array.isArray(providedUnits)){setUnits(providedUnits.filter(u=>u.status!=='hidden'));return}try{const raw=localStorage.getItem('tn_cms_products_v3_units');const products:Product[]=raw?JSON.parse(raw):[];const cms=products.find(p=>p.slug===slug)?.units||[];if(cms.length){setUnits(cms.filter(u=>u.status!=='hidden'));return}const partner=readPartnerPublic().products.find(p=>p.slug===slug);setUnits(((partner?.units||[]) as Unit[]).filter(u=>u.status!=='hidden'))}catch{setUnits([])}};const refresh=()=>{load();setRev(x=>x+1)};load();window.addEventListener('tn-products-updated',refresh);window.addEventListener('happygo-partner-products-updated',refresh);window.addEventListener('tn-rates-updated',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('tn-products-updated',refresh);window.removeEventListener('happygo-partner-products-updated',refresh);window.removeEventListener('tn-rates-updated',refresh);window.removeEventListener('storage',refresh)}},[slug,providedUnits]);
 const selectedDates=useMemo(()=>{if(!checkin)return[];const s=new Date(`${checkin}T12:00:00`),e=checkout?new Date(`${checkout}T12:00:00`):new Date(s.getFullYear(),s.getMonth(),s.getDate()+1);const a:Date[]=[];for(let d=s;d<e;d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1))a.push(d);return a},[checkin,checkout]);
 const choose=(u:Unit)=>window.dispatchEvent(new CustomEvent('tn:select-unit',{detail:{id:u.id,unitId:u.id,code:u.code,name:u.name,pricingBasis:u.pricingBasis,guestType:u.guestType}}));
 const selectLabel=(u:Unit)=>u.pricingBasis==='guest'?'Chọn vé':u.pricingBasis==='package'?'Chọn gói':u.pricingBasis==='cabin_night'||/cabin/i.test(label)?'Chọn cabin':u.pricingBasis==='unit_night'||/(villa|căn)/i.test(label)?'Chọn căn':'Chọn phòng';
 if(!units.length)return null;
 return <section className="detail-block live-units" id="units"><div className="live-units-head"><h2>{label} đang quản lý</h2><p>{checkin?'Giá và tồn được tính theo đúng mùa và thứ của từng ngày đã chọn.':'Giá thay đổi theo mùa, ngày trong tuần và dịp lễ/Tết. Chọn ngày để xem mức giá chính xác.'}</p></div><div className="live-unit-list">{units.map(u=>{
  const stayBasis=u.pricingBasis!=='guest'&&u.pricingBasis!=='package';const allPhotos=(u.images||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
  const calendarRates=ratesForUnit(u.id).filter(r=>r.status==='available'&&Number(r.quantity||0)>0);const calendarPrices=calendarRates.flatMap(ratePriceCandidates).filter(Boolean);const calendarMin=calendarPrices.length?Math.min(...calendarPrices):0;const calendarMax=calendarPrices.length?Math.max(...calendarPrices):0;
  const effectiveDates=stayBasis?selectedDates:selectedDates.slice(0,1);const dayInfo=effectiveDates.map(d=>{const r=rateForDate(u.id,pricingDateKey(d));return {date:d,rate:r,price:r&&r.status==='available'&&Number(r.quantity||0)>0?ratePriceForDate(r,d):r?0:fallbackUnitPrice(u,d)}});const vals=dayInfo.map(x=>x.price).filter(Boolean);const min=vals.length?Math.min(...vals):0,max=vals.length?Math.max(...vals):0;const custom=dayInfo.map(x=>x.rate).filter(Boolean);const soldByCalendar=custom.some(r=>r!.status!=='available'||Number(r!.quantity||0)<=0);const minQty=custom.length?Math.min(...custom.map(r=>Number(r!.quantity||0))):null;const minStay=stayBasis&&custom.length?Math.max(...custom.map(r=>Number(r!.minStay||1))):1;const oldVals=custom.map(r=>money(r!.oldPrice)).filter(Boolean);const oldPrice=oldVals.length?Math.max(...oldVals):0;const stayOk=!stayBasis||!selectedDates.length||selectedDates.length>=minStay;const available=u.status==='available'&&!soldByCalendar&&stayOk;
  const basePrices=[money(u.weekdayPrice),money(u.weekendPrice),money(u.holidayPrice)].filter(Boolean);const baseMin=basePrices.length?Math.min(...basePrices):0;const publicMin=calendarRates.length?calendarMin:baseMin;const unitSuffix=u.pricingBasis==='guest'?'/ khách':u.pricingBasis==='package'?'/ gói':u.pricingBasis==='unit_night'?'/ căn/đêm':u.pricingBasis==='cabin_night'?'/ cabin/đêm':'/ phòng/đêm';
  const seasonal=calendarRates.filter(r=>r.weekdayPrice||r.weekendPrice||r.sundayPrice||r.holidayPrice).sort((a,b)=>a.start.localeCompare(b.start)).slice(0,4);
  return <article key={`${u.id}_${rev}`}><div className="live-unit-main"><div className="live-unit-info"><b>{u.name||'Chưa đặt tên'}</b><small>{u.code||'Chưa có mã'}{u.bedrooms?` · ${u.bedrooms} phòng ngủ`:''}{u.beds?` · ${u.beds}`:''}{u.capacity?` · ${u.capacity}`:' · Sức chứa liên hệ'}{u.area?` · ${u.area}`:''}{u.view?` · ${u.view}`:''}</small>{u.meal&&<span>{u.meal}</span>}{u.amenities&&<span>{u.amenities}</span>}{u.pricingBasis==='guest'&&<span>{u.guestType==='adult'?'Vé người lớn':u.guestType==='child'?'Vé trẻ em':'Vé áp dụng mọi khách'}</span>}{effectiveDates.length&&minQty!==null&&minQty>0&&minQty<50&&<span className="availability-note">Chỉ còn {minQty} {u.pricingBasis==='guest'?'suất':u.pricingBasis==='package'?'gói':'đơn vị'} cho ngày đã chọn</span>}</div>{allPhotos.length>0&&<UnitPhotoGallery title={u.name||'Hạng phòng'} images={allPhotos} kind={/villa|căn/i.test(label)?'villa':'hotel'}/>}</div>
  {effectiveDates.length?<div className="selected-date-price">{oldPrice>max&&<del>{fmt(oldPrice)}</del>}<small>Giá cho ngày đã chọn</small><b>{min?min===max?fmt(min):`${fmt(min)} – ${fmt(max)}`:'Không còn'}</b><em>{unitSuffix}{stayBasis&&selectedDates.length>1?` · ${selectedDates.length} đêm`:''}{stayBasis&&minStay>1?` · tối thiểu ${minStay} đêm`:''}</em>{u.extraAdult&&<span>Phụ thu người lớn: <b>{u.extraAdult}</b></span>}{u.extraChild&&<span>Phụ thu trẻ em: <b>{u.extraChild}</b></span>}</div>:<><div className="selected-date-price"><small>GIÁ THAM KHẢO</small><b>{publicMin?`Từ ${fmt(publicMin)}`:'Liên hệ'}</b>{calendarRates.length>0&&<em>{calendarMin&&calendarMax&&calendarMin!==calendarMax?`Biến động ${fmt(calendarMin)} – ${fmt(calendarMax)} theo mùa/ngày`:'Giá thay đổi theo lịch mùa đã cấu hình'}</em>}</div>{seasonal.length>0?<div className="live-season-rates">{seasonal.map(r=><div key={r.id}><strong>{seasonName(r.season)}</strong><small>{r.start} → {r.end}</small><span>{r.weekdayPrice&&<b>T2–T5: {r.weekdayPrice}</b>}{r.weekendPrice&&<b>T6–T7: {r.weekendPrice}</b>}{r.sundayPrice&&<b>CN: {r.sundayPrice}</b>}{r.holidayPrice&&<b>Lễ/Tết: {r.holidayPrice}</b>}</span></div>)}</div>:calendarRates.length?<div className="live-calendar-hint">📅 Giá được quản lý theo ngày/mùa. Hãy chọn ngày để xem đúng giá của hạng phòng này.</div>:<div className="live-unit-prices"><span><small>Ngày thường</small><b>{u.weekdayPrice||'Liên hệ'}</b></span><span><small>Cuối tuần</small><b>{u.weekendPrice||u.weekdayPrice||'Liên hệ'}</b></span><span><small>Lễ/Tết</small><b>{u.holidayPrice||'Liên hệ'}</b></span></div>}{u.extraAdult&&<div className="unit-extra-fee">Phụ thu người lớn: <b>{u.extraAdult}</b></div>}{u.extraChild&&<div className="unit-extra-fee">Phụ thu trẻ em: <b>{u.extraChild}</b></div>}</>}
  <em className={`unit-public-status ${available?'available':'soldout'}`}>{available?'Còn bán':!stayOk?`Tối thiểu ${minStay} đêm`:'Hết / tạm giữ'}</em>{available?<a href="#booking" onClick={()=>choose(u)}>{selectLabel(u)}</a>:<span className="unit-unavailable">Chưa thể đặt</span>}</article>
 })}</div></section>;
}
