'use client';

import {useMemo,useState} from 'react';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';
import {addCartItem} from '@/components/BookingCart';

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const LOCAL_KEY='tn_local_bookings_v1';
const normalizePhone=(raw:string)=>{const digits=raw.replace(/\D/g,'');return digits.startsWith('84')&&digits.length===11?`0${digits.slice(2)}`:digits};
const normalizeDate=(raw:string)=>{const value=raw.trim();const iso=value.match(/^(\d{4})-(\d{2})-(\d{2})/);if(iso)return `${iso[1]}-${iso[2]}-${iso[3]}`;const vi=value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(vi)return `${vi[3]}-${vi[2].padStart(2,'0')}-${vi[1].padStart(2,'0')}`;return ''};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function saveLocal(payload:any){try{const list=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');const now=new Date();const code=`TN${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(Date.now()).slice(-5)}`;localStorage.setItem(LOCAL_KEY,JSON.stringify([{id:Date.now(),code,kind:'tour',product:payload.product,customer_name:payload.customerName,phone:payload.phone,email:payload.email||'',start_date:payload.startDate,end_date:null,adults:payload.adults,children:payload.children,rooms:1,note:payload.note||'',status:'new',admin_note:'',created_at:now.toISOString(),source:'website-local'},...list].slice(0,500)));window.dispatchEvent(new Event('tn-bookings-updated'));return code}catch{return ''}}

export function TourBookingInquiry({product,departureDates}:{product:string;departureDates:string[]}){
 const settings=useSiteSettings();const [message,setMessage]=useState('');const[state,setState]=useState<'idle'|'sending'|'saved'>('idle');const[code,setCode]=useState('');
 const phoneDigits=settings.hotline.replace(/\D/g,'');const phoneLabel=formatPhone(settings.hotline);const zaloDigits=settings.zalo.replace(/\D/g,'')||phoneDigits;
 const dates=useMemo(()=>{const min=today();return departureDates.map(label=>({label:label.trim(),value:normalizeDate(label)})).filter(x=>x.label&&x.value&&x.value>=min).filter((x,i,a)=>a.findIndex(y=>y.value===x.value)===i).sort((a,b)=>a.value.localeCompare(b.value))},[departureDates]);
 async function submit(form:HTMLFormElement){setMessage('');const data=new FormData(form);const name=String(data.get('name')||'').trim();const phone=normalizePhone(String(data.get('phone')||''));const date=String(data.get('from')||'');if(name.length<2){setMessage('Vui lòng nhập họ tên.');return}if(!/^0\d{9}$/.test(phone)){setMessage('Số điện thoại chưa đúng.');return}if(!date||!dates.some(x=>x.value===date)){setMessage('Vui lòng chọn một ngày khởi hành đang mở bán.');return}const payload={kind:'tour',product,customerName:name,phone,email:String(data.get('email')||'').trim(),startDate:date,endDate:null,adults:Number(data.get('adults')||2),children:Number(data.get('children')||0),rooms:1,note:String(data.get('note')||'').trim(),source:'website'};if(API_BASE){try{setState('sending');const response=await fetch(`${API_BASE.replace(/\/$/,'')}/api/bookings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Booking API error');const result=await response.json();setCode(result.code||'');setState('saved');form.reset();return}catch(error){console.error(error)}}const localCode=saveLocal(payload);setCode(localCode);setState('saved');form.reset()}
 function addCart(form:HTMLFormElement){const data=new FormData(form);const date=String(data.get('from')||'');if(!date||!dates.some(x=>x.value===date)){setMessage('Chọn ngày khởi hành đang mở bán trước khi thêm vào giỏ.');return}addCartItem({kind:'tour',product,startDate:date,endDate:'',adults:Number(data.get('adults')||2),children:Number(data.get('children')||0),rooms:1});setMessage('✓ Đã thêm tour vào giỏ.')}
 return <form className="inquiry-form inquiry-pro" onSubmit={e=>{e.preventDefault();submit(e.currentTarget)}}><div className="inquiry-head-pro"><div className="inquiry-head-icon">✈</div><div><small>YÊU CẦU ĐẶT TOUR</small><h3>Đăng ký tour & giữ chỗ</h3><p>{product}</p></div></div><div className="inquiry-trust"><span>✓ Chưa thanh toán</span><span>✓ Chỉ ngày có chuyến</span><span>✓ Sale xác nhận chỗ</span></div><section className="inquiry-step"><div className="inquiry-step-title"><b>1</b><div><strong>Ngày khởi hành</strong><small>Các ngày khác đã khóa vì không có chuyến</small></div></div>{dates.length?<label><span>Chọn ngày có chuyến *</span><select name="from" required defaultValue=""><option value="" disabled>— Chọn ngày khởi hành —</option>{dates.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label>:<div className="inquiry-no-unit"><span>📅</span><div><b>Chưa có lịch khởi hành đang mở</b><small>Vui lòng liên hệ sale để kiểm tra chuyến mới.</small></div></div>}<div className="inquiry-three inquiry-guest-grid"><label><span>Người lớn</span><input name="adults" type="number" min="1" max="50" defaultValue="2"/></label><label><span>Trẻ em</span><input name="children" type="number" min="0" max="50" defaultValue="0"/></label></div></section><section className="inquiry-step"><div className="inquiry-step-title"><b>2</b><div><strong>Thông tin người đặt</strong><small>Sale sẽ gọi xác nhận chỗ và giá</small></div></div><div className="inquiry-contact-grid"><label><span>Họ và tên *</span><input name="name" autoComplete="name" placeholder="Nguyễn Văn A"/></label><label><span>Số điện thoại *</span><input name="phone" type="tel" inputMode="tel" placeholder={phoneLabel}/></label></div><label><span>Email</span><input name="email" type="email" placeholder="email@example.com"/></label><label><span>Yêu cầu thêm</span><textarea name="note" rows={3} placeholder="Điểm đón, ăn uống, tuổi trẻ em..."/></label></section>{message&&<p className={message.startsWith('✓')?'inquiry-success':'inquiry-error'}>{message}</p>}<div className="inquiry-primary-actions"><button className="inquiry-submit" type="submit" disabled={!dates.length||state==='sending'||state==='saved'}>{state==='sending'?'Đang gửi...':state==='saved'?`Đã gửi · ${code}`:'Gửi yêu cầu giữ chỗ'}</button><small>Chỉ nhận đặt vào các ngày Admin đã mở</small></div><div className="inquiry-secondary-actions"><button className="inquiry-add-cart" type="button" disabled={!dates.length} onClick={e=>addCart(e.currentTarget.form!)}>＋ Thêm vào giỏ</button><a href="/checkout">Xem giỏ / Xác nhận</a></div><div className="inquiry-support"><div><small>Cần chốt nhanh?</small><b>Sale hỗ trợ trực tiếp</b></div><a className="inquiry-call" href={`tel:${phoneDigits}`}>☎ {phoneLabel}</a><a className="inquiry-zalo" href={`https://zalo.me/${zaloDigits}`} target="_blank" rel="noreferrer">Zalo</a></div></form>
}
