'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {tours} from '@/data/catalog';
type CmsTour={id:string;name:string;slug:string;cover?:string;category:string;duration:string;departure:string;route:string;summary:string;status:string;salePrice:string;price:string;departures:string;gallery:string};
const groups=[['all','Tất cả'],['domestic','Trong nước'],['china','Trung Quốc'],['korea','Hàn Quốc'],['japan','Nhật Bản'],['sea','Đông Nam Á'],['europe','Châu Âu'],['usa','Mỹ'],['australia','Úc'],['india','Ấn Độ'],['maldives','Maldives']] as const;
const samples=[
 {slug:'tour-han-quoc-seoul-nami-everland',name:'Hàn Quốc: Seoul - Đảo Nami - Everland',category:'Tour Hàn Quốc',duration:'5N4Đ',route:'Seoul - Nami - Everland',image:'https://images.unsplash.com/photo-1538485399081-7c8979a7d1c2?auto=format&fit=crop&w=1000&q=85',summary:'Hành trình mẫu khám phá Seoul, đảo Nami và công viên Everland.',price:'Từ 16.990.000đ'},
 {slug:'tour-nhat-ban-tokyo-fuji-osaka',name:'Nhật Bản: Tokyo - Núi Phú Sĩ - Kyoto - Osaka',category:'Tour Nhật Bản',duration:'6N5Đ',route:'Tokyo - Fuji - Kyoto - Osaka',image:'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=85',summary:'Tour mẫu Nhật Bản kết hợp đô thị, văn hóa và cảnh quan núi Phú Sĩ.',price:'Từ 29.990.000đ'},
 {slug:'tour-singapore-malaysia-5n4d',name:'Singapore - Malaysia: Sentosa - Kuala Lumpur',category:'Tour Đông Nam Á',duration:'5N4Đ',route:'Singapore - Sentosa - Kuala Lumpur',image:'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=85',summary:'Hành trình mẫu Đông Nam Á kết hợp Singapore và Malaysia.',price:'Từ 12.990.000đ'},
 {slug:'tour-chau-au-phap-thuy-si-y',name:'Châu Âu: Pháp - Thụy Sĩ - Ý',category:'Tour Châu Âu',duration:'10N9Đ',route:'Paris - Lucerne - Milan - Venice - Rome',image:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1000&q=85',summary:'Tour mẫu Châu Âu qua Pháp, Thụy Sĩ và Ý với các thành phố nổi tiếng.',price:'Từ 69.990.000đ'},
 {slug:'tour-my-dong-tay-new-york-las-vegas',name:'Mỹ: New York - Washington D.C. - Las Vegas',category:'Tour Mỹ',duration:'10N9Đ',route:'New York - Washington D.C. - Las Vegas',image:'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=1000&q=85',summary:'Tour mẫu Hoa Kỳ kết hợp Bờ Đông và Las Vegas.',price:'Từ 79.990.000đ'},
 {slug:'tour-uc-sydney-melbourne',name:'Úc: Sydney - Canberra - Melbourne',category:'Tour Úc',duration:'7N6Đ',route:'Sydney - Canberra - Melbourne',image:'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1000&q=85',summary:'Tour mẫu nước Úc với Sydney, Canberra và Melbourne.',price:'Từ 49.990.000đ'},
 {slug:'tour-an-do-tam-giac-vang',name:'Ấn Độ: Delhi - Agra - Jaipur',category:'Tour Ấn Độ',duration:'6N5Đ',route:'Delhi - Agra - Jaipur',image:'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1000&q=85',summary:'Hành trình Tam giác Vàng Ấn Độ, nổi bật với Taj Mahal và Jaipur.',price:'Từ 24.990.000đ'},
 {slug:'tour-maldives-nghi-duong-5n4d',name:'Maldives nghỉ dưỡng 5 ngày 4 đêm',category:'Tour Maldives',duration:'5N4Đ',route:'Malé - Resort Maldives',image:'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1000&q=85',summary:'Tour mẫu nghỉ dưỡng Maldives dành cho cặp đôi và gia đình.',price:'Từ 35.990.000đ'}
];
function groupOf(cat:string){const x=cat.toLowerCase();if(x.includes('trong nước'))return'domestic';if(x.includes('trung quốc'))return'china';if(x.includes('hàn quốc'))return'korea';if(x.includes('nhật bản'))return'japan';if(x.includes('đông nam á'))return'sea';if(x.includes('châu âu'))return'europe';if(x.includes('tour mỹ'))return'usa';if(x.includes('tour úc'))return'australia';if(x.includes('ấn độ'))return'india';if(x.includes('maldives'))return'maldives';return'all'}
export function TourCatalog(){const params=useSearchParams();const q=(params.get('q')||'').toLowerCase();const departure=(params.get('departure')||'').toLowerCase();const initial=params.get('category')||'all';const [category,setCategory]=useState(groups.some(g=>g[0]===initial)?initial:'all');const [cms,setCms]=useState<CmsTour[]>([]);useEffect(()=>{try{setCms((JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]') as CmsTour[]).filter(x=>x.status==='published'))}catch{}},[]);const allStatic=[...tours.map(x=>({...x,price:x.priceFrom||'Liên hệ'})),...samples];const filtered=useMemo(()=>allStatic.filter(x=>(category==='all'||groupOf(x.category)===category)&&(!q||`${x.name} ${x.route} ${x.category} ${x.summary}`.toLowerCase().includes(q))&&(!departure||('departureFrom'in x?x.departureFrom||'':'').toLowerCase().includes(departure))),[category,q,departure]);const cmsFiltered=useMemo(()=>cms.filter(x=>(category==='all'||groupOf(x.category)===category)&&(!q||`${x.name} ${x.route} ${x.category}`.toLowerCase().includes(q))),[cms,category,q]);return <><div className="sub-toolbar"><div><b>{filtered.length+cmsFiltered.length} hành trình phù hợp</b><br/><span>Chọn danh mục tour theo quốc gia / khu vực</span></div></div><div className="sub-filter-row tour-country-filter">{groups.map(([id,label])=><button type="button" key={id} className={`sub-chip ${category===id?'active':''}`} onClick={()=>setCategory(id)}>{label}</button>)}</div><div className="catalog-grid">{filtered.map(item=><article className="catalog-card" key={item.slug}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.category} · {item.duration}</small><h3>{item.name}</h3><p>📍 {item.route}</p><p>{item.summary}</p><p><b style={{color:'#f15a24'}}>{item.price}</b></p><div className="catalog-actions"><Link className="main" href={'itinerary'in item?`/tours/${item.slug}`:`/tours?category=${groupOf(item.category)}&q=${encodeURIComponent(item.name)}`}>Xem chi tiết</Link></div></div></article>)}{cmsFiltered.map(item=><article className="catalog-card" key={item.id}><div className="catalog-image" style={{backgroundImage:`url(${item.cover||'https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1000&q=85'})`}}/><div className="catalog-body"><small>{item.category} · {item.duration}</small><h3>{item.name}</h3><p>📍 {item.route}</p><p>{item.summary}</p><p><b style={{color:'#f15a24'}}>{item.salePrice||item.price||'Liên hệ'}</b></p><div className="catalog-actions"><Link className="main" href={`/tour-product?slug=${encodeURIComponent(item.slug)}`}>Xem chi tiết</Link></div></div></article>)}</div></>}
