'use client';

import {useMemo,useState} from 'react';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';
import {addCartItem} from '@/components/BookingCart';

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const LOCAL_KEY='tn_local_bookings_v1',PRODUCTS_KEY='tn_cms_products_v3_units';
const normalizePhone=(raw:string)=>{const digits=raw.replace(/\D/g,'');return digits.startsWith('84')&&digits.length===11?`0${digits.slice(2)}`:digits};
const normalizeDate=(raw:string)=>{const value=raw.trim();const iso=value.match(/^(\d{4})-(\d{2})-(\d{2})/);if(iso)return `${iso[1]}-${iso[2]}-${iso[3]}`;const vi=value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(vi)return `${vi[3]}-${vi[2].padStart(2,'0')}-${vi[1].padStart(2,'0')}`;return ''};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=(v?:string)=>{const n=String(v||'').replace(/\D/g,'');return n?Number(n):undefined};
const holidays=new Set(['01-01','04-30','05-01','09-02']);
type TourUnit={id:string;code?:string;name?:string;weekdayPrice?:string;weekendPrice?:string;holidayPrice?:string;pricingBasis?:'guest'|'package'|'room_night'|'unit_night'|'cabin_night';guestType?:'adult'|'child'|'all'};type TourProduct={id?:string;slug?:string;name?:string;type?:string;units?:TourUnit[]};
function tourUnits(product:string){try{const all=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'[]') as TourProduct[];const p=(Array.isArray(all)?all:[]).find(x=>x.name===product&&x.type==='Tour')||(Array.isArray(all)?all:[]).find(x=>x.name===product);const units=p?.units||[];const adult=units.find(u=>u.pricingBasis==='guest'&&u.guestType==='adult')||units.find(u=>/người lớn|nguoi lon|adult/i.test(`${u.name||''} ${u.code||''}`));const child=units.find(u=>u.pricingBasis==='guest'&&u.guestType==='child')||units.find(u=>/trẻ em|tre em|child/i.test(`${u.name||''} ${u.code||''}`));return{product:p,adult,child}}catch{return{product:undefined,adult:undefined,child:undefined}}}
function unitPrice(u:TourUnit|undefined,date:string){if(!u)return undefined;const d=new Date(`${date}T12:00:00`),md=`${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,base=money(u.weekdayPrice),weekend=money(u.weekendPrice)||base,holiday=money(u.holidayPrice)||weekend||base;if(holidays.has(md))return holiday;if(d.getDay()===5||d.getDay()===6)return weekend;return base}
function saveLocal(payload:any){try{const list=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');const now=new Date();const code=`TN${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${String(Date.now()).slice(-5)}`;localStorage.setItem(LOCAL_KEY,JSON.stringify([{id:Date.now(),code,kind:'tour',product:payload.product,customer_name:payload.customerName,phone:payload.phone,email:payload.email||'',start_date:payload.startDate,end_date:null,adults:payload.adults,children:payload.children,rooms:1,note:payload.note||'',status:'new',admin_note:'',created_at:now.toISOString(),source:'website-local'},...list].slice(0,500)));window.dispatchEvent(new Event('tn-bookings-updated'));return code}catch{return ''}}

export function TourBookingInquiry({product,departureDates}:{product:string;departureDates:string[]}){
 const settings=useSiteSettings();const [message,setMessage]=useState('');const[state,setState]=useState<'idle'|'sending'|'saved'>('idle');const[code,setCode]=useState('');
 const phoneDigits=settings.hotline.replace(/\D/g,'');const phoneLabel=formatPhone(settings.hotline);const zaloDigits=settings.zalo.replace(/\D/g,'')||phoneDigits;
 const dates=useMemo(()=>{const min=today();return departureDates.map(label=>({label:label.trim(),value:normalizeDate(label)})).filter(x=>x.label&&x.value&&x.value>=min).filter((x,i,a)=>a.findIndex(y=>y.value===x.value)===i).sort((a,b)=>a.value.localeCompare(b.value))},[departureDates]);
 async function submit(form:HTMLFormElement){setMessage('');const data=new FormData(form);const name=String(data.get('name')||'').trim();const phone=normalizePhone(String(data.get('phone')||''));const date=String(data.get('from')||'');if(name.length<2){setMessage('Vui lòng nhập họ tên.');return}if(!/^0\d{9}$/.test(phone)){setMessage('Số điện thoại chưa đúng.');return}if(!date||!dates.some(x=>x.value===date)){setMessage('Vui lòng chọn một ngày khởi hành đang mở bán.');return}const payload={kind:'tour',product,customerName:name,phone,email:String(data.get('email')||'').trim(),startDate:date,endDate:null,adults:Number(data.get('adults')||2),children:Number(data.get('children')||0),rooms:1,note:String(data.get('note')||'').trim(),source:'website'};if(API_BASE){try{setState('sending');const response=await fetch(`${API_BASE.replace(/\/$/,'')}/api/bookings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Booking API error');const result=await response.json();setCode(result.code||'');setState('saved');form.reset();return}catch(error){console.error(error)}}const localCode=saveLocal(payload);setCode(localCode);setState('saved');form.reset()}
 function addCart(form:HTMLFormElement){setMessage('');const data=new FormData(form),date=String(data.get('from')||''),adults=Math.max(0,Number(data.get('adults')||0)),children=Math.max(0,Number(data.get('children')||0));if(!date||!dates.some(x=>x.value===date)){setMessage('Chọn ngày khởi hành đang mở bán trước khi thêm vào giỏ.');return}if(adults+children<1){setMessage('Vui lòng chọn ít nhất 1 khách.');return}const {product:p,adult,child}=tourUnits(product);const added=[];if(adults>0){const x=addCartItem({kind:'tour',product,productId:p?.id,unit:adult?.name||'Vé người lớn',unitId:adult?.id,startDate:date,endDate:'',adults,children:0,rooms:1,pricingBasis:'guest',guestType:'adult',explicitQuantity:adults,sellingPrice:unitPrice(adult,date)});if(x)added.push(x)}if(children>0){const x=addCartItem({kind:'tour',product,productId:p?.id,unit:child?.name||'Vé trẻ em',unitId:child?.id,startDate:date,endDate:'',adults:0,children,rooms:1,pricingBasis:'guest',guestType:'child',explicitQuantity:children,sellingPrice:unitPrice(child,date)});if(x)added.push(x)}if(!added.length){setMessage('Không đủ chỗ cho số khách đã chọn hoặc tour chưa mở tồn.');return}if((adults>0&&!added.some(x=>x.guestType==='adult'))||(children>0&&!added.some(x=>x.guestType==='child')))setMessage('Đã thêm phần còn đủ chỗ. Một loại vé hiện không đủ tồn.');else setMessage(`✓ Đã thêm ${adults?`${adults} vé người lớn`:''}${adults&&children?' + ':''}${children?`${children} vé trẻ em`:''} vào giỏ.`)}
 return <form className="inquiry-form inquiry-pro" onSubmit={e=>{e.preventDefault();submit(e.currentTarget)}}><div className="inquiry-head-pro"><div className="inquiry-head-icon">✈</div><div><small>YÊU CẦU ĐẶT TOUR</small><h3>Đăng ký tour & giữ chỗ</h3><p>{product}</p></div></div><div className="inquiry-trust"><span>✓ Chưa thanh toán</span><span>✓ Chỉ ngày có chuyến</span><span>✓ Sale xác nhận chỗ</span></div><section className="inquiry-step"><div className="inquiry-step-title"><b>1</b><div><strong>Ngày khởi hành</strong><small>Các ngày khác đã khóa vì không có chuyến</small></div></div>{dates.length?<label><span>Chọn ngày có chuyến *</span><select name="from" required defaultValue=""><option value="" disabled>— Chọn ngày khởi hành —</option>{dates.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label>:<div className="inquiry-no-unit"><span>📅</span><div><b>Chưa có lịch khởi hành đang mở</b><small>Vui lòng liên hệ sale để kiểm tra chuyến mới.</small></div></div>}<div className="inquiry-three inquiry-guest-grid"><label><span>Người lớn</span><input name="adults" type="number" min="0" max="50" defaultValue="2"/></label><label><span>Trẻ em</span><input name="children" type="number" min="0" max="50" defaultValue="0"/></label></div></section><section className="inquiry-step"><div className="inquiry-step-title"><b>2</b><div><strong>Thông tin người đặt</strong><small>Sale sẽ gọi xác nhận chỗ và giá</small></div></div><div className="inquiry-contact-grid"><label><span>Họ và tên *</span><input name="name" autoComplete="name" placeholder="Nguyễn Văn A"/></label><label><span>Số điện thoại *</span><input name="phone" type="tel" inputMode="tel" placeholder={phoneLabel}/></label></div><label><span>Email</span><input name="email" type="email" placeholder="email@example.com"/></label><label><span>Yêu cầu thêm</span><textarea name="note" rows={3} placeholder="Điểm đón, ăn uống, tuổi trẻ em..."/></label></section>{message&&<p className={message.startsWith('✓')?'inquiry-success':'inquiry-error'}>{message}</p>}<div className="inquiry-primary-actions"><button className="inquiry-submit" type="submit" disabled={!dates.length||state==='sending'||state==='saved'}>{state==='sending'?'Đang gửi...':state==='saved'?`Đã gửi · ${code}`:'Gửi yêu cầu giữ chỗ'}</button><small>Chỉ nhận đặt vào các ngày Admin đã mở</small></div><div className="inquiry-secondary-actions"><button className="inquiry-add-cart" type="button" disabled={!dates.length} onClick={e=>addCart(e.currentTarget.form!)}>＋ Thêm vào giỏ</button><a href="/checkout">Xem giỏ / Xác nhận</a></div><div className="inquiry-support"><div><small>Cần chốt nhanh?</small><b>Sale hỗ trợ trực tiếp</b></div><a className="inquiry-call" href={`tel:${phoneDigits}`}>☎ {phoneLabel}</a><a className="inquiry-zalo" href={`https://zalo.me/${zaloDigits}`} target="_blank" rel="noreferrer">Zalo</a></div></form>
}
