'use client';

import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {tours} from '@/data/catalog';

type CmsTour={id:string;name:string;slug:string;cover?:string;category:string;duration:string;departure:string;route:string;summary:string;status:string;salePrice:string;price:string;departures:string;gallery:string};
const lines=(v?:string)=>String(v||'').split(/\n+/).map(x=>x.trim()).filter(Boolean);
export function TourCatalog(){
 const params=useSearchParams();const q=(params.get('q')||'').toLowerCase();const departure=(params.get('departure')||'').toLowerCase();const date=params.get('date')||'';const selectedDay=date?date.split('-').reverse().slice(0,2).join('/'):'';const categoryParam=(params.get('category')||'all').toLowerCase();const[category,setCategory]=useState(['china','domestic'].includes(categoryParam)?categoryParam:'all');const[cms,setCms]=useState<CmsTour[]>([]);
 useEffect(()=>setCategory(['china','domestic'].includes(categoryParam)?categoryParam:'all'),[categoryParam]);
 useEffect(()=>{const load=()=>{try{setCms(JSON.parse(localStorage.getItem('tn_cms_tours_v3')||'[]') as CmsTour[])}catch{setCms([])}};load();window.addEventListener('tn-tours-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('tn-tours-updated',load);window.removeEventListener('storage',load)}},[]);
 const staticSlugs=useMemo(()=>new Set(tours.map(x=>x.slug)),[]);
 const mergedStatic=useMemo(()=>tours.flatMap(item=>{const c=cms.find(x=>x.slug===item.slug);if(c&&c.status!=='published')return[];return [{...item,name:c?.name||item.name,category:(c?.category||item.category) as typeof item.category,duration:c?.duration||item.duration,departureFrom:c?.departure||item.departureFrom,route:c?.route||item.route,summary:c?.summary||item.summary,image:c?.cover||item.image,priceFrom:c?.salePrice||c?.price||item.priceFrom,departureDates:c?.departures?lines(c.departures):item.departureDates||[]}]}),[cms]);
 const matches=(item:{name:string;route:string;category:string;summary:string;departureFrom?:string;departureDates?:string[]})=>{const matchQ=!q||`${item.name} ${item.route} ${item.category} ${item.summary}`.toLowerCase().includes(q);const matchDeparture=!departure||(item.departureFrom||'').toLowerCase().includes(departure);const matchCategory=category==='all'||(category==='china'&&item.category==='Tour Trung Quốc')||(category==='domestic'&&item.category==='Tour trong nước');const dates=item.departureDates||[];const matchDate=!selectedDay||dates.some(value=>value.startsWith(selectedDay));return matchQ&&matchDeparture&&matchCategory&&matchDate};
 const filtered=useMemo(()=>mergedStatic.filter(matches),[mergedStatic,q,departure,category,selectedDay]);
 const cmsOnly=useMemo(()=>cms.filter(item=>item.status==='published'&&!staticSlugs.has(item.slug)).map(item=>({...item,departureFrom:item.departure,departureDates:lines(item.departures)})).filter(matches),[cms,q,departure,category,selectedDay,staticSlugs]);
 const cards=useMemo(()=>[...filtered.map(item=>({key:`static_${item.slug}`,slug:item.slug,href:`/tours/${item.slug}`,image:item.image,category:item.category,duration:item.duration,name:item.name,route:item.route,summary:item.summary,price:item.priceFrom||'',dates:item.departureDates||[]})),...cmsOnly.map(item=>({key:`cms_${item.id}`,slug:item.slug,href:`/tour-product?slug=${encodeURIComponent(item.slug)}`,image:item.cover||lines(item.gallery)[0]||'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1000&q=85',category:item.category,duration:item.duration||'Đang cập nhật',name:item.name,route:item.route||'Lịch trình đang cập nhật',summary:item.summary||'Tour được xuất bản từ hệ thống quản trị.',price:item.salePrice||item.price||'',dates:item.departureDates||[]}))],[filtered,cmsOnly]);
 return <><div className="sub-toolbar"><div><b>{cards.length} hành trình phù hợp</b><br/><span>{q?`Điểm đến/từ khóa: ${params.get('q')}`:'Tour gia đình · Tour đoàn · Tour ghép'}{departure?` · Khởi hành: ${params.get('departure')}`:''}{date?` · Ngày đi: ${date.split('-').reverse().join('/')}`:''}</span></div><div className="sub-filter-row"><button type="button" className={`sub-chip ${category==='all'?'active':''}`} onClick={()=>setCategory('all')}>Tất cả</button><button type="button" className={`sub-chip ${category==='china'?'active':''}`} onClick={()=>setCategory('china')}>Trung Quốc</button><button type="button" className={`sub-chip ${category==='domestic'?'active':''}`} onClick={()=>setCategory('domestic')}>Trong nước</button></div></div><div className="catalog-grid">{cards.map(item=><article className="catalog-card" key={item.key}><div className="catalog-image" style={{backgroundImage:`url(${item.image})`}}/><div className="catalog-body"><small>{item.category} · {item.duration}</small><h3>{item.name}</h3><p>📍 {item.route}</p><p>{item.summary}</p>{item.dates.length>0&&<p><b>Khởi hành gần nhất:</b> {item.dates.slice(0,3).join(' · ')}</p>}<p><b style={{color:'#f15a24'}}>Từ {item.price||'Liên hệ'}</b></p><div className="catalog-actions"><Link className="main" href={item.href}>Xem chi tiết</Link></div></div></article>)}</div>{!cards.length&&<div className="empty-results"><b>Không có chuyến vào ngày đã chọn</b><p>Ngày không được Admin mở lịch sẽ không hiển thị Tour. Vui lòng chọn ngày khởi hành khác.</p></div>}</>;
}
