'use client';

import {useMemo,useState} from 'react';
import {AdminMediaPicker} from '@/components/AdminMediaLibrary';

export type UnifiedUnitStatus='available'|'hold'|'soldout'|'hidden';
export type UnifiedUnit={id:string;code:string;name:string;bedrooms:string;beds:string;capacity:string;area:string;view:string;meal:string;amenities:string;weekdayPrice:string;weekendPrice:string;holidayPrice:string;extraAdult:string;extraChild:string;images:string;status:UnifiedUnitStatus;note:string};
export type UnifiedUnitKind='hotel'|'villa'|'cruise'|'generic';
const uid=()=>`u_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
export const blankUnifiedUnit=():UnifiedUnit=>({id:uid(),code:'',name:'',bedrooms:'',beds:'',capacity:'',area:'',view:'',meal:'',amenities:'',weekdayPrice:'',weekendPrice:'',holidayPrice:'',extraAdult:'',extraChild:'',images:'',status:'available',note:''});
const hotelPresets:Array<Partial<UnifiedUnit>&{label:string}>=[{label:'Standard',name:'Standard',beds:'1 Double / 2 Twin',capacity:'2 người lớn'},{label:'Deluxe',name:'Deluxe',beds:'1 King / 2 Twin',capacity:'2 người lớn + 1 trẻ em'},{label:'Suite',name:'Suite',beds:'1 King',capacity:'2 người lớn + 1 trẻ em'}];
const villaPresets:Array<Partial<UnifiedUnit>&{label:string}>=[{label:'Villa 2PN',name:'Villa 2 phòng ngủ',bedrooms:'2',capacity:'4 người lớn + 2 trẻ em'},{label:'Villa 3PN',name:'Villa 3 phòng ngủ',bedrooms:'3',capacity:'6 người lớn + 2 trẻ em'},{label:'Villa 4PN',name:'Villa 4 phòng ngủ',bedrooms:'4',capacity:'8 người lớn + 4 trẻ em'}];
const presets:Record<UnifiedUnitKind,Array<Partial<UnifiedUnit>&{label:string}>>={hotel:hotelPresets,villa:villaPresets,cruise:[{label:'Deluxe Cabin',name:'Deluxe Cabin',capacity:'2 người lớn'},{label:'Executive Cabin',name:'Executive Cabin',capacity:'2 người lớn + 1 trẻ em'},{label:'Suite Cabin',name:'Suite Cabin',capacity:'2 người lớn + 1 trẻ em'}],generic:[...hotelPresets,...villaPresets]};
function F({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'unified-unit-field wide':'unified-unit-field'}><span>{label}</span>{children}</label>}
function firstImage(v:string){return String(v||'').split(/\n+/).map(x=>x.trim()).find(Boolean)||''}
export function UnifiedProductUnitsEditor({units,onChange,label='Căn / Hạng phòng / Cabin & giá',kind='generic'}:{units:UnifiedUnit[];onChange:(units:UnifiedUnit[])=>void;label?:string;kind?:UnifiedUnitKind}){
 const[open,setOpen]=useState<string|null>(null);const list=Array.isArray(units)?units:[];const options=useMemo(()=>presets[kind]||[],[kind]);
 const noun=kind==='hotel'?'hạng phòng':kind==='villa'?'căn villa':kind==='cruise'?'cabin':'căn / phòng / cabin';
 const setUnit=(id:string,k:keyof UnifiedUnit,v:any)=>onChange(list.map(u=>u.id===id?{...u,[k]:v}:u));
 const add=(preset?:Partial<UnifiedUnit>)=>{const u={...blankUnifiedUnit(),...(preset||{}),id:uid()};onChange([...list,u]);setOpen(u.id)};
 const duplicate=(u:UnifiedUnit)=>{const x={...u,id:uid(),code:u.code?`${u.code}-COPY`:'',name:`${u.name||noun} - Bản sao`};onChange([...list,x]);setOpen(x.id)};
 const remove=(u:UnifiedUnit)=>{if(!confirm(`Xóa ${u.name||u.code||noun} này?`))return;onChange(list.filter(x=>x.id!==u.id));if(open===u.id)setOpen(null)};
 return <div className={`unified-units-editor kind-${kind}`}><div className="unified-unit-head"><div><h3>{label}</h3><p>Mỗi {noun} là một sản phẩm con độc lập: ảnh riêng, giá riêng, sức chứa riêng và trạng thái bán riêng.</p></div><button type="button" onClick={()=>add()}>+ Thêm {noun}</button></div>
 {options.length>0&&<div className="unified-unit-presets"><span>Thêm nhanh:</span>{options.map(p=><button type="button" key={p.label} onClick={()=>{const {label:_,...data}=p;add(data)}}>+ {p.label}</button>)}</div>}
 {!list.length&&<div className="unified-unit-empty"><b>Chưa có {noun} nào</b><span>Hãy thêm từng {noun}; mỗi hạng có thể dùng bộ ảnh và mức giá hoàn toàn khác nhau.</span></div>}
 <div className="unified-unit-list">{list.map((u,i)=>{const thumb=firstImage(u.images);return <article key={u.id} className={open===u.id?'open':''}><button type="button" className="unified-unit-summary" onClick={()=>setOpen(open===u.id?null:u.id)}>{thumb?<img className="unified-unit-thumb" src={thumb} alt=""/>:<span>{i+1}</span>}<div><b>{u.name||`Chưa đặt tên ${noun}`}</b><small>{u.code||'Chưa có mã'} · {u.capacity||'Chưa nhập sức chứa'}{u.view?` · ${u.view}`:''}</small></div><strong>{u.weekdayPrice||u.weekendPrice||'Chưa có giá'}</strong><em>{u.status==='available'?'Đang bán':u.status==='hold'?'Tạm giữ':u.status==='soldout'?'Hết':'Ẩn'}</em></button>{open===u.id&&<div className="unified-unit-form">
 <div className="unified-unit-block"><h4>1. Thông tin {noun}</h4><div className="unified-unit-grid"><F label="Mã căn/phòng"><input value={u.code} onChange={e=>setUnit(u.id,'code',e.target.value)} placeholder="VD: DLX-SEA"/></F><F label={`Tên ${noun}`}><input value={u.name} onChange={e=>setUnit(u.id,'name',e.target.value)} placeholder={kind==='hotel'?'Deluxe Ocean View':kind==='villa'?'Villa 3PN hồ bơi':'Tên hạng'}/></F><F label="Số phòng ngủ"><input value={u.bedrooms} onChange={e=>setUnit(u.id,'bedrooms',e.target.value)}/></F><F label="Loại giường"><input value={u.beds} onChange={e=>setUnit(u.id,'beds',e.target.value)} placeholder="King / Twin"/></F><F label="Sức chứa"><input value={u.capacity} onChange={e=>setUnit(u.id,'capacity',e.target.value)} placeholder="2 người lớn + 1 trẻ em"/></F><F label="Diện tích"><input value={u.area} onChange={e=>setUnit(u.id,'area',e.target.value)} placeholder="45 m²"/></F><F label="View"><input value={u.view} onChange={e=>setUnit(u.id,'view',e.target.value)} placeholder="Biển / Vườn / Thành phố"/></F><F label="Bữa ăn"><input value={u.meal} onChange={e=>setUnit(u.id,'meal',e.target.value)} placeholder="Ăn sáng 2 khách"/></F></div></div>
 <div className="unified-unit-block price"><h4>2. Giá riêng của {noun}</h4><p>Giá này chỉ áp dụng cho đúng {noun} này.</p><div className="unified-unit-grid"><F label="Giá ngày thường"><input value={u.weekdayPrice} onChange={e=>setUnit(u.id,'weekdayPrice',e.target.value)} placeholder="2.500.000đ"/></F><F label="Giá cuối tuần"><input value={u.weekendPrice} onChange={e=>setUnit(u.id,'weekendPrice',e.target.value)} placeholder="2.900.000đ"/></F><F label="Giá lễ/Tết"><input value={u.holidayPrice} onChange={e=>setUnit(u.id,'holidayPrice',e.target.value)} placeholder="3.500.000đ"/></F><F label="Phụ thu người lớn"><input value={u.extraAdult} onChange={e=>setUnit(u.id,'extraAdult',e.target.value)}/></F><F label="Phụ thu trẻ em"><input value={u.extraChild} onChange={e=>setUnit(u.id,'extraChild',e.target.value)}/></F><F label="Trạng thái"><select value={u.status} onChange={e=>setUnit(u.id,'status',e.target.value as UnifiedUnitStatus)}><option value="available">Còn bán</option><option value="hold">Tạm giữ</option><option value="soldout">Hết phòng</option><option value="hidden">Ẩn</option></select></F></div></div>
 <div className="unified-unit-block media"><h4>3. Ảnh riêng của {noun}</h4><p>Chỉ tải ảnh đúng hạng này. Ảnh đầu tiên sẽ được dùng làm ảnh đại diện của hạng phòng/căn.</p><AdminMediaPicker multiple value={u.images} onChange={v=>setUnit(u.id,'images',v)} label={`Chọn / tải ảnh ${noun}`}/></div>
 <div className="unified-unit-block"><h4>4. Tiện ích & ghi chú</h4><div className="unified-unit-grid"><F label="Tiện ích riêng" wide><textarea rows={3} value={u.amenities} onChange={e=>setUnit(u.id,'amenities',e.target.value)} placeholder="Ban công, bồn tắm, minibar..."/></F><F label="Ghi chú nội bộ" wide><textarea rows={3} value={u.note} onChange={e=>setUnit(u.id,'note',e.target.value)}/></F></div></div>
 <div className="unified-unit-actions"><button type="button" onClick={()=>duplicate(u)}>Nhân bản {noun}</button><button type="button" className="danger" onClick={()=>remove(u)}>Xóa {noun}</button></div></div>}</article>})}</div></div>}
