import type {Metadata} from 'next';
import Link from 'next/link';
import {TourCatalog,type CmsTour,type TourCatalogQuery} from '@/components/TourCatalog';
import {ContactCtaGroup} from '@/components/ContactCtaGroup';
import {PublicServiceNav} from '@/components/PublicServiceNav';
import {getSiteUrl} from '@/lib/site-url';
import {getPublicSiteState} from '@/lib/server/public-site-state';

const path='/tour-du-lich';
type PageProps={searchParams:Promise<TourCatalogQuery>};
export function generateMetadata():Metadata{const canonical=`${getSiteUrl()}${path}`;return{title:'Tour du lịch trong nước & Tour Trung Quốc',description:'Khám phá tour du lịch trong nước và tour Trung Quốc cùng HappyGo Travel. Lịch khởi hành rõ ràng, hành trình chi tiết và tư vấn theo nhu cầu.',alternates:{canonical},openGraph:{title:'Tour du lịch trong nước & Trung Quốc | HappyGo Travel',description:'Khám phá hành trình trong nước và Trung Quốc cùng HappyGo Travel.',url:canonical,type:'website'},twitter:{card:'summary_large_image',title:'Tour du lịch | HappyGo Travel',description:'Tour trong nước và Trung Quốc với lịch trình rõ ràng, tư vấn nhanh.'}}}

export default async function ToursPage({searchParams}:PageProps){const base=getSiteUrl(),canonical=`${base}${path}`,state=await getPublicSiteState(),initialCms=Array.isArray(state.tn_cms_tours_v3)?state.tn_cms_tours_v3 as CmsTour[]:[],query=await searchParams;const schema=[{"@context":"https://schema.org","@type":"CollectionPage","name":"Tour du lịch HappyGo Travel","url":canonical,"description":"Tour du lịch trong nước và tour Trung Quốc"},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Trang chủ","item":base},{"@type":"ListItem","position":2,"name":"Tour du lịch","item":canonical}]}];return <div className="subpage"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="sub-hero"><div className="container"><div className="sub-breadcrumb"><Link href="/">Trang chủ</Link> / Tour du lịch</div><div className="sub-hero-grid"><div><span className="sub-kicker">TOUR DU LỊCH</span><h1>Tour trong nước & Trung Quốc</h1><p>Chọn hành trình theo điểm đến, thời lượng và loại tour. Lịch khởi hành và giá được HappyGo Travel xác nhận theo từng thời điểm.</p></div><ContactCtaGroup callLabel="Tư vấn tour"/></div></div></section><PublicServiceNav active="tour"/><section className="sub-section"><div className="container"><TourCatalog initialCms={initialCms} query={query}/><div className="sub-cta"><div><h2>Cần tour riêng cho gia đình hoặc doanh nghiệp?</h2><p>Gửi số khách, ngày đi và điểm đến để HappyGo Travel thiết kế hành trình phù hợp.</p></div><ContactCtaGroup mode="footer" callLabel="Gọi tư vấn" zaloLabel="Chat Zalo"/></div></div></section></div>}
