import {NextRequest,NextResponse} from 'next/server';
import {db,hasDatabase} from '@/lib/db';
import {adminActor} from '@/lib/server/admin-access';
import {hashPassword} from '@/lib/server/portal-auth';
import {settleAffiliateBooking} from '@/lib/server/affiliate';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const statuses=new Set(['pending','active','blocked']);
const codeOf=(raw:string)=>raw.toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,32);
const randomCode=()=>`CTV${Math.random().toString(36).slice(2,8).toUpperCase()}`;
const safeUrl=(value:string)=>!value||/^https:\/\//i.test(value)?value:'';

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'affiliates');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});
 try{const sql=db();const [affiliates,referrals,payouts]=await Promise.all([
  sql`select a.id,a.user_id,a.referral_code,a.phone,a.zalo,a.bank_account,a.bank_name,a.account_holder,a.total_commission,a.balance,a.commission_rate,a.status,a.created_at,a.updated_at,s.name,s.email,s.status as staff_status,(select count(*) from affiliate_clicks c where c.affiliate_id=a.id)::bigint as click_count,(select count(*) from affiliate_referrals r where r.affiliate_id=a.id and r.status in ('approved','paid'))::bigint as closed_orders from affiliates a join staff s on s.id=a.user_id order by a.created_at desc`,
  sql`select ar.id,ar.affiliate_id,ar.customer_phone,ar.commission_amount,ar.status,ar.created_at,ar.credited_at,b.id as booking_id,b.code as booking_code,b.status as booking_status,p.name as villa_name,s.name as affiliate_name from affiliate_referrals ar join affiliates a on a.id=ar.affiliate_id join staff s on s.id=a.user_id join bookings b on b.id=ar.booking_id left join products p on p.id=ar.villa_id order by ar.created_at desc limit 300`,
  sql`select cp.id,cp.affiliate_id,cp.amount,cp.status,cp.payout_date,cp.receipt_url,cp.created_at,s.name as affiliate_name from commission_payouts cp join affiliates a on a.id=cp.affiliate_id join staff s on s.id=a.user_id order by cp.created_at desc limit 200`
 ]);const items=affiliates.map((a:any)=>({id:String(a.id),userId:String(a.user_id),name:String(a.name),email:String(a.email),referralCode:String(a.referral_code),phone:String(a.phone||''),zalo:String(a.zalo||''),bankAccount:String(a.bank_account||''),bankName:String(a.bank_name||''),accountHolder:String(a.account_holder||''),totalCommission:Number(a.total_commission||0),balance:Number(a.balance||0),commissionRate:Number(a.commission_rate||0),status:String(a.status),staffStatus:String(a.staff_status),clicks:Number(a.click_count||0),closedOrders:Number(a.closed_orders||0),createdAt:String(a.created_at),updatedAt:String(a.updated_at)}));return NextResponse.json({ok:true,affiliates:items,referrals:referrals.map((r:any)=>({id:String(r.id),affiliateId:String(r.affiliate_id),affiliateName:String(r.affiliate_name),bookingId:String(r.booking_id),bookingCode:String(r.booking_code),bookingStatus:String(r.booking_status),villaName:String(r.villa_name||'Villa'),customerPhone:String(r.customer_phone||''),commissionAmount:Number(r.commission_amount||0),status:String(r.status),createdAt:String(r.created_at),creditedAt:r.credited_at?String(r.credited_at):''})),payouts:payouts.map((p:any)=>({id:String(p.id),affiliateId:String(p.affiliate_id),affiliateName:String(p.affiliate_name),amount:Number(p.amount||0),status:String(p.status),payoutDate:p.payout_date?String(p.payout_date):'',receiptUrl:String(p.receipt_url||''),createdAt:String(p.created_at)})),stats:{total:items.length,active:items.filter(x=>x.status==='active').length,balance:items.reduce((n,x)=>n+x.balance,0),commission:items.reduce((n,x)=>n+x.totalCommission,0)}})}catch(error){console.error('admin_affiliates_get_failed',error);return NextResponse.json({error:'Không đọc được module CTV.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'affiliates');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({}));const action=String(body.action||'');const sql=db();
 try{
  if(action==='create'){
   const name=String(body.name||'').trim(),email=String(body.email||'').trim().toLowerCase(),password=String(body.password||''),phone=String(body.phone||'').trim(),zalo=String(body.zalo||'').trim(),bankAccount=String(body.bankAccount||'').trim(),bankName=String(body.bankName||'').trim(),accountHolder=String(body.accountHolder||'').trim(),referralCode=codeOf(String(body.referralCode||''))||randomCode(),status=statuses.has(String(body.status))?String(body.status):'active',rate=Math.max(0,Math.min(100,Number(body.commissionRate)||5));if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return NextResponse.json({error:'Tên, email hoặc mật khẩu CTV chưa hợp lệ.'},{status:400});if(referralCode.length<4)return NextResponse.json({error:'Mã giới thiệu cần ít nhất 4 ký tự.'},{status:400});
   const staffStatus=status==='active'?'active':status==='blocked'?'locked':'inactive';const rows=await sql`with new_staff as (insert into staff(name,email,phone,password_hash,role,department,status,permissions) values(${name},${email},${phone||null},${hashPassword(password)},'affiliate','affiliate',${staffStatus},'["affiliate"]'::jsonb) returning id) insert into affiliates(user_id,referral_code,phone,zalo,bank_account,bank_name,account_holder,commission_rate,status) select id,${referralCode},${phone||null},${zalo||null},${bankAccount||null},${bankName||null},${accountHolder||null},${rate},${status} from new_staff returning id,user_id,referral_code`;
   const saved=rows[0];await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'affiliate.create','affiliate',${String(saved.id)},${JSON.stringify({name,email,referralCode,commissionRate:rate,status})}::jsonb)`;return NextResponse.json({ok:true,id:String(saved.id),referralCode:String(saved.referral_code)})
  }
  if(action==='update'){
   const id=String(body.id||'');if(!uuid.test(id))return NextResponse.json({error:'CTV không hợp lệ.'},{status:400});const current=(await sql`select a.*,s.name,s.email from affiliates a join staff s on s.id=a.user_id where a.id=${id} limit 1`)[0];if(!current)return NextResponse.json({error:'Không tìm thấy CTV.'},{status:404});const status=statuses.has(String(body.status))?String(body.status):String(current.status),rate=Math.max(0,Math.min(100,Number(body.commissionRate??current.commission_rate)||0)),phone=String(body.phone??current.phone??'').trim(),zalo=String(body.zalo??current.zalo??'').trim(),bankAccount=String(body.bankAccount??current.bank_account??'').trim(),bankName=String(body.bankName??current.bank_name??'').trim(),accountHolder=String(body.accountHolder??current.account_holder??'').trim(),staffStatus=status==='active'?'active':status==='blocked'?'locked':'inactive';await sql`with changed as (update affiliates set phone=${phone||null},zalo=${zalo||null},bank_account=${bankAccount||null},bank_name=${bankName||null},account_holder=${accountHolder||null},commission_rate=${rate},status=${status},updated_at=now() where id=${id} returning user_id) update staff set phone=${phone||null},status=${staffStatus},updated_at=now() where id=(select user_id from changed)`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,before_data,after_data) values(${actor.id},'affiliate.update','affiliate',${id},${JSON.stringify({status:current.status,commissionRate:Number(current.commission_rate||0)})}::jsonb,${JSON.stringify({status,commissionRate:rate})}::jsonb)`;return NextResponse.json({ok:true})
  }
  if(action==='payout'){
   const id=String(body.id||''),amount=Math.max(0,Math.round(Number(body.amount)||0)),receiptUrl=safeUrl(String(body.receiptUrl||'').trim());if(!uuid.test(id)||amount<=0)return NextResponse.json({error:'Số tiền thanh toán chưa hợp lệ.'},{status:400});if(body.receiptUrl&&!receiptUrl)return NextResponse.json({error:'Biên nhận phải là URL HTTPS.'},{status:400});const rows=await sql`with debited as (update affiliates set balance=balance-${amount},updated_at=now() where id=${id} and balance>=${amount} returning id) insert into commission_payouts(affiliate_id,amount,status,payout_date,receipt_url) select id,${amount},'paid',now(),${receiptUrl||null} from debited returning id`;if(!rows[0])return NextResponse.json({error:'Số dư CTV không đủ để thanh toán.'},{status:400});const remaining=(await sql`select balance from affiliates where id=${id}`)[0];if(Number(remaining?.balance||0)===0)await sql`update affiliate_referrals set status='paid',updated_at=now() where affiliate_id=${id} and status='approved'`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'affiliate.payout','affiliate',${id},${JSON.stringify({amount,receiptUrl})}::jsonb)`;return NextResponse.json({ok:true,payoutId:String(rows[0].id)})
  }
  if(action==='reconcile'){
   const bookingId=String(body.bookingId||'');if(!uuid.test(bookingId))return NextResponse.json({error:'Booking không hợp lệ.'},{status:400});const amount=await settleAffiliateBooking(sql,bookingId);await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'affiliate.reconcile','booking',${bookingId},${JSON.stringify({commissionAmount:amount})}::jsonb)`;return NextResponse.json({ok:true,commissionAmount:amount})
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400});
 }catch(error:any){console.error('admin_affiliates_post_failed',error);const text=String(error?.message||'');const duplicate=text.includes('staff_email_key')||text.includes('affiliates_referral_code_key');return NextResponse.json({error:duplicate?'Email hoặc mã giới thiệu đã được sử dụng.':'Không thể cập nhật module CTV.'},{status:duplicate?409:500})}
}
