import {NextRequest,NextResponse} from 'next/server';
import {db,hasDatabase} from '@/lib/db';
import {adminActor} from '@/lib/server/admin-access';

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const statusSet=new Set(['pending_director','changes_requested','rejected','approved','paid']);
function elevated(role:string){return role==='owner'||role==='admin'}
function accounting(role:string,permissions:string[]){return role==='accounting'||permissions.includes('ledger')||elevated(role)}
function canSeeAll(role:string,permissions:string[]){return elevated(role)||accounting(role,permissions)}
function expenseVoucher(id:string,paidAt:string){const d=new Date(paidAt),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return`PC-${stamp}-${id.replace(/-/g,'').slice(-6).toUpperCase()}`}
function shape(r:any){return{id:String(r.id),bookingId:String(r.booking_id),bookingCode:String(r.booking_code||''),customerName:String(r.customer_name_snapshot||''),product:String(r.product_name||''),supplierId:r.supplier_id?String(r.supplier_id):'',supplierName:String(r.supplier_name_snapshot||''),bankName:String(r.bank_name_snapshot||''),accountNumber:String(r.account_number_snapshot||''),accountName:String(r.account_name_snapshot||''),customerPaidAmount:Number(r.customer_paid_amount_vnd||0),amount:Number(r.amount_vnd||0),purpose:String(r.purpose||''),dueDate:r.due_date?String(r.due_date).slice(0,10):'',note:String(r.note||''),status:String(r.status),createdById:String(r.created_by_staff_id),createdByName:String(r.created_by_name||''),submittedAt:String(r.submitted_at||r.created_at),directorBy:String(r.director_by_name||''),directorAt:r.director_at?String(r.director_at):'',directorNote:String(r.director_note||''),paidBy:String(r.paid_by_name||''),paidAt:r.paid_at?String(r.paid_at):'',paidAmount:r.paid_amount_vnd===null?null:Number(r.paid_amount_vnd),paymentMethod:String(r.payment_method||''),transactionRef:String(r.transaction_ref||''),accountingNote:String(r.accounting_note||''),events:Array.isArray(r.events)?r.events:[]}}

export async function GET(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'payments');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const sql=db();
 try{
  const all=canSeeAll(actor.role,actor.permissions);const rows=all?await sql`
   select pr.*,b.code as booking_code,b.customer_name_snapshot,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.product_name_snapshot) from booking_items bi where bi.booking_id=b.id),'') as product_name,cb.name as created_by_name,db.name as director_by_name,pb.name as paid_by_name,
    coalesce((select jsonb_agg(jsonb_build_object('id',e.id::text,'action',e.action,'fromStatus',e.from_status,'toStatus',e.to_status,'detail',coalesce(e.detail,''),'actorName',coalesce(st.name,''),'createdAt',e.created_at,'snapshot',e.snapshot) order by e.created_at) from payment_request_events e left join staff st on st.id=e.actor_staff_id where e.request_id=pr.id),'[]'::jsonb) as events
   from payment_requests pr join bookings b on b.id=pr.booking_id left join staff cb on cb.id=pr.created_by_staff_id left join staff db on db.id=pr.director_by_staff_id left join staff pb on pb.id=pr.paid_by_staff_id order by pr.created_at desc limit 1000`
   :await sql`
   select pr.*,b.code as booking_code,b.customer_name_snapshot,coalesce((select string_agg(bi.product_name_snapshot,', ' order by bi.product_name_snapshot) from booking_items bi where bi.booking_id=b.id),'') as product_name,cb.name as created_by_name,db.name as director_by_name,pb.name as paid_by_name,
    coalesce((select jsonb_agg(jsonb_build_object('id',e.id::text,'action',e.action,'fromStatus',e.from_status,'toStatus',e.to_status,'detail',coalesce(e.detail,''),'actorName',coalesce(st.name,''),'createdAt',e.created_at,'snapshot',e.snapshot) order by e.created_at) from payment_request_events e left join staff st on st.id=e.actor_staff_id where e.request_id=pr.id),'[]'::jsonb) as events
   from payment_requests pr join bookings b on b.id=pr.booking_id left join staff cb on cb.id=pr.created_by_staff_id left join staff db on db.id=pr.director_by_staff_id left join staff pb on pb.id=pr.paid_by_staff_id where pr.created_by_staff_id=${actor.id} order by pr.created_at desc limit 1000`;
  const bookings=all?await sql`select b.id,b.code,b.customer_name_snapshot,b.selling_total_vnd,b.sales_staff_id,coalesce((select string_agg(bi.product_name_snapshot,', ') from booking_items bi where bi.booking_id=b.id),'') product_name,coalesce((select sum(p.amount_vnd) from payments p where p.booking_id=b.id and p.status='paid'),0)::bigint paid_total from bookings b where b.status<>'cancelled' order by b.created_at desc limit 500`:await sql`select b.id,b.code,b.customer_name_snapshot,b.selling_total_vnd,b.sales_staff_id,coalesce((select string_agg(bi.product_name_snapshot,', ') from booking_items bi where bi.booking_id=b.id),'') product_name,coalesce((select sum(p.amount_vnd) from payments p where p.booking_id=b.id and p.status='paid'),0)::bigint paid_total from bookings b where b.status<>'cancelled' and b.sales_staff_id=${actor.id} order by b.created_at desc limit 500`;
  const suppliers=all?await sql`select * from suppliers order by updated_at desc,name`:await sql`select * from suppliers order by updated_at desc,name`;
  return NextResponse.json({ok:true,requests:rows.map(shape),bookings:bookings.map((b:any)=>({id:String(b.id),code:String(b.code),customerName:String(b.customer_name_snapshot||''),product:String(b.product_name||''),sellingTotal:Number(b.selling_total_vnd||0),paidTotal:Number(b.paid_total||0)})),suppliers:suppliers.map((s:any)=>({id:String(s.id),name:String(s.name),bankName:String(s.bank_name||''),accountNumber:String(s.account_number||''),accountName:String(s.account_name||''),phone:String(s.phone||'')})),capabilities:{create:actor.role!=='accounting',approve:elevated(actor.role),pay:accounting(actor.role,actor.permissions),all}})
 }catch(error){console.error('payment_requests_get_failed',error);return NextResponse.json({error:'Không đọc được đề xuất chi production.'},{status:500})}
}

export async function POST(req:NextRequest){
 if(!hasDatabase())return NextResponse.json({error:'Database chưa sẵn sàng.'},{status:503});const actor=await adminActor(req,'payments');if(!actor)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await req.json().catch(()=>({}));const action=String(body.action||'');const sql=db();
 try{
  if(action==='create'){
   if(actor.role==='accounting')return NextResponse.json({error:'Kế toán không tạo đề xuất chi.'},{status:403});const bookingId=String(body.bookingId||''),amount=Math.round(Number(body.amount)||0),supplierId=String(body.supplierId||''),supplierName=String(body.supplierName||'').trim(),bankName=String(body.bankName||'').trim(),accountNumber=String(body.accountNumber||'').trim(),accountName=String(body.accountName||'').trim(),purpose=String(body.purpose||'').trim(),dueDate=String(body.dueDate||''),note=String(body.note||'').trim().slice(0,4000);if(!uuid.test(bookingId)||amount<=0||!supplierName||!accountNumber||!accountName||!purpose)return NextResponse.json({error:'Thông tin đề xuất chi chưa đầy đủ.'},{status:400});
   const bRows=await sql`select id,code,sales_staff_id from bookings where id=${bookingId} limit 1`;const booking=bRows[0];if(!booking)return NextResponse.json({error:'Không tìm thấy booking.'},{status:404});if(!canSeeAll(actor.role,actor.permissions)&&String(booking.sales_staff_id||'')!==actor.id)return NextResponse.json({error:'Bạn không có quyền lập đề xuất cho booking này.'},{status:403});const paidRows=await sql`select coalesce(sum(amount_vnd),0)::bigint as paid from payments where booking_id=${bookingId} and status='paid'`;const customerPaid=Number(paidRows[0]?.paid||0);if(customerPaid<=0)return NextResponse.json({error:'Booking chưa có Phiếu thu khách.'},{status:400});
   let sid=supplierId;if(sid&&!uuid.test(sid))sid='';if(!sid){const s=await sql`insert into suppliers(name,bank_name,account_number,account_name,note) values(${supplierName},${bankName||null},${accountNumber},${accountName},'Tạo từ đề xuất chi') returning id`;sid=String(s[0].id)}
   const rows=await sql`insert into payment_requests(booking_id,supplier_id,supplier_name_snapshot,bank_name_snapshot,account_number_snapshot,account_name_snapshot,customer_paid_amount_vnd,amount_vnd,purpose,due_date,note,status,created_by_staff_id,submitted_at,updated_at) values(${bookingId},${sid},${supplierName},${bankName||null},${accountNumber},${accountName},${customerPaid},${amount},${purpose},${dueDate||null},${note||null},'pending_director',${actor.id},now(),now()) returning *`;const pr=rows[0];await sql`insert into payment_request_events(request_id,actor_staff_id,action,to_status,detail,snapshot) values(${String(pr.id)},${actor.id},'created','pending_director',${`Thực thu khách ${customerPaid} VND`},${JSON.stringify({amount,supplierName,bankName,accountNumber,accountName,purpose,customerPaidAmount:customerPaid})}::jsonb)`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,after_data) values(${actor.id},'payment_request.create','payment_request',${String(pr.id)},${JSON.stringify(pr)}::jsonb)`;return NextResponse.json({ok:true,id:String(pr.id)});
  }
  if(action==='review'){
   if(!elevated(actor.role))return NextResponse.json({error:'Bạn không có quyền duyệt đề xuất.'},{status:403});const id=String(body.id||''),next=String(body.status||''),directorNote=String(body.note||'').trim();if(!uuid.test(id)||!['approved','rejected','changes_requested'].includes(next))return NextResponse.json({error:'Dữ liệu duyệt không hợp lệ.'},{status:400});const beforeRows=await sql`select * from payment_requests where id=${id} limit 1`;const before=beforeRows[0];if(!before)return NextResponse.json({error:'Không tìm thấy đề xuất.'},{status:404});if(String(before.status)!=='pending_director')return NextResponse.json({error:'Đề xuất không còn ở trạng thái chờ duyệt.'},{status:409});if(String(before.created_by_staff_id)===actor.id)return NextResponse.json({error:'Người lập không được tự duyệt đề xuất của mình.'},{status:403});if(next!=='approved'&&!directorNote)return NextResponse.json({error:'Cần ghi rõ lý do.'},{status:400});await sql`update payment_requests set status=${next},director_by_staff_id=${actor.id},director_at=now(),director_note=${directorNote||null},updated_at=now() where id=${id}`;await sql`insert into payment_request_events(request_id,actor_staff_id,action,from_status,to_status,detail,snapshot) values(${id},${actor.id},'director_review','pending_director',${next},${directorNote||null},${JSON.stringify({amount:Number(before.amount_vnd||0),supplierName:String(before.supplier_name_snapshot||'')})}::jsonb)`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,before_data) values(${actor.id},'payment_request.review','payment_request',${id},${JSON.stringify(before)}::jsonb)`;return NextResponse.json({ok:true});
  }
  if(action==='revise'){
   const id=String(body.id||''),amount=Math.round(Number(body.amount)||0),purpose=String(body.purpose||'').trim(),supplierName=String(body.supplierName||'').trim(),bankName=String(body.bankName||'').trim(),accountNumber=String(body.accountNumber||'').trim(),accountName=String(body.accountName||'').trim(),dueDate=String(body.dueDate||''),note=String(body.note||'').trim();if(!uuid.test(id)||amount<=0||!purpose||!supplierName||!accountNumber||!accountName)return NextResponse.json({error:'Thông tin sửa chưa đầy đủ.'},{status:400});const beforeRows=await sql`select * from payment_requests where id=${id} limit 1`;const before=beforeRows[0];if(!before||String(before.created_by_staff_id)!==actor.id||String(before.status)!=='changes_requested')return NextResponse.json({error:'Bạn không thể sửa đề xuất này.'},{status:403});const paid=await sql`select coalesce(sum(p.amount_vnd),0)::bigint as total from payments p where p.booking_id=${String(before.booking_id)} and p.status='paid'`;const customerPaid=Number(paid[0]?.total||0);if(customerPaid<=0)return NextResponse.json({error:'Booking hiện chưa có Phiếu thu khách.'},{status:400});await sql`update payment_requests set supplier_name_snapshot=${supplierName},bank_name_snapshot=${bankName||null},account_number_snapshot=${accountNumber},account_name_snapshot=${accountName},customer_paid_amount_vnd=${customerPaid},amount_vnd=${amount},purpose=${purpose},due_date=${dueDate||null},note=${note||null},status='pending_director',submitted_at=now(),updated_at=now() where id=${id}`;await sql`insert into payment_request_events(request_id,actor_staff_id,action,from_status,to_status,detail,snapshot) values(${id},${actor.id},'revised','changes_requested','pending_director','Người lập sửa và gửi lại',${JSON.stringify({amount,supplierName,bankName,accountNumber,accountName,purpose,customerPaidAmount:customerPaid})}::jsonb)`;return NextResponse.json({ok:true});
  }
  if(action==='pay'){
   if(!accounting(actor.role,actor.permissions))return NextResponse.json({error:'Chỉ Kế toán/Chủ tài khoản được xác nhận chi.'},{status:403});const id=String(body.id||''),paidAmount=Math.round(Number(body.paidAmount)||0),paymentMethod=String(body.paymentMethod||'Chuyển khoản').trim(),transactionRef=String(body.transactionRef||'').trim(),accountingNote=String(body.accountingNote||'').trim();if(!uuid.test(id)||paidAmount<=0)return NextResponse.json({error:'Thông tin chi không hợp lệ.'},{status:400});const beforeRows=await sql`select * from payment_requests where id=${id} limit 1`;const before=beforeRows[0];if(!before||String(before.status)!=='approved')return NextResponse.json({error:'Đề xuất chưa được duyệt hoặc đã xử lý.'},{status:409});if(String(before.created_by_staff_id)===actor.id&&actor.role!=='owner')return NextResponse.json({error:'Người lập không được tự xác nhận chi.'},{status:403});const paidAt=new Date().toISOString();await sql`update payment_requests set status='paid',paid_by_staff_id=${actor.id},paid_at=${paidAt},paid_amount_vnd=${paidAmount},payment_method=${paymentMethod},transaction_ref=${transactionRef||null},accounting_note=${accountingNote||null},updated_at=now() where id=${id}`;await sql`insert into payment_request_events(request_id,actor_staff_id,action,from_status,to_status,detail,snapshot) values(${id},${actor.id},'paid','approved','paid',${`Thực chi ${paidAmount} VND · ${paymentMethod}`},${JSON.stringify({paidAmount,paymentMethod,transactionRef})}::jsonb)`;const voucher=expenseVoucher(id,paidAt);await sql`insert into accounting_entries(voucher_no,entry_type,entry_date,category,description,counterparty,fund,amount_vnd,document_ref,note,source,source_id,created_by_staff_id) values(${voucher},'expense',${paidAt.slice(0,10)},'Thanh toán nhà cung cấp',${String(before.purpose||'Thanh toán dịch vụ')},${String(before.supplier_name_snapshot||'')},${paymentMethod.toLowerCase().includes('tiền mặt')?'cash':'bank'},${paidAmount},${transactionRef||null},${accountingNote||null},'payment_request',${id},${actor.id}) on conflict(voucher_no) do nothing`;await sql`insert into audit_logs(actor_staff_id,action,entity_type,entity_id,before_data) values(${actor.id},'payment_request.paid','payment_request',${id},${JSON.stringify(before)}::jsonb)`;return NextResponse.json({ok:true,voucher});
  }
  return NextResponse.json({error:'Hành động không hỗ trợ.'},{status:400});
 }catch(error){console.error('payment_request_post_failed',error);return NextResponse.json({error:'Không thể cập nhật đề xuất chi production.'},{status:500})}
}
