'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {readCart,writeCart,type CartItem} from '@/components/BookingCart';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';
const BOOKING_KEY='tn_local_bookings_v1';const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const normalizePhone=(v:string)=>{const d=v.replace(/\D/g,'');return d.startsWith('84')&&d.length===11?`0${d.slice(2)}`:d};
export default function CheckoutPage(){const settings=useSiteSettings();const supportPhone=settings.hotline.replace(/\D/g,'');const supportLabel=formatPhone(settings.hotline);const[items,setItems]=useState<CartItem[]>([]);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[note,setNote]=useState('');const[code,setCode]=useState('');const[savedPhone,setSavedPhone]=useState('');const[error,setError]=useState('');const[sending,setSending]=useState(false);useEffect(()=>setItems(readCart()),[]);const totalPeople=useMemo(()=>items.reduce((s,x)=>s+x.adults+x.children,0),[items]);function remove(id:string){const next=items.filter(x=>x.id!==id);setItems(next);writeCart(next)}function saveLocal(booking:any){const old=JSON.parse(localStorage.getItem(BOOKING_KEY)||'[]');localStorage.setItem(BOOKING_KEY,JSON.stringify([booking,...old]));window.dispatchEvent(new Event('tn-bookings-updated'))}
async function submit(){setError('');const p=normalizePhone(phone);if(name.trim().length<2){setError('Vui lòng nhập họ tên.');return}if(!/^0\d{9}$/.test(p)){setError('Số điện thoại chưa đúng.');return}if(!items.length){setError('Giỏ đặt dịch vụ đang trống.');return}const summary=items.map((x,i)=>`${i+1}. ${x.product}${x.unit?` · ${x.unit}`:''}${x.startDate?` · ${x.startDate}${x.endDate?` → ${x.endDate}`:''}`:''}`).join('\n');const payload={kind:items.length>1?'Nhiều dịch vụ':items[0].kind,product:items.length>1?`${items.length} dịch vụ`:items[0].product,customerName:name.trim(),phone:p,email:email.trim()||null,startDate:items[0]?.startDate||null,endDate:items[0]?.endDate||null,adults:items.reduce((s,x)=>s+x.adults,0),children:items.reduce((s,x)=>s+x.children,0),rooms:items.reduce((s,x)=>s+x.rooms,0),note:`DANH SÁCH DỊCH VỤ:\n${summary}${note.trim()?`\n\nGhi chú khách: ${note.trim()}`:''}`,source:'checkout'};setSending(true);try{if(API_BASE){try{const r=await fetch(`${API_BASE.replace(/\/$/,'')}/api/bookings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){const d=await r.json();writeCart([]);setItems([]);setCode(d.code);setSavedPhone(p);return}}catch{}}const bookingCode=`TN${new Date().toISOString().slice(2,10).replace(/-/g,'')}${String(Date.now()).slice(-5)}`;const booking={id:Date.now(),code:bookingCode,kind:payload.kind,product:payload.product,customer_name:payload.customerName,phone:p,email:payload.email,start_date:payload.startDate,end_date:payload.endDate,adults:payload.adults,children:payload.children,rooms:payload.rooms,note:payload.note,status:'new',admin_note:'',created_at:new Date().toISOString()};saveLocal(booking);writeCart([]);setItems([]);setCode(bookingCode);setSavedPhone(p)}catch{setError('Chưa thể lưu yêu cầu. Vui lòng thử lại hoặc gọi hotline.')}finally{setSending(false)}}
if(code)return <div className="checkout-page"><div className="container checkout-success"><div className="checkout-success-icon">✓</div><small>YÊU CẦU ĐÃ ĐƯỢC GHI NHẬN</small><h1>Cảm ơn anh/chị</h1><p>Mã booking của anh/chị là</p><strong>{code}</strong><p>Thúy Nguyên Travel sẽ liên hệ để xác nhận giá, tình trạng dịch vụ và phương thức thanh toán.</p><div><Link href={`/payment?code=${encodeURIComponent(code)}&phone=${encodeURIComponent(savedPhone)}`}>Thanh toán / QR</Link><Link href="/booking-lookup">Tra cứu booking</Link><Link href="/account">Tài khoản & lịch sử</Link><a href={`tel:${supportPhone}`}>Gọi {supportLabel}</a></div></div></div>;
return <div className="checkout-page"><section className="checkout-hero"><div className="container"><small>THÚY NGUYÊN TRAVEL</small><h1>Xác nhận yêu cầu đặt dịch vụ</h1><p>Kiểm tra dịch vụ đã chọn và gửi một lần. Chưa thu tiền ở bước này.</p></div></section><div className="container checkout-layout"><main><div className="checkout-step"><b>1</b><div><h2>Dịch vụ đã chọn</h2><p>{items.length} mục · {totalPeople} khách</p></div></div>{items.length?items.map(x=><article className="checkout-item" key={x.id}><div><small>{x.kind}</small><h3>{x.product}</h3>{x.unit&&<p>Hạng/căn/cabin: <b>{x.unit}</b></p>}<p>{x.startDate||'Chưa chọn ngày'}{x.endDate?` → ${x.endDate}`:''}</p><span>{x.adults} người lớn · {x.children} trẻ em · {x.rooms} phòng/cabin</span></div><button onClick={()=>remove(x.id)}>Xóa</button></article>):<div className="checkout-empty"><b>Chưa có dịch vụ</b><p>Quay lại chọn Tour, Villa, khách sạn hoặc du thuyền.</p><Link href="/">Chọn dịch vụ</Link></div>}</main><aside className="checkout-form-card"><div className="checkout-step"><b>2</b><div><h2>Thông tin liên hệ</h2><p>Nhân viên dùng thông tin này để xác nhận booking.</p></div></div><label>Họ và tên<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn A"/></label><label>Số điện thoại<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0969 973 949" inputMode="tel"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com" type="email"/></label><label>Ghi chú<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Yêu cầu riêng, tuổi trẻ em, giờ liên hệ..."/></label>{error&&<p className="checkout-error">{error}</p>}<button className="checkout-submit" onClick={submit} disabled={!items.length||sending}>{sending?'Đang gửi...':'Gửi yêu cầu & nhận mã booking'}</button><small className="checkout-policy">Bước này chưa thanh toán. Giá cuối cùng được xác nhận theo ngày đi, tình trạng phòng/cabin và chính sách của nhà cung cấp.</small></aside></div></div>}
