'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {readCart,writeCart,type CartItem} from '@/components/BookingCart';
import {formatPhone,useSiteSettings} from '@/components/useSiteSettings';

const BOOKING_KEY='tn_local_bookings_v1';
const PRODUCTS_KEY='tn_cms_products_v3_units';
const RATES_KEY='tn_cms_daily_rates_v1';
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const normalizePhone=(value:string)=>{const digits=value.replace(/\D/g,'');return digits.startsWith('84')&&digits.length===11?`0${digits.slice(2)}`:digits};
const money=(v?:string)=>{const d=String(v||'').replace(/\D/g,'');return d?Number(d):0};
const fmt=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseYmd=(value:string)=>{const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d,12,0,0,0)};
const nightsBetween=(start:string,end?:string)=>{if(!start)return 0;if(!end)return 1;const [sy,sm,sd]=start.split('-').map(Number);const [ey,em,ed]=end.split('-').map(Number);const diff=Math.round((Date.UTC(ey,em-1,ed)-Date.UTC(sy,sm-1,sd))/86400000);return Math.max(1,diff)};
const holiday=new Set(['01-01','04-30','05-01','09-02']);
const dayKind=(d:Date)=>holiday.has(`${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)?'holiday':(d.getDay()===5||d.getDay()===6)?'weekend':'weekday';
type Unit={id:string;code?:string;name?:string;weekdayPrice?:string;weekendPrice?:string;holidayPrice?:string};
type Product={name?:string;slug?:string;units?:Unit[]};
type Rate={unitId:string;start:string;end:string;price:string;quantity:string;status:string};
type LocalBooking={id:number;code:string;kind:string;product:string;customer_name:string;phone:string;email:string;start_date:string|null;end_date:string|null;adults:number;children:number;rooms:number;note:string;status:'new';admin_note:string;created_at:string;source:string};
function unitForItem(item:CartItem){try{const products=JSON.parse(localStorage.getItem(PRODUCTS_KEY)||'[]') as Product[];const product=products.find(p=>p.name===item.product)||products.find(p=>(p.units||[]).some(u=>item.unit?.includes(u.code||'')||item.unit?.includes(u.name||'')));if(!product)return null;return (product.units||[]).find(u=>item.unit?.includes(u.code||'')||item.unit?.includes(u.name||''))||null}catch{return null}}
function rateFor(unitId:string,date:string){try{const rates=JSON.parse(localStorage.getItem(RATES_KEY)||'[]') as Rate[];const matches=rates.filter(r=>r.unitId===unitId&&r.start&&r.end&&date>=r.start&&date<=r.end);return matches.length?matches[matches.length-1]:null}catch{return null}}
function fallbackPrice(u:Unit,d:Date){const w=money(u.weekdayPrice),we=money(u.weekendPrice)||w,h=money(u.holidayPrice)||we||w;return dayKind(d)==='holiday'?h:dayKind(d)==='weekend'?we:w}
function resolvePrice(item:CartItem){if(item.priceLabel&&money(item.priceLabel))return {label:item.priceLabel,total:0,nights:item.startDate?nightsBetween(item.startDate,item.endDate):0};const u=unitForItem(item);if(!u)return {label:'Liên hệ',total:0,nights:item.startDate?nightsBetween(item.startDate,item.endDate):0};if(!item.startDate){const vals=[money(u.weekdayPrice),money(u.weekendPrice),money(u.holidayPrice)].filter(Boolean);return {label:vals.length?`Từ ${fmt(Math.min(...vals))}`:'Liên hệ',total:0,nights:0}};const nights=nightsBetween(item.startDate,item.endDate);const start=parseYmd(item.startDate);const prices:number[]=[];for(let i=0;i<nights&&i<31;i++){const d=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i,12,0,0,0);const r=rateFor(u.id,dateKey(d));const p=r?(r.status==='available'&&Number(r.quantity||0)>0?money(r.price):0):fallbackPrice(u,d);if(p)prices.push(p)}const rooms=Math.max(1,item.rooms||1);const total=prices.reduce((s,p)=>s+p,0)*rooms;return {label:prices.length?(prices.every(p=>p===prices[0])?`${fmt(prices[0])}/đêm`:`${fmt(Math.min(...prices))} – ${fmt(Math.max(...prices))}/đêm`):'Liên hệ',total,nights}}

export default function CheckoutPage(){
 const settings=useSiteSettings();const supportPhone=settings.hotline.replace(/\D/g,'');const supportLabel=formatPhone(settings.hotline);const[items,setItems]=useState<CartItem[]>([]);const[name,setName]=useState('');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[note,setNote]=useState('');const[code,setCode]=useState('');const[error,setError]=useState('');const[sending,setSending]=useState(false);const[priceRev,setPriceRev]=useState(0);
 useEffect(()=>{const load=()=>{setItems(readCart());setPriceRev(x=>x+1)};load();window.addEventListener('tn-rates-updated',load);window.addEventListener('tn-products-updated',load);window.addEventListener('storage',load);return()=>{window.removeEventListener('tn-rates-updated',load);window.removeEventListener('tn-products-updated',load);window.removeEventListener('storage',load)}},[]);
 const totalPeople=useMemo(()=>items.reduce((sum,item)=>sum+item.adults+item.children,0),[items]);
 const priced=useMemo(()=>items.map(item=>({item,...resolvePrice(item)})),[items,priceRev]);
 const grandTotal=useMemo(()=>priced.reduce((sum,x)=>sum+x.total,0),[priced]);
 function remove(id:string){const next=items.filter(item=>item.id!==id);setItems(next);writeCart(next)}
 function saveLocal(booking:LocalBooking){try{const old=JSON.parse(localStorage.getItem(BOOKING_KEY)||'[]') as LocalBooking[];localStorage.setItem(BOOKING_KEY,JSON.stringify([booking,...old].slice(0,500)));window.dispatchEvent(new Event('tn-bookings-updated'))}catch{}}
 async function submit(){setError('');const normalizedPhone=normalizePhone(phone);if(name.trim().length<2){setError('Vui lòng nhập họ tên.');return}if(!/^0\d{9}$/.test(normalizedPhone)){setError('Số điện thoại chưa đúng.');return}if(!items.length){setError('Giỏ đặt dịch vụ đang trống.');return}setSending(true);try{
   const summary=priced.map(({item,label,total,nights},index)=>`${index+1}. ${item.product}${item.unit?` · ${item.unit}`:''}${item.startDate?` · ${item.startDate}${item.endDate?` → ${item.endDate}`:''}`:''} · ${nights||1} đêm · ${item.adults} NL · ${item.children} TE · ${item.rooms} phòng/cabin · Giá: ${label}${total?` · Tạm tính: ${fmt(total)}`:''}`).join('\n');
   const bookingCode=`HG${new Date().toISOString().slice(2,10).replace(/-/g,'')}${String(Date.now()).slice(-5)}`;
   const booking:LocalBooking={id:Date.now(),code:bookingCode,kind:items.length>1?'Nhiều dịch vụ':items[0].kind,product:items.length>1?`${items.length} dịch vụ`:items[0].product,customer_name:name.trim(),phone:normalizedPhone,email:email.trim(),start_date:items[0]?.startDate||null,end_date:items[0]?.endDate||null,adults:items.reduce((sum,item)=>sum+item.adults,0),children:items.reduce((sum,item)=>sum+item.children,0),rooms:items.reduce((sum,item)=>sum+item.rooms,0),note:`DANH SÁCH DỊCH VỤ:\n${summary}${grandTotal?`\n\nTỔNG TẠM TÍNH: ${fmt(grandTotal)}`:''}${note.trim()?`\n\nGhi chú khách: ${note.trim()}`:''}`,status:'new',admin_note:'',created_at:new Date().toISOString(),source:'checkout-local'};
   let finalCode=bookingCode;
   if(API_BASE){try{const payload={kind:booking.kind,product:booking.product,customerName:booking.customer_name,phone:booking.phone,email:booking.email,startDate:booking.start_date,endDate:booking.end_date,adults:booking.adults,children:booking.children,rooms:booking.rooms,note:booking.note,source:'checkout'};const response=await fetch(`${API_BASE.replace(/\/$/,'')}/api/bookings`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('api');const result=await response.json();finalCode=result.code||bookingCode}catch{saveLocal(booking)}}else saveLocal(booking);
   writeCart([]);setItems([]);setCode(finalCode);
 }catch{setError('Chưa thể lưu yêu cầu. Vui lòng thử lại hoặc gọi hotline.')}finally{setSending(false)}}
 if(code)return <div className="checkout-page"><div className="container checkout-success"><div className="checkout-success-icon">✓</div><small>YÊU CẦU ĐÃ ĐƯỢC GHI NHẬN</small><h1>Cảm ơn anh/chị</h1><p>Mã booking của anh/chị là</p><strong>{code}</strong><p>HappyGo Travel sẽ gọi lại để xác nhận giá, tình trạng phòng/cabin và chốt dịch vụ. Bước này chưa thanh toán.</p><div><Link href="/">Tiếp tục xem dịch vụ</Link><a href={`tel:${supportPhone}`}>Gọi {supportLabel}</a></div></div></div>;
 return <div className="checkout-page"><section className="checkout-hero"><div className="container"><small>HAPPYGO TRAVEL</small><h1>Xác nhận yêu cầu đặt dịch vụ</h1><p>Kiểm tra dịch vụ, giá tạm tính và gửi một lần. Chưa thu tiền ở bước này.</p></div></section><div className="container checkout-layout"><main><div className="checkout-step"><b>1</b><div><h2>Dịch vụ đã chọn</h2><p>{items.length} mục · {totalPeople} khách</p></div></div>{priced.length?priced.map(({item,label,total,nights})=><article className="checkout-item" key={item.id}><div><small>{item.kind}</small><h3>{item.product}</h3>{item.unit&&<p>Hạng/căn/cabin: <b>{item.unit}</b></p>}<p>{item.startDate||'Chưa chọn ngày'}{item.endDate?` → ${item.endDate}`:''}</p><span>{item.adults} người lớn · {item.children} trẻ em · {item.rooms} phòng/cabin</span><div className="checkout-item-price"><small>GIÁ KHÁCH XEM</small><strong>{label}</strong>{total>0&&<b>Tạm tính {nights} đêm × {item.rooms} phòng/căn: {fmt(total)}</b>}</div></div><button type="button" onClick={()=>remove(item.id)}>Xóa</button></article>):<div className="checkout-empty"><b>Chưa có dịch vụ</b><p>Quay lại chọn Tour, Villa, khách sạn hoặc du thuyền.</p><Link href="/">Chọn dịch vụ</Link></div>}{grandTotal>0&&<div className="checkout-grand-total"><span>TỔNG TẠM TÍNH</span><strong>{fmt(grandTotal)}</strong><small>Giá cuối cùng được xác nhận theo tồn phòng và chính sách tại thời điểm chốt.</small></div>}</main><aside className="checkout-form-card"><div className="checkout-step"><b>2</b><div><h2>Thông tin liên hệ</h2><p>Nhân viên dùng thông tin này để xác nhận booking.</p></div></div><label>Họ và tên<input value={name} onChange={event=>setName(event.target.value)} placeholder="Nguyễn Văn A" autoComplete="name"/></label><label>Số điện thoại<input value={phone} onChange={event=>setPhone(event.target.value)} placeholder={supportLabel} inputMode="tel" autoComplete="tel"/></label><label>Email<input value={email} onChange={event=>setEmail(event.target.value)} placeholder="email@example.com" type="email" autoComplete="email"/></label><label>Ghi chú<textarea rows={4} value={note} onChange={event=>setNote(event.target.value)} placeholder="Yêu cầu riêng, tuổi trẻ em, giờ liên hệ..."/></label>{error&&<p className="checkout-error">{error}</p>}<button className="checkout-submit" type="button" onClick={submit} disabled={!items.length||sending}>{sending?'Đang gửi...':'Gửi yêu cầu & nhận mã booking'}</button><small className="checkout-policy">Chưa thanh toán. Giá cuối cùng được HappyGo xác nhận theo ngày đi và tình trạng thực tế.</small></aside></div></div>}
