import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {guidePosts,getGuide} from '@/data/guides';
import {ContactQuickLink} from '@/components/ContactQuickLink';
const base='https://banguyen310941-coder.github.io/thuy-nguyen-travel';
export function generateStaticParams(){return guidePosts.map(p=>({slug:p.slug}))}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const p=getGuide(params.slug);if(!p)return{};const url=`${base}/guide/${p.slug}`;return{title:p.title,description:p.excerpt,keywords:p.keywords,alternates:{canonical:url},openGraph:{title:p.title,description:p.excerpt,url,type:'article',images:[p.image]}}}
export default function GuideArticle({params}:{params:{slug:string}}){const p=getGuide(params.slug);if(!p)notFound();return <main className="subpage seo-article-page"><div className="container article-container"><nav className="article-breadcrumb"><Link href="/">Trang chủ</Link><span>›</span><Link href="/guide">Cẩm nang</Link><span>›</span><b>{p.category}</b></nav><article className="public-article seo-static-article"><header><div className="article-meta"><span>{p.category}</span><span>{p.date}</span><span>{p.readTime}</span></div><h1>{p.title}</h1><p className="article-lead">{p.excerpt}</p></header><img className="article-cover" src={p.image} alt={p.title}/><div className="article-content"><p><strong>Tóm tắt:</strong> {p.excerpt}</p>{p.content.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs.map((x,i)=><p key={i}>{x}</p>)}</section>)}</div><div className="article-actions"><Link href="/stay">Xem lưu trú</Link><Link href="/cruises">Xem du thuyền</Link><ContactQuickLink label="Nhận tư vấn"/></div></article><aside className="related-guides"><h2>Bài viết liên quan</h2><div className="guide-grid">{guidePosts.filter(x=>x.slug!==p.slug).slice(0,3).map(x=><Link className="guide-card" href={`/guide/${x.slug}`} key={x.slug}><div className="guide-image" style={{backgroundImage:`url(${x.image})`}}/><div className="guide-body"><small>{x.category}</small><h3>{x.title}</h3><p>{x.excerpt}</p><b>Đọc bài →</b></div></Link>)}</div></aside></div></main>}
