import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {guidePosts,getGuide} from '@/data/guides';
import {GuideArticleEditable} from '@/components/GuideArticleEditable';
const base='https://banguyen310941-coder.github.io/thuy-nguyen-travel';
export function generateStaticParams(){return guidePosts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getGuide(slug);if(!p)return{};const url=`${base}/guide/${p.slug}`;return{title:p.title,description:p.excerpt,keywords:p.keywords,alternates:{canonical:url},openGraph:{title:p.title,description:p.excerpt,url,type:'article',images:[p.image]}}}
export default async function GuideArticle({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getGuide(slug);if(!p)notFound();const url=`${base}/guide/${p.slug}`;const schema={"@context":"https://schema.org","@type":"Article",headline:p.title,description:p.excerpt,image:[p.image],datePublished:'2026-08-23',dateModified:'2026-08-23',mainEntityOfPage:url,author:{"@type":"Organization",name:'Thúy Nguyên Travel'},publisher:{"@type":"Organization",name:'Thúy Nguyên Travel'}};return <main className="subpage seo-article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><div className="container article-container"><nav className="article-breadcrumb"><Link href="/">Trang chủ</Link><span>›</span><Link href="/guide">Cẩm nang</Link><span>›</span><b>{p.category}</b></nav><GuideArticleEditable post={p}/><aside className="related-guides"><h2>Bài viết liên quan</h2><div className="guide-grid">{guidePosts.filter(x=>x.slug!==p.slug).sort((a,b)=>Number(b.category===p.category)-Number(a.category===p.category)).slice(0,3).map(x=><Link className="guide-card" href={`/guide/${x.slug}`} key={x.slug}><div className="guide-image" style={{backgroundImage:`url(${x.image})`}}/><div className="guide-body"><small>{x.category}</small><h3>{x.title}</h3><p>{x.excerpt}</p><b>Đọc bài →</b></div></Link>)}</div></aside></div></main>}
